### ISSUE TITLE
SPUserProfileServiceApp - MySiteHostLocation Should be required

### ISSUE THREAD

**Issue by llowevad** [PowerShell/SharePointDsc#1000]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spprofileserviceapplication?view=sharepoint-ps

According to the above powershell command that is used in the SPUserProfileServiceApp, the MySiteHostLocation is a required parameter. The parameter on the DSC resource should be required as well. When I don't provide the parameter it fails on running the associated powershell command to create the service application.

**Comment by andikrueger** [comment]
This is a bug.

For now we should add a warning, that the `MySiteHostLocation` is a required parameter. Making this parameter required would be a breaking change.

https://github.com/PowerShell/SharePointDsc/blob/4b3133ec1e7e369277afd61720eb4b34991d1e5e/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof#L7

**Comment by ykuijs** [comment]
Added a warning in the code and a note in the Readme for the resource. We will have to implement the breaking change in the v4 release.

Warning message will be in my next Bugfix PR.

**Comment by ykuijs** [comment]
Implemented via PR #1133 in the v4.0-development branch. Will be included in v4.0.
