### ISSUE TITLE
SPInstallLanguagePack

### ISSUE THREAD

**Issue by Domivo** [PowerShell/SharePointDsc#1001]
SharePoint 2019 German Language Pack couldn't be installed. 

Error:

PowerShell DSC resource MSFT_SPInstallLanguagePack  failed to execute Test-TargetResource functionality with error message: Unknown folder structure 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SP2019.splab.local

DSC Script:

 SPInstallLanguagePack GermanLanguagePack
	        {
	            BinaryDir            = $ConfigurationData.SharePoint.Settings.LanguagePackPath
                    Ensure               = "Present"
	            DependsOn            = "[SPInstall]SharePointInstall"
	            PsDscRunAsCredential = $SPSetupAccount
	        }

ConfigData:

LanguagePackPath = "C:\DSC SP 2019\SP2019\LanguagePack"

**Comment by regularroutine** [comment]
Hey Domivo,

are you sure the path exist on the machine? Can you try to navigate there?

Thanks,
David

**Comment by Domivo** [comment]
Hey David,

yes the path exists on the machine and i can navigate there.

There exists a subfolder "German" with the german language pack inside. I also tried the following in the ConfigData:
LanguagePackPath = "C:\DSC SP 2019\SP2019\LanguagePack\German"
LanguagePackPath = "C:\DSC SP 2019\SP2019\LanguagePack\German\serverlanguagepack.exe"

The result is the same error message.

Greetings!

**Comment by regularroutine** [comment]
Hey Domivo,
I believe you need to reference the root of the folder where the files reside.
Cheers

**Comment by Domivo** [comment]
Thank you andikrueger! 

That was the solution for my problem.

Greetings!
