### ISSUE TITLE
SPProductUpdate: Update does not contain the language code in the correct format.

### ISSUE THREAD

**Issue by Domivo** [PowerShell/SharePointDsc#1007]
Hello,

I installed the SharePoint 2019 CU January 2019 (LanguagePack independent) with SharePointDSC.
I also want to install SharePoint 2019 CU January 2019 (LanguagePack dependent) with SharePointDSC, but i get the following error message:

PowerShell DSC resource MSFT_SPProductUpdate failed to execute Test-TargetResource functionality with error message: Update does not contain the language code in the correct format.

I tried the german (German LanuagePack is installed) and english version but get the same message. I could install the CU manually.

Greetings.

**Comment by andikrueger** [comment]
Could you share your file names and screenshots of the file properties > details. The resource  checks the file name and this check results in this error.
https://github.com/PowerShell/SharePointDsc/blob/9ddfa8dbff12af52bc7eb3aa202dabdd00574a4b/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L76-L83

**Comment by Domivo** [comment]
![sp2010-cu-lp](https://user-images.githubusercontent.com/46443767/50979278-72150000-14f6-11e9-8b6d-289ae05d629a.PNG)

**Comment by ykuijs** [comment]
We are also looking for a screenshots of the file properties of the files: Right click the file > Select Properties > Click on the Details tab

**Comment by Domivo** [comment]
![properties1](https://user-images.githubusercontent.com/46443767/51020516-104ca880-157f-11e9-8421-fa93d80d1000.PNG)
![properties2](https://user-images.githubusercontent.com/46443767/51020517-104ca880-157f-11e9-9e04-e04b6d1b857c.PNG)

**Comment by ykuijs** [comment]
I see what the problem is. In SP2019, the localized patches have the words "Language Pack" in it, where in previous versions this was only used for actual Language Packs. That is why the code now thinks this is a language pack and is looking for a language code, which it does not have (CU are multi-lingual).

@andikrueger How far are you with the revised version of this module? Just wondering if it is worth the time to dive into this issue or not ;-)

**Comment by andikrueger** [comment]
@ykuijs The current implementation would have the very same problem. 

https://github.com/andikrueger/SharePointDsc/blob/5651df5cfc8e4d84b8fef1c47a9c70799b378947/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L91-L98

Wouldn't it be sufficient to check for the SharePoint Version in this if statements condition: 

https://github.com/andikrueger/SharePointDsc/blob/5651df5cfc8e4d84b8fef1c47a9c70799b378947/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L84

```
    if ($setupFileInfo.VersionInfo.FileDescription -match "Language Pack" -and -not($sharePointVersion -eq 2019))
``` 

Linking #679 for trace-ability.

**Comment by ykuijs** [comment]
I think this won't work, since this means the installation of Service Packs for Language Packs for SP2019 won't be able. Even though these probably won't be released for SP2019, I do not want to take that chance.

I rather check if we can use the File Description as well.

**Comment by andikrueger** [comment]
good point!
Is the file name "wssloc..." unique to CUs for language dependent updates or wasit used for service packs for language packs too?

**Comment by ykuijs** [comment]
Ok, did some investigation. Here are the results:

**SP2013 LP SP:**
File Description: Service Pack 1 for Microsoft SharePoint Server 2013 Language Pack (KBxxxxxx) 64-Bit Edition
Product Name: Microsoft SharePoint Server 2013 Language Pack

**SP2013 CU**
File Description: Update for Microsoft SharePoint Enterprise Server 2013 (KBxxxxxx) 64-Bit Edition
Product Name: Microsoft SharePoint Enterprise Server 2013

**SP2016 CU sts.exe**
File Description: Security Update for Microsoft SharePoint Enterprise Server 2016 (KBxxxxxx) 64-Bit Edition
Product Name: Microsoft SharePoint Enterprise Server 2016

**SP2016 CU wssloc.exe**
File Description: Update for Microsoft SharePoint Enterprise Server 2016 (KBxxxxxx) 64-Bit Edition
Product Name: Microsoft SharePoint Enterprise Server 2016

**SP2019 CU sts.exe**
File Description: Update for Microsoft SharePoint Server 2019 Core (KBxxxxxx)
Product Name: Microsoft SharePoint Server 2019 Core

**SP2019 CU wssloc.exe**
File Description: Update for Microsoft SharePoint Server 2019 Language Pack (KBxxxxxx) 64-Bit Edition 
Product Name: Microsoft SharePoint Enterprise Server 2019 Language Pack

I did some further testing and I think that updating the current regex "Language Pack" to "Service Pack.*Language Pack" will fix this issue. Agree?

**Comment by andikrueger** [comment]
Great insight on the structure of these files!

**Comment by paololec** [comment]
There are problems with CU gen SP2019 and actual dev fix.
When esecuted "wss" two times report: Update has version 16.0.10340.20015 (ok)
but then NOT detect is already installed and report "Update is a Cumulative Update" and then "The lowest version of any SharePoint component is 
16.0.10340.12101" <- (the sts package..)

So it's do a wrong a general "Get-SPDscFarmVersionInfo" (it's seems that NOT check the "Update for Microsoft SharePoint Server 2019 Language pack (KB4461514)" (that is 16.0.10340.20015).

Then go to error "17028" try to reinstall it (that is the product is already installed).

Second bug: due to the error throw it not restart the shutdown services! (this part must be execute always also if there is some errors, if the sharepoint timer services remain disabled there are many problems after.. )

**Comment by andikrueger** [comment]
This is a known issue. The current resource requires a SPConfigWizard directly after the update execution. This will Update the Configuration Database and then we are able to get the versions right. 

For more details and insight on how we plan to solve this issue see #679.

**Comment by paololec** [comment]
None, the problem si the wrong detect of "Get-SPDscFarmVersionInfo" !! 
It's NOT detect:
Update for Microsoft SharePoint Server 2019 Language pack (KB4461514)" (that is 16.0.10340.20015).

So 16.0.10340.20015 is MORE high than 16.0.10340.12101 (that is the only detect referenced to "Security Update for Microsoft SharePoint Server 2019 core (KB4461634)" and so always try to reinstall the update of Language pack already installed !!!

**Comment by andikrueger** [comment]
`Get-SPDscFarmVersionInfo` returns information obtained from the configuration database. The configuration database gets updated by executing the ConfigWizard on every server in the farm. 

Did you run the Config Wizard or did you structure your DSC configuration similar to this:
```
SPProductUpdate WSS{...}
SPConfigWizard ConfigWizard {
     DependOn = "[SPProductUpdate]WSS"
}
```

**Comment by paololec** [comment]
Yes.
The wss (kb4461514) is: 16.0.10340.20015 (high!)
the sts (kb4461634) is: 16.0.10340.12101 
![image](https://user-images.githubusercontent.com/21666251/52630195-e3601e00-2ebb-11e9-8660-caab5b6461a6.png)

Managed Patch Status report wss and sts installed correctly:
![image](https://user-images.githubusercontent.com/21666251/52630290-1f937e80-2ebc-11e9-9423-0d9ebff7b488.png)

Get-SPDscFarmVersionInfo return wrong:
Highest                        16.0.10340.12101                                                                                                                                                

The problems is in $patchableUnits line 231 is wrong:
 (($patchableUnit -notmatch "Microsoft SharePoint Server (2013|2016|2019)" -or `
                  $patchableUnit -match "Core")))

"notmatch" need do be "match" to match it correctly !!

**Comment by andikrueger** [comment]
Thank you for this valuable information.

https://github.com/PowerShell/SharePointDsc/blob/6fb1710ccbe03c1e86fbc4a8be77f3929d789e00/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L231

The code above was last changed 7 months ago and before that 2 years ago. 

@ykuijs can you confirm the proposed change?
