### ISSUE TITLE
SPInstallPrereqs: incorrect os-version on Windows Server 2019

### ISSUE THREAD

**Issue by scoreman** [PowerShell/SharePointDsc#1008]
When installing SharePoint 2019 on Windows Server 2019 the code assumes major OS-version=11 but Windows Server 2019 has major version 10 (my testing shows 10.0.17763.0 when running [System.Environment]::OSVersion).

This is no big issue today since the same features are activated for server 2016 and 2019 but it could introduce bugs in the future.

**Comment by ykuijs** [comment]
Investigate this issue and you are absolutely right. Windows Server 2019 is build 10.0.17763 (https://docs.microsoft.com/en-us/windows/desktop/sysinfo/operating-system-version, https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions#Server_versions).

I also noticed that SharePoint 2016 is also supported on Windows Server 2019 (https://docs.microsoft.com/nl-nl/windows-server/get-started-19/app-compat-19, https://docs.microsoft.com/nl-nl/SharePoint/install/hardware-and-software-requirements#software-requirements-for-sharepoint-server-2016), which the current version of the resource does not handle well. This also needs to get updated at the same time.
