### ISSUE TITLE
PSConfigWizard : Wizard fails but not error with PSConfigUI

### ISSUE THREAD

**Issue by philippe-entringer** [PowerShell/SharePointDsc#1012]
When SPConfigWizard run , the following command is performed 
**upgrade -inplace b2b -wait -force -cmd installcheck -noinstallcheck**
But the wizard fails. 
No ERROR are displayed on the upgrade log.

On the Stefan Gossner blog,  https://blogs.technet.microsoft.com/stefan_gossner/2015/08/20/why-i-prefer-psconfigui-exe-over-psconfig-exe, the following command is recommended:

**PSConfig.exe -cmd upgrade -inplace b2b -wait -cmd applicationcontent -install -cmd installfeatures -cmd secureresources -cmd services -install**
No error with this command.

So Could we use this command instead ?

#### Version of the DSC module that was used ('dev' if using current dev branch)
SharePointDSC 3.0.0.0

**Comment by ykuijs** [comment]
Good point. I will update the resource accordingly. Will be included in my next Bugfix PR.
