### ISSUE TITLE
AppCatalog - Access denied with DSC

### ISSUE THREAD

**Issue by IlleNilsson** [PowerShell/SharePointDsc#1014]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by IlleNilsson** [comment]
Details of the scenario you tried and the problem that is occurring
App Catalog will not finnish due to access permission, running as setup or farm admin account during DSC run/setup.
Verbose logs showing the problem
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:43 This event indicates that a non-termi
                                                                                  nating error was thrown when DSCEngin
                                                                                  e was executing Set-TargetResource on
                                                                                   MSFT_SPAppCatalog DSC resource. Full
                                                                                  yQualifiedErrorId is -2144108125,PSSe
                                                                                  ssionOpenFailed. Error Message is Con
                                                                                  necting to remote server SIA failed w
                                                                                  ith the following error message : The
                                                                                   WinRM client cannot process the requ
                                                                                  est. A computer policy does not allow
                                                                                   the delegation of the user credentia
                                                                                  ls to the target computer. Use gpedit
                                                                                  .msc and look at the following policy
                                                                                  : Computer Configuration -> Administr
                                                                                  ative Templates -> System -> Credenti
                                                                                  als Delegation -> Allow Delegating Fr
                                                                                  esh Credentials.  Verify that it is e
                                                                                  nabled and configured with an SPN app
                                                                                  ropriate for the target computer. For
                                                                                   example, for a target computer name
                                                                                  "myserver.domain.com", the SPN can be
                                                                                   one of the following: WSMAN/myserver
                                                                                  .domain.com or WSMAN/*.domain.com. Fo
                                                                                  r more information, see the about_Rem
                                                                                  ote_Troubleshooting Help topic..
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:43 MIResult: 1
                                                                                  Error Message: Connecting to remote s
                                                                                  erver SIA failed with the following e
                                                                                  rror message : The WinRM client canno
                                                                                  t process the request. A computer pol
                                                                                  icy does not allow the delegation of
                                                                                  the user credentials to the target co
                                                                                  mputer. Use gpedit.msc and look at th
                                                                                  e following policy: Computer Configur
                                                                                  ation -> Administrative Templates ->
                                                                                  System -> Credentials Delegation -> A
                                                                                  llow Delegating Fresh Credentials.  V
                                                                                  erify that it is enabled and configur
                                                                                  ed with an SPN appropriate for the ta
                                                                                  rget computer. For example, for a tar
                                                                                  get computer name "myserver.domain.co
                                                                                  m", the SPN can be one of the followi
                                                                                  ng: WSMAN/myserver.domain.com or WSMA
                                                                                  N/*.domain.com. For more information,
                                                                                   see the about_Remote_Troubleshooting
                                                                                   Help topic.
                                                                                  Message ID: -2144108125,PSSessionOpen
                                                                                  Failed
                                                                                  Error Category: 1
                                                                                  Error Code: 1
                                                                                  Error Type: MI
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:43 This event indicates that a non-termi
                                                                                  nating error was thrown when DSCEngin
                                                                                  e was executing Set-TargetResource on
                                                                                   MSFT_SPAppCatalog DSC resource. Full
                                                                                  yQualifiedErrorId is Microsoft.ShareP
                                                                                  oint.PowerShell.SPCmdletUpdateSPAppCa
                                                                                  talogConfiguration. Error Message is
                                                                                  Access is denied. (Exception from HRE
                                                                                  SULT: 0x80070005 (E_ACCESSDENIED)).
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:43 MIResult: 1
                                                                                  Error Message: Access is denied. (Exc
                                                                                  eption from HRESULT: 0x80070005 (E_AC
                                                                                  CESSDENIED))
                                                                                  Message ID: Microsoft.SharePoint.Powe
                                                                                  rShell.SPCmdletUpdateSPAppCatalogConf
                                                                                  iguration
                                                                                  Error Category: 6
                                                                                  Error Code: 6
                                                                                  Error Type: MI
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:43 This event indicates that failure hap
                                                                                  pens when LCM is processing the confi
                                                                                  guration. Error Id is 0x1. Error Deta
                                                                                  il is The SendConfigurationApply func
                                                                                  tion did not succeed.. Resource Id is
                                                                                   [SPAppCatalog]AppCatalog and Source
                                                                                  Info is C:\Users\inn\OneDrive - Visit
                                                                                  y AB\PowerShell\Source\DSC\~Config\SP
                                                                                  FarmDSC.ps1::136::17::SPAppCatalog. E
                                                                                  rror Message is The PowerShell DSC re
                                                                                  source '[SPAppCatalog]AppCatalog' wit
                                                                                  h SourceInfo 'C:\Users\inn\OneDrive -
                                                                                   Visity AB\PowerShell\Source\DSC\~Con
                                                                                  fig\SPFarmDSC.ps1::136::17::SPAppCata
                                                                                  log' threw one or more non-terminatin
                                                                                  g errors while running the Set-Target
                                                                                  Resource functionality. These errors
                                                                                  are logged to the ETW channel called
                                                                                  Microsoft-Windows-DSC/Operational. Re
                                                                                  fer to this channel for more details.
                                                                                  .
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:43 MIResult: 1
                                                                                  Error Message: The PowerShell DSC res
                                                                                  ource '[SPAppCatalog]AppCatalog' with
                                                                                   SourceInfo 'C:\Users\inn\OneDrive -
                                                                                  Visity AB\PowerShell\Source\DSC\~Conf
                                                                                  ig\SPFarmDSC.ps1::136::17::SPAppCatal
                                                                                  og' threw one or more non-terminating
                                                                                   errors while running the Set-TargetR
                                                                                  esource functionality. These errors a
                                                                                  re logged to the ETW channel called M
                                                                                  icrosoft-Windows-DSC/Operational. Ref
                                                                                  er to this channel for more details.
                                                                                  Message ID: NonTerminatingErrorFromPr
                                                                                  ovider
                                                                                  Error Category: 7
                                                                                  Error Code: 1
                                                                                  Error Type: MI
SIA            c619ddf8-4092-44a3-a974-1894d073a027 ERROR     2019-01-24 19:10:51 MIResult: 1
                                                                                  Error Message: The SendConfigurationA
                                                                                  pply function did not succeed.
                                                                                  Message ID: MI RESULT 1
                                                                                  Error Category: 0
                                                                                  Error Code: 1
                                                                                  Error Type: MI
SIA            c619ddf8-
Suggested solution to the issue
The DSC configuration that is used to reproduce the issue (as detailed as possible)
# insert configuration here
The operating system the target node is running
Windows 2012 R2, 2016
Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016 SP1
Version and build of PowerShell the target node is running
5.1
Version of the DSC module that was used ('dev' if using current dev branch)
3.1.0.0

**Comment by ykuijs** [comment]
Hi @IlleNilsson Looks like you didn't configure CredSSP properly. As you can see in the Wiki article for this resource (https://github.com/PowerShell/SharePointDsc/wiki/SPAppCatalog), does this resource require CredSSP to work properly.

**Comment by IlleNilsson** [comment]
Thanks, I’ll look into CredSSP


________________________________

**Comment by IlleNilsson** [comment]
Shure

**Comment by ykuijs** [comment]
Closing issue

**Comment by DennisL68** [comment]
> [...] this resource require CredSSP to work properly.

I've run into this very same issue. Do you have a any good links about how to set up CredSSP to work with this resource?

**Comment by ykuijs** [comment]
Hi @DennisL68, you need to configure CredSSP on all DSC nodes. The DSC push server does not need to have any CredSSP config at all. The reason behind this is that SPDsc is running on the DSC node and using PowerShell remoting, connecting back to the server itself. So the DSC node is both CredSSP client and server.

So you need to add these lines to your DSC config:
https://github.com/dsccommunity/SharePointDsc/blob/999074b509a49df987f4679bfd5115d1c2c2da4c/tests/Integration/Azure/DscConfigs/DomainController.ps1#L27-L37
Just update the DelegateComputers to the correct value
