### ISSUE TITLE
WaitForFarmToExist no need in example?

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/SharePointDsc#1022]
I have a simple question to ask. I used the older versions before, the example SharePoint.ps1 in the module usually contains resource "WaitForAll WaitForFarmToExist" to wait for the farm creation before joining other nodes. 

Now I noticed in the example, "JoinFarm" on the second node simply just depends on "InstallSharePoint"? 

Thanks
Tony Huang

**Comment by andikrueger** [comment]
The SPFarm resource has been updated in SharePointDsc V 3.0 to replace the obsolete SPCreateFarm and SPJoinFarm resources. 

The resource to join a farm has been replaced and any server in your configuration can create the farm. Any other server that tries to create or join a farm is waiting for the first server to create the farm.

https://github.com/PowerShell/SharePointDsc/blob/2f4dbba4e1fc1ec1273d65ea9d59ce0f34d88fc4/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L513-L524

Technically there shouldn't be the need to use the WaitFor* resources.

**Comment by ykuijs** [comment]
@andikrueger is absolutely right. With the new SPFarm resource the WaitFor is no longer required.

If this answers your question, please close the issue. If not, please let us know what more information you are looking for.

**Comment by tonyhxh** [comment]
Thanks a lot!
