### ISSUE TITLE
Please add Readme files in with the Examples

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/SharePointDsc#1024]
Readme files that sit with the examples can add a decent overview of how these are expected to be used and would make it easier in understanding the differences in Examples and specifics around order of execution (inc prereqs to being able to run them)

**Comment by ykuijs** [comment]
Hi @kilasuit The examples are used to generate the wiki pages, for example [SPFarm](https://github.com/PowerShell/SharePointDsc/wiki/SPFarm). The current examples also contain info about the example, which is used on the wiki page.

Is this similar to what you are suggesting? If not, can you explain a little more?

**Comment by ykuijs** [comment]
@kilasuit Do you have an update?

**Comment by kilasuit** [comment]
I wouldn't have thought to look at the Wiki as lots of projects don't properly use them

Perhaps add a readme that points to the wiki for completeness

**Comment by ykuijs** [comment]
Where would you think this readme would make most sense? In the root of the module, right next to the psd1 file?

**Comment by kilasuit** [comment]
In the root of each of the examples

**Comment by ykuijs** [comment]
Added a readme.md file to the root of the Examples folder. Will be included in my next Bugfix PR
