### ISSUE TITLE
SPUserProfileServiceApp should not need CredSSP anymore

### ISSUE THREAD

**Issue by Francois-Rousseau** [PowerShell/SharePointDsc#1029]
#### Details of the scenario you tried and the problem that is occurring
Trying to use SPUserProfileServiceApp and get an error message related to CredSSP. However, this is not supposed to be required since release v2.0, as resolved in issue #389.
There is also some comments about CredSSP that is required is the resource description, but it is not supposed to. Those comments should be removed.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/40836601/53089296-364c5d80-34da-11e9-8c0d-78055f4ea466.png)

#### Suggested solution to the issue
- Remove the code that throw an error about CredSSP in SPUserProfileServiceApp resource
- Remove/modify the NOTE in resource description : "NOTE: Due to the fact that SharePoint requires certain User Profile components to be provisioned as the Farm account, this resource and SPUserProfileSyncService retrieve the Farm account from the Managed Accounts. This does however mean that CredSSP is required, which has some security implications. More information about these risks can be found at: http://www.powershellmagazine.com/2014/03/06/accidental-sabotage-beware-of-credssp/"
- Remove "Requires CredSSP: Yes" in resource description
- Remove mention "Requires CredSSP **" after SPUserProfileServiceApp in the resource list. 
 
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
            SPUserProfileServiceApp UserProfileServiceApp
            {
                Name                         = "User Profile Service Application"
                ApplicationPool              = "SecurityTokenServiceApplicationPool"
                ProfileDBName = "User Profile Service Application_ProfileDB"
                SocialDBName = "User Profile Service Application_SocialDB"
                SyncDBName = "User Profile Service Application_SyncDB"
                #MySiteHostLocation

                PsDscRunAsCredential         = $InstallCredential
            }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard Evaluation
OsOperatingSystemSKU : 79
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2791.amd64fre.rs1_release.190205-1511
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                 
----                           -----                                                                                                                 
PSVersion                      5.1.14393.2791                                                                                                        
PSEdition                      Desktop                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
BuildVersion                   10.0.14393.2791                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                       
WSManStackVersion              3.0                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                   
SerializationVersion           1.1.0.1 

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.1.0.0

**Comment by ykuijs** [comment]
You are partly right, we removed the CredSSP dependency in v2.0, but had to put it back in v2.2 because of a technical issue we hadn't thought about. This has been discussed in #709.

So unfortunately we still require CredSSP for this (and some other) resource.

**Comment by Francois-Rousseau** [comment]
Thanks @ykuijs for the answer.
I close this issue.
