### ISSUE TITLE
SPFarm: dev branch exception with Dev Dashboard

### ISSUE THREAD

**Issue by ronx** [PowerShell/SharePointDsc#1032]
Using dev branch (and not adding DeveloperDashboard param to SPFarm) to create new farm, hit the following exception:

PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Exception setting "DisplayLevel": "Cannot convert null to type 
"Microsoft.SharePoint.Administration.SPDeveloperDashboardLevel" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The 
possible enumeration values are "Off,OnDemand,On"." 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure

**Comment by ykuijs** [comment]
Also encountered this issue and already implemented a fix in my dev branch. Will be included in my next Bugfix PR

**Comment by ykuijs** [comment]
Fixed in PR #1036
