### ISSUE TITLE
MSFT_SPInstall failed with exit code 30030

### ISSUE THREAD

**Issue by ThomasLie** [PowerShell/SharePointDsc#1034]
Hey there,

I'm currently facing issues with SP DSC, getting errors as below:

Event ID 4252
PowerShell DSC resource MSFT_SPInstall failed to execute Set-TargetResource functionality with error messsage: SharePoint install failed, exit code was 30030.

Event ID 4097:
The SendConfigurationApply did not succeed.

The handle is invalid

OS: Windows Server 2016
SharePoint version to install 2019
SharePointDsc version: 3.1.0.0

Thanks in advance...

Regards
Thomas

**Comment by considerITman** [comment]
Hi Thomas,

It appears that you were able to resolve the issue within the day.
Could you kindly point me towards the solution?

Thanks!
Alex

**Comment by ThomasLie** [comment]
Hi Alex,

It's been almost a year since I opened the issue...honestly, I can't remember...sorry...

Regards,
Thomas

**Comment by considerITman** [comment]
Hi Thomas,

no worries, thanks for taking the time to get back to me! 

Take care,
Alex

**Comment by considerITman** [comment]
For anyone with the same issue:
**Check your ProductKey Parameter!**

Learn from my mistakes - SP2019 will expect a valid SP2019 license key 😅

**Comment by ykuijs** [comment]
Thanks for updating the issue with your solution, even though the problem was between the keyboard and the chair 😆

**Comment by ThomasLie** [comment]
Well, my client provided a SP2016 Key for a SP2019 installation 😉

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Büroservices GbR
Ilse-Pohl-Strasse 67
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  http://www.lieftüchter.de/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Donnerstag, 5. März 2020 16:26
An: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; State change <state_change@noreply.github.com>
Betreff: Re: [dsccommunity/SharePointDsc] MSFT_SPInstall failed with exit code 30030 (#1034)


Thanks for updating the issue with your solution, even though the problem was between the keyboard and the chair 😆

**Comment by considerITman** [comment]
> Thanks for updating the issue with your solution, even though the problem was between the keyboard and the chair 😆

Maybe I can save someone a bunch of hair 😉
Layer 8 errors happen 😂
