### ISSUE TITLE
SPInfoPathFormsServiceConfig: Allow setting the property for Performance Optimization

### ISSUE THREAD

**Issue by cvollmann** [PowerShell/SharePointDsc#1040]
#### Details of the scenario you tried and the problem that is occurring
As mentioned in this support article by Microsoft (https://support.microsoft.com/en-us/help/2984138/forms-timeout-or-take-a-long-time-to-open-in-infopath-2010-or-infopath) we had problems after migrating a InfoPath Form from a SP 2013 to a SP 2016 environment. We used DSC to build the new enviroment and tried to replicate all settings from the old farm regarding Service Applications.

This particular property was not set by us because it was not part of the DSC ressource.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Add the property to the ressource. 

- The setter in plain PowerShell is pretty straightforward:
```powershell
$f = Get-SPInfoPathFormsService
$f.Properties.Add("AllowEventPropagation", $false)
$f.Update()
```
- The test should check if the property is there and then if the value is false.
- The getter should check for the property and then the value.
- The "true" state should be the removed property,

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.18969.amd64fre.winblue_ltsb.180309-0600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running

PSVersion: 5.1.14409.1005
BuildVersion: 10.0.14409.1005

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.1.0.0

The current version is also missing this property.

**Comment by ykuijs** [comment]
Will be added in my next Bugfix PR
