### ISSUE TITLE
SPSelfServiceSiteCreation: New SP 2019 SelfService Site Settings Web Application Properties need to be added

### ISSUE THREAD

**Issue by pstork** [PowerShell/SharePointDsc#1043]
### ISSUE TITLE:
SPSelfServiceSiteCreation: New SP 2019 SelfService Site Settings Web Application Properties need to be added

### ISSUE DESCRIPTION:
In SharePoint 2019 the SharePoint Home is always displayed on the web application used for OneDrive. Team and Communication sites that are created using the "Create Site" link on that page are therefore created on the OneDrive web application also. This default behavior can be changed by editing the Self-Service Site Settings on the OneDrive Web application in Central Admin. There appear to be two new properties that are used to control this behavior, SelfServiceCreationAlternateUrl  and SelfServiceCreationManagedPath. Changes made in the UI only increment the Version property and the SelfServiceCreationAlternateUrl on the Web Application. Changes made in the UI do change the behavior of the 'Create Site' link.  But changes made using PowerShell to the same properties are not reflected in the Web Application UI. I have not been able to find a way to change these properties programmatically.

#### Details of the scenario you tried and the problem that is occurring
Tried changing the Alternate URL setting for the Self-Service settings on the Web Application using both the UI and PowerShell.  The changes are effective in the UI, but not in PowerShell.

#### Verbose logs showing the problem
Nothing to show in the logs

#### Suggested solution to the issue
 I have a Pull request with the two new parameters implemented. The parameters work, but the  changes don't do anything.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
#This would be the proposed configuration for the resource if I could get PowerShell to work. 
SPSelfServiceSiteCreation SSC
            {
                WebAppUrl = $OneDriveUrl
                Enabled   = $true
                OnlineEnabled = $false
                ShowStartASiteMenuItem = $true
                CreateIndividualSite = $false
                SelfServiceManagedPath = 'sites'
                SelfServiceAlternateUrl = $PortalUrl
                PsDscRunAsCredential    = $SPInstallCreds
                DependsOn = @('[SPWebApplication]SharePointSites', '[SPWebApplication]OneDriveSites')
            }

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Pull from dev

**Comment by ykuijs** [comment]
Will be included in my next Bugfix PR

**Comment by pstork** [comment]
Thanks, then I will just drop the pull I did and let you handle it.  Much appreciated.
