### ISSUE TITLE
Typo in SPSearchContentSource.psm1

### ISSUE THREAD

**Issue by okeol** [PowerShell/SharePointDsc#1047]
In the file 
Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1 
there is a typo in line 880.
The parameter "ContinousCrawl" doesnt exist anywhere, it has to be "ContinuousCrawl" (with "nUou").
With this typo the parameter "ContinuousCrawl" will never be checked correctly and a change of it never be detected.   (If I undestood the whole mechanisms correctly ...)

Thats's not a big deal, since not many people will _change_ the crawl type with DSC.
But perhaps someone could clean that up - my github knowledge is too small for a pull/change/whatever

thx for that 

Okee

**Comment by ykuijs** [comment]
Is included in my Bugfix PR
