### ISSUE TITLE
SPInstallPrereqs potentially problem checking version

### ISSUE THREAD

**Issue by HeKr09** [PowerShell/SharePointDsc#1062]
#### Details of the scenario you tried and the problem that is occurring
Trying to install SharePoint 2019 and wondered about an error while installing Prereqs. The version was not correct.
I wondered about the code within the ressource.

#### Verbose logs showing the problem
Prerequisite [PLaceholder] was found but had unexpected version. Expected minimum version [WAS EMPTY] but found version 14.12.X.Y.

#### Suggested solution to the issue
The code seems to be not correct or do I forgot anything? I guess the if is not correct for e.g. the following values:
MinimumRequiredVersion: 15.1.0.3
InstalledVersion: 16.0.1.2
Afterwards $isRequiredVersionInstalled is $false I guess but should be $true?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
The code implemented was:
```powershell
                    $isRequiredVersionInstalled = $true;

                    [int[]]$minimumRequiredVersion = $itemToCheck.MinimumRequiredVersion.Split('.')
                    [int[]]$installedVersion = $installedItem.DisplayVersion.Split('.')
                    for ([int]$index = 0; $index -lt $minimumRequiredVersion.Length -and $index -lt $installedVersion.Length; $index++)
                    {
                        if ($minimumRequiredVersion[$index] -gt $installedVersion[$index])
                        {
                            $isRequiredVersionInstalled = $false;
                        }
                    }
```

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.3.0.0

**Comment by ykuijs** [comment]
Hi @HeKr09 This error message is given when one of the required components is installed, but not the correct version (too low version). Based on the version number you gave (14.12) I guess this is the C++ library, but without the exact error this is hard to say.

The check you are referring to checks if the minimum version is greater than the actual installed version. If this is true, the required version is NOT installed since the installed version is lower that the required version. Therefore the variable is set to false.

**Comment by HeKr09** [comment]
Yeah but I wondered about the check method.
If I do have the minimum version 15.1.0.3 and the installed version is 16.0.1.2 I'd expect a true within the variabel $isRequiredVersionInstalled. But the implemented code will return false I guess. Am I wrong?

If you run thorugh the code:
First loop
`if(15 -gt 16) -> $isRequiredVersionInstalled = $true`
Second loop
`if(1 -gt 0) -> $isRequiredVersionInstalled = $false`
Third loop
`if(0 -gt 1) -> $isRequiredVersionInstalled = still $false`
Fourth loop
`if(3 -gt 2) -> $isRequiredVersionInstalled = still $false`

If you check the version logically
`if(15.1.0.3 -gt 16.0.1.2) -> $isRequiredVersionInstalled = should be $true`

Do I get something wrong?

**Comment by ykuijs** [comment]
No I get what you mean! :-)

Will dig into this and get back to you asap!

**Comment by ykuijs** [comment]
@jensotto Since you added this piece of code:
https://github.com/PowerShell/SharePointDsc/blob/736c08612a73f7f11502af9e9685f144fca81365/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L1117-L1135

What was the reason you used this code instead of something like the following:
```PowerShell
[System.Version]$minimumRequiredVersion -gt [System.Version]$installedVersion
```

**Comment by jensotto** [comment]
That looks a lot cleaner. Not sure why I didn't think of something like that. I created a test for that scenario, so as long as that does not fail I don't see why your code could replace my convoluted code :)

**Comment by jensotto** [comment]
I see the problem in my code. Stupid mistake. Using the System.Version makes a lot more sense.

**Comment by ykuijs** [comment]
Ok, no problem mate! Will update the resource with alternative check. Will be included in my next bugfix PR!
