### ISSUE TITLE
NewResourceName: SPProductSlipstream

### ISSUE THREAD

**Issue by ColinHJ** [PowerShell/SharePointDsc#1069]
### Description
When doing a slipstream install of SharePoint 2016 and using a feature pack 1 mini role. The install hangs silently with a debugger in the background. I have seen this in multiple farms. I'm currently using the below script resource to install the patch post SharePoint install. I'm not sure if a new resource should be created or the SPProductUpdate should be updated. The below logic should allow for testing of an update before building the farm.

### Proposed properties
$STSFilePath = "E:\Share\sts2016-kb4464510-fullfile-x64-glb.exe"
        Script STSPatch
        {
            SetScript = {
                Start-Process $using:STSFilePath -ArgumentList "/quiet" -wait
            }
            TestScript = { 
                $UninstallDisplaynames = Get-ChildItem HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall | Where {$_.Name -match '(([0-9A-Fa-f]{8}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{12}))'} | Get-ItemProperty -Name DisplayName
                $UpdateName = Get-Item -Path $using:STSFilePath | Select @{name="UpdateName"; expression={$_.versioninfo.FileDescription}}
                Return $UpdateName.UpdateName -in $UninstallDisplaynames.DisplayName
            }
            GetScript = { @{ Result = (Get-ChildItem HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall | Where {$_.Name -match '(([0-9A-Fa-f]{8}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{4}[-][0-9A-Fa-f]{12}))'} | Get-ItemProperty -Name DisplayName) } }
            PsDscRunAsCredential      = $SPSetupAccount
            DependsOn = "[SPInstallLanguagePack]InstallLPBinaries"
        }

### Special considerations or limitations
mini roles that do not exist in the RTM install.

**Comment by ykuijs** [comment]
Hi @ColinHJ, it is possible to install a slipstreamed version of SharePoint using the SPInstall resource. You can then use SPFarm to create the new farm, which checks the version of the installed binaries and allows the two new Minroles introduced in Feature Pack 1 to be used.

With the updated version of SPProductUpdate , introduced in v3.3, you should also be install to install the RTM version of SharePoint and install a CU before creating the farm. Afterwards you should be able to use SPFarm to create the farm with the new Minroles.

What exactly is the scenario you are describing here? What are you trying to do? Do you have example configs? And do you get any error messages?

**Comment by andikrueger** [comment]
As @ykuijs said, with the latest update of the SPProductUpdate resource you are able to install SharePoint updates before creating a farm.

There is a known (but not blocking) issue with slipstreaming of SP 2016: https://docs.microsoft.com/en-us/sharepoint/support/server-install/administration-tool-stopped-working-during-a-slipstream-installation

**Comment by ColinHJ** [comment]
I checked the SPProducts Wiki when I was updating my script. It still reflects the Farm requirement. I see in the change log the update to SPProducts in v3.3. I will try that.

**Comment by ykuijs** [comment]
Hi Collin, good point! With the release of v3.3, we didn't update the Readme file. I have just updated that, which will be included in the v3.5 (we auto generate the Wiki content), but is already available in the [Dev branch](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md)

Thanks for pointing that out!
