### ISSUE TITLE
SPSecureStoreServiceApp is set to absent but test finds it and set does not.

### ISSUE THREAD

**Issue by Bjorn80** [PowerShell/SharePointDsc#1070]
#### Verbose logs showing the problem

VERBOSE: [VM0013]: LCM:  [ Start  Test     ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Testing secure store service application Secure Store Service Application
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Getting secure store service application 'Secure Store Service Application'
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Executing as the local run as user CONTOSO\SPAdmin
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Specified database name does not match the actual database name. This resource cannot rename the database.
VERBOSE: [VM0013]: LCM:  [ End    Test     ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]  in 0.2660 seconds.
VERBOSE: [VM0013]: LCM:  [ Start  Set      ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Setting secure store service application 'Secure Store Service Application'
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Getting secure store service application 'Secure Store Service Application'
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Executing as the local run as user CONTOSO\SPAdmin
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Removing Secure Store Service Application Secure Store Service Application
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Executing as the local run as user CONTOSO\SPAdmin
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
Object not found.
    + CategoryInfo          : ObjectNotFound: (Microsoft.Share...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGetServiceApplication
    + PSComputerName        : localhost
 
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplicationProxy.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplicationProxy.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplicationProxy.
VERBOSE: [VM0013]: LCM:  [ End    Set      ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]  in 0.4220 seconds.
PowerShell DSC resource MSFT_SPSecureStoreServiceApp  failed to execute Set-TargetResource functionality with error message: You cannot call a method on a null-valued expression. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [VM0013]:                            [] Consistency check completed.
The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration manually.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 81.671 seconds

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
ServiceApplications = @{
    AccessService             = "Absent"                          # Present or Absent. Requires SQL Mixed mode authentication.
    AppManagementService      = "Absent"                         # Present or Absent. 
    MachineTranslationService = "Present"                         # Present or Absent. 
    ManagedMetadataService    = "Absent"                         # Present or Absent. 
    PerformancePointService   = "Present"                         # Present or Absent. 
    ProjectServerService      = "Absent"                         # Present or Absent. 
    SearchService             = "Present"                         # Present or Absent. 
    SecureStoreService        = "Absent"                         # Present or Absent. 
    SubScriptionService       = "Present"                         # Present or Absent. 
    UserProfileService        = "Absent"                         # Present or Absent. 
    VisoGraphicsService       = "Present"                         # Present or Absent.
    WordAutomationService     = "Absent"                         # Present or Absent. 
    WorkFlow                  = "Present"                         # Present or Absent. 
}     


# SECURESTORE SA
SPSecureStoreServiceApp SecureStoreServiceApp
{
    Name                 = "Secure Store Service Application"
    Ensure               = $ConfigurationData.NonNodeData.SharePoint.ServiceApplications.SecureStoreService
    ApplicationPool      = $ConfigurationData.NonNodeData.SharePoint.ApplicationPool
    AuditingEnabled      = $true
    AuditlogMaxSize      = 30
    DatabaseName         = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "SecureStore")
    PsDscRunAsCredential = $SPSetupCred
    DependsOn            = "[AddEntryToLog]Log_SPSubscriptionSettingsServiceApp"
}

#### The operating system the target node is running
Microsoft server 2012 R2 Standard
StandardServerEdition
64-bit
Eng-Us

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP 2016 Update may 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.3.0.0

**Comment by ykuijs** [comment]
Hi @Bjorn80 thanks for reporting this issue. I just investigated and see what is happening here:
If I am not mistaking, you environment doesn't have the SecureStore ServiceApp deployed, right?

The Test method calls the Get method. You log shows that just the Get-SPServiceApplication cmdlet is called, indicating that it didn't return anything, so the Get method returns a NullReturn variable.

Since your config specified a Database name, the Test method checks if it matches the value returned by the Get method. That doesn't contain a database name, so it returns False (which shouldn't happen).

Because the Test method fails, the Set method is called where it tried to delete the ServiceApp which does not exist.

Will update the resource, so this won't happen anymore. Will be included in my next Bugfix PR.

**Comment by Bjorn80** [comment]
Hi @ykuijs 
That is right the service application should be absent but a default database name is hardcoded in the dscressource.
Thanks for the quick reply and information.
brgs

Bjørn
