### ISSUE TITLE
SPWebAppAuthentication: Specified Web Application is using Classic Authentication and Claims Authentication is specified.

### ISSUE THREAD

**Issue by brussell41** [PowerShell/SharePointDsc#1076]
#### Details of the scenario you tried and the problem that is occurring

When creating a SPWebApplication that has UseClassic set to $true, the SPWebAppAuthentication module throws an error stating: Specified Web Application is using Classic Authentication and Claims Authentication is specified.  For the Default Zone, I have attempted to use Kerberos as the authentication method, and even changed it to NTLM to see if that would resolve the issue, but no joy. 

No other zones are configured; just Default.

#### Verbose logs showing the problem

{ "Exception": { "Message": "PowerShell DSC resource MSFT_SPWebAppAuthentication failed to execute Set-TargetResource functionality with error message: Specified Web Application is using Classic Authentication and Claims Authentication is specified. Please use Convert-SPWebApplication first! ", "Data": { }, "InnerException": { "SerializedRemoteException": "System.Management.Automation.RuntimeException: Specified Web Application is using Classic Authentication and Claims Authentication is specified. Please use Convert-SPWebApplication first!", "SerializedRemoteInvocationInfo": "System.Management.Automation.InvocationInfo", "ErrorRecord": "Specified Web Application is using Classic Authentication and Claims Authentication is specified. Please use Convert-SPWebApplication first!", "WasThrownFromThrowStatement": false, "Message": "Specified Web Application is using Classic Authentication and Claims Authentication is specified. Please use Convert-SPWebApplication first!", "Data": "System.Collections.ListDictionaryInternal", "InnerException": null, "TargetSite": "Void EndInvoke()", "StackTrace": " at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()\r\n at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)\r\n at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32\u0026 resultStatusHandle, Collection`1\u0026 result, ErrorRecord\u0026 errorRecord, PSModuleInfo localRunSpaceModuleInfo)", "HelpLink": null, "Source": "System.Management.Automation", "HResult": -2146233087 }, "TargetSite": null, "StackTrace": null, "HelpLink": null, "Source": null, "HResult": -2146233079 }, "TargetObject": null, "CategoryInfo": { "Category": 7, "Activity": "", "Reason": "InvalidOperationException", "TargetName": "", "TargetType": "" }, "FullyQualifiedErrorId": "ProviderOperationExecutionFailure", "ErrorDetails": null, "InvocationInfo": null, "ScriptStackTrace": null, "PipelineIterationInfo": [ ] }

#### The operating system the target node is running

Windows Server 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2016 w/May 2019 patch (KB4464549)

#### Version and build of PowerShell the target node is running

PowerShell v5.1.18362.113

#### Version of the DSC module that was used ('dev' if using current dev branch)

SharePointDSC: 3.4.0.0

**Comment by ykuijs** [comment]
Hi @brussell41, when using SPWebAppAuthentication and classic, you have to specify Classic as the AuthenticationMethod in this resource. When specifying NTLM and Kerberos, the use of Claims is implied.

Can you please share your config to validate this?

**Comment by brussell41** [comment]
Ok, that would make sense since I stated Kerberos as my desired authentication method.   I do not see this notated anywhere in the documentation, so could we update? 

My config is as follows: 

       SPWebAppAuthentication MIMWAAuthentication {
            WebAppUrl = "http://mim.contoso.com"
            Default = @(MSFT_SPWebAppAuthenticationMode {
                    AuthenticationMethod = "Kerberos"
                }
            )
            DependsOn = "[SPWebApplication]MIMWebApplication"
            PsDSCRunAsCredential   = $DomainCred
        }

**Comment by ykuijs** [comment]
You need to use AuthenticationMethod = "Classic" in order to configure classic.

I will check out the documentation and update where required. Thanks for reporting!
