### ISSUE TITLE
SPProduct Update 

### ISSUE THREAD

**Issue by xenophobentx** [PowerShell/SharePointDsc#1078]
https://github.com/PowerShell/SharePointDsc/wiki/SPProductUpdate

Is the following sections still valid?

"IMPORTANT: This resource retrieves build information from the Configuration Database. Therefore it requires SharePoint to be installed and a farm created. If you like to deploy a new farm and install updates automatically, you need to implement the following order:

Install the SharePoint Binaries (SPInstall)
(Optional) Install SharePoint Language Pack(s) Binaries (SPInstallLanguagePack)
Create SPFarm (SPFarm)
Install Cumulative Updates (SPProductUpdate)
Run the Configuration Wizard (SPConfigWizard)"

As far as i understand 3.4 now use a different method to retreive build info.

**Comment by andikrueger** [comment]
This information is no longer correct. With the latest update, it’s possible to install an update directly after the initial setup. 
Keep in mind to install language packs prior to a CU. 
@ykuijs could you update the wiki?

**Comment by ykuijs** [comment]
The Wiki pages are generated by the build process, based on the [Readme file](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md). I will update the readme file, so the Wiki will be updated with the next release.
