### ISSUE TITLE
SearchServiceInstance not found

### ISSUE THREAD

**Issue by ThomasLie** [PowerShell/SharePointDsc#1079]
Hi there,

having an issue with creating new search topology: DSC returns error 'SearchServiceInstance is not found on server SP001.

Checked the instance on the server and it is online.

I'm usind SharePoint 2019 with German langiuage pack on Windows Server 2016.
SharePointDSC version is 3.3.0.0

Any help is aprreciated...

Thanks in advance...

**Comment by ykuijs** [comment]
Hi @ThomasLie Can you please share your config and the Verbose output of the deployment?

**Comment by ThomasLie** [comment]
Hi,

meanwhile we solved the issue, was due to a couple of group policies. 

Regards
Thomas

**Comment by ykuijs** [comment]
Hi @ThomasLie, could you please share which policies caused this and what setting of those policies was the solution? This might be beneficial to others or we could include this in our documentation.

**Comment by ykuijs** [comment]
@ThomasLie Do you have the opportunity to share the policies that caused this issue?

**Comment by ThomasLie** [comment]
Hi Yorik,

I‘m currently on vacation...going to share the GPO when I‘m back...

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT-Consulting & Büroservices GbR
Ilse-Pohl-Str. 67
63303 Dreieich - Germany
Fon: +49 171.2625166
Email: thomas@lieftuechter.de
Web: http://www.lieftüchter.de/TL
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
________________________________
Von: Yorick Kuijs <notifications@github.com>
Gesendet: Wednesday, July 3, 2019 8:06:14 PM
An: PowerShell/SharePointDsc
Cc: Thomas Lieftüchter; Mention
Betreff: Re: [PowerShell/SharePointDsc] SearchServiceInstance not found (#1079)


@ThomasLie<https://github.com/ThomasLie> Do you have the opportunity to share the policies that caused this issue?

**Comment by ykuijs** [comment]
Hi @ThomasLie, are you able to share the GPO so we have the resolution of this issue properly documented>

**Comment by ThomasLie** [comment]
Hi Yorick,

I discussed this with my client and I’m not allowed to share any information.

I’m sorry…

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Büroservices GbR
Ilse-Pohl-Strasse 67
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  http://www.lieftüchter.de/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Dienstag, 29. Oktober 2019 15:24
An: PowerShell/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [PowerShell/SharePointDsc] SearchServiceInstance not found (#1079)


Hi @ThomasLie<https://github.com/ThomasLie>, are you able to share the GPO so we have the resolution of this issue properly documented>

**Comment by ykuijs** [comment]
That is too bad, would really help others in the future. Isn't only sharing the name of the policy and the value with which is breaks an option? Just so someone else in the future is able to check out that policy when running into the same issue.

**Comment by ThomasLie** [comment]
Hi Yorick,

going to ask the client on Monday…one of the keywords is CredSSP ;-)

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Büroservices GbR
Ilse-Pohl-Strasse 67
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  http://www.lieftüchter.de/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Donnerstag, 31. Oktober 2019 14:10
An: PowerShell/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [PowerShell/SharePointDsc] SearchServiceInstance not found (#1079)


That is too bad, would really help others in the future. Isn't only sharing the name of the policy and the value with which is breaks an option? Just so someone else in the future is able to check out that policy when running into the same issue.

**Comment by ykuijs** [comment]
Issue has been resolved, closing this issue. @ThomasLie if you are able to share the name of the policy and the value you had to configure to get it to work, please add this to the issue.

**Comment by ThomasLie** [comment]
Hi Yorick,

a bit late...

My client disabled CredSSP completely...this caused some other issues as well...

Computer Configuration | Administrative Templates | System | Credentials Delegation

I good guide, how to configure CredSSP via GPO can be found here:
https://www.jfe.cloud/how-to-enable-credssp-for-powershell-remoting-through-gpo/

Regards,
Thomas
