### ISSUE TITLE
SPExcelServiceApp: Get Method throws error

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SharePointDsc#1081]
#### Details of the scenario you tried and the problem that is occurring
The Get-DscConfiguration Cmdlet throws an error when SPExcelServiceApp is called.

#### Verbose logs showing the problem
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Importing the module MSFT_SPExcelServiceApp in force mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Importing the module MSFT_SPExcelServiceApp in force mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Getting Excel Services Application 'SCWZUDA0SPSEXL'
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Executing as the local run as user CHLOROPHYLLE\CSAPTTD10SPSFFP
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Leaving BeginProcessing Method of Get-SPServiceApplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Leaving ProcessRecord Method of Get-SPServiceApplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Leaving EndProcessing Method of Get-SPServiceApplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Leaving BeginProcessing Method of Get-SPExcelFileLocation.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Leaving ProcessRecord Method of Get-SPExcelFileLocation.
COMMENTAIRES : [SPS15DEV01]:                            [[SPExcelServiceApp]APPLICATION_Exc
elService] Leaving EndProcessing Method of Get-SPExcelFileLocation.
Get-DscConfiguration : GetConfiguration did not succeed.
Au caractère Ligne:1 : 1
+ Get-DscConfiguration -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DSCLocalConfigurationManager:root/Micro 
   soft/...gurationManager) [Get-DscConfiguration], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Get-DscConfiguratio

Event log:
Message Cannot convert value "-1" to type "System.UInt64". Error: "Value was either too large or too small for a UInt64." 
HResult : -2147467262 
StackTrack :    at System.Management.Automation.LanguagePrimitives.ConvertStringToInteger(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo[T](Object valueToConvert)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetPSObjectValue(CimType cimType, Object propertyValue)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamsHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)

#### Suggested solution to the issue
Change parameter PrivateBytesMax and UnusedObjectAgeMax to System.String

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        SPExcelServiceApp APPLICATION_ExcelService
        {
            Name = 'SCWZUDA0SPSEXL'
            ApplicationPool = 'SharePoint Service Applications'
            PsDscRunAsCredential = $credential
            TrustedFileLocations = MSFT_SPExcelFileLocation
            {
                Address = "https://"
                LocationType = 'SharePoint'
                IncludeChildren = $true
                WarnOnDataRefresh = $true
                AbortOnRefreshOnOpenFail = $true
                UdfsAllowed = $true
                ExternalDataAllowed = 'DclandEmbedded'
                DefaultWorkbookCalcMode = 'File'
                DisplayGranularExtDataErrors = $true
                SessionTimeout = 450
                ShortSessionTimeout = 450
                NewWorkbookSessionTimeout = 1800
                RequestDurationMax = 300
                WorkbookSizeMax = 10
                ChartAndImageSizeMax = 1
                PeriodicExtDataCacheLifetime = 300
                ManualExtDataCacheLifetime = 300
                ConcurrentDataRequestsPerSessionMax = 5
                AutomaticVolatileFunctionCacheLifetime = 300
                RESTExternalDataAllowed = $false
                Description = 'https Excel File location'
            }
        }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64 bits
WindowsBuildLabEx    : 9600.19376.amd64fre.winblue_ltsb_escrow.190520-1700
OsLanguage           : en-US
OsMuiLanguages       : {en-US, fr-FR}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.4.0.0

**Comment by ykuijs** [comment]
Although changing the type to String will work, the issue is caused by the fact that the type is set to an unsigned Integer instead of a signed integer.

As you can see in Example 2 of [Set-SPExcelServiceApplication](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spexcelserviceapplication?view=sharepoint-ps#examples), a value of -1 means that Excel will use half of the available memory. Unfortunately the value of -1 cannot be stored in an UInt32, instead the SInt32 needs to be used.

**Comment by luigilink** [comment]
So I need to change parameter to SInt32, I already changed to string. I'll do it ASAP.

**Comment by ykuijs** [comment]
See my comment in the PR for details. There is a slight difference in change between the schema and the psm1 file.
