### ISSUE TITLE
Apply vscode auto-formatting to all files

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#1085]
Currently there are many files, that are not formatted properly. 
Running the vscode auto-formatting should fix this issue.

@ykuijs There is one general question with auto-formatting:

Currently we format the following code block like this:

```powershell
    $result = Invoke-SPDscCommand -Credential $InstallAccount `
                                  -Arguments $PSBoundParameters `
                                  -ScriptBlock {
```

After runing auto-format, this block will look like this:

```powershell
  $result = Invoke-SPDscCommand -Credential $InstallAccount `
        -Arguments $PSBoundParameters `
        -ScriptBlock {
```

Is this something you care about?

**Comment by ykuijs** [comment]
Personally, I find the first one better readable. Do you know if there is way to have VSCode use that formatting? If not, let's stick to the second one.

**Comment by andikrueger** [comment]
I did not find a setting  for option 1. Maybe @johlju knows a way?

**Comment by johlju** [comment]
Don’t think it is possible to align the dashes when continue the row on the next row. 
Maybe @bergmeister can give a definitive answer is PSScriptAnalyzer supports that.

**Comment by bergmeister** [comment]
I am not aware of such a feature but PSSA has options for hashtable alignments IIRC, therefore I suggest to use splatting

**Comment by andikrueger** [comment]
Thank you for your feedback. We do have several functions already, that use splatting.

**Comment by andikrueger** [comment]
Reopening. Closed it by mistake
