### ISSUE TITLE
SPFarm: SingleServer maybe obsolet

### ISSUE THREAD

**Issue by HeKr09** [PowerShell/SharePointDsc#1104]
#### Details of the scenario you tried and the problem that is occurring
I want to install a SingleServerFarm and wondered about the DSC resource SPFarm where you can choose a server role between "SingleServer" and "SingleServerFarm". In later installations I've choosen "SingleServerFarm" and it worked fine.
Now I found a thread about this [topic](https://github.com/PowerShell/SharePointDsc/issues/489) but as far as I understood there is a bug within the product when a server joins a farm.

So when do I choose the server role "SingleServer"? At join or install or what scenario? Isn't it possible to remove this value?

#### Verbose logs showing the problem
n/a

#### Suggested solution to the issue
Remove "SingleServer"?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
n/a

#### The operating system the target node is running
n/a

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
n/a

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.5.0.0

**Comment by ykuijs** [comment]
Not sure where the SingleServer value came from, but it indeed should be SingleServerFarm for a single server.

**Comment by ykuijs** [comment]
The SingleServer was already present in the old SPCreateFarm resource and was copied across to the current SPFarm resource.

Since SingleServer isn't an accepted value, I will remove it in a next bugfix PR

**Comment by ykuijs** [comment]
This issue is now fixed in dev and will be released with v3.7
