### ISSUE TITLE
SPConfigWizard: Psconfig won't run when upgraded needed starting with 3.5.0.0

### ISSUE THREAD

**Issue by iosgitr** [PowerShell/SharePointDsc#1107]
#### Details of the scenario you tried and the problem that is occurring

SPConfigWizard works in 3.4.0.0 but starting with 3.5.0.0, the check that was added below prevents pconfig wizard from running when it needs to be run.

https://github.com/PowerShell/SharePointDsc/blob/d714e5b2929939a5164113ba2d720aabdd8e7d47/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1#L100-L108

I've confirmed that running `Get-SPDscServerPatchStatus` manually on a farm server returns `NoActionRequired` if psconfig doesn't need to be run and `UpgradeAvailable` if it needs to be run.  Basically the same server status you'd see in Central Admin.  SPConfigWizard however only runs psconfig if `Get-SPDscServerPatchStatus` returns `NoActionRequired` which doesn't seem right.

For now, I've removed the SPConfigWizard code above in our copy and it works again.

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Possibly check for a different `Get-SPDscServerPatchStatus` return value?  I haven't looked into what `InstallRequired` status means but maybe that's an indication that some servers are missing binaries?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

N/A

#### The operating system the target node is running

Windows 2012 R2

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2013

#### Version and build of PowerShell the target node is running

5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

3.5.0.0

**Comment by ykuijs** [comment]
Hi @iosgitr, I am checking this issue however I cannot figure it out just yet. Can you please share your config for SPConfigWizard?

**Comment by ykuijs** [comment]
Did some more digging. You are right, we should not check for NoActionRequired, but for UpgradeRequired and UpgradeAvailable. Will update this in a next bugfix PR

**Comment by ykuijs** [comment]
This issue is now fixed in dev and will be released with v3.7
