### ISSUE TITLE
New Proposal for the SPFeature resource

### ISSUE THREAD

**Issue by jimbrayDel** [PowerShell/SharePointDsc#1113]
ISSUE TITLE:
Allowing the SPFeature Resource to handle multiple Web Applications on execution.

    ISSUE DESCRIPTION
In executing a complex Build the current module activates features on a web application.
SPFeature 6a06509d-2172-49f5-b6df-51ccc2b71bd1
        {
            Version              = "15.0.4.0";
            Name                 = "PublishingTimerJobs";
            FeatureScope         = "WebApplication";
            Ensure               = "Present";
            PsDscRunAsCredential = $CredFarm;
            Url                  = "https://web.myappdomain.com/";
        }
This feature may possibly need to be enabled on many web applications. 
Currently you need a Feature block for each web app, in my case I have 15 web apps on the farm, so I would have 15 of these exact Feature blocks with only the URL being different.

Proposal: 
 What is it could be done this way

SPFeature 6a06509d-2172-49f5-b6df-51ccc2b71bd1
        {
            Version              = "15.0.4.0";
            Name                 = "PublishingTimerJobs";
            FeatureScope         = "WebApplication";
            Ensure               = "Present";
            PsDscRunAsCredential = $CredFarm;
            Url                  = "https://web.myappdomain.com/", "https://web2.myappdomain.com/", "https://web3.myappdomain.com/", "https://web4.myappdomain.com/", "https://web5.myappdomain.com/" ;
        }

Enabling us to have a single SPFeature Block to execute on all Web Applications within the farm, also reducing the size of our script and configuration data. Of course Nik would have to make some updates to ReverseDSC to ensure the script is written in the new way so cloning of existing farms can be done easily with a less complex file to edit or modify.

**Comment by ykuijs** [comment]
In SPFeature the Url parameter is specified as Key parameter for this resource and DSC does not allow Key parameters to be collections.

Changing Url not being Key is also not possible, since need that to be key so we can specify multiple web applications for the same feature without DSC complaining about duplicates.

So unfortunately, implementing this suggestion is not possible. Implementing one resource per web application is the only option for now.

**Comment by jimbrayDel** [comment]
Thank You Yorick,
I understand now,  I get it, the URL was key because you must have a specific app to apply the feature to and while reading your email, I got the other point that with multiple URL’s how would DSC report non compliance and be specific with where the problem was.

In my best Yoda,
More ideas I have, Share them I will…. 😊

JB
--
James Bray
D:  615-882-6691 | M: 615-516-1987
--
www.deloitte.com<http://www.deloitte.com/>

**Comment by ykuijs** [comment]
You are welcome @jimbrayDel Keep the ideas coming!!
