### ISSUE TITLE
SPFarm does not change central admin auth mode

### ISSUE THREAD

**Issue by zsolt-illes** [PowerShell/SharePointDsc#1115]
Hi,
I've created a new farm with Central Admin being on NTLM. Later I decided I wanted to change to Kerberos. I've changed the CentralAdministrationAuth parameter to Kerberos and pushed the configuration again. It went through without error, but the authentication for the Central Admin has not changed.
Thanks,
Zsolt

**Comment by ykuijs** [comment]
@ronx Since you are already working on updating SPFarm: Do you have the opportunity to check/fix this issue?

**Comment by ronx** [comment]
@ykuijs I'll try to take a look this week.
