### ISSUE TITLE
MSFT_SPSearchFileType fail to modify Built-In FileTypes

### ISSUE THREAD

**Issue by Jocorteslopez** [PowerShell/SharePointDsc#1119]
The line 230 of this module is trying to remove the file type to push later the new values that the configuration is defining. 

This is not possible if the File Type is a Built-In. 

**SCENARIO**: We try to rename the Existing File Type "GIF" and this is the code we pretend to execute:
             SPSearchFileType "gif"
             {
                 FileType = "gif"
                 ServiceAppName = "My Search Service"
                 Description ="gif"
                 MimeType = "application/gif"
                 Ensure = "Present"
                 PsDscRunAsCredential = "My Super Priviledge Account"
             }          

**Result of this execution is a SharePoint error:**
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Testing Search File Type 'gif'
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Getting Search File Type 'gif'
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Executing as the local run as user US\MySuperUserAccount
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving ProcessRecord Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving EndProcessing Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Current Values: Description=Graphics Interchange Format; Enabled=True; Ensure=Present; FileType=gif; InstallAccount=; MimeType=image/gif; ServiceAppName=Search Service Application
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Target Values: Description=gif; Ensure=Present; FileType=gif; MimeType=application/gif; ServiceAppName=Search Service Application; Verbose=True
VERBOSE: [MachineName]: LCM:  [ End    Test     ]  [[SPSearchFileType]gif::[DTISearch]SearchTopology]  in 0.2650 seconds.
VERBOSE: [MachineName]: LCM:  [ Start  Set      ]  [[SPSearchFileType]gif::[DTISearch]SearchTopology]
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Setting Search File Type 'gif'
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Getting Search File Type 'gif'
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Executing as the local run as user US\MySuperUserAccount
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving ProcessRecord Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving EndProcessing Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Checking if Service Application 'Search Service Application' exists
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Executing as the local run as user US\MySuperUserAccount
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] **Updating File Type gif**
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Executing as the local run as user US\MySuperUserAccount
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving ProcessRecord Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving EndProcessing Method of Get-SPEnterpriseSearchFileFormat.
VERBOSE: [MachineName]:                            [[SPSearchFileType]gif::[DTISearch]SearchTopology] Leaving BeginProcessing Method of Remove-SPEnterpriseSearchFileFormat.
**Built-in formats cannot be removed.**
    + CategoryInfo          : InvalidData: (Microsoft.Offic...arserFileFormat:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.Search.Cmdlet.RemoveDocumentParserFileFormat
    + PSComputerName        : localhost

**Suggested Solution**: 
Introduce in the module an if condition to check if the FileType is a Built-In and if that's the case just change description, and the Format 

**Bonus Track**
Adding FileTypes via command line is a different experience than in the UI. When adding the FileTypes from the Search Administration page, the list of available FileTypes reflects the extensions and icons, but doing it through the PS Command it is not showing up in the Search Administration Page. It would be nice to have the same user experience.

**Comment by NikCharlebois** [comment]
@Jocorteslopez To update the MimeType and description of existing properties, we need to call back into the New-SPEnterpriseSearchFileFormat cmdlet. However, this only works with Non Built-In properties. For built-in properties this will results in the error:

_The processing of files of type 'gif' is already supported by the parsing system._

For example, if you run the following:

`New-SPEnterpriseSearchFileFormat -FormatId 'nik' -SearchApplication "Search Service Application" -FormatName 'Nik' -MimeType 'Nik'`

Once will create the property. Run it again:

`New-SPEnterpriseSearchFileFormat -FormatId 'nik' -SearchApplication "Search Service Application" -FormatName 'Nik Updated Value' -MimeType 'Nik'`

Will update the description with "Nik Updated Value" and won't throw any errors. However running:

`New-SPEnterpriseSearchFileFormat -FormatId 'jpeg' -SearchApplication "Search Service Application" -FormatName 'jpeg' -MimeType 'image/jpeg'`

Will always throw an error. There really aren't any ways around it.

**Comment by Jocorteslopez** [comment]
ok let's close this issue :)
