### ISSUE TITLE
DSC Farm Join does not complete PSConfig wizard tasks

### ISSUE THREAD

**Issue by jimbrayDel** [PowerShell/SharePointDsc#1122]
#### Details of the scenario you tried and the problem that is occurring
          Executing SPFarm Join from the configuration data file
          SPFarm Application
		{
			Passphrase = New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString -String $ConfigurationData.NonNodeData.PassPhrase -AsPlainText -Force));
			AdminContentDatabaseName = $ConfigurationData.NonNodeData.AdminDB;
			FarmAccount = $CredFarm;
			FarmConfigDatabaseName = $ConfigurationData.NonNodeData.ConfigDB;
			CentralAdministrationPort = 10000;
			PsDscRunAsCredential = $CredFarm;
			CentralAdministrationAuth = "NTLM";
			DeveloperDashboard = "Off";
			RunCentralAdmin = $ConfigurationData.NonNodeData.RunCentralAdmin;
			ServerRole = $ConfigurationData.NonNodeData.ServerRole;
			Ensure = "Present";
			IsSingleInstance = "Yes";
			DatabaseServer = $ConfigurationData.NonNodeData.DatabaseServer;
		}

Then attempting to complete by running the PSConfig Wizard
               SPConfigWizard App
		{
			IsSingleInstance     = "Yes"
			PsDscRunAsCredential = $Credfarm
		}

#### Suggested solution to the issue
If I have not done anything in error, then possibly looking at what in the PSConfig Wizard resource needs to be resolved.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here

Using a Conditional statement to create the MOF files
Node $AllNodes.Where{$_.Role -eq “Application”}.NodeName
	{
		SPFarm ApplicationandSearchServer
		{
			Passphrase = New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString -String $ConfigurationData.NonNodeData.PassPhrase -AsPlainText -Force));
			AdminContentDatabaseName = $ConfigurationData.NonNodeData.AdminDB;
			FarmAccount = $CredFarm;
			FarmConfigDatabaseName = $ConfigurationData.NonNodeData.ConfigDB;
			CentralAdministrationPort = 10000;
			PsDscRunAsCredential = $CredFarm;
			CentralAdministrationAuth = "NTLM";
			DeveloperDashboard = "Off";
			RunCentralAdmin = $ConfigurationData.NonNodeData.RunCentralAdmin;
			ServerRole = $ConfigurationData.NonNodeData.ServerRole;
			Ensure = "Present";
			IsSingleInstance = "Yes";
			DatabaseServer = $ConfigurationData.NonNodeData.DatabaseServer;
		}
		
SPConfigWizard AppnSearchRun
		{
			IsSingleInstance     = "Yes"
			PsDscRunAsCredential = $Credfarm
		}


	}

```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2016 with 33 Language Packs 
Languages
Arabic
Bosnian
Bulgarian
Chinese Simple
Chinese Traditional
Croatian
Danish
Dutch
Estonian
Finnish
French
German
Greek
Hebrew
Hindi
Hungarian
Indonesian
Italian
Japanese
Latvian
Norwegian-Belgium
Polish
Portugese-Brazil
Portugese-Portugal
Romanian
Russian
Slovak
Slovenian
Spanish
Swedish
Thai
Turkish
Ukranian

#### Version of the DSC module that was used ('dev' if using current dev branch)
SharepointDSC 3.3.0.0

**Comment by ykuijs** [comment]
Hi @jimbrayDel It isn't required to use the Config Wizard to join a server to a farm. The SPFarm resource should do this correctly by itself.

This being said, running the Config Wizard after joining the farm should completed successfully, even though it should not do anything. What exactly are you experiencing? Do you have any logging that shows your issue?

**Comment by jimbrayDel** [comment]
Hi Yorick,
Yes the farm resource joins the server to the farm, that works. The part that I am confused by is that “after” the server is joined to the farm, if you go run Config Wizard, it starts on step 4 of 8, which seems to me that something is not being completed.   So I attempted to resolve that by calling the config wizard itself after the SPFarm resource, and it seems to just exit without running.

I will run it again and see if I can capture some logs or screen output.


JB
--
James Bray
D:  615-882-6691 | M: 615-516-1987
--
www.deloitte.com<http://www.deloitte.com/>

**Comment by jimbrayDel** [comment]
This can be closed, I kept digging into the issue where I always encountered a PSConfig run that still needed steps 5 thru 8 to be completed.  Finally after discussing with Nik C. I realized that the CU updates that had been applied are the issue, These were applied on an image but PSConfig had not been executed to seal them since I was using an vhdx image to provision VM's from.
