### ISSUE TITLE
SPSearchContentSource: Missing CrawlSetting for SharePoint site collections

### ISSUE THREAD

**Issue by davidtappan** [PowerShell/SharePointDsc#1124]
#### Details of the scenario you tried and the problem that is occurring

I used SharePointDSC.Reverse to extract the Search content sources from one farm. When I tried to apply these settings to another farm, some of content sources were not created, with the error:  "Only web applications can be specified when a Microsoft SharePoint Server content source is set to crawl web applications".  This is not correct.  In the Central Admin UI, SharePoint sites content sources can have  Crawl Settings of "Only crawl the Site Collection of each start address".  I am using this setting, and wish to apply it.  

#### Verbose logs showing the problem

VERBOSE: [DV-SP19APP01]:
[[SPSearchContentSource]AccountingDM92199286-c3c7-41d1-a350-1833b2625072] Leaving BeginProcessing Method of
New-SPEnterpriseSearchCrawlContentSource.
Only web applications can be specified when a Microsoft SharePoint Server content source is set to crawl web
applications.
Parameter name: address
Actual value was https://dm-dev.acmecorp.com/accounting.
    + CategoryInfo          : InvalidData: (Microsoft.Offic...wlContentSource:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.Search.Cmdlet.NewSearchCrawlContentSource
    + PSComputerName        : DV-SP19APP01

#### Suggested solution to the issue

The PowerShell command New-SPEnterpriseSearchCrawlContentSource has a parameter SharePointCrawlBehavior that can have the value CrawlSites to crawl only particular site collections.  Please add this setting. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

# insert configuration here
```
        SPSearchContentSource AccountingDM92199286-c3c7-41d1-a350-1833b2625072
        {
            PsDscRunAsCredential = $Credsspadmin;
            CrawlSetting         = "CrawlFirstOnly";
            FullSchedule         = MSFT_SPSearchCrawlSchedule{
                CrawlScheduleRepeatDuration = "0"
                CrawlScheduleRepeatInterval = "0"
                CrawlScheduleDaysOfWeek = "Saturday"
                CrawlScheduleRunEveryInterval = "4"
                StartHour = "8"
                ScheduleType = "Weekly"
                StartMinute = "0"
            };
            Ensure               = "Present";
            ContentSourceType    = "SharePoint";
            Addresses            = @("https://dm-dev.acmecorp.com/accounting");
            IncrementalSchedule  = MSFT_SPSearchCrawlSchedule{
                CrawlScheduleRepeatDuration = "1440"
                CrawlScheduleRepeatInterval = "240"
                CrawlScheduleRunEveryInterval = "1"
                StartHour = "0"
                ScheduleType = "Daily"
                StartMinute = "0"
            };
            Name                 = "Accounting DM";
            ContinuousCrawl      = $True;
            ServiceAppName       = "Search Service Application";
            Priority             = "Normal";
        }

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
Source: SharePoint 2013
Target: SharePoint 2019

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

SharePointDSC 3.6.0.0

**Comment by ykuijs** [comment]
We need to extend the schema here to add the CrawlBehavior. Marking this as an Enhancement

**Comment by ykuijs** [comment]
@ruandersMSFT has just submitted a PR for this issue
