### ISSUE TITLE
MSFT_SPDistributedCacheService: The server <ServerName> was not found in the array for distributed cache servers

### ISSUE THREAD

**Issue by zsolt-illes** [PowerShell/SharePointDsc#1125]
#### Details of the scenario you tried and the problem that is occurring
Provisioning multi-server farm with DSC. Getting the error in the Verbose log section. The server has ApplicationWithSearch role. The .mof file on the affected server(s) do not contain the reference to have the Distributed Cache service provisioned:
instance of MSFT_SPDistributedCacheService as $MSFT_SPDistributedCacheService1ref
{
ResourceID = "[SPDistributedCacheService]DCService";
ServerProvisionOrder = {
    "otherserver01",
    "otherserver02"
};
PsDscRunAsCredential = $MSFT_Credential15ref;
Ensure = "Present";
ServiceAccount = "CONTOSO\\setupaccount";
SourceInfo = "D:\\dsc\\integration\\SharePoint_MultiFarm.ps1::270::9::SPDistributedCacheService";
Name = "AppFabricCachingService";
CreateFirewallRules = True;
ModuleName = "SharePointDsc";
ModuleVersion = "3.5.0.0";
CacheSizeInMB = 1024;
DependsOn = {
    "[SPServiceAppPool]AppPoolCollab"};
ConfigurationName = "SharePointInstall";
};

#### Verbose logs showing the problem
PowerShell DSC resource MSFT_SPDistributedCacheService  failed to execute Set-TargetResource functionality with error message: The
server AFFECTEDSERVER02 was not found in the array for distributed cache servers
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : affectedserver02

#### Suggested solution to the issue
¯\_(ツ)_/¯

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3269.amd64fre.rs1_release.190929-1234
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.5.0.0

**Comment by ruandersMSFT** [comment]
Distributed Cache is not part of the services available with the [_ApplicationWithSearch_ MinRole](https://docs.microsoft.com/en-us/sharepoint/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016).  Ensure the _Distributed Cache_, Front-end with Distributed Cache, _Single-server farm_ or _Custom_ MinRole is utilized for servers where you are looking to run Distributed Cache.

The error message regarding "_The server was not found in the array for distributed cache servers_" is throw on line 240 of [SPDistributedCacheService](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1).  It appears you are calling _SPDistributedCacheService_ on a DSC Node with _Ensure = Present_; however, said node is not in the _ServerProvisionOrder_ array.  Ensure you are executing _SPDistributedCacheService_ against each SharePoint Node and that _Ensure = Present_ if the node is contained within _ServerProvisionOrder_ or _Ensure = Absent_ if it is not contained within.

Refer back to the _Specific Components_ section of the [SharePoint DSC Wiki](https://github.com/PowerShell/SharePointDsc/wiki).

**Comment by zsolt-illes** [comment]
Hi,

I'm not sure I get it. I've been using the ApplicationWithSearch MinRole on a server where the error is thrown. I know it is not supposed to be there. I do not want it to be there, yet the error comes.

Thanks
Zsolt

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ykuijs** [comment]
Closed via #1128

**Comment by ykuijs** [comment]
Fix will be included in v3.7, to be released next Wednesday (October 30th 2019)
