### ISSUE TITLE
Add support for NetBIOS domain names in xSPUserProfileServiceApp

### ISSUE THREAD

**Issue by andy-cox** [PowerShell/SharePointDsc#210]
Allow the xSPUserProfileServiceApp resource to [enable NetBIOS domain names](https://technet.microsoft.com/en-gb/library/ee721049.aspx#NetBIOSProc).

**Comment by BrianFarnhill** [comment]
This is in progress under #349 and should be merged to the dev branch soon

**Comment by BrianFarnhill** [comment]
This was closed in #349 and will be in the 1.2 release. Closing this issue
