### ISSUE TITLE
Allow xSPDistributedCacheService to change the cache size

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#236]
Currently xSPDistributedCacheService will set the size of the cache on a node when it is provisioned but then it will not be validated again. The resource should be able to identify nodes that do not have the correct cache size and update them like it does at provisioning time.

**Comment by ykuijs** [comment]
Implemented in my next Bugfix PR

**Comment by ykuijs** [comment]
Closed via PR #826
