### ISSUE TITLE
xSPSearchServiceApp SDDL string error in standalone install

### ISSUE THREAD

**Issue by NaomiReeves** [PowerShell/SharePointDsc#255]
In my standalone SharePoint 2013 environments, I'm receiving this error when creating the Search Service Application:

```
The SDDL string contains an invalid sid or a sid that cannot be translated
```

According to [this article](http://social.technet.microsoft.com/wiki/contents/articles/17933.sharepoint-2013-the-sddl-string-contains-an-invalid-sid-or-a-sid-that-cannot-be-translated.aspx) it looks like this is a known issue in standalone installations. However; after I followed the steps outlined in the article to resolve the error, subsequent executions of the DSC resource gave these error messages:

```
Invoke-DscResource : Exception calling ".ctor" with "1" argument(s): "searchContext"
```

and 

```
Invoke-DscResource : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "userName" is not valid. Change the value of the "userName" argument and run the operation again."
```

When I look at the server, the service application is created, but it doesn't have a proxy and is in an error status.

**Comment by BrianFarnhill** [comment]
@NaomiReeves Can you share your config/config data with me? (either here or via email). I'm not sure we are doing the same things as the config wizard here so it might be the same error but I'm not convinced it's releated, but I want to try to repro what you are doing to see if I can come up with it.

**Comment by NaomiReeves** [comment]
@BrianFarnhill Sure! I'm using Chef with DSC, so below is the specific resource as outlined in my code (using the Chef DSL) and how it would look if I was using traditional DSC. Let me know if you have questions or want to see it in my environment (which might be helpful).

##### Chef DSL
```
dsc_resource 'Search Service App' do
  resource :xSPSearchServiceApp
  property :name, 'Search Service Application'
  property :applicationPool, 'SharePoint Service Applications'
  property :DatabaseServer, 'server_name'
  property :DatabaseName, "DEV_L_SA_Search"
  property :InstallAccount, ps_credential(install_account, sp_managed_accounts_vault['install_account'])
end
```

##### Traditional DSC
```
    xSPSearchServiceApp SearchServiceApp
    {  
        Name                  = "Search Service Application"
        DatabaseServer        = "server_name"
        DatabaseName          = "DEV_L_SA_Search"
        ApplicationPool       = "SharePoint Service Applications"
        PsDscRunAsCredential  = $InstallAccount
    }
```

**Comment by BrianFarnhill** [comment]
@NaomiReeves Perfect, I'll investigate and see what I can come up with. If I can't see it in my environment I'll reach back out to you to see it in yours and we can go from there.

**Comment by Mattheweckburg** [comment]
Any update on this issue? I am seeing the same problem at times, thought intermittently. I am using Azure Automation and the workaround is to delete the service application and wait for the LCM to run again, whereby it will successfully pass the issue.

**Comment by BrianFarnhill** [comment]
@Mattheweckburg I haven't been able to repro this one, so I'm not sure the specific circumstance that causes this error to happen. If you can help shine some light on when this occurs I can definitely code something to get around it.

**Comment by avishnyakov** [comment]
Having the same issue with win2012r2 + sharepoint 2013 sp1. Same DSC, getting the same error.

Nailed down to the following call:
```
$c = [Microsoft.Office.Server.Search.Administration.SearchContext]::GetContext($s)
```
https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L96

The search service app is created, it seems to be healthy but context can't be created while passing SPSIte into the static method. However, getting context by the search service app name works well:
```
$c = [Microsoft.Office.Server.Search.Administration.SearchContext]::GetContext("Search Service Application")
```

Happens on one out of dozen VMs. Use the same DSC / SharePoint DSC / Chef to get all setup but, really, once in a while getting such error.

I'll try to modify that line to get the contet by the search service app name and see how it would go locally. Hope that helps a bit.

**Comment by BrianFarnhill** [comment]
Thanks @avishnyakov - will get the code updated accordingly.

**Comment by avishnyakov** [comment]
Sure, no worries.
