### ISSUE TITLE
xSPUserProfileSyncService Status field of Get function hastable is missing in mof file

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/SharePointDsc#273]
Get function hash table code
        return @{
            UserProfileServiceAppName = $upa.Name
            Ensure = $localEnsure
            FarmAccount = $farmAccount
            InstallAccount = $params.InstallAccount
            Status = $syncService.Status
        } 

Mof definition
class MSFT_xSPUserProfileSyncService : OMI_BaseResource
{
    [Key, Description("The name of the user profile service for this sync instance")] string UserProfileServiceAppName;
    [Write, Description("Present to ensure the service is running, absent to ensure it is not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("The farm account, which is needed to provision the service app"), EmbeddedInstance("MSFT_Credential")] String FarmAccount;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

Proposed fix : add Status field in mof definition
[read] String Status;

**Comment by BrianFarnhill** [comment]
Let me look at this, I think the status thing might have been redundant and we can remove it rather than add to the schema, but I'll investigate when I get a sec

**Comment by BrunoReboul** [comment]
Yes, seams to be redundant as Ensure is already built on $synService.Status (that is status). so let's go for removal. I propose code fix through a PR.

**Comment by BrianFarnhill** [comment]
This was fixed in #318 - closing
