### ISSUE TITLE
new resource xSPLogLevel

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/SharePointDsc#274]
A new resource I'm working on.
Used to adjust the severity of events logged to the Windows Event Log and to the SharePoint ULS logs. Can specify specific categories using the same format as Set-SPLogLevel cmdlet, or can instruct the resource to apply changes to all Categories. Also supports resetting categories back to defaults.

xSPLogLevel   VerboseEvents {
  Categories = "SharePoint Foundation:*","SharePoint Server:Database","SharePoint Server:Audit"
  TraceLog = "Verbose"
  EventLog = "Verbose"
}

xSPLogLevel AllVerbose {
 Categories = "All"
 TraceLog = "Verbose"
 EventLog = "Verbose"
}

xSPLogLevel AllBacktoDefaults {
 Categories = "All"
 ResetToDefault = $true
}

**Comment by BrianFarnhill** [comment]
@anlynes @caadam - your thoughts on this from an architectural perspective?

@MikeLacher448 I assume that categories then becomes the key here, yea? I think I'm happy with this approach, just wanted to get some input from my guys on this as well.

**Comment by MikeLacher448** [comment]
yes, categories is the key
the resource will look at the value of categories, and if it's simply the test "All", then it will call Set-SPLogLevel with out specifying the category, which causes it to apply the settings to all of them. If the category does not match "All", then the categories are passed directly to the Set-SPLogLevel cmdlet.

**Comment by BrianFarnhill** [comment]
Sounds like a decent enough approach to me - lets run with it and we can go over the finer details when I code review the PR. Thanks @MikeLacher448

**Comment by ykuijs** [comment]
Great addition!

**Comment by MikeLacher448** [comment]
still on my plate, just not a high priority at the moment

**Comment by MikeLacher448** [comment]
finally getting to this one,  appreciate some input on get and test methods.

suppose I have a configuration stating "Cat1","Cat2","Cat3" should be "Verbose".
but my current state is "Cat1","Cat3" are Verbose.

what should I return from Get? I only want to return one value each for Event and Trace Severity. I don't want to return all categories that match the desired severity, as I may pickup categories I set using a different resource id, or even ones that are set that way by default.

I could return the provided categories back during get, but return the severity as null, this will trigger the test to fail and cause a set to run. Is that good enough? I'm thinking we should return more detail, but am struggling to come up with a good way to do it.

suggestions?

**Comment by ykuijs** [comment]
Please take a look at the subclass I used in the SPWebAppPolicy resource. I think this is ideal for your situation:
```
SPLogLevel WebAppPolicy
{
    Loglevels = @(
        MSFT_SPLogLevelItem {
            Category     = "SharePoint Foundation"
            SubCategory  = "General"
            TraceLevel   = "Medium"
            EventlogLevel = "Verbose"
        }
        MSFT_SPLogLevelItem {
            Category     = "Access Services"
            SubCategory  = "Administration"
            TraceLevel   = "Medium"
            EventlogLevel = "Verbose"
        }
    )
    PsDscRunAsCredential = $SetupAccount
}
```

**Comment by ykuijs** [comment]
This way you can return just the categories that were requested in the config, including their value. The test method can then test for the correct value and fail if one is not correct.

The set method then needs to loop all through all categories, check their values and set them if they do not match the configured value.

**Comment by MikeLacher448** [comment]
interesting approach, I'll play around with that and see how that works. Thanks.

**Comment by BrianFarnhill** [comment]
Yea I agree with @ykuijs - this approach gives the ability to set specific categories through DSC while leaving others to be managed through traditional means, so a much more flexible solution. I think we need to add a wildcard option in there to set all though, so something like this for all categories, or all sub-categories in a category:

    SPLogLevel AllLogs {
        Loglevels = @(
            MSFT_SPLogLevelItem {
                Category     = "*"
                SubCategory  = "*"
                TraceLevel   = "Medium"
                EventlogLevel = "Verbose"
            }
        )
        PsDscRunAsCredential = $SetupAccount
    }

    SPLogLevel SpecificCategory {
        Loglevels = @(
            MSFT_SPLogLevelItem {
                Category     = "SharePoint Foundation"
                SubCategory  = "*"
                TraceLevel   = "Medium"
                EventlogLevel = "Verbose"
            }
        )
        PsDscRunAsCredential = $SetupAccount
    }

Now I get this will complicate the code a little in terms of the get method (I think, I could be wrong - just shooting from the hip here) but I think it makes it the most robust option to move forward with.

**Comment by MikeLacher448** [comment]
Brian, I was thinking the same thing with supporting a wildcard for area and category as well.

**Comment by ykuijs** [comment]
@MikeLacher448 Any update on this resource?

**Comment by MikeLacher448** [comment]
sorry for letting this one slip... resource is nearly done, working on tests now.

**Comment by MikeLacher448** [comment]
feedback wanted..
at first I wanted to be able to specify a collection of desired categories and log level settings in one resource instance... and while I have it working, I'm wondering if it's more complex than it needs to be (certainly making the test cases more difficult), and if it's better that each Area/Name combination be a unique instance of the resource?

**Comment by ykuijs** [comment]
My preference is to do it as much as possible in one resource. This might be a little more complex in development of the resource, but I think it reduces the complexity of the config. Which in the end is the goal of our resource ;-)

With one resource for one category, you potentially need a huge list of resources.

**Comment by MikeLacher448** [comment]
I can see that too. Very well, will carry on as is.

**Comment by ykuijs** [comment]
Closed with PR 685
