### ISSUE TITLE
Incorrect prerequisite file name for SP2016 - Microsoft Information Protection and Control Client 2.1

### ISSUE THREAD

**Issue by brianlala** [PowerShell/SharePointDsc#289]
_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

**Details of the scenario you try and problem that is occurring:**
xSharePoint is looking for setup_msipc_x64..msi (which would be valid for SP2013), but the correct file for SharePoint 2016 is actually setup_msipc_x64.**exe**. In fact, the former is version 2.0 but the .exe is reporting version 2.1.

**The DSC configuration that is using the resource:**
xSharePoint\0.12.0.0\Examples\Single Server\SharePoint.ps1

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2016 TP4, native PowerShell 5.0

**Version of the DSC module you're using:**
0.12.0.0
_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project._
_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

**Comment by BrianFarnhill** [comment]
Thanks for reporting Brian - we might need to look at providing some specific examples for SP2013 and SP2016 as separate files for things like this, or at a minimum highlighting things like that in the examples. Leave this one with me and I'll see what we can do.

**Comment by BrianFarnhill** [comment]
This was updated in #382 (to default the example to online mode rather than use the specific offline examples to avoid confusion)
