### ISSUE TITLE
Add xSPSearchCrawlRule resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#29]
The xSPSearchCrawlRule resource is used to set a crawl rule against the specified search service app. It should be structured as follows:

xSPSearchCrawlRule IntranetCrawlAccount
{
    Path = "https://intranet.sharepoint.contoso.com"
    ServiceAppName = "Enterprise Search Service Application"
    Ensure = "Present"
    CrawlConfiguration = "Include"
    CrawlConfigurationRules = "FollowLinksNoPageCrawl,CrawlComplexUrls"
    Authentication = "SpecificAccount"
    AuthenticationCredentials = $Credentials
}

A combination of rules and ways of specifiying all of the appropriate options and combinations needs to be created to apply these rules correctly.

**Comment by ykuijs** [comment]
Working on this one!

**Comment by ykuijs** [comment]
Just created a PR: #290

**Comment by BrianFarnhill** [comment]
Closing this as the PR was merged
