### ISSUE TITLE
Remove dependency on Win32_Product in SPInstallPrereqs

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#293]
**Details of the scenario you try and problem that is occurring:**

Currently the SPInstallPrereqs resource depends on the Win32_Product class to determine what is installed and what isn't. As per [this article](https://blogs.technet.microsoft.com/heyscriptingguy/2011/11/13/use-powershell-to-quickly-find-installed-software/) this query isn't optimised and can trigger some additional consistency checks, which should be avoided. All the checks in the get method for this resource should therefore use alternative approaches to determine what is installed and what isn't (either registry or file system checks)

**The DSC configuration that is using the resource:**

SPInstallPrereqs

**Version of the Operating System and PowerShell the DSC Target Node is running:**

n/a

**Version of the DSC module you're using:**

0.12 (but issue has existed since the very beginning at 0.2)

**Comment by BrianFarnhill** [comment]
Linking this to an [issue in the main DscResources repo](https://github.com/PowerShell/DscResources/issues/108)

**Comment by luigilink** [comment]
Made a fix for this issue: Pull request #340
