### ISSUE TITLE
Add xSPWebAppUserPermissions resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#296]
_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

**Details of the scenario you try and problem that is occurring:**
We need a new resource that is able to manage the "User Permissions for Web Application" section in Central Admin. A customer asked for this resource today.

Syntax would be something like:

xSPWebAppUserPermissions WebAppUserPermissions {
	WebAppUrl = "https://intranet.contoso.com"
	List Permissions = "Manage Lists", "Override List Behaviors,Add Items", "Edit Items", "Delete Items", "View Items", "Approve Items", "Open Items", "View Versions", "Delete Versions", "Create Alerts", "View Application Pages"
	Site Permissions = "Manage Permissions", "View Web Analytics Data", "Create Subsites", "Manage Web Site", "Add and Customize Pages", "Apply Themes and Borders", "Apply Style Sheets", "Create Groups", "Browse Directories", "Use Self-Service Site Creation", "View Pages", "Enumerate Permissions", "Browse User Information", "Manage Alerts", "Use Remote Interfaces", "Use Client Integration Features", "Open", "Edit Personal User Information"
	Personal Permissions = "Manage Personal Views", "Add/Remove Personal Web Parts", "Update Personal Web Parts"
}

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
N/A

_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project._
_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

**Comment by BrianFarnhill** [comment]
Thanks @ykuijs - it's on the backlog for now. Will you be working on this with your customer? Or do you want me to take it as help wanted?

**Comment by ykuijs** [comment]
Place it on Help Wanted for now. Working on the Blob Cache now. Maybe someone else has time to pick this one up before I can. If not, I will update this issue later :-)

**Comment by ykuijs** [comment]
Working on it!

**Comment by ykuijs** [comment]
Issue can be closed. PR is merged.
