### ISSUE TITLE
Add xSPSearchFileType resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#30]
The xSPSearchFileType resource will register a new file type with the search service app (or remove it). It should be structured as follows:

 xSPSearchFileType PdfSearchCrawl
{
    ServiceAppName = "Enterprise Search Service Application"
    Name = "PDF"
    Ensure = "Present"
}

**Comment by mrpullen** [comment]
shouldn't this be closed??
