### ISSUE TITLE
new resource SPServiceProxyGroup

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/SharePointDsc#300]
_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

**Details of the scenario you try and problem that is occurring:**
a new resource to create and manage membership of service application proxy groups

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
current Dev branch (as of May 27th)

_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project._
_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

My customer uses service application proxy groups to control web application to service application mapping in a large environment. I'm getting ready to develop a DSC resource for this and wanted to get feedback on what I'm envisioning.

 SPServiceAppProxyGroup FarmProxyGroup1 {
   Name = "Farm Proxy Group 1"
   Ensure = "Present" #Absent will delete the proxy group
   WebApplications = "https://web1","https://web2" # explicit list, will ensure only these web apps are included
   WebApplicationsToInclude = ...  # will add these web apps to group, maintaining existing membership
   WebApplicationsToExclude =  ...  # will remove these web apps from the group.
   ServiceApplicationProxies = "Farm Search Service","Farm User Profile1" #explicit membership
   ServiceApplicationProxiesToInclude = ... # add these proxies to the group
   ServiceApplicationProxiesToExclude = ... # remove these proxies from the group
}

Thoughts?

**Comment by MikeLacher448** [comment]
as I'm building this, I'm thinking this resource should create the proxygroup and manage service app membership, and a second resource should be used to have the web applications consume the services in that proxy group.

**Comment by BrianFarnhill** [comment]
@caadam @anlynes @camiloborges @ykuijs thoughts on this approach guys?

**Comment by camiloborges** [comment]
Hello.

I like the idea. I haven't done many proxy groups in the past and when I did was mostly to get around fuck ups, or to avoid them.

I believe this resource would be really long, but that would be the first one.

Does it need to tackle, or check things like the mms proxy options, or the anything related to user profile service?

**Comment by ykuijs** [comment]
What would be the reason to split the resource in two separate ones?

I would say it makes sense to place everything in one resource. All settings are then combined into one configuration. Just like the template you suggested in your initial post.

**Comment by MikeLacher448** [comment]
I was thinking a separate web application proxy resource could be in the config in the same section as the SPWebApplication related resources to build and configure the web applications. But the more I think of it, the more I'm seeing this as one of the last resources in a config, to put all the required services and web apps into their respective proxy groups after all web apps and services are built.

@camiloborges what MMS and UPA proxy options are you referring to?

**Comment by MikeLacher448** [comment]
one benefit however, to separate resources, is the relationship logic becomes clearer to understand. Services can be members of multiple Service Proxy groups, but a web app can only be connected to one service proxy group. Using two resources, this becomes a bit clearer, as the resource for the services would still support the explicit list, or the list to include and list to exclude. No logic is needed to ensure you're not making the services a member of multiple groups.
The corresponding web app resource, however, would only take two properties. The URL of the web application, and the name of a single proxy group to connect to.

**Comment by ykuijs** [comment]
Agree, in order to apply the configuration, the resource would have to depend on all service applications and web applications being created first.

With your last example it would make sense to create two resources: One to create the proxy groups and one to link web applications to proxy groups:
- Web app 1 would be created
- Service app 1 and 2 would be created
- Service proxy group would be created and made dependant on the config for service apps 1 and 2
- The web app to proxy group link would be established by the second resource and in the config would be make dependant on the Web app 1 and Service proxy group config

I agree that this makes the overview much clearer

**Comment by camiloborges** [comment]
Hello
MMS
-default storage location for keywords
- column specific term sets

UPA, and anything that relies on MMS
- Do we need to validate anything regarding  term sets? 
      - USer Profile Properties
     - Site Columns
     - Managed Navigation

**Comment by BrianFarnhill** [comment]
I'll throw my two cents in here - I don't think we need a separate resource to bind the web app to the group. Surely we can just have "ServiceAppProxyGroup" as a property on SPWebApplication and that can do the binding?

**Comment by MikeLacher448** [comment]
Brian, I thought of that too. Just need to make sure all the service apps are created first.

**Comment by MikeLacher448** [comment]
one issue with putting it as a property of the SPWebApplication, if you were to create all services first, build the proxy group and then join the web app, there are some services that you should have the web apps built for first. For example, so that you have the mysite host setup when building the UPA, and having a site for the content type hub when building MMS. This is why my current powershelgl build script (non DSC), builds the web apps first, then builds the services, then creates the proxy group with the services, then connects the web app. There's a lot of interdependencies here that I think will be easier to maintain if it was a separate resource.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 Happy with that logic - we should make sure that we discuss that point in the documentation to explain why its separate and what the desired order should usually be.

**Comment by MikeLacher448** [comment]
Will do

**Comment by BrianFarnhill** [comment]
Fixed and merged in #323 - closing this issue
