### ISSUE TITLE
SPUserProfileProperty and SPUserProfileSection return from Set-TargetResource

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/SharePointDsc#308]
_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

                        
We should not be using return $variable in Set-TargetResource, PSSA fails due to this:
PSDSCReturnCorrectTypesForDSCFuncti Information  MSFT_SPUse 351   Set-TargetResource function in DSC Resource should not      
ons                                              rProfilePr       output anything to the pipeline.                            
PSDSCReturnCorrectTypesForDSCFuncti Information  MSFT_SPUse 114   Set-TargetResource function in DSC Resource should not      
ons                                              rProfileSe       output anything to the pipeline.    

**Details of the scenario you try and problem that is occurring:**

Running PSSA 

**The DSC configuration that is using the resource:**

NA 

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using:**

0.12

_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project._
_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

**Comment by BrianFarnhill** [comment]
Hey @KarolKaczmarek - I pushed these in to the release-1.0 branch for #304 so they are included in the release. We can close this off when the merge happens.

**Comment by BrianFarnhill** [comment]
This issue has been resolved, closing
