### ISSUE TITLE
Resolve warnings about alias 

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#309]
**Details of the scenario you try and problem that is occurring:**

The PSScriptAnalyzer shows a number of warnings for the use of PowerShell aliases throughout the module (such as % instead of ForEach-Object) . These should be removed and replaced with the full function names.

**The DSC configuration that is using the resource:**

n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**

n/a

**Version of the DSC module you're using:**

0.12

**Comment by camiloborges** [comment]
really???? Aliases are so much more readable... :(

**Comment by BrianFarnhill** [comment]
@camiloborges They are shorter - they aren't more readable. At least not in my opinion, and in the opinion of the team writing the script analyzer. So we're going to clean house on this one and then make sure we catch any breaches in our tests.
