### ISSUE TITLE
Add xSPSearchCrawlerImpactRule resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#31]
The xSPSearchCrawlerImpactRule resource will add a crawler impact rule to the specified service application.

xSPSearchCrawlerImpactRule ThrottleIntranetCrawl
{
    ServiceAppName = "Enterprise Search Service Application"
    Site = "https://intranet.sharepoint.contoso.com"
    RequestLimit = "8"
}

This rule also needs to accommodate the wait time between requests option for an impact rule as well (which can't be used at the same time as the request limit option)

**Comment by mrpullen** [comment]
Looking at [New-SPEnterpriseSearchSiteHitRule](https://technet.microsoft.com/en-us/library/ff608048(v=office.15).aspx)

seems like we could do something like

```
xSPSearchCrawlerImpactRule ThrottleIntranetCrawl
{
ServiceAppName = "Enterprise Search Service Application"
Site = "https://intranet.sharepoint.contoso.com"
Behavior = "" // ValidateSet("RequestLimit","WaitTime")
HitRate = 8  // Request Limit or Wait Time in seconds.
}
```

or something like this, where we only allow them to specify either RequestLimit or WaitTime.

```
xSPSearchCrawlerImpactRule ThrottleIntranetCrawl
{
ServiceAppName = "Enterprise Search Service Application"
Site = "https://intranet.sharepoint.contoso.com"
RequestLimit = 8
WaitTime = 60  
}
```

**Comment by ykuijs** [comment]
Resource created in PR 531
