### ISSUE TITLE
$null should be on the left side of equality comparisons

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#311]
**Details of the scenario you try and problem that is occurring:**

The PSScriptAnalyzer returns many instances where $null is on the right side of a equality comparison (such as '-eq') - due to the way PowerShell does comparisons this should be avoided.

**The DSC configuration that is using the resource:**

n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**

n/a

**Version of the DSC module you're using:**

0.12

**Comment by ykuijs** [comment]
Am a little confused: The title indicates that $null should be on the left side of the equality comparison, but the details say "this should be avoided". Which of the two is true?

**Comment by BrianFarnhill** [comment]
@ykuijs Sorry dude, my mistake. They should be on the left, I fixed the typo in my original post to reflect this one.
