### ISSUE TITLE
Add xSPSearchAuthoratativePages resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#32]
The xSPSearchAuthoratativePages resource is used to define the authoritative sites in the search service app. It should be structured as per the below example:

xSPSearchAuthoratativePages SetAuthoratativePages
{
    ServiceAppName = "Enterprise Search Service Application"
    FirstLevel = "https://intranet.sharepoint.contoso.coim"
    SecondLevel = ""
    ThirdLevel = ""
    DemoteSites = ""
}

**Comment by mrpullen** [comment]
```
xSPSearchAuthoratativePages SetAuthoratativePages
{
  ServiceAppName = "Enterprise Search Service Application"
  Url = "Page URL"
  Level = 0.0  //between 0.0 and 2.0
  Demoted = $true | $false 
  Ensure = "Present"
}
```
xSPSearchAuthoratativePages SetAuthoratativePages
{
  ServiceAppName = "Enterprise Search Service Application"
  PageUrl = "Page URL"
  Level = 0.0  //between 0.0 and 2.0
  Demoted = $true | $false 
  Ensure = "Present"
}

from Cmdlets:

New-SPEnterpriseSearchQueryDemoted
New-SPEnterpriseSearchQueryAuthority 

If demoted is true we would ignore level..

Or we could have two resources, one for authoritative pages, another for demoted pages..

Key would be Search Service Application and Url.

**Comment by ykuijs** [comment]
Resource created in PR 530
