### ISSUE TITLE
SPSecureStoreServiceApp Get-TargetResource AuditingEnabled

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#324]
The Get-TargetResource for the SPSecureStoreServiceApp resource is taking in a mandatory parameter called AuditingEnabled, but is not returning it as part of its output hash. This is causing issues for the reverse DSC which is now dynamic. Are we able to either:

1 - Figure out a way to retrieve this value from the Object Model, modify the Get-TargetResource method accordingly and add the AuditingEnabled property to the returned hash;

or

2 - Make the parameter non-mandatory

Thanks

**Comment by BrianFarnhill** [comment]
Good catch @NikCharlebois - will get this looked at for you.

**Comment by ykuijs** [comment]
Closed with PR 660
