### ISSUE TITLE
SPInstallPrereqs - KB2898850 is missing in Set/Get/Test params def and in MOF too

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/SharePointDsc#329]
KB2898850 appears in the hastable returned by Get, but is not defined in the param blocks of Get Set Test nor in the mof.
Resulting an error 4252 when checking the conf with get : "The KB2898850 key is not a valid property in the corresponding DSC resource schema file"
However KB2898850 installation does not seam to be yet managed by Set.
As a temporary fix I have added the missing definitions in the param block and mof.
The is fix available if needed on 
https://github.com/BrunoReboul/SharePointDsc/tree/fix-SPInstallPrereqs-ParamList

**Comment by BrianFarnhill** [comment]
Thanks for reporting @BrunoReboul - This should have been removed in [this changeset](https://github.com/PowerShell/SharePointDsc/commit/60273ec66c448a2353ea2fd96837524853aa1011) but it got missed. I'll put a PR forward to remove this from the return value of the get method shortly.
