### ISSUE TITLE
Add xSPSearchManagedProperty resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#33]
The xSPSearchManagedProperty resource is used to define managed properties in the search service application. This should be structured as per the below:

xSPSearchManagedProperty MyCustomSearchProperty
{
    ServiceAppName = "Enterprise Search Service Application"
    Ensure = "Present"
    Name = "MyProperty"
    PropertyType = "Text"
    Searchable = $true
    Queryable = $true
    Retrievable = $true
    AllowMultipleValues = $true
    Refinable = "Yes-Latent"
    Sortable = "Yes-Active"
    SafeForAnonymous = $false
    Alias = "PropertyAlias"
    TokenNormalisation = $true
    CompleteMatching = $false
    IncludeAllCrawledProperties = $false
    CrawledProperties = "Field1,Field2"
}

**Comment by NikCharlebois** [comment]
@ykuijs Please assign to me. I am working on a Ressource for this.

**Comment by ykuijs** [comment]
All yours!

**Comment by ykuijs** [comment]
Implemented in PR #876
