### ISSUE TITLE
Refactor to align with test standards

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#332]
When SharePointDsc began there was no formal guidance for the structure of the pester tests that are run, nor were there standards for integration testing. [These standards](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) now exist and our solution needs to be refactored to accommodate these. 

I'll be doing the refactor of this (and have already been working on the integration tests), and am capturing this work item here to track technical debt and raise awareness of the standards. Once we have examples comited with the new test templates, then all future PRs will be expected to follow this model.

**Comment by camiloborges** [comment]
@BrianFarnhill Brian, I am keen to help on this and the integration tests :)

**Comment by BrianFarnhill** [comment]
I've been doing some research on this one, and I've got some concerns about implementing this one. Looking at the Initialize-TestEnvironment cmdlet, my issues are:

* This won't find out modules as we don't follow the standard directory structure
* We would still have to implement logic to load our stub modules and other additional 'prep' before each test run
* It does some stuff that is redundant around working directories (although that's going to get cleaned up at some point)

My issue at this point is that I don't see this change as being something that will add any value or remove any of the complexity of our test set up. At this point I want to hold off on this one and re-evaluate how we can better structure the repetitive parts of our test suite and implement that.
