### ISSUE TITLE
Add optional "Proxy Name" property to all service app resources

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/SharePointDsc#338]
Currently the suffix " Proxy" is added to multiple Service App proxy names.
For some customers it could break the service naming convention.

Proposition : make the suffix optional by adding a new setting on the corresponding resource
First implementation available for the Secure Store Service here:
https://github.com/BrunoReboul/SharePointDsc/tree/Imp-ServiceApp-ProxySuffix

**Comment by BrianFarnhill** [comment]
@BrunoReboul Thanks for raising this. I think what actually needs to be done here is that we need to not assume a naming structure for the proxy objects, and make it an "optional" property in every service app where if it gets defined we use that name for the proxy, and if it is not specified then it will be "[Name of service app] Proxy". I'll get this on the backlog to be worked on.

**Comment by BrunoReboul** [comment]
@BrianFarnhill Thanks for the feedback.
Ok not to assume proxy naming structure
New implementation proposed for secure store at
https://github.com/BrunoReboul/SharePointDsc/tree/Imp-ServiceApp-ProxySuffix
Let me know if ok for you, then I will generalize to other service apps

**Comment by BrianFarnhill** [comment]
Looks OK at a quick glance. Open a PR for this and I'll do a popper code review with reviewable of the secure store service app change you made, and then you can keep committing to the same branch with the changes to the other and we can close it out as one PR with everything in it.

**Comment by MikeLacher448** [comment]
good update, I noticed that the proxy names are inconsistent currently, this will be a welcome change.

**Comment by NikCharlebois** [comment]
@BrunoReboul where are you at with these changes? I can jump in and do the modifications if you want.

**Comment by BrianFarnhill** [comment]
OK so "part" of this got done in v1.3 but it looks like we missed a few service apps. For example, Managed Metadata has it, but access and excel do not. So if we lift the work that @BrunoReboul did for those ones that already have and it put it in the missing ones we'll be done.

**Comment by ykuijs** [comment]
Issue can be closed. Was fixed in #414

**Comment by ykuijs** [comment]
@NikCharlebois Was this also fixed in #414??

**Comment by NikCharlebois** [comment]
@ykuijs No. I've made the modifications for the Visio Service App, bu not the others. I can have a look this week if you wish.

**Comment by ykuijs** [comment]
@BrunoReboul What is the status of your PR?

**Comment by BrianFarnhill** [comment]
@ykuijs I think that the PR @BrunoReboul  did was closed, but we needed to get the missing apps from this done, and I'm not sure we had an owner on that looking at the conversation here.

**Comment by ykuijs** [comment]
Updated the remaining resources that support a custom proxy name. Included in my next PR

**Comment by ykuijs** [comment]
Fixed in PR #680
