### ISSUE TITLE
Passphrase Issue

### ISSUE THREAD

**Issue by thegingerwizard** [PowerShell/SharePointDsc#357]
_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

Trying to use the Example Small Farm solution that ships with the module

New Farm DSC configuration

Windows 2012 R2, PS5, Module 1.1.0.0

DSC Module 1.1.0.0

I am having an issue generating MOF files, the error I am getting isbelow, any help would be greatly appreciated. - Thankyou :

Write-NodeMOFFile : Invalid MOF definition for node 'SERVER001': Exception calling "ValidateInstanceText" with "1" argument(s): "Convert property 'Passphrase' value from type 'STRING' to type 'INSTANCE' failed
 At line:203, char:2
 Buffer:
"SharePointServer";
};^
insta
"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2275 char:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

**Comment by BrianFarnhill** [comment]
Hi @thegingerwizard - this is a currently known issue with the example (I didn't get updated in 1.1 like it was meant to, my fault for missing it). This will be resolved in 1.2 but in the mean time the work around involves a couple of quick steps.

1. Add a new PSCredential parameter to the top of the config, exactly the same as the other ones there
2. Change the passphrase variable in the SPCreateFarm resource (and the SPJoinfarm resources if you are using the small farm template) to be that new variable. 

The username in the credential is ignored, the password in it is used as the passphrase. This makes sure that the passphrase is always stored as an encrypted value and not in plain text.

Does that help? Let me know if you need more specific info on this one.

**Comment by thegingerwizard** [comment]
Hi Brian,

That appears to have sorted things.. Thankyou.

I almost got there as yesterday I set the parameter as you suggested but in then I was calling $parameter.password..

Thanks for your help.

Andy


_____________________________

**Comment by BrianFarnhill** [comment]
I'm leaving this issue open until we resolve it in the examples - it'll get cleaned up when we do #315 but in the mean time if others have this issue they can see the info here. Thanks @thegingerwizard

**Comment by BrianFarnhill** [comment]
This was completed in #382
