### ISSUE TITLE
Add xSPMachineTranslationServiceApp resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#36]
The xSPMachineTranslationServiceApp resource is used to provision the machine translation service app. It should be structured as follows:

xSPMachineTranslationServiceApp MachineTranslation
{
    Name = "Machine Translation Service Application"
    Ensure = "Present"
    DatabaseName = "SP_MachineTranslation"
    DatabaseServer = "SQL01.contoso.com"
    AppPool = "SharePoint Web Services"
    PartitionedMode = $true
}

**Comment by camiloborges** [comment]
needs to take the 'Set' Cmdlet parameters as per 
https://technet.microsoft.com/en-us/library/jj219583.aspx

**Comment by ykuijs** [comment]
Resource created in PR 548
