### ISSUE TITLE
Remving service applications leaves orphan proxy objects

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#360]
**Details of the scenario you try and problem that is occurring:**

Currently if you look at setting "Ensure = Absent" on to any of the SharePoint service application resources they will remove the service applications, but will leave the proxy there. This can create issues when trying to create a new service app with the same name (which in the current version would mean the same proxy name would be used). These should be able to look up the corresponding proxies and remove them when the service applications are removed.

The following resources are impacted by this

* SPAccessServiceApp
* SPAppManagementServiceApp
* SPBCSServiceApp
* SPExcelServiceApp
* SPManagedMetadataServiceApp
* SPPerformancePointServiceApp
* SPSearchServiceApp
* SPSercureStoreServiceApp
* SPUserProfileServiceApp
* SPVisioServiceApp
* SPWordAutomationServiceApp
* SPWorkManagementServiceApp

**Version of the DSC module you're using:**

1.1

**Comment by NikCharlebois** [comment]
@BrianFarnhill I'll take a look at this one as soon as reverse DSC is completed and merged. Please have it assigned to me. Cheers

**Comment by BrianFarnhill** [comment]
@NikCharlebois Let me know when you start work and I'll make it as in progress

**Comment by NikCharlebois** [comment]
@BrianFarnhill I'm starting the work on these items.

**Comment by ykuijs** [comment]
Will be fixed in PR #414

**Comment by ykuijs** [comment]
Issue can be closed. Was fixed in PR #414
