### ISSUE TITLE
SPSearchServiceApp Failed to execute Test-TargetResource functionality

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SharePointDsc#363]
**Details of the scenario you try and problem that is occurring:**
Error Message: 
`PowerShell DSC resource MSFT_SPSearchServiceApp failed to execute Test-TargetResource functionality with error message: The term 'Get-SPWebApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Why:
Because the PowerShell Snapin for SharePoint is not loaded in Get-SPDSCContentAccessAccount function => line 221 in MSFT_SPSearchServiceApp.psm1

New Error Message after fixed the snapin loading:
`PowerShell DSC resource MSFT_SPSearchServiceApp failed to execute Test-TargetResource functionality with error message: An item with the same key has already been added. `

**The DSC configuration that is using the resource:**
MSFT_SPSearchServiceApp

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2 and PowerShell 5.0

**Version of the DSC module you're using:**
SharePointDSC 1.0.0.0

**Comment by BrianFarnhill** [comment]
This was fixed in #337 and was released in v1.1 - so I'll close this one off. Grab the latest version and you will be fine :)
