### ISSUE TITLE
SPVisioServiceApp does not create service app proxy

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/SharePointDsc#374]
**Details of the scenario you try and problem that is occurring:**
SPVisioSericeApp resource does not create an associated proxy. This is due to the fact that the underlying cmdlet, New-SPVisioServiceApplication does not create an associated proxy by default. Resource should either create a proxy by default to match the behavior of other service app resources, or accept an optional parameter to create the proxy.

**The DSC configuration that is using the resource:**
SPVisioServiceApp VisioServiceApp 
		{
			Name = "SP Visio Service Application"
			Ensure = "Present"
			ApplicationPool = "SP_VisioSvc_AppPool"
			DependsOn	= "[SPServiceAppPool]VisioServiceAppPool"
		}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012R2, WMF5 RTM

**Version of the DSC module you're using:**
dev branch  as of 7/18/2016

**Comment by BrianFarnhill** [comment]
@MikeLacher448 Thanks for reporting, will add it to the backlog

**Comment by NikCharlebois** [comment]
@BrianFarnhill assign that one to me since I'm the one who created it in the first place. I'll take care of it once the Reverse DSC is taken care of. Thanks

**Comment by BrianFarnhill** [comment]
@NikCharlebois Let me know when you start work and I'll tag it as in progress.

**Comment by NikCharlebois** [comment]
I am on it right now actually. Will have it done before COB today ;)

**Comment by ykuijs** [comment]
Issue can be closed. This was fixed in #411
