### ISSUE TITLE
SPShellAdmins throws error Get-SPDSCContentDatabase not known

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#380]
**Details of the scenario you try and problem that is occurring:**
SPShellAdmins does not work. Error is Get-SPDSCContentDatabase is not recognized as the name of a cmdlet...

I removed the wrapper function Get-SPDSCContentDatabase and replaced all calls with Get-SpContentDatabase in MSFT_SPShellAdmins.psm1. This way it worked.

**The DSC configuration that is using the resource:**
        SPShellAdmins ShellAdmins
        {
            Name                 = "Shell Admins"
            Members              = $SPBinaryPathCredential.UserName
            AllContentDatabases  = $true
            PsDscRunAsCredential = $SPSetupAccount
            DependsOn            = "[SPCreateFarm]CreateSPFarm"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012R2, SharePoint 2016, WMF5 RTM

**Version of the DSC module you're using:**
SharePointDSC 1.1.0.0

**Comment by BrianFarnhill** [comment]
Thanks for reporting @typozh - will investigate!

**Comment by ykuijs** [comment]
Just checked this: The code is calling a method that is declared at the bottom of the file. However, the method is called within an Invoke-SPDSCCommand block, which means it cannot find the code since it is not loaded within that context. We should either move this method to an util file or solve the Pester issue in a different way.

**Comment by typozh** [comment]
Hi, any update on this? Is there a schedule for the next version to be released?

**Comment by BrianFarnhill** [comment]
@typozh Not yet - we've had to spend a lot of time for 1.3 working on standards and things for the PowerShell team that related to us being able to ditch the "x" off the front of the name for this. Now that being said, I know I've got a customer I'll be seeing in the not all too distant future that will need this fixed as well, so if someone else hasn't had a chance to get it looked at by then I'll definitely get it addressed then. Will keep this issue updated when progress is made.

**Comment by ykuijs** [comment]
Working on it!

**Comment by ykuijs** [comment]
Issue is fixed. Will be included in my next PR, which will be a bugfix rollup PR.

**Comment by ykuijs** [comment]
@BrianFarnhill, Issue can be closed. Is fixed in PR415
