### ISSUE TITLE
Acces Denied Problem with SPAppCatalog

### ISSUE THREAD

**Issue by arashalvandi** [PowerShell/SharePointDsc#386]
When I try to execute **SPAppCatalog** Resource with FarmAccount or Setup Account I get an access denied.

`SPAppCatalog MainAppCatalog
        {
            SiteUrl = $Node.SharePoint.Apps.AppCatalogUrl
            PsDscRunAsCredential = $SPSetupAccount
            DependsOn            = @('[SPAppDomain]LocalFarmAppUrls')
            #InstallAccount = $SPSetupAccount
        }`

**Error Deails here:**

VERBOSE: [MYDEV]: [[SPAppCatalog]MainAppCatalog] Leaving BeginProcessing Method of Update-SPAppCatalogConfiguration.
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
    + CategoryInfo          : InvalidData: (Microsoft.Share...ogConfiguration:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletUpdateSPAppCatalogConfiguration
    + PSComputerName        : MYDEV

**When I try to execue the normal powershell command:**
Update-SPAppCatalogConfiguration -Site  @"http://contoso.com/sites/AppCatalog" -Force
it does work perfect for me.

Any idea what the problem could be?

Here are some environemnt informations:
- PS 5.0
- OS Win 12 R2
- SharePoint 2013
- Dsc Module Version 1.1.0.0

**Comment by BrianFarnhill** [comment]
Confirmed bug - I've seen this while building out the integration tests as well. We know this definitely used to work and we haven't changed the code either so I'm wondering if a specific cumulative update or something is causing us the issue. Can you confirm for me what update level your SharePoint 2013 farm is at?

**Comment by arashalvandi** [comment]
The Server Patch level is Oct. 2015

**Comment by BrianFarnhill** [comment]
@arashalvandi Finally got to the bottom of this one. It appears the Update-SPAppCatalogConfiguration command doesn't like running as the setup account (that created the web app in this case). The workaround is to use the farm account to run this resource (change PsDscRunAsCredential to be the same creds as the farm account). We'll add a specific error trap for this to show a more meaningful error in 1.5, and we'll be updating the documentation shortly.
