### ISSUE TITLE
Invoke-SPDSCCommand in SharePointDsc.Util.psm1

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/SharePointDsc#397]
Is the purpose of Invoke-SPDSCCommand in SharePointDsc.Util.psm1 only for Powershell 4 where PsDscRunAsCredential is not available?

So in PowerShell 4, use InstallAccount, and In PowerSehll 5, use PsDscRunAsCredential?

Thanks
Tony Huang

**Comment by BrianFarnhill** [comment]
Hi Tony,

Yes definitely use PsDscRunAsCredential in PowerShell 5. As for is the Invoke-SPDSCCommand used just like that - mostly, yes. We do talk about this a little [in the wiki](https://github.com/PowerShell/SharePointDsc/wiki/Remote%20sessions%20and%20the%20InstallAccount%20variable) but there are currently a couple of exceptions to this which we touch on in #389 which we will address as a breaking change for a 2.0 release at some point in the future.

Hope that helps!
