### ISSUE TITLE
New improvements to make it usable for automatic installation

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#398]
Please add more details documentations/how-to on wiki (example: guide to automatically install SharePoint 2016 on 4 vm in h.a. + 2 vm for sql and 2 vm for owa/oos: prepare sql, install module, ability this, launch this...) and example of configurations and options to use it.

I use autospinstaller , "SharePointDsc" have same or more features and simple configuration as it? 
I want be able to easy define and do the same thing, but it seems very hard to do it now respect to autospinstaller. 
And autospinstaller is easy debuggable and fixable in case of problems, SharePointDsc is more complicated (or not easy to learn).

The logical step must be (with a GUI as autospinstaller.com ? ):
-define number of server
-define account
-define common settings (web application, version of SharePoint, database name, central admin)
-define services application and role for every server (ex. put distributed cache and search in this server, but frontend here, but application here with this services)

**Comment by BrianFarnhill** [comment]
Hi @paololec - I've been in conversation with @brianlala in regards to how we get customers to transition from AutoSPInstaller to SharePointDsc. We have some ideas in this regard, but nothing that we are ready to start implementing as yet. So if you are dependent on a GUI to create your SharePoint farm, then right now AutoSPInstaller is a better option. I'm hopeful this will change in future, but until we have some specific plans on that front I can't give you a better option.

I will however leave this issue open so we can have some discussion around this issue and as we get closer to implementing a GUI to create configurations with we can refer to this issue.

**Comment by MikeLacher448** [comment]
My 2 cents on this... 
I agree that we can always work on improving documentation and expand on the examples. However, the real benefits of SharePointDsc is not in providing a master script or workflow for everyone to use. Everyone has different requirements on how their farm is built. But rather, SharePointDsc provides the building blocks for you to implement within your process, as simple or as complicated as needed. With SharePointDsc, you can focus on building the farm topology and configuration as code, maintaining it under source control, without focusing on the back end powershell needed to create a farm, create a web application, configure search, etc...

**Comment by monkeymagik** [comment]
I would happily continue using AutoSPInstaller to deploy SharePoint environments, except for the way it handles passwords which DSC does a better and more secure job of and a few little things here and there that I've had to write extra functions.

While it's true every SharePoint install is different, AutoSPInstaller will pretty much do everything you need for 90% of SharePoint environments I've seen.

Are there any examples available anywhere of what you've been working on to incorporate the features of AutoSPInstaller? I've started modifiying the example files so that it takes most of it's input from and AutoSPInstallerInput.xml file... but I've still got a way to go.

**Comment by mrpullen** [comment]
Are you looking for a DSC Configuration that consumes the AutoSPInstaller XML file? 

Seems like this would be straightforward to do.. Just feed the xml in as a parameter, then in the Configuration map specific settings to specific resources. 

Would a standard AutoSPInstaller.xml file work as a sample?

**Comment by BrianFarnhill** [comment]
@mrpullen I agree, this would be a fairly straightforward thing to do. We could even have it parse the XML up front to show warnings about the things that are in the XML file that we don't support or do yet. I feel like if we start with a standard XML file as an example though that would make a good starting point to a solution here.

**Comment by NikCharlebois** [comment]
@Brian<mailto:Brian.Lalancette@microsoft.com> And I had started to look at a AutoSP <--> SPDSC converter at one point, and I know Brian may also have something of his own. I'd be interested in helping out

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by NikCharlebois** [comment]
Folks, I recommend trying to close the loop on this one. My efforts to have a converter from AutoSPInstaller into DSC have been dropped in favor of using ReverseDSC. My recommendation is to close this issue, and let people use ReverseDSC instead. Users that have current investments in AutoSPInstaller, can build a farm using the AutoSP scripts, then run ReverseDSC against it to have the equivalent SharePointDSC script generated instead. Thoughts?

**Comment by paololec** [comment]
I need convert from AutoSPInstaller to DSC or easy "configurator" for DSC.
Now I using a "template" of xml for AutoSPInstaller, go to site autospinstaller.com, change parameter to adapter for many clients and using new xml to install and configure SP2016.  It's fast, complete and works also for complex scenario.
I never use SharePointDSC because there is no simple "configurator", no good prebuild template to using it with my case (1 server, 2 server, 2 server in h.a., custom role, etc..).  No fast, no complete, very complex to use and no easy as powershell command for install SP on many clients and debug.

**Comment by NikCharlebois** [comment]
Thanks @paololec . I completely understand your point. This is something that affects DSC in general however, not just the SharePoint bits. We are working on various tools internally to make it easier for users to "visually" build their DSC configuration. At this point in time however, we do not have any plans to create an equivalent to autospinstaller.com. Adding @mgreenegit as FYI only

**Comment by johlju** [comment]
Closing this issue as per previous comments by https://github.com/PowerShell/SharePointDsc/issues/398#issuecomment-358305465. This is out of the scope of this resource module.
