### ISSUE TITLE
Use with Azure

### ISSUE THREAD

**Issue by DeanGross** [PowerShell/SharePointDsc#402]
**I'm a complete noob with DSC and before I dig in, I'm wondering if this package can be used to create dev/test farms for SP in Azure:**

**n/a:**

**n/a:**

**n/a**

**Comment by luigilink** [comment]
If you talk about azure automation, I hope someone can help you, because I haven't tested yet.
But if you have a azure VM with the Pull Server Role, It works perfectly. 
My2Cents

**Comment by BrianFarnhill** [comment]
@DeanGross While we haven't specifically tested Azure Automation support, we have seen success when using both the DSC extension for virtual machines as well as just deploying your own pull server virtual machine also (the same as you would on-premises). From what I know of Azure Automation there should be no issues making this work with that also, but it's just not a scenario we've had time to test.

Does that help? Is there something specific you need information on?

**Comment by BrianFarnhill** [comment]
I'm going to close this issue off, but if you have a specific question to follow up with i'll open this one again for further discussion.
