### ISSUE TITLE
Extend SPDatabaseAAG to map databases to AG's via name pattern

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#407]
**Details of the scenario you try and problem that is occurring:**

Currently SPDatabaseAAG works by specifying the name of an individual database that needs to be added to an availability group and working that in. It should be extended to look for databases based on a pattern as well as by individual name. This would allow for scenarios where additional content databases are created post deployment that follow a naming convention being added to the correct availability groups automatically, thus simplifying configuration for those who wish to use this approach.

**The DSC configuration that is using the resource:**

SPDatabaseAAG

**Version of the Operating System and PowerShell the DSC Target Node is running:**

n/a

**Version of the DSC module you're using:**

SharePointDsc 1.2

**Comment by ykuijs** [comment]
How do you see this being included into the schema? What notation should be used? Including wildcards (e.g.: "SP_Content*") or just matching a specified string (e.g.: "Content")??

**Comment by BrianFarnhill** [comment]
I want to do it using PowerShell's syntax so we can do something like this in the code:

    Get-SPDatabase | Where-Object -FilterScript { $_.Name -like $params.Name }

Does that make sense?

**Comment by ykuijs** [comment]
Working on it

**Comment by ykuijs** [comment]
Have implemented this change. Unfortunately Azure requires additional steps to support SQL Always-On, so I cannot test it on my current environment. Am creating a new environment in Hyper-V as we speak, so I can test it on that environment.

**Comment by BrianFarnhill** [comment]
If you need a hand with the AGs in Azure let me know, I wrote a [blog post](https://blogs.msdn.microsoft.com/brian_farnhill/2016/03/03/configuring-sql-server-alwayson-availability-groups-in-azure-rm-virtual-machines/) on how to get this going with ARM VM's so I can definitely help with that one. Let me know if you need a hand.

**Comment by ykuijs** [comment]
Problem is that my current test environment has been created using the old OOTB template and therefore is based on the classic model.

**Comment by ykuijs** [comment]
Have deployed a new environment in Azure based on the HA template. This does the configuration for me :-)

This did reveal an issue: The Add-DatabaseToAvailabilityGroup cmdlet was introduced in the April 2014 CU (Post SP1): http://www.harbar.net/archive/2014/03/20/Support-for-SQL-Server-Always-On-Async-Replication-with-SharePoint.aspx

Since the HA template deploys a SP1 environment, this cmdlet did not exist yet. I think we should add a check to test is the minimum version is the April 2014 CU. @BrianFarnhill, do you agree?

**Comment by BrianFarnhill** [comment]
Damn I thought it was SP1,  my mistake! Yes absolutely we should add a check for that one too

**Comment by ykuijs** [comment]
No problem, SP1 was released in April 2014 as well, but the cmdlet was added shortly after the code freeze for SP1 :-)

Will add this check as well!

**Comment by BrianFarnhill** [comment]
Just merged in to dev, closing this off.
