### ISSUE TITLE
SPAlternateUrl resource missing -Internal parameter on native cmdlet calls

### ISSUE THREAD

**Issue by iosgitr** [PowerShell/SharePointDsc#423]
**Details of the scenario you try and problem that is occurring:**
I'm trying to use SPAlternateUrl to add an internal URL to an existing zone.  I provided the WebAppUrl, Zone, and Url parameters per documentation (https://github.com/PowerShell/SharePointDsc/wiki/SPAlternateUrl) and although verbose output shows that resource is in desired state, I don't see my new internal URL.  I looked at the Set-TargetResource function in the SPAlternateUrl resource (MSFT_SPAlternateUrl.psm1) and tried running New-SPAlternateUrl manually (per line 118) using the same parameters.  All that did was change my public URL to the new internal URL I was trying to add.  I then looked at the New-SPAlternateUrl help and noticed the -Internal parameter.  Running New-SPAlternateUrl with the same parameters but this time adding -Internal had the desired affect.

Please add -Internal to the native cmdlet calls in the SPAlternateUrl resource where appropriate.

**The DSC configuration that is using the resource:**
Not sure what this means.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 and WMF 5.0

**Version of the DSC module you're using:**
1.3.0.0

**Comment by BrianFarnhill** [comment]
Hi @iosgitr - thanks for reporting,

We've seen success with other deployments using this in it's current form, so I'm hesitant to make a blanket change (as the internal option does process things differently to public alternate URLs which are the default). That said, we should be exposing the Internal option as an attribute on the resource so it can be selected, so I'll add that to the backlog.

In terms of understanding your specific issue a bit more though, are you able to share the actual configuration element from your powershell for the alternate URL (where you set the properties of the alternate URL you want to create) as well as any relevant info about what the web applications URLs are so we can understand how the logic in our resources would behave against your environment a little better. I'm keen to understand why it's not working in it's current form as well as adding the additional attribute for use.

Let me know if you have any questions.

 - B

**Comment by iosgitr** [comment]
That makes more sense.  So it sounds like the resource is intended to ensure the public URL specified is set for the specified web app and zone but that there is no support for adding additional internal URLs to the specified zone (primarily used for reverse proxy scenarios).

Microsoft PFEs I've worked with in the past have been very clear about not adding a public zone URL without extending the web app although it is easy to do so through the UI and PowerShell.  I looked in the SharePointDsc module just now for a resource for extending a web app and don't see one but I don't have a lot of time at the moment so I might have missed it.  I would have assumed that if one wants to add a new public URL/zone, that would be accomplished with an "extend web app" resource and that if one wanted to add an internal URL to an existing zone that already has a public URL, one would use SPAlternateUrl.

Generally speaking, the SharePointDsc module is awesome and I'm absolutely loving using it to build our company's new farms.  Thanks for all the hard work!

**Comment by BrianFarnhill** [comment]
I'm a PFE as well, so the advice varies depending on the situation :)

Definitely happy to get the internal option added though so there is flexibility in the resource, so we'll leave this one open in the backlog and update this issue when we get to it. Thanks!

**Comment by ykuijs** [comment]
Closed with PR 660
