### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md has a Question mark to much

### ISSUE THREAD

**Issue by StefanSchoof** [PowerShell/SharePointDsc#427]
In https://github.com/PowerShell/SharePointDsc/blob/dev/.github/PULL_REQUEST_TEMPLATE.md Line 15 should be the question mark after [Style Guidelines] removed. So that it is:

```
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
```

**Comment by ykuijs** [comment]
I am on it!

**Comment by ykuijs** [comment]
@BrianFarnhill Fixed in PR438, issue can be closed
