### ISSUE TITLE
IISReset each time SPInstallPrereqs test fails

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#430]
**Details of the scenario you try and problem that is occurring:**
If the SPInstallPrereqs test fails the set function runs the prereqs exe. This triggers a IISReset. In my case the Prerequisites were all installed and the prereqs exe did not change anything but the test still failed because of a different version of Microsoft Visual C++ 2015 Redistributable (x64) package. 
I had version 14.0.23506.0 installed but the test expected version 14.23026.0. My workaround is to install the expected version.
I think this is a big risk for production systems because a update could install a different version and the test would fails again leading to IISReset in every test-cycle. One solution could be to remove the config block once the farm is setup but this is against the idea of dsc.

**The DSC configuration that is using the resource:**
SPInstallPrereqs, Version 1.3

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2
Powershell 5

**Version of the DSC module you're using:**
1.3

**Comment by BrianFarnhill** [comment]
Thanks for reporting Brian, will get on to this one ASAP! I'll own putting this fix in and we'll see if we can get it out in 1.4

**Comment by BrianFarnhill** [comment]
Got a fix open for this, should be in dev within a couple of days and will make the 1.4 release.

**Comment by typozh** [comment]
Thanks for taking this up! Hope it will make the 1.4 release.
