### ISSUE TITLE
Update doco on SPInstallLanguagePack to explain process

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#431]
Capturing an item that came from the discussion in #410 - we need to update the readme.md file in the SPInstallLanguagePack folder to explain the correct sequence that is expected for installing language packs:
1. Install of SharePoint Binaries
2. Install of SharePoint Language Pack(s)
3. Create SPFarm 
4. Install of Cumulative Updates

This way it will be reflected in the wiki and inbuilt PowerShell help

**Comment by ykuijs** [comment]
I am on it!

**Comment by ykuijs** [comment]
@BrianFarnhill Fixed in PR438, issue can be closed
