### ISSUE TITLE
Creating and Joining the farm

### ISSUE THREAD

**Issue by Bjorn80** [PowerShell/SharePointDsc#442]
Hi this is not an issue, but i could not find the question section:-)

**Details of the scenario you try and problem that is occurring:**
Is the SharePoint configuration wizard run when creating/joining the farm?
Or are we required to run the psconfig afterwards?
(Get-spserver $env:computer).needsupgrade does show false.

**The DSC configuration that is using the resource:**
SharePointdsc 1.2.0.0

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Server 2012R2

**Version of the DSC module you're using:**
SharePointdsc 1.2.0.0

**DELETE THIS LINE AND BELOW**

_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project._
_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

brgs

Bjørn

**Comment by ykuijs** [comment]
Hi @Bjorn80, you do not have to run psconfig when using SharePointDsc. The SPJoinFarm and SPCreateFarm will do the work for you.

**Comment by Bjorn80** [comment]
Excellent ykuijs!

Thank you.

brgs

Bjørn
