### ISSUE TITLE
SPInstallLanguagePack

### ISSUE THREAD

**Issue by bardtomm** [PowerShell/SharePointDsc#443]
Installing language pack fails with SharePoint 2016

Fails with "Unknown folder structure"
I see that it checks for osrvFolder (osrv*.*) but 2016 Language files does not contain this folder..

What about checking for osmui*.' instead?

Powershell 5.0, SharePointDSC 1.3.0.0 Windows Server 2012 R2

**Comment by ykuijs** [comment]
Thanks @bardtomm for reporting. Am investigating the issue.

**Comment by ykuijs** [comment]
Issue fixed in PR #454

**Comment by BrianFarnhill** [comment]
Issue merged to dev, will be released in v1.5 - closing this one off.
