### ISSUE TITLE
SPSearchTopology server name case sensitive

### ISSUE THREAD

**Issue by mariusv-msft** [PowerShell/SharePointDsc#444]
**Details of the scenario you try and problem that is occurring:**
When trying to apply the SPSearchTopology on a single SharePoint 2016 vm, with custom role, the server names supplied are expected to be in the same case

I've used:
             SPSearchTopology LocalSearchTopology 
             { 
                 ServiceAppName          = "Search Service Application" 
                 Admin                   = @("Test02") 
                 Crawler                 = @("TEST02") 
                 ContentProcessing       = @("TEST02") 
                 AnalyticsProcessing     = @("TEST02") 
                 QueryProcessing         = @("TEST02") 
                 PsDscRunAsCredential    = $SetupAccount 
                 FirstPartitionDirectory = "C:\SearchIndexes\0" 
                 IndexPartition          = @("TEST02") 
             } 

This generates the following error:
SC resource MSFT_SPSearchTopology  failed to execute Set-TargetResource functionality with error message: Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'Test02'  Key being added: 'TEST02'" 

Not a big Issue, maybe just something to be aware about or add to the Wiki

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2

**Version of the DSC module you're using:**
1.4

**Comment by BrianFarnhill** [comment]
Nice catch, will get this sorted!

**Comment by BrianFarnhill** [comment]
@mariusv-msft I've just opened a PR with a fix, we should see this go out in 1.5
