### ISSUE TITLE
Add xSPBlobCacheSettings resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#45]
The xSPBlobCacheSettings resource will allow for configuration of the blob cache on the current server (through manipulating the web.config file). It should be structured as follows:

    xSPBlobCacheSettings BlobCacheSettings 
    {
        WebApplication = "SharePoint Sites"
        Zone = "Default"
        EnableCache = $true
        Location = "F:\BlobCache"
        MaxSize = 10
        FileTypes = "\.(gif|jpg|png|css|js)$"
    }

**Comment by MikeLacher448** [comment]
I can take this one, I have a module that's 80% done already.

**Comment by BrianFarnhill** [comment]
Thanks Mike, it's yours

**Comment by MikeLacher448** [comment]
my  resource does not edit the web.config directly (I've always tried to avoid that at all costs), but rather uses the WebConfigModifications method of the Web Application object.

Thoughts?

**Comment by BrianFarnhill** [comment]
@MikeLacher448 We've had a lot of discussion (in #219) about how to manage web.config changes - my opinion is that I want to avoid SPWebConfigModifications at all costs, and my reasoning is in that issue. So have a read through there as a starting point and we can discuss it from there. If you can convince me that it's the best way forward then we can go for it, but at this point I would rather see a resource that would modify the files directly.

**Comment by MikeLacher448** [comment]
might be a little bit before I can get to this one, if someone else wants to take a shot at it, go for it. Otherwise, it will most likely be sometime next month before I have the cycles to look at it.

**Comment by ykuijs** [comment]
Can you share the code you already have created with me? Then I will have a crack at it when I am done with the current resource I am working on.

**Comment by MikeLacher448** [comment]
I can, but my resource uses the webconfigmodifications method of the web app. If we wanted to go that way, I'll I need to do is clean up the code to fit the style guide and finish the pester test. But my understanding from the prior discussion is that we wanted to modify the web.config files on the servers directly.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 That's correct, we want to do this without webconfigmodification use

**Comment by ykuijs** [comment]
Working on this one

**Comment by BrianFarnhill** [comment]
All yours @ykuijs

**Comment by ykuijs** [comment]
Issue can be closed since the PR is merged
