### ISSUE TITLE
Small Farm Role Support

### ISSUE THREAD

**Issue by monkeymagik** [PowerShell/SharePointDsc#450]
When will SharePointDSC be updated to support the new small farm roles available with SharePoint 2016 Feature Pack 1?

**Comment by BrianFarnhill** [comment]
I'm working on it as we speak - hoping to get it released as part of 1.5 at the end of this month

**Comment by BrianFarnhill** [comment]
@monkeymagik I've got the pull request open with the code for this, it'll get reviewed then merged to dev and will ship in v1.5

**Comment by BrianFarnhill** [comment]
@monkeymagik This update has been made to the dev branch and will release with v1.5 in a few weeks.
