### ISSUE TITLE
Create SPFarm resource to supercede SPCreateFarm and SPJoinFarm

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#455]
After running around with the v0.x and v1.x versions of SharePointDsc for a while now I've come across an issue with the approach to the create/join farm resources and it is to do with the disaster recovery scenario for a server that has CreateFarm in its config. Basically it will only ever join a server to a farm when there is no farm there. If you decide you need to destroy and re-create a server that uses SPCreateFarm it will never succeed as it will never be able to create another farm, so you need to manually re-join it to the existing farm for the resource to pass and continue it's configuration.

Based on that, there really should be just a single resource called SPFarm which will create the farm if it doesn't exist, and if it does then join a server to it as well. This will address the above scenario (and be a step towards removing the need for a "farm" server that we have been using at the moment, which creates issues for high availability). I've got some theories about how to implement this which I'll open another issue on as there are wider reaching issues than just these resources, so this issue can focus discussion on the SPFarm resource (which will be a v2.0 resource) and I'll link other related discussions here as I open them.

**Comment by ykuijs** [comment]
Good catch, never thought of this scenario. We definitely need to resolve this! The challenge here would be preventing two servers creating a new farm at the same time.

**Comment by BrianFarnhill** [comment]
@ykuijs Exactly, which is why I suggest a config database in #457 to help manage this type of "locking" to avoid conflicts

**Comment by luigilink** [comment]
To continue with problem with SPCreateFarm and SPJoinFarm.
I suggest this PR #495.
Can we talk about this ?

**Comment by BrianFarnhill** [comment]
@luigilink I did a quick glance at the code and I like the approach you've taken - it doesn't necessarily solve the issue with with only one server looking to create the farm but it does cover off a couple of scenarios. So I think we will still need to look at how to merge these two, but the code you've put there looks like it'll be a big help in that direction so I'll do a full review when I get a minute and then we can get it merged in.

**Comment by BrianFarnhill** [comment]
OK I've got a first cut in progress, check out the [resource so far](https://github.com/BrianFarnhill/SharePointDsc/blob/feature-spfarm/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1) and let me know what you think. I'm still testing so I'll open a PR when it's ready. The basic process though is that this resource will detect if the config DB exists as a first step, and from there it will either create the farm or join it based on that. It also has a flag built in to it to determine if central admin should be running on that server (this way, in theory if I have a WFE create the farm which wouldn't normally run the CA site, the CA site will still be provisioned later by the first server that should run it that joins the farm). Would love some feedback on this code early if I can - @ykuijs I'm looking at you mate :)

**Comment by luigilink** [comment]
@BrianFarnhill Yes your approach is better than mine. Check in first step the registry key is for me the right way.
