### ISSUE TITLE
Breaking changes for a v2.0 release

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#456]
I wanted to open an issue that we could link all items that relate to breaking changes that will go in a v2.0 release, as well as have a central place to discuss other items relating to a 2.0 release such as:

- How to document and communicate the breaking changes
- How to work on the breaking changes at the same time (such as a v2.0 dev branch)

I want to group as many of the breaking changes together in to a single release as I can so we don't have a continuing run of them to implement over several months, just a single release with all of the changes in one go will be easier for an administrator to cope with I feel (let me know if you disagree though). 

To get things started, the pending list of breaking changes to be included in a v2.0 release would include the following issues:

- Create SPFarm resource to supercede SPCreateFarm and SPJoinFarm ( #455)
- Infer UseSSL value for SPWebApplication from URL (#424)

I also want to make some changes to search topology and distributed cache as well which I don't have open issues on yet, so I'll get my thoughts on those written down and linked in here as well

**Comment by BrianFarnhill** [comment]
The plan will be to move any breaking change in to the "[preview-2.0](https://github.com/PowerShell/SharePointDsc/tree/preview-2.0)" branch and when we are ready to ship version 2.0 with all of the pending breaking changes we can ship that branch in to dev and go from there.

**Comment by mrpullen** [comment]
#538

**Comment by ykuijs** [comment]
More breaking changes which will be implemented in v2.0:
#644 #423 #550

**Comment by ykuijs** [comment]
PR #660 is implementing most of these breaking changes

**Comment by ykuijs** [comment]
Only issue #538 is still open, all other breaking changes are fixed.

**Comment by ykuijs** [comment]
All breaking issues have been implemented and preparations for the v2.0 release are started

**Comment by NikCharlebois** [comment]
![image](https://user-images.githubusercontent.com/2547149/33721238-6ece9750-db34-11e7-9644-e14b10366f63.png)

**Comment by ykuijs** [comment]
v2.0 has been released, closing issue
