### ISSUE TITLE
The 'Invoke-SPDSCCommand' command was found in the module 'SharePointDsc'

### ISSUE THREAD

**Issue by KoenigLear** [PowerShell/SharePointDsc#465]
Hi,
I'm trying to create a site but fails with 'Invoke-SPDSCCommand' command was found in the module 'SharePointDsc', but the module could not be loaded.

    node localhost
    {        
        SPSite TeamSite
        {
            Url                      = "..."
            OwnerAlias               = "...\sp_farm"
            Name                     = "a Site"
            Template                 = "STS#0"
            PsDscRunAsCredential     = $SPSetupAccount
        }
    }

I'm running this on Windows 2012 R2, Powershell 5 using xSharepoint 1.4 (as reported by 
Get-DscResource -Module SharepointDsc)

Any ideas?

many thanks,

Lear

**Comment by ykuijs** [comment]
Hi @KoenigLear, can you share a screenshot of the error message? And can you tell me when this issue occurs? When DSC is testing the existance of the site (Test/Get methods) or when it tries to create the site (Set method)?

**Comment by KoenigLear** [comment]
@ykuijs  Thanks - See below:
![sharepoint_dsc_error](https://cloud.githubusercontent.com/assets/19749651/20685006/654204b6-b5aa-11e6-9308-655a11373c26.png)

**Comment by ykuijs** [comment]
Do all resources fail or just the SPSite one?

**Comment by KoenigLear** [comment]
Never mind for some reason I'm yet to determine the files C:\Program Files\WindowsPowerShell\Modules\SharePointDsc\Modules were not in its place.   I'm using an Azure RM DSC extension and this complicates the setup a bit.  It's working fine for me now.
