### ISSUE TITLE
MSFT_SPSite Get-TargetResource not returning proper QuotaTemplate Name

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#467]
The Get-TargetResource method in MSFT_SPSite simply returns SPSite.Quota as a value for the QuotaTemplate parameter which translates it to the following string: ""Microsoft.SharePoint.Administration.SPQuota" instead of the proper template name. The return for this parameter should be the following instead:

([Microsoft.SharePoint.Administration.SPWebService]::ContentService.QuotaTemplates | ?{$_.QuotaID -eq $site.Quota.QuotaID}).Name

This currently causes errors in the ReverseDSC process since it is trying to call 

New-SPSite [...] -QuotaTemplate "Microsoft.SharePoint.Administration.SPQuota" 

Which throws errors

**The DSC configuration that is using the resource:**
MSFT_SPSite

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 - SP2016

**Version of the DSC module you're using:**
1.4.0.0

**Comment by ykuijs** [comment]
I have some time available next week. Will pick this up together with the other bugs you reported.
