### ISSUE TITLE
Microsoft SharePoint is not supported with version 4.0.30319.17929 of the Microsoft .Net Runtime.

### ISSUE THREAD

**Issue by VerdonTrigance** [PowerShell/SharePointDsc#472]
**Details of the scenario you try and problem that is occurring:**
Microsoft SharePoint is not supported with version 4.0.30319.17929 of the Microsoft .Net Runtime.

**The DSC configuration that is using the resource:**
Configuration TestBuildRelease  
{
	param( 
		[Parameter(Mandatory=$true)] 
		[String]
		$Server,

		[parameter(Mandatory = $true)]  
        [String]   
        $Name,

        [parameter(Mandatory = $true)]  
        [String]   
        $LiteralPath
	) 
    Import-DSCResource -ModuleName SharePointDsc
	Node $Server
	{  
		SPFarmSolution FakeProject
		{
			Name = $Name
			LiteralPath = $LiteralPath
            PsDscRunAsCredential = $cred
		}
	} 
}
$ConfigData = @{
    AllNodes = @(
        @{
            NodeName = $env:COMPUTERNAME
            PSDscAllowDomainUser = $true
            PSDscAllowPlainTextPassword = $true
        }
    )
}
$cred = Get-Credential -UserName "corp\abc" -Message "password: "
TestBuildRelease -Server $env:COMPUTERNAME -Name "FakeProject.wsp" -LiteralPath "C:\Deploy\TestBuildRelease_20161212.13\FakeProject.wsp" -OutputPath "C:\Deploy\TestBuildRelease_20161212.13\Deploy" -ConfigurationData $ConfigData
Start-DscConfiguration -Path "C:\Deploy\TestBuildRelease_20161212.13\Deploy" -Wait -Force -Verbose -Credential $cred

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2008 R2 and powershell 5.0

**Version of the DSC module you're using:**
[ClassVersion("1.0.0.0"), FriendlyName("SPFarmSolution")]

So question is how to run all of this on powershell 2.0 that is required for SharePoint 2010?

**Comment by BrianFarnhill** [comment]
@VerdonTrigance Since PowerShell DSC requires at least PowerShell 4, there is no way we can add support for SharePoint 2010. As stated on our [wiki page](https://github.com/PowerShell/SharePointDsc/wiki), we only support SharePoint 2013 and 2016.
