### ISSUE TITLE
MSFT_SPAppManagementServiceApp not returning Database Name

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#476]
**Details of the scenario you try and problem that is occurring:**
When calling the Get-TargetResource function of the MSFT_SPAppManagementServiceApp resource, the database server and database name are not returned.

The return block is the following:
return  @{
                Name = $serviceApp.DisplayName
                ApplicationPool = $serviceApp.ApplicationPool.Name
                DatabaseName = $serviceApp.Database.Name
                DatabaseServer = $serviceApp.Database.Server.Name
                Ensure = "Present"
                InstallAccount = $params.InstallAccount
            }

But the property is $serviceApp.Databases with an 's' in Databases.

**The DSC configuration that is using the resource:**
N\A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 5 / Win Server 2012 R2
**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
I have some time available next week. Will pick this up together with the other bugs you reported.
