### ISSUE TITLE
MSFT_SPAccessServiceApp needs to return DatabaseServer

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#477]
**Details of the scenario you try and problem that is occurring:**
While using ReverseDSC, if we call the Get-TargetResource function to extract the current state, the DatabaseServer property is never returned. However, this property is mandatory in the Set-TargetResource function which then causes an error compiling the .MOF file.

Question: Should it be made a Best Practice that we need to return every Mandatory parameters in the Get-TargetResource? If not, it causes its lot of issues for the ReverseDSC

**The DSC configuration that is using the resource:**
N\A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 5\ Win 2012 R2

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
I would say a definite yes. In this case we should also check if the database server matches the specified database server. It probably isn't possible to change the database server, so we should throw an error specifying that the resource isn't in the desired state, but changing the database server using DSC isn't possible.

This is the same behavior as implemented in SPContentDatabase.

**Comment by ykuijs** [comment]
I have some time available next week. Will pick this up together with the other bugs you reported.
