### ISSUE TITLE
MSFT_SPDesignerSettings error getting Site Collection

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#478]
**Details of the scenario you try and problem that is occurring:**
When calling the Get-TargetResource function of the MSFT_SPDesignerSettings Resource passing in a "SiteCollection" scope, the site is never found. The issue comes from line 124, where we try to find the site by filtering the list using a variable ($url) that doesn't exist. Instead this block of code need to be filtering using the $params.Url parameter received by the function call as follow:

# Check if site collections exists
$site = Get-SPSite | Where-Object -FilterScript { 
    $_.Url -eq $params.Url 
}

**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 5 / Windows Server 2012 R2

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
I have some time available next week. Will pick this up together with the other bugs you reported.
