### ISSUE TITLE
MSFT_SPFarmSolution not using full Type Namespace

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#479]
**Details of the scenario you try and problem that is occurring:**
While this may not be a big deal, it would be good to keep consistency between all resources. Each resource seems to declare parameters using the Full Namespace (e.g. System.String) whereas MSFT_SPFarmSolution simply uses the short names (e.g. String). I would recommend keeping this consistent across and modifying the resource to keep the long name.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 4 / Win Server 2012 R2

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
I have some time available next week. Will pick this up together with the other bugs you reported.
