### ISSUE TITLE
MSFT_SPFarmSolution missing Param in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#480]
**Details of the scenario you try and problem that is occurring:**
Calling the Get-TargetResource function on the MSFT_SPFarmSolution Resource returns a value for parameter ContainsGlobalAssembly. However, this param is not taken by the Get, Set, or Test function. Either remove this from the return block of the Get-TargetResource function, or add it as an input param for each resource.

**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 4 / Win2012 R2
**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
I have some time available next week. Will pick this up together with the other bugs you reported.
