### ISSUE TITLE
MSFT_SPHealthAnalyzerRuleState doesn't accept and set proper value for On Demand rules

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#482]
**Details of the scenario you try and problem that is occurring:**
TheGet-TargetResource function of the MSFT_HealthAnalyzerRuleState specify that they accept "OnDemandOnly", which is the right value. However, with a default installation of SP2013, Health Analyzer has a default rule named "One or more app domains for web applications aren't configured correctly." that has a schedule value of "On Demand". Now, this may be a bug in the product, but I was wondering if it wouldn't be a good thing for the Get-TargetResource to account for this hick-up and translate any Schedule value of "On Demand" to "OnDemandOnly".

**The DSC configuration that is using the resource:**

N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/ WMF4

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
This is a bug indeed. When opening that item in Central Admin, the Schedule dropdown shows no default value. When selecting OnDemandOnly and saving, the item is then shown as OnDemandOnly

**Comment by ykuijs** [comment]
I will check how we can best handle this in Get-TargetResource

**Comment by ykuijs** [comment]
Included in bugfix PR

**Comment by BrianFarnhill** [comment]
@ykuijs again, which PR mate? :)
