### ISSUE TITLE
SPWebApplication inconsistent results

### ISSUE THREAD

**Issue by CStahlberg** [PowerShell/SharePointDsc#483]
**Details of the scenario you try and problem that is occurring:**
I am trying to create a new multi server SharePoint 2013 Farm in Azure using my own vhd template with pre installed SharePoint Software but it fails 90% of the time because the first server is incapable of creating a consistent web application. It manages to create a web application without any content database which leads to the following creation of a Site failing. Only after I manually remove the web application and rerun the configuration the dsc creates a content database. The database server is an alias if that is of any relevance

**The DSC configuration that is using the resource:**
SPWebApplication SharePointSites
            {
                Name                   = "SharePoint Portal"
                ApplicationPool        = "SharePoint Portal"
                ApplicationPoolAccount = $WebPoolManagedAccount.UserName
                AllowAnonymous         = $false
                AuthenticationMethod   = "NTLM"
                DatabaseName           = "SP_Content_Portal_01"
                DatabaseServer         = "Content"
                Url                    = "http://$($FarmName).$($DomainFQDN)"
                HostHeader             = "$($FarmName).$($DomainFQDN)"
                Port                   = 80
                PsDscRunAsCredential   = $PSSPSetupAccount
                DependsOn              = "[SPManagedAccount]WebPoolManagedAccount"
            }
SPSite TeamSite
            {
                Url                      = "http://$($FarmName).$($DomainFQDN)"
                OwnerAlias               = "${DomainName}\$($SPSetupAccount.UserName)"
                Name                     = "Portal"
                Template                 = "STS#0"
                PsDscRunAsCredential     = $PSSPSetupAccount
                DependsOn                = "[SPWebApplication]SharePointSites"
            }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
The Server is running Windows Server 2012 R2 in azure.
**Version of the DSC module you're using:**
The DSC Version is 2.21.0.0 and the SharePoint Module is 1.5.0.0

**Comment by CStahlberg** [comment]
The intial problem seems to be my mistake I thought I would not have to wait for the Alias Creation of all 4 Aliases since the CreateSPFarm was depending on one of them. 
 
Now I get the problem that the webapplication gets created but everytime the dsc reports an error because of the webapplication being updated by the same account in the timer service (OWSTIMER) even though it is the first server being created and the script is running the first time.
>The object SPWebApplication Name=SharePoint Portal was updated by Mydomain\\spfarm, in the OWSTIMER (1332) process, on machine DEVSPSAP01. 

Since I saw that the Url is not a required field I removed it from SharePointSites 
This error then leads to the other azure servers not being created because of the error result.

**Comment by BrianFarnhill** [comment]
@CStahlberg So typically we see this happen when we have multiple DSC resources on different machines trying to update or change the same object at the same time, its why we recommend that you only do things related to a web application on a single server in the farm and not all of them. Do you have any of the items that touch the web application running on more than one server in your farm?

**Comment by CStahlberg** [comment]
@BrianFarnhill no it is only the first server in the farm which is running the configuration all other servers are depending on the completion of the task. Thats why I find it weird that it even happens. Maybe I will try to create a seperate dsc configuration that runs after the last server has been joined to the farm whose only job is to create the web application

**Comment by BrianFarnhill** [comment]
That shouldn't be necessary - what DSC resource is failing with the message about the update conflict there?

**Comment by CStahlberg** [comment]
Thre Resource that is failing is the Webapplication below:

            SPWebApplication SharePointSites
            {
                Name                   = "SharePoint Portal"
                ApplicationPool        = "SharePoint Portal"
                ApplicationPoolAccount = $WebPoolManagedAccount.UserName
                AllowAnonymous         = $false
                AuthenticationMethod   = "NTLM"
                DatabaseName           = "SP_Content_Portal_01"
                DatabaseServer         = "Content"
                Url                    = "http://$($FarmName).$($DomainFQDN)"
                Port                   = 80
                PsDscRunAsCredential   = $PSSPSetupAccount
                DependsOn              = "[SPManagedAccount]WebPoolManagedAccount"
                Ensure                 = "Present"
            }

            SPContentDatabase PortalContent 
            {
                Name                   = "SP_Content_Portal_01"
                DatabaseServer         = "Content"
                WebAppUrl              = "http://$($FarmName).$($DomainFQDN)"
                Ensure                 = "Present"
                PsDscRunAsCredential   = $PSSPSetupAccount
                DependsOn              = "[SPWebApplication]SharePointSites", "[xSQLServerAlias]Content"
            }

            SPSite TeamSite
            {
                Url                      = "http://$($FarmName).$($DomainFQDN)"
                OwnerAlias               = "${DomainName}\$($SPSetupAccount.UserName)"
                Name                     = "Portal"
                Template                 = "STS#0"
                PsDscRunAsCredential     = $PSSPSetupAccount
                DependsOn                = "[SPWebApplication]SharePointSites"
            }

I am starting to think that the problem lies within azure since I could not even get my arm template to deploy in the first place but today it gets to the sharepoint configuration without me changing anything.

Those are the error messages I am getting in thet status file in reversed order:

> The PowerShell DSC resource \u0027[SPWebApplication]SharePointSites\u0027 with SourceInfo \u0027C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.21.0.0\\DSCWork\\ConfigureSharePoint.0\\ConfigureSharePoint.ps1::214::13::SPWebApplication\u0027 threw one or more non-terminating errors while running the Set-TargetResource functionality

>DSC Configuration \u0027ConfigureSharePoint\u0027 completed with error(s). Following are the first few: An update conflict has occurred, and you must re-try this action. The object SPWebApplication Name=SharePoint Portal was updated by mydomain\\spfarm, in the OWSTIMER (2956) process, on machine SDEVS13SPSAP01

Upon reviewing the ULS Log I think I find the root cause but I am unsure how to fix it.
>UpdatedConcurrencyException: The object SPWebApplication Name=SharePoint Portal was updated by another user.  Determine if these changes will conflict, resolve any differences, and reapply the second change.  This error may also indicate a programming error caused by obtaining two copies of the same object in a single thread. Previous update information: User: mydomain\spfarm Process:OWSTIMER (2956) Machine:SDEVS13SPSAP01 Time:January 23, 2017 06:01:21.0000  Current update information: User: mydomain\ADFSAdmin Process:wsmprovhost (1120) Machine:SDEVS13SPSAP01 Time:January 23, 2017 06:02:21.0344

The user that is used in the DSC resource is ADFSAdmin while spfarm is the farm account.

**Comment by BrianFarnhill** [comment]
@CStahlberg OK so what I can see here is that there is something else that is touching the web app while it's being created. If you look through the ULS logs at what is happening at the same time, can you see anything else making changes to it? 

The only thing we send you in to the set method for on a web app is to create it, if it exists you wont ever hit set-targetresource again. So from what I can see here one of the things touching it is DSC, but the second thing has to be coming from somewhere else on that machine, and the ULS logs should help you shine light on what it is.

**Comment by CStahlberg** [comment]
@BrianFarnhill thank you very much for your help!

I looked at the ULS there is no other process running at the exact time as the error. The last process before the segment with the wsmprovhost is the owstimer with the message "UserAgent not available, file operations may not be optimized." what is really interesting is that the contentdatabasecollection.add seems to be executed twice but the second time it runs into the update concurrency exception. I Guess I would have to set the log level to verbose to see what exactly is going on.

I Added the ULS Log as attachment the firs tab is the merged log only containing the erro the second tab is the complete ULS of that time
[AzureULS.xlsx](https://github.com/PowerShell/SharePointDsc/files/725746/AzureULS.xlsx)

**Comment by CStahlberg** [comment]
@BrianFarnhill I managed to get this working by setting up the webapplication on the second server in the farm which is ok for me but I think there might a design oversight in the SPDistributedCacheService regarding azure loops.

There is a part in the SPDistributedCacheService configuration where you check if the ServiceInstance for the distributed cache can be found using only the servername but I don't think that will work in azure dsc loops. 

`# Attempt to see if we can find the service with just the computer `
`# name, or if we need to use the FQDN`
`$si = Get-SPServiceInstance -Server $currentServer  | Where-Object -FilterScript { $_.GetType().Name -eq "SPDistributedCacheServiceInstance" }`

Those azure loops seem to process multiple servers in parallel which is a problem because all servers have been joined to the farm using the parameter "SkipRegisterAsDistributedCacheHost" (see MSFT_SPJoinFarm.psm1). If server two now tries to check for the existence of server one which has not yet started processing, the script will think it has to use the fqdn even if the server only uses a netbios name. In the end it will timeout after 30 minutes and still create the service but if you try to get the name from Get-SPServer that should not be the problem.

`$srv = Get-SPServer | ? {$_.Address -eq $currentServer} `
`if($srv -eq $null)`
`{`
`    $domain = (Get-CimInstance -ClassName Win32_ComputerSystem).Domain`
`    $currentServer = "$currentServer.$domain"`
`}`

**Comment by BrianFarnhill** [comment]
@CStahlberg When you say "Azure DSC loops" what exactly are you referring to? It shouldn't make a difference if you are in Azure or not. 

The thinking behind the logic inside the distributed cache one is to wait for servers to be available for it to run. If you need to put them in to a sequence so only one at a time runs you can use the "ServerProvisionOrder" to tell the distributed cache service to do the servers in a specific order (they will poll every 60 seconds I believe and will wait up to 60 minutes (I believe, it might be 30, I need to check) for the other servers to succeed in provisioning before moving on to the next. Perhaps this property might help you here?

**Comment by CStahlberg** [comment]
@BrianFarnhill in Azure JSON templates you can insert a [copy object](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-multiple) into a resource which makes azure deploy the resource multiple times. I use this to deploy two or more front end servers (depending on the copycount parameter). The proplem is that both copies are created at the same time or the second server might start deploying before the first one. 

Let's say the provisioning order is Server01, Server02.
This is where there is a problem not with the provisioning order but the fact that the second server might start provisioning the cache before the first server reaches that point.  

Now checking for the distributed cache service using the servername Server01 on Server02 will not work because Server01 has not yet reached the point of deploying the instance so of course it will return null and the server will henceforth use the FQDN Server01.domain to check the status (for 30 minutes) which will never work because the server registered using the netbios name in the meantime.

                        # Attempt to see if we can find the service with just the computer 
                        # name, or if we need to use the FQDN
                        $si = Get-SPServiceInstance -Server $currentServer `
                            | Where-Object -FilterScript { 
                                $_.GetType().Name -eq "SPDistributedCacheServiceInstance" 
                        }

                        if ($null -eq $si) 
                        { 
                            $domain = (Get-CimInstance -ClassName Win32_ComputerSystem).Domain
                            $currentServer = "$currentServer.$domain"
                        }
                        
                        Write-Verbose "Waiting for cache on $currentServer"
                        $serviceCheck = Get-SPServiceInstance -Server $currentServer `
                            | Where-Object -FilterScript { 
                                $_.GetType().Name -eq "SPDistributedCacheServiceInstance" -and `
                                $_.Status -eq "Online" 
                        }

Server01 will start provisioning and finish beforce Server02 eventually decides to skip ahead after 30 minutes not finding a service on Server01.domain.

After changing the script to always look for both names (netbios and FQDN) the script finds the other server but somehow the cache never manages to deploy working on both servers one always gets stuck on provisioning but that might just be my servers.

I hope you undersand what I mean now because I am not a native speaker and I don't know how else to put it.

**Comment by BrianFarnhill** [comment]
@CStahlberg No I think I understand the challenge here, and I suspect this comes back to some design issues we had with the distributed cache resource in the first place (in that it sort of does depend on what is happening with other servers at any given time before it can do anything). Leave this one with me and I'll see what we can come up with to make that sort of approach better.

**Comment by CStahlberg** [comment]
@BrianFarnhill I really appreciate your help. I suppose I can close this issue then. The webapplication does work now running it on a different server at a different time and the distributed cache was never really part of this problem.

It would be great if the deployment of the distributed cache could be handeld by a queue. 
Tanks again for the help
