### ISSUE TITLE
MSFT_SPSearchServiceApp gives error even if not Hybrid Search is enabled

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#484]
**Details of the scenario you try and problem that is occurring:**
I am probably the one who wrote this back in the days 👍 but when you call the Set-TargetResource function of the MSFT_SPSearchServiceApp and pass it $CloudIndex = $False, if the farm is not at least at the August 2015 CU, it will thrown an error saying you need to install that CU. I am of the opinion that if this parameter is present, but set to $False, that the Resource should simply ignore this step. We could modify the resource like the following:

Current:

            if ($params.ContainsKey("CloudIndex") -eq $true)

New

            if ($params.ContainsKey("CloudIndex") -eq $true -and $params.Get_Item("CloudIndex") -eq $true)

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 5
**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
Included in bugfix PR

**Comment by ykuijs** [comment]
After implementing the change, I also removed it again. What if you want to change a Cloud SSA into a regular SSA? You would use CloudIndex=$false, but with this change the value would be ignored. Therefore I think we should not implement this change.

@NikCharlebois What do you think?

**Comment by NikCharlebois** [comment]
Agreed, we need to handle the scenario where we want to change it from a cloud based index to an on-prem one. I am just wondering if there is an easier way to prevent an error from being thrown if a given parameter is passed. 

If we compare this to the SPCreate and SPJoin Farm, I ServerRole is passed, then we error out if the farm is not 2016. I think it this case it makes sense, since we are taking about major version, and it is okay to have the "DSC signature" be different between SP2016 and 2013. In the CloudIndex case however, we are dealing with two different signature within the same major version (2013). My take on this, is that a given DSC configuration script for 2013, should work against all other SP2013 environments, unless it is trying to leverage a feature (CloudIndex=$true) that is not supported. 

What do you guys think?

**Comment by BrianFarnhill** [comment]
Do we even support changing it from a cloudindex SSA to a non cloud enabled one? I thought the process was to create a new SSA when you wanted to make this change (there was some early doco of being able to change it while this feature was being tested, but I was of the understanding that it wasn't actually supported come release). 

I agree we shouldn't just be checking for the parameter to be present, it should be a matter of:

1. Is it present?
2. Is it true?
3. Is the build number high enough? If not, throw an error

So then it just becomes a matter of something like

    $params.ContainsKey("CloudIndex") -eq $true and $params.CloudIndex -eq $true

as the check before we do the binary version check. Does that make sense? Thoughts?

**Comment by NikCharlebois** [comment]
Just confirmed with Neil H. that this is not possible. The property is Read-Only anyway once the SSA has been created.
