### ISSUE TITLE
MSFT_SPSearchServiceApp doesn't return DatabaseName and Server in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#485]
**Details of the scenario you try and problem that is occurring:**
MSFT_SPSearchServiceApp doesn't return the Database Name and Server in its Get-TargetResource. The Return block tries to return a property that doesn't exist:

Current:
DatabaseName = $serviceApp.Database.Name
DatabaseServer = $serviceApp.Database.Server.Name

Should be:
DatabaseName = $serviceApp.**SearchAdminDatabase**.Name
DatabaseServer = $serviceApp**.SearchAdminDatabase**.Server.Name

**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2012 R2/WMF 4
**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
Included in bugfix PR

**Comment by BrianFarnhill** [comment]
@ykuijs I don't see a PR for this one? Is there a fix or did I miss something (I'm still coming out of holiday mode so forgive me if I did!)

**Comment by ykuijs** [comment]
I know, haven't had the time to actually create the PR yet. It is a little hectic at the moment :-) Fixes are implemented though.

Will create the PR in the next couple of days.
