### ISSUE TITLE
MSFT_SPAppManagementService App Get-Target Resource not returning Database

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#486]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource function of the MSFT_SPAppManagementServiceApp resource is not returning the Database Name and Server. The return block is calling property .Database instead of **.Databases**.

**Current:**
DatabaseName = $serviceApp.Database.Name
DatabaseServer = $serviceApp.Database.Server.Name

**Should Be:**
DatabaseName = $serviceApp.Databases.Name
DatabaseServer = $serviceApp.Databases.Server.Name

Or check to make sure that there is a way to have multiple databases associated and then properly return an array?
**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 4
**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
Included in bugfix PR

**Comment by ykuijs** [comment]
Duplicate of issue #476. Please close this issue

**Comment by NikCharlebois** [comment]
My bad, this was already reported
