### ISSUE TITLE
MSFT_SPCreateFarm Get-TargetResource method should return ServerRole property for SP2016

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#487]
**Details of the scenario you try and problem that is occurring:**
When calling the Get-TargetResource function of the MSFT_SPCreateFarm resource, the Return block does not return the ServerRole property associated with the current server. Maybe this is the expected behavior, but then in this case MSFT_SPJoinFarm should return it instead, but it is not returning it either. Ideally they should both return that property.

**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016 / WMF 5
**Version of the DSC module you're using:**
1.5.0.0

**Comment by NikCharlebois** [comment]
@BrianFarnhill  Assign that one to me, I'll take care of it today. Thanks

**Comment by NikCharlebois** [comment]
I think this one may be a little more challenging than I originally anticipated. I you call the Get-TargetResource on either the SPCreateFarm or SPJoinFarm.....how do you know which server to retrieve the server role from?

**Comment by BrianFarnhill** [comment]
@NikCharlebois You should be able to find the current server with something like this:

    $server = Get-SPServer -Identity $env:COMPUTERNAME

Have a look in the search topology and distributed cache resources as we do the same thing on those, but we also have a little catch all loop on those to account for appending the current domain name as well in case that is needed too, but you should be able to lift the same script from there. Does that make sense?

**Comment by ykuijs** [comment]
@NikCharlebois I would like to include this bugfix in v2.0. Can you manage to implement the fix in the upcoming weeks?

**Comment by NikCharlebois** [comment]
Absolutely mate. I’ll get on it

**Comment by NikCharlebois** [comment]
Fixed in my latest PR

**Comment by BrianFarnhill** [comment]
@ykuijs This one needs to go into the 1.x version of the product. There won't be a SPCreateFarm and SPJoinFarm in v2.0 since we decprecated them and need to take them out.

**Comment by ykuijs** [comment]
Ok, should we add these to the v1.9 release then, since that is not yet merged into Master......

**Comment by NikCharlebois** [comment]
Folks, I actually made the change in the SPFarm resource. I don't see the advantage of updating the SPCreate and SPJoin Farm resources with this change at this stage. Those are pretty much set in stone at this stage since we are starting work on 2.0. I recommend we go ahead and merge these changes into 2.0 only. Thoughts?

**Comment by ykuijs** [comment]
I agree!

**Comment by NikCharlebois** [comment]
Fixed in latest PR
