### ISSUE TITLE
People Picker configuration

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#488]
**Details of the scenario you try and problem that is occurring:**
Are there any plans to add a resource to configure the People Picker with custom filters?

**Comment by BrianFarnhill** [comment]
There are now, we'll track it against this issue!

**Comment by typozh** [comment]
Any news?

**Comment by ykuijs** [comment]
Hi @typozh, I am working on this resource as we speak. Will be included in my next PR

**Comment by ykuijs** [comment]
Fixed in PR #680
