### ISSUE TITLE
MSFT_SPSearchIndexPartition Get-TargetResource not returning FolderPath

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#496]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource function of the MSFT_SPSearchIndexPartition resource is not properly returning the RootDirectory value. It simply returns whatever you passed it as parameters instead.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 4

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
Closed with PR 660
