### ISSUE TITLE
MSFT_SPDistributedCache Get-TargetResource not returning the status of remote servers

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#497]
**Details of the scenario you try and problem that is occurring:**
When calling the Get-TargetResource, it will return the null block if the DC is not enabled on the server on which you are running the script from, which is ok. But the Get-TargetResource function should be able to extract the current state of the DC for a remote server (not the one running the script). Currently, when running the ReverseDSC and calling into the Get-TargetResource function, if the DC is not enabled on the current server, it will never retrieve information about the other servers. We either need to modify the query filter so that it doesn't only filter the Hosts based on the current server name or we need to add an additional parameter (say "ComputerName") that would allow the method to detect the DC service status on that remote SPServer.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 / WMF 4

**Version of the DSC module you're using:**
1.5.0.0

**Comment by BrianFarnhill** [comment]
@NikCharlebois I disagree. All of the logic in all of our resources has always only ever been focussed on running on the server that the code is executing on, and while this would be convenient for your reverse scenario I don't think it's something I want to break in our design approach to fit that one in. @ykuijs what do you think?

**Comment by ykuijs** [comment]
I agree with @BrianFarnhill, this has been the focus for all resources.

**Comment by BrianFarnhill** [comment]
Thanks @ykuijs - Sorry @NikCharlebois but I'm gonna close this one off. Ping me an email though and we can have a chat about other alternatives that might be able to help you with what you are doing mate.
