### ISSUE TITLE
CentralAdministration - SecureSocketsLayer

### ISSUE THREAD

**Issue by bardtomm** [PowerShell/SharePointDsc#498]
**Details of the scenario you try and problem that is occurring:**
CentralAdministration is created with http

**The DSC configuration that is using the resource:**
SPCreateFarm
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016, SharePointDSC 1.5.0.0

**Version of the DSC module you're using:**

Would like it to be possible to create the CentralAdministration with SSL

**Comment by BrianFarnhill** [comment]
@bardtomm You can do this through combining a couple of resources

1. Create the farm with SPCreateFarm
2. Add a HTTPS alternate URL with SPAlternateUrl
3. (optional) Bind your SSL certificate to the site in IIS using xWebsite in the xWebAdministration module

This is the approach I've taken with a number of customers and it works a treat. The reason we do it like this is that the central admin site always comes out of the New-SPConfigurationDatabase command as HTTP, so in the same way as you would normally need to add the URL we do the same with DSC. Does that make sense?

I'm going to close this issue off as it's not something we can change in the DSC resources, but if you need help using the alternate URL approach let me know.
