### ISSUE TITLE
New resource to configure DistributedCacheClientSettings

### ISSUE THREAD

**Issue by hermansolberg** [PowerShell/SharePointDsc#505]
**Details of the scenario you try and problem that is occurring:**
Suggestion to create a new resource that can configure the DistributedCacheClientSettings according to this [guidance](https://technet.microsoft.com/en-us/library/jj219613.aspx#finetune)

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
1.5.0.0

**Comment by MikeLacher448** [comment]
my customer ran into an issue yesterday where we needed to adjust some of these settings, I'll take a stab at this resource.

**Comment by ykuijs** [comment]
Closed via PR #769
