### ISSUE TITLE
Add support to configure DefaultQuotaTemplate for a web application

### ISSUE THREAD

**Issue by hermansolberg** [PowerShell/SharePointDsc#507]
**Details of the scenario you try and problem that is occurring:**
Add a property to the resource SPWebApplication or SPWebAppGeneralSettings to allow configuration of DefaultQuotaTemplate.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
Implementing the property in SPWebAppGeneralSettings

**Comment by ykuijs** [comment]
Fixed in PR #680
