### ISSUE TITLE
HappyHour values not being set properly

### ISSUE THREAD

**Issue by wfeaser** [PowerShell/SharePointDsc#511]
Values for a HappyHour (SPWebApplication.Throttling) are not being set properly.  No error is being raised.  The issue is the values are being passed/tested as $Settings, which is correct.  However, when the values are assigned to the variables of $h, $m, and $d, an undeclared variable of $happyhour is being used.  This results in no values actually being set.

Resource:  MSFT_SPWebAppThrottlingSettings
Module:  SPWebApplication.Throttling
Function:  Set-SPDSCWebApplicationHappyHourConfig

PowerShell 5 on Windows Server 2012 R2

Version of DSC Module:  master branch, release 1.5.  also confirmed the problem exists in the current dev branch (as of 2/16/2017).

**Comment by MikeLacher448** [comment]
I'm looking at this one, and in addition to the mismatched variable names, it appears to fail the test method when the current and desired happy hour values don't match. In my lab, the Test-SPDSCObjectHasProperty is picking up the HappyHoud embedded cim instance.

**Comment by BrianFarnhill** [comment]
OK thanks @MikeLacher448 - let me know if you need anything with this one

**Comment by MikeLacher448** [comment]
fixed by PR #526
