### ISSUE TITLE
Add support for claims authentication providers to SPWebApplication and SPWebAppExtention

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#512]
**Details of the scenario you try and problem that is occurring:**

Currently SPWebApplication and SPWebAppExtension (when it is finalised, see discussion in #40) do not support claims based authentication, only Windows auth as either NTLM or Kerberos. This support needs to be added.

**Comment by Yvand** [comment]
Hello,
SharePointDsc 1.6 adds possibility to specify federated authentication in SPWebApplication resource, which is great, but current implementation has multiple issues:
- Parameter AuthenticationMethod accepts "NTLM", "Kerberos" and "Claims", but all (NTLM, Kerberos, FBA or Federated) are actually claims authentication, so possible values should be "NTLM", "Kerberos" and "Federated".
- FBA is missing.
- Parameter AutheticationMethod misses possibility to specify multiple authentication modes.

The same mistake is being made in [upcoming resource SPWebApplicationExtension](https://github.com/PowerShell/SharePointDsc/pull/510)

**Comment by BrianFarnhill** [comment]
@Yvand I agree with you on this (I think I asked the question about calling it claims in code review but we let it slip). Can I get you to open a new issue for this one, since we already shipped 1.6 changing this would be a breaking change so it'll go in to our upcoming 2.0 release. Then we can use this issue was about adding that federated support so we'll close this one off once #510 closes and then we can track your issue there as a separate piece of work.

**Comment by Yvand** [comment]
@BrianFarnhill sure, I'll take care of this

**Comment by ykuijs** [comment]
@Yvand Any update?

**Comment by ykuijs** [comment]
Ok, so we can close this issue then?

**Comment by Yvand** [comment]
Yes

**Comment by ykuijs** [comment]
Ok, closing issue. Thanks for the reply
