### ISSUE TITLE
Typo in SPSearchIndexPartition return of Get-targetresource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#518]
**Details of the scenario you try and problem that is occurring:**
I feel bad reporting this but there is a typo in the return block for the return block of Get-TargetResource where ServiceAppName has a capital 'P'. It doesn't cause any issue, just needs to be fixed to look more professional :)

return @{
            Index = $params.Index
            Servers = $IndexComponents
            RootDirectory = $params.RootDirectory
            ServiceAPpName = $params.ServiceAppName
            InstallAccount = $params.InstallAccount
        }

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
win 2012 r2/wmf 5.1

**Version of the DSC module you're using:**
1.5.0.0

**Comment by NikCharlebois** [comment]
Hey B, assign that one to me, I've got some cycles to fix the issues I reported around Get-TargetRessource

Cheers!

**Comment by ykuijs** [comment]
@NikCharlebois Have you fixed this already? I can include this in my bugfix PR I am working on at the moment.

**Comment by NikCharlebois** [comment]
@ykuijs  No, I haven't started if you wish to take in on. Thanks

**Comment by ykuijs** [comment]
Will do!

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
