### ISSUE TITLE
SPSearch Topology Get-TargetResource not returning FirstPartitionDirectory

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#519]
**Details of the scenario you try and problem that is occurring:**
Reverse Engineering the SPSearchTopology resource doesn't return a value for FirstPartitionDirectory. Now, I understand it may be though to determine which index location was the very first one to be created, but at least, I believe that the Get-TargetResource should return the "IndexLocation" property of one of the AdministrationComponent.

**The DSC configuration that is using the resource:**
SPSearchTopology 7a180ea7-2a7a-46a2-be72-ea9f9b71f922
        {
            ContentProcessing = @("OSFI-SP2016");
            AnalyticsProcessing = @("OSFI-SP2016");
            InstallAccount = $CredsFarmAccount;
            IndexPartition = @("OSFI-SP2016");
            Crawler = @("OSFI-SP2016");
            Admin = @("OSFI-SP2016");
            ServiceAppName = "2013_Search Service Application";
            QueryProcessing = @("OSFI-SP2016");
            FirstPartitionDirectory = "*";
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 5.1

**Version of the DSC module you're using:**
1.5.0.0

**Comment by NikCharlebois** [comment]
@BrianFarnhill  Assign that one to me buddy. I am planning on returning the first partition no matter what...if that makes sense

**Comment by ykuijs** [comment]
@NikCharlebois I would like to include this bugfix in v2.0. Can you manage to implement the fix in the upcoming weeks?

**Comment by NikCharlebois** [comment]
Yah man. I’ll get it done next week

**Comment by NikCharlebois** [comment]
Fixed in my latest PR

**Comment by NikCharlebois** [comment]
Fixed in latest PR
