### ISSUE TITLE
Improve doco on SPInstallLanguagePack

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#523]
Just had a conversation with someone using this resource for SharePoint 2016 - it looks like there was a change to use EXE files for the langauge packs instead of the old IMG file downloads for the 2013 ones. This is confusing some people about the BinaryDir value as when you point it at the EXE or the folder the EXE is in the whole thing doesn't work. 

The good news is that it does still work if you extract the EXE ( .\serverlanguagepack.exe /extract:C:\temp\test will do it) so I just want to capture that in the readme.md file for this one with a bit more of a detailed write up about those differences so the documentation is clear.

**Comment by ykuijs** [comment]
I am on it, will be fixed in a bugfix PR

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
