### ISSUE TITLE
SPFarm Get-TargetResource doesn't return RunCentralAdmin

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#527]
**Details of the scenario you try and problem that is occurring:**
The new SPFarm resource in 1.6.0.0 doesn't return mandatory parameter RunCentralAdmin as part of its Get-TargetResource.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016 / PoSh 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
I am on it, will be fixed in a bugfix PR

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
