### ISSUE TITLE
SPSecureStoreServiceApp doesn't expose a Database property

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#529]
**Details of the scenario you try and problem that is occurring:**
In the Get-TargetResource method for SPSecureStoreServiceApp, the return block tries to access the Database property of the Service App instance, however that property doesn't exist on that object, resulting in both the DatabaseServer and DatabaseName properties to be empty. Instead, I believe we will need to retrieve this information by using the Get-SPDatabase cmdlet and check for DBs of type Microsoft.Office.SecureStoreService.Server.SecureStoreServiceDatabase

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/PoSh 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
Any clue how to determine which database belongs to which service application? For example: What if there are multiple Secure Store Service Applications?

**Comment by NikCharlebois** [comment]
Quickly looking at the DB, Service App, and SA Proxy object and can't seem the figure out the relation between the SA and its DB unfortunately. SecStore has always been a tough nut to crack...Sorry

**Comment by BrianFarnhill** [comment]
I feel like that's why this might have been missed at the time! @ykuijs have a look and let me know if you need an extra set of eyes to identify the properties. If you need to, take a look at how we get the databases in SPUserProfileService - we had to reflect those out so we might need to do something similar here.

**Comment by ykuijs** [comment]
Ok, figured out how to retrieve this value. Will include this in my bugfix PR

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
