### ISSUE TITLE
SPManagedMetaDataServiceApp throws error in Get-targetResource trying to retrieve Conten Type Hub Url

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#532]
**Details of the scenario you try and problem that is occurring:**
When trying to extract the Current state of my SP2016 farm (Dec 2016 PU), the Get-TargetResource method of SPManagedMetaDataServiceApp throws an error (which is properly catch) when trying to retrieve the Content Type Hub Url which results in the URL always being null. It seems like the "GetContentTypeSyndicationHubLocal" doesn't exist anywhere in the object model for the service Application. Can any of you check to confirm that they are properly able to retrieve this value out of an existing environment?

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/PoSh 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
This is probably a SP2016 issue. Just tested it on SP2013 and it works fine there. Will validate it on SP2016 in the upcoming days.

**Comment by ykuijs** [comment]
Indeed looks something has changed in SP2016. Just tried the code in SP2016 and just like what your ran into as well, it returns an empty property. Will have to check how to retrieve this URL from SP2016.

@BrianFarnhill, @NikCharlebois Any clue?

**Comment by BrianFarnhill** [comment]
Not off to top of my head - maybe we need to look in to whether it is there as a private property now? It seems weird that it would be removed like that.

**Comment by ykuijs** [comment]
The property "GetContentTypeSyndicationHubLocal" doesn't exist at all anymore. Have been looking with Ilspy to get some information, but all required classes are specified as Internal.

**Comment by ykuijs** [comment]
Figured out how to retrieve this property in SP2016, thanks to @BrianFarnhill :-) Will add this to the bugfix PR.

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
