### ISSUE TITLE
Update documentation on guidance for HNSC when using SPSite

### ISSUE THREAD

**Issue by nissan** [PowerShell/SharePointDsc#534]
**Details of the scenario you try and problem that is occurring:**
I am creating 4 Host Named Site Collections under a main Web Application using the SPSite keyword.
While the sites are created and reported in SP Central Administration, and a HOSTS file edit has been made to route the DNS names used to the Single Server Farm server, I was getting a HTTP 404 error when trying to access the URL.

My fix: The fix came when I examined IIS Bindings for the Web Application, and added the Bindings for the URL of the Site Collections manually. Then the site collections were displayed. However, this step is not presently documented in the SPSite GitHub documentation.
Ideal fix: I think this step to create the additional bindings in IIS should be part of the SharePointDSC or added in notes with reference to how to use another DSC Module (possibly xWebAdministration) to ensure the change happens.
Attaching the DSC script used to configure the Single Server Farm and create the web application and host named site collections
[sp2016singleserver.zip](https://github.com/PowerShell/SharePointDsc/files/838338/sp2016singleserver.zip)

**The DSC configuration that is using the resource:**
Single Server Farm created using SharePointDSC with site collections created using the SPSite keyword

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Target system is running Window Server 2012 R2 running Powershell v5.0.10586.20151218

**Version of the DSC module you're using:**
SharePointDSC v1.4.0.0

**Comment by ykuijs** [comment]
Hi @nissan, this is correct. This is exactly the same behavior when a site collection from Central Administration. You have to do this manually, via xWebAdministration (when using DSC) or by using a wildcard domain (for example add *.domain.com to your IIS websites and then create new site collections in site1.domain.com and site2.domain.com).

I think it is a good addition to include this in the documentation to prevent others from spending time on troubleshooting.

**Comment by nissan** [comment]
Actually, when I updated my SharePointDSC to 1.6.0 and removed the "HostHeader" field in creating my web application, the new site collections worked correctly (once the DNS entries were made in my AD to point the hostnames to the SP WFE, something that can also be achieved with a HOSTS file entry on the machine browsing the site if you are only testing). If the HostHeader field is present, it binds the IP to the web application name, and prevents IIS from resolving any of the site collection URLs. However this is actually what should be the documentation enhancement for both SPSite and SPWebApplication (to remove the HostHeader parameter if planning to use Host Named Site Collections). There are documentation references for this host header parameter concern on [MSDN ](https://blogs.msdn.microsoft.com/kaevans/2012/03/27/what-every-sharepoint-admin-needs-to-know-about-host-named-site-collections/)and [TechNet](https://technet.microsoft.com/en-us/library/cc424952.aspx#section1e)

**Comment by luigilink** [comment]
Exactly if you want to use Host Named Site Collections, you have to create the SPWebapplication without HostHeader parameter. But it's a good point, we have to add this tips in documentation.

In term of best practices, never change manually the IIS bindings because these bindings are saved in SharePoint_Config_Db, so If you add a new server in your farm, the IIS Bindings will be settings with the informations  saved in this database.

**Comment by BrianFarnhill** [comment]
The points by @ykuijs and @luigilink are correct here. SPSite will never touch the IIS bindings as we have no way to do that on every server from that one resource. The advice should be to use the xWebsite resource in xWebAdministration to manage bindings on each WFE server in the farm. So lets go ahead and add that to the documentation (I feel the doco change needs to go on both SPWebApplication and SPSite to make it super obvious) and go from there

**Comment by ykuijs** [comment]
Will be included in my bugfix PR
