### ISSUE TITLE
MSFT_SPHealthAnalyzerRuleState logic question

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#535]
**Details of the scenario you try and problem that is occurring:**
I have a customer who ran ReverseDSC on their existing SP2013 environment and who are now trying to configure a new farm using the extracted script. They are running into an issue where the original server they executed ReverseDSC against had a Health Rule named "Critical state of this rule indicates that the Word Automation Services is not running when it should be running.". However, that rule doesn't exist on their new environment, so when they run SharePointDSC (forward), they get the following error thrown:

"Could not find specified Health Analyzer Rule. Health Analyzer Rule settings will not be applied"

By looking at the MSFT_SPHealthAnalyzerRuleState, I seem to understand that this resource never creates anything. Instead the Set-TargetResource function expects the $Name parameter to match an existing rule and then simply configures it based on the received parameters. Two questions:

1 - Shouldn't the Set-TargetResource allow for the creation of new Health Rules?

2 - Can we find a way to better handle the error in the case the rule is not found? I can see being a real problem when switching between environments where the rules (e.g. from 3rd party tools) are different.

**The DSC configuration that is using the resource:**
{...}
SPHealthAnalyzerRuleState 6ffe217d-ea75-4cc4-ac7c-e51c47bd1a2e
        {
            FixAutomatically = $False;
            Name = "Critical state of this rule indicates that the Word Automation Services is not running when it should be running.";
            Schedule = "Hourly";
            InstallAccount = $CredsFarmAccount;
            RuleScope = "Any Server";
            Enabled = $True;
        }
{...}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
win 2016/PoSh 5.1
**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
Since this resource is called, SPHealthAnalyzerRule**State** it is purely focussed on the state of Health Analyzer rules.

Not entirely sure, but shouldn't new Health Analyzer rules be deployed using code deployed on the environment? In other words, would DSC be able to create new rules?

**Comment by NikCharlebois** [comment]
@ykuijs You are absolutely correct, deploying a new custom SPHealthAnalysisRule would require FTC to be deployed. However, I am wondering how it is that these rules differ from one environment to an other.The rule mentioned above is defined here (https://technet.microsoft.com/en-us/library/hh487298.aspx) so it looks like this is an out of the box one. However, I don't have it in the latest builds for my SP2013 farms. This will be an issue for anyone trying to create and configure a new environment. Isn't there a way we can notify the user if the rule he is trying to change the state for doesn't exist, but not throw an error?

**Comment by NikCharlebois** [comment]
I am actually wondering if this rule gets automatically created when a new Word Automation Service App is being instantiated. Will take a closer look later today. This would simply mean that a DependsOn clause would be required by the user and would solve my issue.

**Comment by NikCharlebois** [comment]
@ykuijs Ok, I confirmed that these rules get automatically added to the farm the moment you create a Word Automation Service application. Therefore, I will need to come up with a rule engine inside of ReverseDSC that will automatically assign DependsOn clause to "service app" specific rules to make sure the Service Application is instantiated before we attempt to configure the rule.

**Comment by ykuijs** [comment]
That was my guess exactly, either not on the same patch level or the Word Automation Service App not deployed yet. Good to hear this is indeed the case :-)

Is there a way to check which service application implements which rule? If this would be a manual inventory, we have to evaluate each cumulative update/service pack/etc for changes, new rules, etc. Not a good option I would say.

Doesn't it make sense to configure the Health Analyzer rules as one of the last steps in the configuration process? That way you don't have to implement the rule engine.

**Comment by BrianFarnhill** [comment]
I still think the fix here for us if a rule doesn't exist is that we should throw an error with some helpful text like "The rule isn't here, please make sure that any service apps it needs exist" or something like that. Thoughts?

**Comment by NikCharlebois** [comment]
I agree that this would be the best way to handle it on your end. I am trying to get an official Rule-Dependency list from PG for my stuff.

**Comment by ykuijs** [comment]
Will include this update in the bugfix PR I am working on

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
