### ISSUE TITLE
configuration generator

### ISSUE THREAD

**Issue by shurick81** [PowerShell/SharePointDsc#536]
This is not the issue but a suggestion.
I think it would be great if we could generate configuration using existing farms. We maintain lots of existing farms that were configured without DSC. If there was some mechanism that generates configuration from existing farm, we could use DSC for them.

**Comment by ykuijs** [comment]
Hello @shurick81, thanks for the suggestion. We are currently working on a ReverseDSC functionality to generate a DSC configuration based on an existing farm. This is however a pretty complex implementation, which unfortunately is taking quite some time to develop.

@NikCharlebois, do you have an update?

**Comment by NikCharlebois** [comment]
Take a look at http://aka.ms/ReverseDSC

Put both file on one of the servers in the farm and run SharePointDSC.Reverse.ps1. If that server doesn't have internet connectivity, make sure you manually have SharePointDSC 1.6.0.0 in your module folder



________________________________

**Comment by shurick81** [comment]
Thanks, this tool looks quite promising!
