### ISSUE TITLE
Extend documentation to include Ensure=Present is the default setting

### ISSUE THREAD

**Issue by shurick81** [PowerShell/SharePointDsc#537]
**Details of the scenario you try and problem that is occurring:**
Provisioining distributed cache on new farm servers
removing distributed cache service from farm servers
I'm looking at command description but can't get my head around how should I disable and enable nodes? https://github.com/PowerShell/SharePointDsc/wiki/SPDistributedCacheService
In the documentation it says that "Ensure" is for enabling and if this parameter is missing, then DSC will ensure that the service is not run on the machine: 
_Ensure
Present to ensure the current server should be running distributed cache, absent to ensure that it isn't running_

However, in the same documentation I can find an example without Ensure:

    node localhost {
        SPDistributedCacheService EnableDistributedCache
        {
            Name                 = "AppFabricCachingService"
            CacheSizeInMB        = 8192
            ServiceAccount       = "DEMO\ServiceAccount"
            InstallAccount       = $SetupAccount
            CreateFirewallRules  = $true
        }
    }

So where is the truth?

**The DSC configuration that is using the resource:**
?

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 Standard
Powershell 5.1

**Version of the DSC module you're using:**

**Comment by ykuijs** [comment]
Where have you seen that not when Ensure is missing, DSC would not deploy the DC on the server?

The default value for Ensure is Present. So not specifying the Ensure parameter will deploy the DC to the server.

**Comment by shurick81** [comment]
As I told, I inferred this meaning from following statement in documentation:
_Ensure
Present to ensure the current server should be running distributed cache, absent to ensure that it isn't running_

How can I remove the service from the node? I have servers in the farm where distributed cache is running but it is not supposed to run there.

**Comment by BrianFarnhill** [comment]
@shurick81 Yes you can, if you specifically specify that Ensure = Absent it will remove distributed cache from that node.

@ykuijs You think we need to add "Default is 'present'" to the doco of all of our ensure properties to make this obvious?

**Comment by shurick81** [comment]
Well, now I see that I just misunderstood and I hope most people will get it right. What could be helpful though is some sample code with Ensure = Absent. For example, it's not yet clear if required parameters should be included even with Absent. For example, if I specify Ensure = Absent, "CacheSizeInMB" parameter is still mandatory, right?

**Comment by ykuijs** [comment]
I think it is a good idea to add this to the documentation. Will include this one in the bugfix PR I am working on.

**Comment by mrpullen** [comment]
Can we also add a Unit test to catch when Ensure doesn't have a default value of "Present". I always forget and have to go back and update my PRs.

Thanks!!

**Comment by ykuijs** [comment]
This sounds like a great idea! @BrianFarnhill what do you think? Can you add this to the Appveyor tests?

**Comment by BrianFarnhill** [comment]
Yea we can probably do that, we can use the AST stuff to reflect it back out and test on it

**Comment by BrianFarnhill** [comment]
The doco has been added to all resources and will be updated at our next release, closing this issue
