### ISSUE TITLE
Extend SPSite with the ability to change the email address for access requests

### ISSUE THREAD

**Issue by nissan** [PowerShell/SharePointDsc#539]
Details of the scenario you try and problem that is occurring:
[Help Wanted]
I configured SPOutgoingEmailSettings with email address From and ReplyTo addresses at the farm level, however Access Request Settings at a Site Collection level do not retain this email setting for "Send requests for access to the following email address:" parameter, and I do not see a setting for this at the SPSite keyword documentation. 
Can this be automated presently? Or does this presently require a manual configuration step?

Attaching the screenshot at the site collection level setting, as well as the DSC configuration script presently being used
![access request settings](https://cloud.githubusercontent.com/assets/12583/24113824/6d51aa86-0d74-11e7-9519-26ec77b33bdd.jpg)
[sp2016singleserver.zip](https://github.com/PowerShell/SharePointDsc/files/855882/sp2016singleserver.zip)

The DSC configuration that is using the resource:
Single Server Farm created using SharePointDSC with site collections created using the SPSite keyword

Version of the Operating System and PowerShell the DSC Target Node is running:
Target system is running Window Server 2012 R2 running Powershell v5.0.10586.20151218

Version of the DSC module you're using:
SharePointDSC v1.6.0.0

**Comment by ykuijs** [comment]
Hi @nissan, the SPSite resource currently is able to configure this setting and the SPOutgoingEmailSettings resource cannot be used for this setting.

Good addition though, I will change the title of this issue to describe this addition a little better and keep track on this change

**Comment by nissan** [comment]
Is it in the documentation on what keyword is used to change this settiing at the Site Collection level using SPSite? I'm not seeing the keyword, or it's not that obvious?

Thanks for the help.
- Nissan

**Comment by BrianFarnhill** [comment]
@nissan I think @ykuijs made a typo there - currently SPSite *can not* configure this setting. But as he said it's a good addition, so it's on the backlog and we'll see if someone can get to it

**Comment by andikrueger** [comment]
The property [RequestAccessEmail](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spweb.requestaccessemail.aspx) is a member of the SPWeb object. The SPWeb has to have unique permissions. In case of the root web this requirement is fulfilled. The SPWeb Resource allows to break role inheritance. Therefore I think the SPWeb resource is suitable for this change.
