### ISSUE TITLE
Extend SPOutgoingEmailSettings with TLS and SMTP port number for SP2016

### ISSUE THREAD

**Issue by nissan** [PowerShell/SharePointDsc#540]
Details of the scenario you try and problem that is occurring:
[Help Wanted]
I want to turn TLS Encryption off for my outgoing email settings. [Wiki Documentation for SPOutgoingEmailSettings](https://github.com/PowerShell/SharePointDsc/wiki/SPOutgoingEmailSettings) does not show this as an available parameter, although I see [Powershell commands documented](https://social.technet.microsoft.com/wiki/contents/articles/34167.sharepoint-2016-outgoing-email-configuration-settings.aspx#Configure_using_the_PowerShell) that allows this to be done manually 
Can this be automated presently as a parameter on SPOutgoingEmailSettings? Or does this presently require a manual configuration step?

Attaching the screenshot at the farm level setting that I wish to configure
![web application outgoing email settings](https://cloud.githubusercontent.com/assets/12583/24118191/4b8fcdd8-0d83-11e7-897c-8007efd09842.PNG)
 
The DSC configuration that is using the resource:
Single Server Farm created using SharePointDSC with outgoing email settings configured using the SPOutgoingEmailSettings at the farm level (the central administration web application)

Version of the Operating System and PowerShell the DSC Target Node is running:
Target system is running Window Server 2012 R2 running Powershell v5.0.10586.20151218

Version of the DSC module you're using:
SharePointDSC v1.6.0.0

**Comment by ykuijs** [comment]
Hi @nissan, this functionality has been added in SP2016. The resouces was build when SP2016 wasn't available yet. We will have to extend the functionality of this resource.

**Comment by ykuijs** [comment]
Will be added in my next rollup PR

**Comment by ykuijs** [comment]
Fix included in PR 600
