### ISSUE TITLE
Build a timeout loop in to SPFarmSolution

### ISSUE THREAD

**Issue by mrpullen** [PowerShell/SharePointDsc#544]
**Details of the scenario you try and problem that is occurring:**

Apply a DSC configuration, but there is an issue with the farm, so the WSP / Solution file that needs to be deployed can't deploy. But DSC seems to just wait indefinitely, so the rest of the configuration isn't applied, and if I am not watching it specifically I don't know what is going on.

Is there any way to add a "timeout" to the Resource(s), so after a specific time we just kill the session accept that the resource being applied has failed, and move on? 

**The DSC configuration that is using the resource:**

SPSolution farmSolution {
  *** details don't matter **
}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WIN 2008 R2 
Powershell 5

**Version of the DSC module you're using:**
V1.5

**Comment by BrianFarnhill** [comment]
Most of the other resources that loop have internal time outs of 30 minutes on them, so the SPFarmSolution resource should do the same. Will add to the backlog

**Comment by mrpullen** [comment]
I was hoping we could add a timeout to the Invoke-SPDSCCommand, but I don't see a simple way to do it, then if any resource needed a timeout, we could supply the 30m as a default but allow the value to be set in the resource so we could timeout as desired.

**Comment by BrianFarnhill** [comment]
@mrpullen Yea that wouldn't be something we could easily do - plus then we run the risk of cutting out mid way through a script that would be in a valid (all be it slow) run, so I wouldn't want to do it that way. So for now lets make sure we fix SPFarmSolution and any others that should have it and go from there.
