### ISSUE TITLE
SPUserProfileProperty throwing errors when editing string based properties

### ISSUE THREAD

**Issue by larbre** [PowerShell/SharePointDsc#550]
Running SharePoint DSC 1.6.0.0 installing SharePoint 2016 there is an issue when creating string based user profile properties. It works when the property is created for the first time but fails when running the same DSC configuration again. The bug seems to be realted to a change in the userprofiles.coreproperty.type enumeration (https://msdn.microsoft.com/en-us/library/microsoft.office.server.userprofiles.coreproperty.type.aspx) when comparing the existing type against the new type.

The DSC module allows "string" and "StringMultiValue" - the type enumeration from SP16 binaries differentiates between "string (Single Value)" and "string (Multi Value)" adjusting the schema and psm1 to use those values seem to be working against SP16.

**Comment by BrianFarnhill** [comment]
I think this is something that we keep our schema the same for, but substitute the values out for at runtime if the server is 2016. Adding this to the buglist, thanks for reporting

**Comment by larbre** [comment]
that's fine as well, I just needed a quick fix for now ;-)

**Comment by ykuijs** [comment]
Investigating this issue. It looks like the resource is implemented a little strange. When looking at the example "Create user profile properties by using the SharePoint server object model" in  https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-work-with-user-profiles-and-organization-profiles-by-using-the-server-obj the CoreProperty.Type property is filled with a value coming from the PropertyDataType object.

In the resource we input the Type parameter into the CoreProperty.Type property.

When reviewing this object (https://msdn.microsoft.com/en-us/library/microsoft.office.server.userprofiles.propertydatatype_members.aspx), it contains a lot of static properties that output string values which absolutely do not match the allowed input values of the DSC resource.

So I am wondering how this resource is able to work properly. Will perform some more tests.

This is exactly the same in SP2013 and SP2016

**Comment by ykuijs** [comment]
The current version of the resource isn't handling strings (single and multi values) in the correct way. It is unable to create a multi value and is using the incorrect value for single value, resulting in the test always failing. This is for both SP2013 and SP2016.

Will update the resource to fix this issue.

**Comment by ykuijs** [comment]
I have fixed this issue in my next rollup PR. The fixes will however break existing configurations, labeled as Breaking Change

**Comment by ykuijs** [comment]
Closed with PR 660
