### ISSUE TITLE
MSFT_SPUserProfileProperty Test-Resource failing when ADImport conncetion is configured

### ISSUE THREAD

**Issue by larbre** [PowerShell/SharePointDsc#551]
Running SharePoint DSC 1.6.0.0 installing SharePoint 2016 there is an issue when an ADImport connection has been setup. It first fails on the Test-Resouce function when executing

```
$syncConnection  = $userProfileConfigManager.ConnectionManager | `
            Where-Object -FilterScript { 
                $null -ne $_.PropertyMapping.Item($params.Name) 
            }
```
based on MS this will always report $null if ADImport is used (compare https://msdn.microsoft.com/en-us/library/microsoft.office.server.userprofiles.connection.propertymapping.aspx)
So we can't really report existing mappings if ADImport is used. To work around this I just used

```
$syncConnection  = $userProfileConfigManager.ConnectionManager
if ($syncConnection.Type -eq "ActiveDirectoryImport")
{
	Write-Verbose -Message "ActiveDirectoryImport can't report mapped properties"
	$syncConnection = $null
}
else
{
	$syncConnection  = $userProfileConfigManager.ConnectionManager | `
          Where-Object -FilterScript { 
          $null -ne $_.PropertyMapping.Item($params.Name) 
        }
}
```
The same later happens in the Set-TargetResource function. I did some rework as there was another issue where the ADImport would never be touched as the variable "Conncetion" in this block is never assigned:
` if ($connection.Type -eq "ActiveDirectoryImport")`
So the final reworked block looks like

```
if ($null -eq $syncConnection ) 
{
	throw "connection not found"
}
if ($syncConnection.Type -eq "ActiveDirectoryImport")
{
	 
	if ($export) 
	{
		throw "not implemented"
	} 
	else 
	{
		$syncConnection.AddPropertyMapping($params.MappingPropertyName,$params.Name)  
		$syncConnection.Update()  
	}
}
else
{
	$currentMapping  = $syncConnection.PropertyMapping.Item($params.Name)

	if($null -eq $currentMapping `
		-or ($currentMapping.DataSourcePropertyName -ne $params.MappingPropertyName) `
		-or ($currentMapping.IsImport `
				-and $params.ContainsKey("MappingDirection") `
				-and $params.MappingDirection -eq "Export") 
	   )
	{
		if ($null -ne $currentMapping)
		{
			$currentMapping.Delete() #API allows updating, but UI doesn't do that.
		}

		$export = $params.ContainsKey("MappingDirection") -and $params.MappingDirection -eq "Export"
	
		if ($export)
		{  
			$syncConnection.PropertyMapping.AddNewExportMapping([Microsoft.Office.Server.UserProfiles.ProfileType]::User,
																$params.Name,
																$params.MappingPropertyName)
		}
		else
		{
			$syncConnection.PropertyMapping.AddNewMapping([Microsoft.Office.Server.UserProfiles.ProfileType]::User,
														  $params.Name,
														  $params.MappingPropertyName)
		}
	}
}
```

**Comment by NikCharlebois** [comment]
@larbre there have been major changes to that resource with the 2.1.0.0 release. Are you still experiencing the issue with the latest versions?

**Comment by NikCharlebois** [comment]
@ykuijs I recomend we close this since we did not hear back from @larbre . As mentionned, there has been major refactoring of that resources in the last few versions to address this specific issue.

**Comment by johlju** [comment]
Closing this as per previous comment. If this was closed in error please reopen or comment.
