### ISSUE TITLE
SPWebAppGeneralSettings: Get-TargetResource for property SecurityValidationTimeOutMinutes is wrong

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#553]
**Details of the scenario you try and problem that is occurring:**
When using the SPWebAppGeneralSettings SecurityValidationTimeOutMinutes Property the test always fails.
The script SPWebApplication.GeneralSettings.psm1 uses a wrong property on line 20:
SecurityValidationTimeoutMinutes = $WebApplication.FormDigestSettings.timeout.minutes

should be:
SecurityValidationTimeoutMinutes = $WebApplication.FormDigestSettings.timeout.TotalMinutes

**The DSC configuration that is using the resource:**
                SPWebAppGeneralSettings $internalGeneralSettingsName {
                    Url                              = $webApp.Url
                    Alerts                           = $webApp.GeneralSettings.Alerts
                    AlertsLimit                      = $webApp.GeneralSettings.AlertsLimit
                    AllowOnlineWebPartCatalog        = $webApp.GeneralSettings.AllowOnlineWebPartCatalog
                    BlogAPI                          = $webApp.GeneralSettings.BlogAPI
                    BlogAPIAuthenticated             = $webApp.GeneralSettings.BlogAPIAuthenticated
                    BrowserFileHandling              = $webApp.GeneralSettings.BrowserFileHandling
                    CustomerExperienceProgram        = $webApp.GeneralSettings.CustomerExperienceProgram
                    MaximumUploadSize                = $webApp.GeneralSettings.MaximumUploadSize
                    PresenceEnabled                  = $webApp.GeneralSettings.PresenceEnabled
                    RecycleBinCleanupEnabled         = $webApp.GeneralSettings.RecycleBinCleanupEnabled
                    RecycleBinEnabled                = $webApp.GeneralSettings.RecycleBinEnabled
                    RecycleBinRetentionPeriod        = $webApp.GeneralSettings.RecycleBinRetentionPeriod
                    RSS                              = $webApp.GeneralSettings.RSS
                    SecondStageRecycleBinQuota       = $webApp.GeneralSettings.SecondStageRecycleBinQuota
                    SecurityValidation               = $webApp.GeneralSettings.SecurityValidation
                    SecurityValidationExpires        = $webApp.GeneralSettings.SecurityValidationExpires
                    SecurityValidationTimeOutMinutes = $webApp.GeneralSettings.SecurityValidationTimeOutMinutes
                    SelfServiceSiteCreationEnabled   = $webApp.GeneralSettings.SelfServiceSiteCreationEnabled
                    TimeZone                         = $webApp.GeneralSettings.TimeZone
                    PsDscRunAsCredential             = $SetupAccount
                    DependsOn                        = "[SPWebApplication]$webAppInternalName" 
                }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2
PowerShell 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by BrianFarnhill** [comment]
What version of SharePoint are you using? I want to make sure the property name didn't change between 2013/2016

**Comment by typozh** [comment]
SharePoint 2016

**Comment by ykuijs** [comment]
The TotalMinutes property also exists in SP2013, so we can use this in SP2013 as well. Have included this in my bugfix PR.

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
