### ISSUE TITLE
SPWebAppThrottlingSettings: set function for RequestThrottling property does not work

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#554]
**Details of the scenario you try and problem that is occurring:**
Change the RequestThrottling setting using SPWebAppThrottlingSettings, RequestThrottling 

**The DSC configuration that is using the resource:**
                SPWebAppThrottlingSettings $internalThresholdSettingsName {
                    Url                          = $webApp.Url
                    ListViewThreshold            = $webApp.ThresholdSettings.ListViewThreshold
                    AllowObjectModelOverride     = $webApp.ThresholdSettings.AllowObjectModelOverride
                    AdminThreshold               = $webApp.ThresholdSettings.AdminThreshold
                    ListViewLookupThreshold      = $webApp.ThresholdSettings.ListViewLookupThreshold
                    HappyHourEnabled             = $webApp.ThresholdSettings.HappyHourEnabled
                    UniquePermissionThreshold    = $webApp.ThresholdSettings.UniquePermissionThreshold
                    RequestThrottling            = $webApp.ThresholdSettings.RequestThrottling

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, PowerShell 5.1, SharePoint 2016

**Version of the DSC module you're using:**
1.6.0.0

**Comment by wickedave** [comment]
I have the same thing. The RequestThrottling setting is not applying. We are not receiving any error but the setting is not getting modified.

**Comment by ykuijs** [comment]
I found the issue. Implementing a fix.

**Comment by ykuijs** [comment]
Fixed in PR #680
