### ISSUE TITLE
SPWebAppPolicy.psm1 Write-Verbose message parameter with + cause error

### ISSUE THREAD

**Issue by DenisK87** [PowerShell/SharePointDsc#557]
**Details of the scenario you try and problem that is occurring:**
When PowerShell try to write verbose message with "+" sign in it it falls in the error:
"A positional parameter cannot be found that accepts argument '+'."

The code that cause this error is in the file "Modules\SharePointDsc.WebAppPolicy\SPWebAppPolicy.psm1" line 65.
Code:
Write-Verbose -Message "Permission level different for " + `
                                           "$($policy.IdentityType) user '$($policy.Username)'"

**The DSC configuration that is using the resource:**
SPWebAppPolicy CESAccountAppPoolPermissions
{ 
	WebAppUrl = $node.WebAppUrl
	MembersToInclude = @(
	MSFT_SPWebPolicyPermissions {
		Username           = "DOMAIN\accountname"                    
		PermissionLevel    = "Full Read"
		IdentityType       = "Claims" }
	)
	PsDscRunAsCredential = $setupAccount
}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, PowerShell 5.1, SharePoint 2016

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
Hi @DenisK87, thanks for reporting. I will include this fix in a bugfix PR I am working on.

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
