### ISSUE TITLE
SPWebApplication Get-TargetResource can't get AuthProvider

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#558]
**Details of the scenario you try and problem that is occurring:**
Configure a SharePoint farm using SharePoint DSC and the DSC block below. The WebApp gets created with the "Windows" Auth Provider. Then call into the Get-TargetResource function against it. It somehow detects that it is Claims even though it is not, and can't retrieve the AuthProvider Name.

**The DSC configuration that is using the resource:**
SPWebApplication RootWebApp
        {
            Name = "RootWebApp"
            ApplicationPool = "SharePoint - 80"
            ApplicationPoolAccount = $adminAccount.UserName
            Url = "http://localhost"
            DatabaseServer = "SPTechCon-SQL"
            DatabaseName = "WebApp-SharePoint-80"
            Port = 80
            PsDSCRunAsCredential = $farmAccount
        }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win server 2016/SP2016/WMF 5

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
When not specifying the AuthenticationMethod parameter, a Classic web application is created. This type of web application does not have an authentication provider and therefore returns the incorrect information.

Will update the resource to return the correct AuthenticationMethod from the Get method.

**Comment by ykuijs** [comment]
Fix included in PR 600
