### ISSUE TITLE
Wiki documentation for SPWebApplication doesn't include Claims as valid Auth

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#559]
**Details of the scenario you try and problem that is occurring:**
when looking at the SPWebApplication Resource, the AuthenticationMethod parameter accepts "NTLM, Kerberos, and Claims", however the Wiki example only mentions NTLM and Kerberos

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
The parameters on the Wiki pages are being generated from the schema file. For SPWebApplication the schema file shows the correct parameter values, so not sure why this pages hasn't been updated.

@BrianFarnhill Do you have any clue?

**Comment by BrianFarnhill** [comment]
My bad guys, forgot to hit publish on the doco when 1.6 shipped. Doco is now up to date from that release.
