### ISSUE TITLE
SPSite Template approach in Get-TargetResource is wrong

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#560]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource function in MSFT_SPSite uses the following logic to retrieve the Template parameter:

"$($site.RootWeb.WebTemplate)#$($site.RootWeb.WebTemplateId)"

However, for an App Catalog site, while the WebTemplate is correct ("APPCATALOG"), its WebTemplateID is '18' and "APPCATALOG#18" is not valid. The App Catalog Template should be "APPCATALOG#0"

**The DSC configuration that is using the resource:**
From ReverseDSC:
SPSite 4b1af197-b7b3-44e7-9002-6be21c26484a
        {
            OwnerAlias = "contoso\sp_farm";
            PsDscRunAsCredential = $Credssp_farm;
            Url = "http://sptechcon-wfe1/sites/catalog";
            Language = 1033;
            CompatibilityLevel = 15;
            Template = "APPCATALOG#18";
            ContentDatabase = "WebApp-SharePoint-80";
            DependsOn =  @("[SPWebApplication]RootWebApp");
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win Server 2016/WMF 5.1/SP 2016

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
$site.RootWeb.WebTemplateId needs to be changed to $site.RootWeb.Configuration. Have included this in my bugfix PR.

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
