### ISSUE TITLE
Database in Get-TargetResource for MST_SPSubscriptionSettingsServiceApp

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#561]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource method for MSFT_SPSubscriptionSettingsServiceApp tries to access a Database property on the Service App instance to retrieve the DatabaseServer and DatabaseName properties. However, this property doesn't exist and always returns null;

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/WMF 5.0/SP2016

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
Will be included in my next bugfix PR

**Comment by ykuijs** [comment]
Fix included in PR 600
