### ISSUE TITLE
SPAppCatalog weird behavior

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#563]
**Details of the scenario you try and problem that is occurring:**
I honestly don't believe this is caused by SharePointDSC, but when I specify an AppCatalog block for one of my web app, then navigate to the configure catalog page in Central Admin, it shows blank and asks me if I want to create an app catalog for my WebApp. However, if I use PowerShell to read the AppCatalog url for my web app, it does display the url properly properly, so it is configured. If I rerun Update-SPAppCatalogConfiguration -Site http://sptechcon-wfe1/sites/catalog which is the same URL I defined in the SPAppCatalog block, then it prompts me with the following:

App Catalog site will be changed from /sites/catalog to /sites/catalog.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y

So it is already configured properly. If I accept the prompt, then I see the URL appear in Central Admin. Has anyone else experiences this behavior?

**The DSC configuration that is using the resource:**
SPAppCatalog a958dbfa-4a34-40e7-aff6-77d7792cce1f
{
            PsDscRunAsCredential = $Credssp_farm;
            SiteUrl = "http://sptechcon-wfe1/sites/catalog";
}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/WMF 5/SP 2016

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
@NikCharlebois Did you ever managed to resolve this issue? Does this still exists? Maybe it was solved in a more recent CU?

**Comment by NikCharlebois** [comment]
@ykuijs I ca replicate this using regular sequential PowerShell commands. Therefore it is not SharePointDSC specific, simply a weird behavior of the OOB product. Let's close this issue.
