### ISSUE TITLE
SPSearchContentSource examples produce errors

### ISSUE THREAD

**Issue by nissan** [PowerShell/SharePointDsc#571]
The documented examples in the [wiki page for SPSearchContentSource](https://github.com/PowerShell/SharePointDsc/wiki/SPSearchContentSource) produce errors if used as is.

In the first example, ContinuousCrawl parameter is set to $true, however an IncrementalCrawl schedule is also specified. This produces an error when attempted to be applied in my environment using an Azure Automation DSC account "You can not specify an incremental crawl schedule on a content source that will use continous crawl"

In the 2nd example, the error generated is "Parameter LimitServerHops is not valid for website content sources" when it is applied using Azure Automation DSC in a similar manner.

**Comment by ykuijs** [comment]
Closed with PR 660

**Comment by shurick81** [comment]
Was something fixed regarding "Parameter LimitServerHops is not valid for website content sources"?
I'm running on 2.2 version and still getting the error.

```
                    SPSearchContentSource WWWsiteSource
                    {
                        Name                    = "site.com"
                        ServiceAppName          = "Search Service Application"
                        ContentSourceType       = "Website"
                        Addresses               = @("https://www.site.com")
                        CrawlSetting            = "CrawlEverything"
                        IncrementalSchedule     = MSFT_SPSearchCrawlSchedule{
                                                    ScheduleType    = "Daily"
                                                    StartHour       = "3"
                                                    StartMinute     = "0"
                                                }
                        Priority                = "Normal"
                        LimitServerHops         = 0
                        Ensure                  = "Present"
                        PsDscRunAsCredential    = $SPInstallAccountCredential
                        DependsOn               = "[SPSearchTopology]SearchTopology"
                    }
```
