### ISSUE TITLE
SPShellAdmin doesn't work for non-content databases

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#572]
**Details of the scenario you try and problem that is occurring:**

Right now if you use the SPShellAdmins resource it only works for content databases, not for any other database in the farm. This is sort of by design I think as we made the property name "Content Databases" but in reality there are scenarios that shell rights need to be granted to other databases also. So I'll call this an "enhancement" request rather than a bug.

**The DSC configuration that is using the resource:**

Anything using SPShellAdmin

**Version of the Operating System and PowerShell the DSC Target Node is running:**

All versions

**Version of the DSC module you're using:**

SharePointDSC 1.6

**Comment by ykuijs** [comment]
Just reviewed the necessary changes and the easiest implementation will mean this will be a breaking change. So it would probably best fit in the v2.0 release.

**Comment by ykuijs** [comment]
Implemented change for a 2.0 PR

**Comment by ykuijs** [comment]
Fixes merged into 2.0 branche
