### ISSUE TITLE
Question on AlwaysOn and SharePoint dbs

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#573]
**Details of the scenario you try and problem that is occurring:**
I'm using xSqlServer resources to pre-stage the SharePoint databases and then I mount them using the SharePointdsc resources. This works fine but I would like to move the dbs into Alwayson groups using dsc. I know there is the SPDatabaseAAG resource to do that but I don't get the concept. What do I need to configure as dbserver when creating the databases? I don't want to change the configuration in the process but I can't use the Alwayson group name to create the database (or can I?). 
Currently I'm using SQLAlias to switch between server\instance name and Alwayson name. The sql team moves the dbs for me and then I change the configuration to use the Alias pointing to the Always on group. It works but I would like to automate the complete process.
Could you provide a configuration example for a new content database including the move to AlwaysOn?

Thanks for the great work!

Brian

**The DSC configuration that is using the resource:**
SPDatabaseAAG
SPContentDatabase
SPFarm
...

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2, WMF5.1, SQL 2016, SharePoint 2016

**Version of the DSC module you're using:**
1.6

**Comment by BrianFarnhill** [comment]
Hey Brian,

So the process is basically that you can create the databases against the listener for the AG and the database will then be created on whichever server is currently the primary in the AG as just a normal database and that will work for as long as you need (as long as you don't change the primary!). So from there you can then SPDatabaseAAG to tell SharePoint to do the backups and then add the database to the availability group properly and it'll handle it from there. So in your case, the process should look like this:

1. Set up SQL Server, configure the availability groups
2. Pre-stage the databases on the primary database server in the AG
3. Set up sharepoint using the staged DBs, using the AG listener as the server name so they look to the primary
4. Have SPDatabaseAAG add the databases to the availability groups from there

I'm not sure what you are using the alias for in this scenario - you should have a DNS address for the listener on your availability group that you use for the server name and thats it, you don't need to get in to client aliases at all. 

Does all that make sense? Let me know if you need more info

**Comment by typozh** [comment]
Hi Brian,

The reason I'm using SQLAliases is because we are using custom ports for our listeners. 

I tried to follow your sequences but with the Aliases pointing to the listeners. The staging does not work (db's can be created but when trying to connect them and create the farm I get a version conflict exception). 

I then tried to skip the pre-staging and the farm creation worked. Step 4 fails in the set sequence with the exception:
Could not connect to [ListenerName] using integrated security: Cannot connect to database master at SQL server at [ListenerName]. The database might not exist, or the current user does not have permission to connect to it.

I think the cmdlet Add-DatabaseToAvailabilityGroup does not support custom ports.

Looks like I have to move the databases on the sql side...

Thanks,
Brian

**Comment by wickedave** [comment]
To bypass the this issue, you can create an SQL alias. My colleague already put a post for this issue in SharePoint : https://wespoint.wordpress.com/2015/09/15/sharepoint-2013-alwayson-availability-group-and-sql-alias/

You must make sure that your SQL instance is using a static port for this solution to work.

**Comment by johlju** [comment]
Closing this as answered. If this was closed in error please reopen or comment.
