### ISSUE TITLE
Is there any function to change the C2WTS Account?

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#577]
**Details of the scenario you try and problem that is occurring:**
I would like to change the Service Account for the Claims to Windows Token Service. Are there any plans to provide a functionality like this?

I think it could be accomplished like described here: [How to reset the Claims to Windows Token Service account](https://technet.microsoft.com/en-us/library/gg502596(v=office.14).aspx)

**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A
**Version of the DSC module you're using:**
1.6

**Comment by BrianFarnhill** [comment]
There are now, I'll tag this so it's on our backlog and we'll see when someone can get to it. Thanks for reporting the idea!

**Comment by MikeLacher448** [comment]
I have some code that does this, just need to clean it up and write the tests. I'll try to have a PR ready next week.

**Comment by ykuijs** [comment]
Change included in PR #642
