### ISSUE TITLE
SPInstall Get-TargetResource doesn't work for Sharepoint Foundation 2013

### ISSUE THREAD

**Issue by Identitry** [PowerShell/SharePointDsc#580]
**Details of the scenario you try and problem that is occurring:**
When installing Sharepoint Foundation 2013 using SPInstall Get-TargetResource searches the "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" registry key for "Microsoft SharePoint Server (2013|2016)", this won't give a match for "Microsoft SharePoint Foundation 2013".

**The DSC configuration that is using the resource:**
N/A
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016, Powershell 5
**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
Hi @Identitry, unfortunately we do not support SharePoint Foundation with SharePoint DSC, only SharePoint Server.

@BrianFarnhill, I see that this isn't specifically mentioned in the Wiki page. Can I change the Wiki page manually or will that be overwritten when we regenerated the documentation?

**Comment by ronx** [comment]
Hey @ykuijs, I updated the main wiki page to clarify this (under Supported SharePoint versions). If you guys think it needs to be called out in the SPInstall documentation as well, that could be updated in the Readme.md under that resource I believe.

**Comment by BrianFarnhill** [comment]
Yea we mention in the [SPInstall documentation](https://github.com/PowerShell/SharePointDsc/wiki/SPInstall) how to install SP Foundation (see example 3), but I think we need to put something in the readme for this documentation and in the supported versions part of the wiki as well.

@Identitry Check out that link above to get your SP Foundation install working
@ykuijs Can you include an update to the readme on SPInstall in your next bug fix PR if you're working on one?
@ronx Wanna update the wiki page that has the supported SharePoint versions?

Thanks guys

**Comment by ronx** [comment]
@BrianFarnhill sure, main wiki page is updated. Good idea, @ykuijs.

**Comment by ykuijs** [comment]
Done!
