### ISSUE TITLE
Minimal path to awesome - Wikipage

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#583]
**Details of the scenario you try and problem that is occurring:**
To offer a better starting point with SharePointDSC, a guidance should be offered on how to prepare a development and test environment.

- [x] How to contribute? (see: [Contributing SharePointDsc](https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc))

I think there is good guidance available for these two topics: 
- [ ] How to develop a new resource?
- [ ] How to run a test?

The following three topics aren't well documented in the wiki yet. I think it is hard to get all the information needed.
- [ ] What prerequistes do exist?
- [ ] What are third party dependencies?
- [ ] How to install and prep a development machine

I created a wiki page in my branch to compensate that issue and would like to join this page to the main wiki. I think a PR on wiki pages is not possible by now. So please feel free to copy that content into the main wiki.
Here is my current WIP: [Minimal path to awesome]( https://github.com/andikrueger/SharePointDsc/wiki/Minimal-Path-to-Awesome)

**Comment by BrianFarnhill** [comment]
Hey @andikrueger 

I think its a good idea that we prepare some better documentation for those who are looking to develop resources to contribute here vs. those who are just consuming the resources. I think the content you have prepared would make a good extension to the contributing to SharePointDsc page that you linked to there on the wiki currently. 

@ronx is my go to documentation guy so would like to loop him in on the discussion here - do you think we can review what Andi has here as a starting point and begin to extend what we have on our wiki?

I'm a little hesitant to document too much about the integration tests yet as they are still "work in progress" (that I started ages ago but got side tracked by other work and never got back to), but the bare minimum of things like this would be what I want in there:

1. What tools do we use (VSCode, git for windows, git credential manager for windows, Pester, NPM and NodeJs, etc)
2. How to start a fork of the repository
3. How to clone your fork to your local machine
4. How to create a new branch to start working on something in
5. How to submit a pull request

Now I know that some of these steps get covered in the main PowerShell repo wiki as well - so anything that is SharePointDsc specific I would want in our wiki, but anything more generic I think we can contribute to that wiki and link to it from ours to help everyone benefit from it as well. 

Let me know what you think of that approach guys and we can look at making the updates.

**Comment by ronx** [comment]
I started reading through @andikrueger 's wiki a week and a half ago when he posted this and meant to follow up with you, @BrianFarnhill, to get your thoughts. But, you know, life.... anyway, I think it's an excellent idea and certainly one I'm interested in digging into further and documenting along the way. I'll make some time this week to really read through what Andi has going over there and maybe we can touch base at the end of the week if our schedules allow it. Otherwise, we can keep the dialog going here for now. You've done a tremendous job developing this project and, I agree, it's time for the supporting documentation to be fortified to help everyone embrace the DSC/PowerShell approach to installation, configuration, and (hell yes) development. ;)

**Comment by BrianFarnhill** [comment]
@ronx love it, ping me when you have something and we can go from there, and we can keep @andikrueger in the loop too

**Comment by andikrueger** [comment]
Thank you @ronx and @BrianFarnhill for picking this up. Let me know if you need any help with my guidance or for the review. I’m glad to help.

While I’ve been writing this “Minimal Path to awesome”, I got stuck with the whole integration test thing. I started another [wiki page](https://github.com/andikrueger/SharePointDsc/wiki/Setting-up-a-new-SharePointDSC-development-server) on that topic too, but ran out of time with this part. Do you already have a DSC configuration or an Azure template for the setup of the integration farm in place?

**Comment by ronx** [comment]
FYI, I created a [new page](https://github.com/ronx/SharePointDsc/wiki/Contributing-to-SharePointDsc) in my fork this morning to start merging content. It's a pretty rough merge right now with a few changes and some notes. There is certainly a good deal of overlap with the DscResources guides, so I'll be reviewing all that in more detail to try to determine what we should link to and what makes sense to include here. It could be content that is specific to SharePointDsc (and/or the SP DSC contributing process), or it could just be that a simpler explanation of something is warranted. The DscResources guides can be pretty comprehensive, so there might be some content worth "borrowing" and stripping down to be more relevant to this project. I'll keep you guys posted, and will definitely appreciate your eyes for review along the way -- I'll let you know when a first draft is ready for review.

**Comment by BrianFarnhill** [comment]
@andikrueger nah we don't ahve the doco on that integration test stuff yet (like i said, got busy and never finished it). What I want to crank out for that are two things:

1. A documented setup for you to run this against any SP environment
2. A set of ARM templates that will help you install SP and SQL and everything up to the level needed for the tests to run, so that if you want to run them in Azure we can speed up the process

**Comment by andikrueger** [comment]
@BrianFarnhill I already have a DSC Configuration in place. I'm busy next week, but could "modify" the configuration to have  an ARM Template by the begin of June. What do you think?
Current DSC configuration:
- Active Directory with all necessary Accounts
- SQL Server Setup and permissions
- Directory for the SharePoint Binaries

**Comment by ykuijs** [comment]
All, I have given the [wiki article](https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc) a major update this afternoon.

@ronx, @andikrueger: Can you please review the new article and let me know what you think of this and if you think anything is missing?

**Comment by ronx** [comment]
I've started making some edits on the fly -- mostly punctuation, but some restructuring for clarity. If you would rather I fork the wiki, make all edits "offline", and then submit a PR for the wiki, let me know ASAP ;).

Of course, anything more involved than simple edits, I'll bring it up here first.

**Comment by andikrueger** [comment]
@ykuijs Awesome work on that wiki page!!! It's great addition to get started with SharePointDsc development!

Just a few minor additions to make the process on getting started easier:

The section [Test your changes on a SharePoint test environment](https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc#test-your-changes-on-a-sharepoint-test-environment) should have a link to the wiki page [Creating an Azure development environment](https://github.com/PowerShell/SharePointDsc/wiki/Creating%20an%20Azure%20development%20environment).

The section [Tools](https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc#tools) should mention the PSScriptAnalyzer, as this a major component while developing with VSCode.

I will reread the article later on to see, if I missed something. Right now it looks perfect.

**Comment by ykuijs** [comment]
@andikrueger Great additions, I have updated the article!

@ronx Since the Wiki has its own repo, forking that and submitting a PR is a bit of a hassle, so please go ahead.

**Comment by ykuijs** [comment]
@andikrueger, @ronx Any more updates/comments? If not, I suggest to close this issue.

**Comment by andikrueger** [comment]
You wrote a fantastic article on how to get started with SharePointDsc. I think we can close this issue and wait for further suggestions for improvement.

**Comment by ykuijs** [comment]
Closing issue
