### ISSUE TITLE
Custom resource: SharePoint object properties not available within dsc resource

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#584]
**Details of the scenario you try and problem that is occurring:**
I'm writing a dsc resource to set permission in a SharePoint site. The code I'm using works perfectly fine when I test it in a powershell shell with the snappin Microsoft.SharePoint.PowerShell loaded.
 As a dsc resource the object Microsoft.SharePoint.SPWeb does not return the properties although it seems to load fine.
All I can read from the SPweb object is the url. If I try to read other properties like Title I get no values back. 
What am I missing here? I do load the SharePoint Snapin and the user has the required permission.

I also posted this in the powershell.org forum including the code I'm using. 
https://powershell.org/forums/topic/sharepoint-object-properties-not-working-withing-dsc-resource/#post-70189

Thanks for help,
Brian

**Comment by BrianFarnhill** [comment]
Are you writing a custom resource or using the Script resource? What account are you running your resource as? The same account as the one you use when you test it in the normal PowerShell window?

**Comment by typozh** [comment]
I'm writing a custom resource. The account I'm using is the same as in the PowerShell window. 

the test function looks like this:

function Test-TargetResource
{
    [CmdletBinding()]
    [OutputType([System.Boolean])]
    param
    (
        [parameter(Mandatory = $true)]
        [System.String]
        $GroupName,

        [System.String]
        $LoginName,

        [System.String]
        $WebUrl,

        [ValidateSet("Present","Absent")]
        [System.String]
        $Ensure
    )
    Add-PSSnapin Microsoft.SharePoint.PowerShell
    [boolean]$result = $false
    
    Write-Verbose "try to load the web object"
    try {
        $web = Get-SPWeb -Identity $WebUrl -ErrorAction Stop
    }
    catch {
        Write-Error ("Could not load web with url: " + $weburl)
    }

    if($web) {
        if($Group = $Web.SiteGroups[$GroupName]) {
		    try {
			    $User = $web.EnsureUser($LoginName)
			    foreach ($GroupUser in $group.users) {
				    if ($GroupUser.Userlogin -eq $User.Userlogin) {
					    $result = $true
                        Write-Verbose ("User " + $User.Userlogin + " is member of the group: " + $GroupName)
				    }
			    }
            }
            catch {
                Write-Error ("User not found: " + $LoginName)
            }
        }
        else {
            Write-Error ("Group not found: " + $GroupName)
        }
        $result
    }
}

The configuration:
            srSPGroupMember VisitorGroupRoot {
                GroupName = "TestGroup"
                WebUrl = "http://myweb.sharepoint.local"
                Ensure = "Present"
                LoginName = "User1"
                PsDscRunAsCredential = $SetupAccount
            }

Where $SetupAccount is the account with site collection admin permission.

thanks,
brian

**Comment by BrianFarnhill** [comment]
Humour me, instead of loading the snap-in yourself can you wrap your code in "Invoke-SPDscCommand" like we do for the script resource in the wiki example at https://github.com/PowerShell/SharePointDsc/wiki/Using-the-Script-resource-in-configurations-that-use-SharePointDsc to see if that helps at all.

**Comment by ykuijs** [comment]
I have seen issues with the SPSite/SPWeb object using remote Powershell. Code that runs just fine locally, doesn't work when using Remoting: Many properties of the objects are empty.

To rule out DSC: Can you try to run the code using remoting to see if that works or not?

**Comment by ykuijs** [comment]
@typozh Do you still have this issue? If so, you might try the following:
`$wa = Get-SPWebApplication
$wa.GrantAccessToProcessIdentity("domain\user")
`
Use the account you are using as PsDscRunAsCredential as domain\user.

This will add the account to the Web Application User Policy in Windows Classic format. If you do this via the Central Admin, the claims format is always added. However if you connect via PS Remoting, you are always using Windows Claims and that user doesn't have the permissions to read the object properties of SPSite or lower.

Have ran into this issue multiple times before ;-)

**Comment by ykuijs** [comment]
Closing due to lack of response of the creator. Please reopen if the issue still occurs
