### ISSUE TITLE
SPServiceAppSecurity gives error when assigning rights to the Managed Metadata Service

### ISSUE THREAD

**Issue by DarenDaigle** [PowerShell/SharePointDsc#585]
**Details of the scenario you try and problem that is occurring:**

When configuring the Managed Metadata service, the service pool account is not given sufficient permssions to the service pool account.  When the attempt to add the permission via SPServiceAppSecurity using "Full Control" and error message is returned:

`PowerShell DSC resource MSFT_SPServiceAppSecurity  failed to execute Set-TargetResource functionality with error
message: The argument Rights is invalid. Valid values are: Read Access to Term Store, Read and Restricted Write Access
to Term Store, Full Access to Term Store
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost`

But when I run the configuration with the correct term listed in the error, it will not compile the MOF because the entry is incorrect.

**The DSC configuration that is using the resource:**

>Code Fragment
        SPManagedMetaDataServiceApp ManagedMetaDataServiceApp {
            Name = "Managed Metadata Web Service"
            ApplicationPool = $Node.SP_AP_ServiceAppPool
            DatabaseName = "$($Node.SQLDatabasePrefix)_ManagedMetadata"
            DatabaseServer = "$($Node.SQLServiceAlias)"
            PsDscRunAsCredential = $Node.SP_S_InstallAccount
            DependsOn = "[SPServiceInstance]SecureStoreServiceInstance"
        }
        SPServiceInstance ManagedMetadata {
            Name = 'Managed Metadata Web Service'
            PsDscRunAsCredential = $Node.SP_S_InstallAccount
            Ensure = 'Present'            
        }
        SPServiceAppSecurity MetaDataPermissions {
            ServiceAppName = "Managed Metadata Web Service"
            SecurityType = "SharingPermissions"
            MembersToInclude = @(
                MSFT_SPServiceAppSecurityEntry {
                    Username = "devbgca\sp_services"
                    AccessLevel = "Full Access to Term Store"
                }
            )
            PsDscRunAsCredential = $Node.SP_S_InstallAccount
        }

DSC Resources Used
SPSerivceAppSecurity and SPManagedMetaDataServiceApp

**Version of the Operating System and PowerShell the DSC Target Node is running:**

WMF 5.0 Running on Windows 2012 R2

**Version of the DSC module you're using:**
1.6.0.0

**Comment by lazda** [comment]
Extend ValueMap and Values in
DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.schema.mof
with missing values:
"Read Access to Term Store", "Read and Restricted Write Access to Term Store", "Full Access to Term Store", "Manage Profiles", "Manage Audiences", "Manage Permissions", "Retrieve People Data for Search Crawlers", "Manage Social Data"

Someone, please fix this bug in source code.

**Comment by BrianFarnhill** [comment]
Happy to put the extra changes in, but I want to also include some logic for a meaningful error if you choose a permission level that doesn't map to the service app you are targeting. For example, if I use the permission "Retrieve People Data for Search Crawlers" on a managed metadata service app, I want to get an error out of this that tells me what the valid options of the MMS service app are. I'll tag this on to the backlog to get picked up and put in.

**Comment by ykuijs** [comment]
This has been implemented via PR #954 (based on issue #825) and available in v3.0. Closing this issue
