### ISSUE TITLE
Fix error output for Excel Services when attempted to be used on SharePoint 2016

### ISSUE THREAD

**Issue by wickedave** [PowerShell/SharePointDsc#589]
Hi,

I'm using SharePointDSC version 1.6.0.0 with SharePoint 2016.

I'm trying to provision an Excel service with SPExcelServiceApp resource and I'm always getting an error:

```
VERBOSE: [MTL-SPST-WFE01]: LCM:  [ Start  Test     ]  [[SPExcelServiceApp]ExcelService-01]
VERBOSE: [MTL-SPST-WFE01]:                            [[SPExcelServiceApp]ExcelService-01] Testing Excel Services
Application 'Lab-Excel-01'
Method invocation failed because [System.Exception] does not contain a method named 'op_Addition'.
    + CategoryInfo          : InvalidOperation: (op_Addition:) [], CimException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : localhost

VERBOSE: [MTL-SPST-WFE01]:                            [[SPExcelServiceApp]ExcelService-01] Getting Excel Services
Application 'Lab-Excel-01'
Method invocation failed because [System.Exception] does not contain a method named 'op_Addition'.
    + CategoryInfo          : InvalidOperation: (op_Addition:) [], CimException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : localhost

VERBOSE: [MTL-SPST-WFE01]:                            [[SPExcelServiceApp]ExcelService-01] Executing as the local run
as user domain\user
VERBOSE: [MTL-SPST-WFE01]:                            [[SPExcelServiceApp]ExcelService-01] Leaving BeginProcessing
Method of Get-SPServiceApplication.
VERBOSE: [MTL-SPST-WFE01]:                            [[SPExcelServiceApp]ExcelService-01] Leaving ProcessRecord Method
 of Get-SPServiceApplication.
VERBOSE: [MTL-SPST-WFE01]:                            [[SPExcelServiceApp]ExcelService-01] Leaving EndProcessing Method
 of Get-SPServiceApplication.
VERBOSE: [MTL-SPST-WFE01]: LCM:  [ End    Test     ]  [[SPExcelServiceApp]ExcelService-01]  in 0.2810 seconds.
```
This is a new farm so it never hosted any Excel Service in the past.

Thanks

**Comment by BrianFarnhill** [comment]
Can you share your configuration with us so we can try to replicate it?

**Comment by andikrueger** [comment]
SharePoint 2016 does not have Excel Services as they are part of the Office Online Server now. The methods to provision Excel Services shouldn't be available in SharePoint 2016.

**Comment by BrianFarnhill** [comment]
*facepalm*

Yep, @andikrueger is right. You should have actually seen an error telling you that though, the issue here is that the exception logic needs some brackets wrapped around it. So I'm gonna leave this one open until we fix the bit that throws the error - @ykuijs can you slip some brackets around the error message on this one in your next roll up PR. Because it goes over multiple lines the + sign is freaking it out.

**Comment by wickedave** [comment]
Sorry about posting this issue. I feel a little bit noob. I should have noticed that Excel Service is now removed from SharePoint. Thanks for the answer.

**Comment by ykuijs** [comment]
Done! Will be included in my next PR

**Comment by ykuijs** [comment]
Fix included in PR 600
