### ISSUE TITLE
SPUserProfileServiceApp error with InstallAccount vs PSDSCRunAscredential

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#592]
**Details of the scenario you try and problem that is occurring:**

Running the DSC block below gives out the following error:
PowerShell DSC resource MSFT_SPUserProfileServiceApp  failed to execute Set-TargetResource functionality with error
message: Unable to use both InstallAccount and PsDscRunAsCredential in a single resource. Remove one and try again.

<# ----------------------------------------------Block---------------------------------------- #>
SPUserProfileServiceApp UserProfileServiceApp
        {
            ApplicationPool = "User Profile Service";
            ProxyName = "User Profile Service Proxy";
            ProfileDBName = "ProfilesDB";
            FarmAccount = $Credss_img_swsadmin;
            Name = "User Profile Service";
            SocialDBName = "SocialDB";
            Ensure = "Present";
            PsDSCRunAsCredential = $Credss_img_swsadmin;
            EnableNetBIOS = $False;
            SyncDBServer = "CSNI-SvcApp";
            ProfileDBServer = "CSNI-SvcApp";
            SyncDBName = "SyncDB";
            SocialDBServer = "CSNI-SvcApp";
            MySiteHostLocation = "*";
        }

However, I only specified PSDSCRunAsCredential, not InstallAccount

**The DSC configuration that is using the resource:**
See block above

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0 (latest commit)

**Comment by BrianFarnhill** [comment]
Can you verify the MOF doesn't have the InstallAccount option? Also can you confirm if you have changed the credential property of the LCM or done anything else that would change the account it runs as elsewhere?

**Comment by NikCharlebois** [comment]
I did check already and the Mof doesn't have InstallAccount. This is a plain vanilla win 2012 R2 so no lcm modifications

**Comment by NikCharlebois** [comment]
Not sure if it can help the troubleshooting, but I just spin off a new VM, that has local AD, SQL Server and SP2013 SP1. I ran PSConfig to create the farm, and right after that I tried to execute this trimmed down Config, and still get the same error.


Configuration SharePointFarm
{
    $Credss_img_swsadmin= Get-Credential

    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName SharePointDSC
    

    node $env:COMPUTERNAME
    {
        SPUserProfileServiceApp UserProfileServiceApp
{
ApplicationPool = "User Profile Service";
ProxyName = "User Profile Service Proxy";
ProfileDBName = "ProfilesDB";
FarmAccount = $Credss_img_swsadmin;
Name = "User Profile Service";
SocialDBName = "SocialDB";
Ensure = "Present";
PsDSCRunAsCredential = $Credss_img_swsadmin;
EnableNetBIOS = $False;
SyncDBServer = "CSNI-SvcApp";
ProfileDBServer = "CSNI-SvcApp";
SyncDBName = "SyncDB";
SocialDBServer = "CSNI-SvcApp";
MySiteHostLocation = "*";
}        LocalConfigurationManager
        {
            RebootNodeIfNeeded = $True
        }
    }
}
$ConfigData = @{
    AllNodes = @(    
    @{
        NodeName = $env:COMPUTERNAME;
        PSDscAllowPlainTextPassword = $true;
        PSDscAllowDomainUser = $true;
    }
)}
SharePointFarm -ConfigurationData $ConfigData

**Comment by NikCharlebois** [comment]
Ok, after investigation, the issue comes from this block (obviously) in the SharePointDSC.
Util.psm1 module. My Credential is DND\s-img-swsadmin and it is also the user I am logged in with, so it doesn't contains any '$' in its username and therefore throws the error. Now, if we really want to ensure we are not trying to configure the UPS with the currently logged in user, we should probably improve the error message. The current message is extremely confusing since I am not passing in both the InstallAccount and PSDscRunAsCredential params.

if ($null -eq $Credential) 
{...} 
else 
{
        if ($Credential.UserName.Split("\")[1] -eq $Env:USERNAME) 
        { 
            if (-not $Env:USERNAME.Contains("$")) 
            {
                throw [Exception] ("Unable to use both InstallAccount and " + `
                                   "PsDscRunAsCredential in a single resource. Remove one " + `
                                   "and try again.")
                return
            }
        }

**Comment by BrianFarnhill** [comment]
Ahhhh, ok so essentially this doubles up with issue #389 where we plan to fix this behaviour in our 2.0 release anyway. Agree its confusing and needs to change, so we'll get on to that when we can mate.

**Comment by NikCharlebois** [comment]
Just wanted to follow up on this issue. Since all dependencies on xCredSSP have been removed in the current 2.0 preview branch, I assume this issue has been addressed as a collateral?

**Comment by ykuijs** [comment]
That is correct. Since the dependency on CredSSP was removed, this issue is also solved. Closing the issue!

**Comment by avishnyakov** [comment]
Ouch.. okay. Single-farm-testing scenario, well, we can live with that :)

> If the $PSDscRunAsCredentials are the same as the $FarmAccount, then the error is thrown. If we want to ensure they are not the same, we should probably catch the error in the Resource itself and throw a more meaningful error. The current error is extremely confusing since I am not passing both InstallAccount and PSDscRunAsCredential
