### ISSUE TITLE
Issue when installing multiple LanguagePacks with SPInstallLanguagePack

### ISSUE THREAD

**Issue by lazda** [PowerShell/SharePointDsc#594]
Details of the scenario you try and problem that is occurring:

Is not possible to install multiple language packs (binaries) at once without running PSCONFIG after each LP Installation because of verification:

if ((**$languagePackInstalled -eq 1**) -or ($setupType -eq "B2B_UPGRADE"))

It makes more sense to install all LP binaries and only then execute PSCONFIG on each server. This will decrease Installation time.

Another enhancement could be to use LCID verification of $cultureInfo.LCID vs. RegKey values from HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\16.0\InstalledLanguages when identifying if LP is installed or not.

Version of the Operating System and PowerShell the DSC Target Node is running:
WinSrv 2016

Version of the DSC module you're using:
1.6

**Comment by ykuijs** [comment]
Hi @lazda, this issue was already reported to me by email and I am already working on fixing this. Will be included in my next Rollup PR

**Comment by lazda** [comment]
Hi. 
Thanx. Please check SPProductUpdate resource for the same condition. Line 326

**Comment by ykuijs** [comment]
For SPProductUpdate this is required to prevent a possible endless loop.

**Comment by ykuijs** [comment]
Fix included in PR 600
