### ISSUE TITLE
SPSearchResult for SP2016 throws error

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#599]
**Details of the scenario you try and problem that is occurring:**
Looks as if configuring  search on a SP2016 RTM farm installs a new Query Federation Manager called "Graph Provider". Configuring Search creates a new Search Result named "Local SharePoint Graph" which uses this new Provider. However, the MSFT_SPSearchResultSource module doesn't accept this as a valid entry for the ProviderType param. 

**The DSC configuration that is using the resource:**
[...]
SPSearchResultSource 19254015-abbe-4384-ac53-d70d63d1f3c2
 {
            Name = "Local SharePoint Graph";
            PsDscRunAsCredential = $CredsSP_Installer;
            SearchServiceAppName = "Search Service Application";
            ProviderType = "Graph Provider";
            Ensure = "Present";
            Query = "{searchTerms}";
 }
[...]

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win Server 2016 /WMF 5

**Version of the DSC module you're using:**
1.6.0.0

**Comment by BrianFarnhill** [comment]
@NikCharlebois What build of SharePoint 2016 are you using? RTM or a CU? Can you confirm the build number for us?

**Comment by NikCharlebois** [comment]
RTM running on Azure IaaS

**Comment by NikCharlebois** [comment]
Build 16.0.4351.1000

**Comment by NikCharlebois** [comment]
I did confirm with other folks that this "hidden" Result Source gets created even with the most recent PUs. Either I need to modify ReverseDSC to ignore its extraction, or we need to make sure SharePointDSC can gracefully handle this new provider.

**Comment by BrianFarnhill** [comment]
@NikCharlebois OK, well realistically when you do search providers in SharePointDsc we currently only support SharePoint, Website and Fileshare content sources only. Anything else will throw you an error saying so. Based on that, I think this is likely an issue for you to address in your ReverseDSC script - what do you think?

**Comment by NikCharlebois** [comment]
Agreed. At this point, I will have ReverseDSC 1.7.0.0 ignore this provider. Thanks
