### ISSUE TITLE
MSFT_SPWebAppPermissions error in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#601]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource function of MSFT_SPWebAppPermission returns an invalid URL. Instead of returning the Web App's URL, it simply returns the string "url"

if ($wa.RightsMask -eq [Microsoft.SharePoint.SPBasePermissions]::FullMask) 
        {
            $returnval = @{
                WebAppUrl = "url"
                AllPermissions = $true
            }
        } 

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by BrianFarnhill** [comment]
Well that's rubbish - good catch. Will get it fixed

https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L63

**Comment by ykuijs** [comment]
Included in my bugfix PR #600
