### ISSUE TITLE
SPWebAppPolicy.psm1 verbose messages causing errors

### ISSUE THREAD

**Issue by wfeaser** [PowerShell/SharePointDsc#602]
There are four Write-Verbose lines in SPWebAppPolicy.psm1 that are throwing the following error:  "A positional parameter cannot be found that accepts argument '+'.".  The error is occurring because the message is a concatenated string, but is not enclosed in parenthesis.

DSC Resource:  SPWebAppPolicy.psm1
https://github.com/PowerShell/SharePointDsc/blob/963f8fe9947a8225fe0ddaaa7745acf4c992c566/Modules/SharePointDsc/Modules/SharePointDsc.WebAppPolicy/SPWebAppPolicy.psm1

OS:  Windows Server 2012 R2
PS Version:  5.0

**Comment by BrianFarnhill** [comment]
Thanks for reporting, we'll get it sorted.

**Comment by ykuijs** [comment]
Will be fixed in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
