### ISSUE TITLE
SPFarm not retrieving Auth Mode for CA

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#603]
**Details of the scenario you try and problem that is occurring:**
There is already a #TODO note in the code, but wanted to make sure this gets captured somewhere. The Get-TargetResource function for MSFT_SPFarm does not return current CentralAdministrationAuth parameter, it simply reflects back what was passed to it. The code to retrieve this value should be:

$spCentralAdmin.IisSettings[0].DisableKerberos

If false, then the Auth Method should be set to Kerberos.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/WMF 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
Closed with PR 660
