### ISSUE TITLE
SPQuotaTemplate Test-TargetResource fails when MaximumUsagePointsSolutions equals WaningUsagePointsSolutions

### ISSUE THREAD

**Issue by psel10** [PowerShell/SharePointDsc#605]
**Details of the scenario you try and problem that is occurring:**
Trying to create a Quota Template that does not have a sandboxed solutions usage limit, so I did not include MaximumUsagePointsSolutions or  WarningUsagePointsSolutions in the configuration.  This gave me an error that said:
PowerShell DSC resource MSFT_SPQuotaTemplate  failed to execute Test-TargetResource functionality with error message: 
MaximumUsagePointsSolutions must be equal to or larger than WarningUsagePointsSolutions. 

So I tried putting 0 for MaximumUsagePointsSolutions and  WarningUsagePointsSolutions, but got the same error.

Looking in the psm1 file it says on line 307:
if ($MaximumUsagePointsSolutions -le $WarningUsagePointsSolutions) 
So if the variables are equal it will throw the error even though the message says that MaximumUsagePointsSolutions must be equal to or larger than WarningUsagePointsSolutions. 

Should this be -lt instead of -le?

**Version of the Operating System and PowerShell the DSC Target Node is running:**
OS: Windows Server 2012 R2
PS Version: 5.0
**Version of the DSC module you're using:**
1.7.0.0

**Comment by BrianFarnhill** [comment]
Seems like a fair interpretation - we will get that fixed for you

**Comment by ykuijs** [comment]
Will be fixed in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
