### ISSUE TITLE
SPServiceAppProxyGroup should use DisplayName instead of Name

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/SharePointDsc#606]
**Details of the scenario you try and problem that is occurring:**
Not all Service Application Proxies have a valid Name parameter (notably the Subscription Settings Service App Proxy). This causes the resource to try and use a null value when adding a new proxy. Switching the resource to use the Proxy's DisplayName will fix this issue.

**The DSC configuration that is using the resource:**
SPServiceAppProxyGroup default
{
 PsDscRunAsCredential = $MySetupCred;
 Ensure = "Present";
 ServiceAppProxies = {
    "SPA State Service Application",
    "SPA Usage Service Application",
    "SPA MMS1 Managed Metadata Service Application Proxy",
    "SPA MMS2 Managed Metadata Service Application Proxy",
    "SPA App Management Service Application Proxy",
    "SPA Default User Profile Service Application Proxy",
    "Microsoft SharePoint Foundation Subscription Settings Service Application Proxy"
};

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012R2, PS 5.0

**Version of the DSC module you're using:**
current DEV as of 6/2/2017

I will fix and make a new pull request shortly.

**Comment by ykuijs** [comment]
Fixed in PR 608
