### ISSUE TITLE
xSQLServerScript complains about duplicates when reusing scripts

### ISSUE THREAD

**Issue by DarenDaigle** [PowerShell/SharePointDsc#607]
xSQLServer Issue, deleting to prevent search engine issues.

**Comment by NikCharlebois** [comment]
@DarenDaigle Since this is SQLServer specific, please make sure you post your Issue in the xSQLServer repo: https://github.com/powershell/xsqlserver. Thanks

**Comment by DarenDaigle** [comment]
Wow, i was on the wrong screen.  please close this...
