### ISSUE TITLE
BlobCacheSettings Issue when trying to declare same URL with different zone;

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#609]
**Details of the scenario you try and problem that is occurring:**
Imagine the case where you have a DSC configuration that declares two different BlobCacheSettings, for the same Web Application, but for a different Zone. Trying to compile such a resource gives an error similar to the following:

Test-ConflictingResources : A conflict was detected between resources
'[SPBlobCacheSettings]5daeca26-879d-4f5b-be9f-7270aa6551d1 (C:\temp\SP-Farm.DSC.ps1::584::9::SPBlobCacheSettings)' and '[SPBlobCacheSettings]ef14ea31-4cd6-41ad-8920-f7fd9de1aee4 (C:\temp\SP-Farm.DSC.ps1::595::9::SPBlobCacheSettings)' in node 'MVA-APP'. Resources have identical key properties but there are differences in the following non-key properties:
'Zone'. Values 'Default' don't match values 'Intranet'. Please update these property values so that they are identical in both cases.

when looking at the *.schema.mof file, I off course see that while the Zone parameter is marked as required, that only the WebAppUrl parameter is identified as a Key. Can't we also make the Zone a Key parameter to solve this issue?

**The DSC configuration that is using the resource:**
[...]
SPBlobCacheSettings 5daeca26-879d-4f5b-be9f-7270aa6551d1
        {
            MaxSizeInGB = 10;
            PsDscRunAsCredential = $Credssp_farm;
            FileTypes = "\.(gif|jpg|jpeg|jpe|jfif|bmp|dib|tif|tiff|themedbmp|themedcss|themedgif|themedjpg|themedpng|ico|png|wdp|hdp|css|js|asf|avi|flv|m4v|mov|mp3|mp4|mpeg|mpg|rm|rmvb|wma|wmv|ogg|ogv|oga|webm|xap)$";
            EnableCache = $False;
            Location = "C:\BlobCache\14";
            MaxAgeInSeconds = 0;
            Zone = "Default";
            WebAppUrl = "http://mva-wfe/";
        }
        SPBlobCacheSettings ef14ea31-4cd6-41ad-8920-f7fd9de1aee4
        {
            MaxSizeInGB = 10;
            PsDscRunAsCredential = $Credssp_farm;
            FileTypes = "\.(gif|jpg|jpeg|jpe|jfif|bmp|dib|tif|tiff|themedbmp|themedcss|themedgif|themedjpg|themedpng|ico|png|wdp|hdp|css|js|asf|avi|flv|m4v|mov|mp3|mp4|mpeg|mpg|rm|rmvb|wma|wmv|ogg|ogv|oga|webm|xap)$";
            EnableCache = $False;
            Location = "C:\BlobCache\14";
            MaxAgeInSeconds = 0;
            Zone = "Intranet";
            WebAppUrl = "http://mva-wfe/";
        }
[...]
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win Server 2016/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by BrianFarnhill** [comment]
Agree that zone should be a key as well, adding to the backlog

**Comment by ykuijs** [comment]
Will be changed in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
