### ISSUE TITLE
SPWebAppGeneralSettings Error with TimeZone

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#610]
**Details of the scenario you try and problem that is occurring:**
If the TimeZone is not set on a Web Application, the Module returns value -1, which is invalid. Should we return null, or simply not return this parameter if it is not set? -1 is not a valid Uint64 value and causes error when trying to compile:

ConvertTo-MOFInstance : System.Management.Automation.RuntimeException error processing property 'TimeZone' OF TYPE 'SPWebAppGeneralSettings': Cannot convert value "-1" to type "System.UInt64". Error: "Value was either too large or too small for a UInt64."

**The DSC configuration that is using the resource:**
SPWebAppGeneralSettings 895df459-ed46-487d-874e-bc3a219f8bbc
        {
            BlogAPI = $True;
            BlogAPIAuthenticated = $False;
            SecurityValidationTimeoutMinutes = 30;
            PsDscRunAsCredential = $Credssp_farm;
            CustomerExperienceProgram = $False;
            SecurityValidation = $True;
            SelfServiceSiteCreationEnabled = $False;
            MaximumUploadSize = 2047;
            SecurityValidationExpires = $True;
            RSS = $True;
            RecycleBinEnabled = $True;
            BrowserFileHandling = "Strict";
            RecycleBinCleanupEnabled = $True;
            AllowOnlineWebPartCatalog = $True;
            SecondStageRecycleBinQuota = 50;
            AlertsLimit = 500;
            Alerts = $True;
            PresenceEnabled = $True;
            Url = "http://mva-wfe/";
            TimeZone = -1;
            RecycleBinRetentionPeriod = 30;
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by BrianFarnhill** [comment]
It should probably be $null, adding to the backlog

**Comment by ykuijs** [comment]
Fixed in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
