### ISSUE TITLE
SPUserProfileProperty Issue with Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#611]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource method of the SPUserProfileProperty Resource returns a parameter named "UserProfileServiceAppName" where the parameter expected by the 3 *-TargetResource is named UserProfileService only.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows server 2016/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by ykuijs** [comment]
Added to backlog

**Comment by ykuijs** [comment]
Will be fixed in next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
