### ISSUE TITLE
SPUserProfileServiceAppPermissions includes too many manadatory parameters

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#612]
**Details of the scenario you try and problem that is occurring:**
Looks like every single parameter is made mandatory in the SPUserProfileServiceAppPermissions resource. To me, it looks like only ProxyName should be made mandatory.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows server 2016/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by ykuijs** [comment]
The Readme of the resource specifies that if you don't want to use that permission, you have to specify "None". The code in the methods is relying on this to be present.

So we have to decide if we want to change this. @BrianFarnhill, what do you think?

**Comment by BrianFarnhill** [comment]
Yea look we probably could make the change for the other options to optional here, but realistically I don't see it as a huge problem based on what @ykuijs said about the doco around how it's used. If @ykuijs wants to we can put it on the backlog and if someone gets bored they can code a fix for it, but I would put this in the low priority category. I assume this is something else causing your reverseDSC scripts some grief?

**Comment by NikCharlebois** [comment]
Yes, the issue here was around ReverseDSC. I will take a crack at it and remove the mandatory from these parameters. The code that checks for "None" will need to remain as to not introduce a breaking change, but I will also add logic to threat the params missing as "none"

**Comment by ykuijs** [comment]
Closed via PR #735
