### ISSUE TITLE
SPRemoteFarmTrust misses ensure property default in the test method

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#614]
**Details of the scenario you try and problem that is occurring:**

Currently the test method of SPRemoteFarmTrust will fail on resources that do not specifically set the Ensure property to be present (the default value). The trust provisions fine the first time around but then fails its tests and tries to set at every run because this line (which is in all other resources with a default for ensure) is missing from the test method:

    $PSBoundParameters.Ensure = $Ensure

For anyone experiencing the issue, the workaround in the meantime is to specifically add "Ensure = 'Present'" to all instances of this resource

**Version of the DSC module you're using:**

SharePointDsc 1.7

**Comment by ykuijs** [comment]
Will be fixed in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
