### ISSUE TITLE
MSFT_SPUsageApplication

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#617]
**Details of the scenario you try and problem that is occurring:**
I created a SPUsageApplication using DSC. Now if I rerun the exact same DSC config I used to create it in the first place, it gives the following error. It feels to me like the Test-TargetResource method is not properly detecting that the instance I want already exists, and that it tries to recreate a second one instead.

A Usage Application already exists in this farm.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewUsageApplication
    + PSComputerName        : localhost

**The DSC configuration that is using the resource:**
SPUsageApplication UsageandHealthDataCollectionServiceApplication
        {
            Ensure = "Present";
            PsDscRunAsCredential = $Credsdw_spfarm;
            UsageLogCutTime = 30;
            UsageLogMaxFileSizeKB = 1024;
            DatabaseCredentials = $Credsdw_spfarm;
            UsageLogMaxSpaceGB = 5;
            DatabaseName = "DW_UsageAndHealth";
            Name = "Usage and Health Data Collection";
            UsageLogLocation = "D:\Logs\SharePointUsage";
            DatabaseServer = $env:Computername;
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2k12 R2/WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by lazda** [comment]
Try FQDN and/or alias for DatabaseServer

**Comment by BrianFarnhill** [comment]
@NikCharlebois Have you got the verbose output from the failed run? The test method should tell you in its verbose output what property it failed to match on, which will help us narrow down what's happening here.

**Comment by NikCharlebois** [comment]
Can't replicate. Must have been a brain fart.
