### ISSUE TITLE
SPSessionStateService issue in get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#618]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource tries to return the following:

 return @{
            DatabaseName = $svc.DatabaseId
            DatabaseServer = $svc.DatabaseServer
            Ensure = $Ensure
            SessionTimeout = $svc.Timeout.TotalMinutes
        }

However, DatabaseServer doesn't exist on the object, and DatabaseID is not the proper value to return here. Instead, this should be:

 return @{
            DatabaseName = $svc.CatalogName
            DatabaseServer = $svc.ServerName
            Ensure = $Ensure
            SessionTimeout = $svc.Timeout.TotalMinutes
        }

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
win 2k12R2 / WMF 5.1

**Version of the DSC module you're using:**
1.7.0.0

**Comment by ykuijs** [comment]
Will be fixed in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
