### ISSUE TITLE
SPWebAppPolicy Issues with internal CIMInstance

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#620]
**Details of the scenario you try and problem that is occurring:**
Given the DSC blocks below, it looks like since the MSFT_SPWebPolicyPermissions class is declaring UserName as its Key, thatyou can't have more than one parent SPWebAppPolicy block declaring the same UserName. (Try to deploy the below DSC script to get more details). Hopefully this doesn't open a can of worms...

**The DSC configuration that is using the resource:**
SPWebAppPolicy 025c1ec0-36c0-4df0-b9ce-b8bc0bcfeb51
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $True;
            WebAppUrl = "https://my-dev2013.eydev.net/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "eydev\dw-spfarm"
                IdentityType = "Claims"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy 40cc67bb-1636-4ba4-8a97-4f5da31870cf
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $False;
            WebAppUrl = "http://localhost:1233/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "EYDEV\dw-spfarm"
                IdentityType = "Native"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy f192cc56-50e3-4394-9219-c53e59364d1f
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $False;
            WebAppUrl = "http://localhost:1234/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "EYDEV\dw-spfarm"
                IdentityType = "Native"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy bc1fab99-d40b-4165-a6a3-b203e0165b93
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $False;
            WebAppUrl = "http://localhost:1235/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "EYDEV\dw-spfarm"
                IdentityType = "Native"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy 345c2ed3-525c-4431-a86e-4c4ef8a061f0
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $False;
            WebAppUrl = "http://localhost:1236/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "EYDEV\dw-spfarm"
                IdentityType = "Native"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy c00d363d-8ac8-4fec-9073-83fb1238aa26
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $True;
            WebAppUrl = "http://find-dev2013.eydev.net/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "eydev\dw-spfarm"
                IdentityType = "Claims"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy 42bfb676-01af-494b-82ee-618f879aa96a
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $True;
            WebAppUrl = "https://share-dev2013.eydev.net/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "eydev\dw-spfarm"
                IdentityType = "Claims"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }
        SPWebAppPolicy b43ab3b0-9a11-4e4f-aca6-12a42ea2840a
        {
            PsDscRunAsCredential = $Credsdw_spfarm;
            SetCacheAccountsPolicy = $False;
            WebAppUrl = "http://ey-standalone:12877/";
            Members = MSFT_SPWebPolicyPermissions{
                Username = "eydev\dw-spfarm"
                IdentityType = "Claims"
                PermissionLevel = "Full Read"
                ActAsSystemAccount = $False
            };
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2k12R2 / WMF 5.1
**Version of the DSC module you're using:**
1.7.0.0

**Comment by BrianFarnhill** [comment]
@NikCharlebois Looks like you're right - lets drop this on the backlog and see where it goes. Changing a child objects key to just "required" shouldn't break anything, but lets kick the tyres on it and find out.

**Comment by ykuijs** [comment]
Closed with PR 660
