### ISSUE TITLE
MSFT_SPJoinFarm/MSFT_SPCreateFarm - ConfigDB registry key check

### ISSUE THREAD

**Issue by puthurr** [PowerShell/SharePointDsc#621]
**Details of the scenario you try and problem that is occurring:**

Installing a SharePoint Farm using Microsoft SPPLA scripts. Those still use SPCreateFarm and SPJoinFarm 

A registry key could not be found exception was thrown as below.

```
VERBOSE: [APP-SHP21]: LCM:  [ End    Test     ]  [[SPCreateFarm]CreateSPFarm]  in 1.3910 seconds.
PowerShell DSC resource MSFT_SPCreateFarm  failed to execute Test-TargetResource functionality with error message: Specified registry key hklm:SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\16.0\Secure\ConfigDB could not be found.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : APP-SHP21
```
The failure command was 
$configDbDsn = Get-SPDSCRegistryKey -Key $cfgDbRegKey -Value "dsn" 

* We tried to add -ErrorAction SilentlyContinue  (like module MSFT_SPFarm) but no success. Still the exception is thrown back to the invoking host. 

**We ended wrapping the  Get-SPDSCRegistryKey line with a try /catch and that fixes it.** 

**The DSC configuration that is using the resource:**
```
SPCreateFarm CreateSPFarm
            {
                DatabaseServer           = $ConfigurationData.NonNodeData.SQLServer.FarmDatabaseServer
                FarmConfigDatabaseName   = $ConfigurationData.NonNodeData.SharePoint.Farm.ConfigurationDatabase
                Passphrase               = $PassPhrase #$ConfigurationData.NonNodeData.SharePoint.Farm.Passphrase
                FarmAccount              = $FarmAccount
                PsDscRunAsCredential     = $SPSetupAccount
                AdminContentDatabaseName = $ConfigurationData.NonNodeData.SharePoint.Farm.AdminContentDatabase
                CentralAdministrationPort = $ConfigurationData.NonNodeData.SharePoint.Farm.CentralAdminPort
                ServerRole               = $Node.ServerRole
                DependsOn                = $FarmInstallTask
            }

```
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 b1607 
PowerShell 5.1 
 
**Version of the DSC module you're using:**
1.7.0.0

**Comment by puthurr** [comment]
To clarify the fix we implemented looks like 

try { $configDbDsn = Get-SPDSCRegistryKey -Key $cfgDbRegKey -Value "dsn" } catch { $configDbDsn = $null }

**Comment by ykuijs** [comment]
Believe it or not, I have been discussing this exact same issue with someone else and was about to create an issue for it :-)

Will implement a fix in my next rollup PR

**Comment by ykuijs** [comment]
As a workaround, please check out SPFarm.

This new resource will replace SPCreateFarm and SPJoinFarm as of v2.0

**Comment by puthurr** [comment]
Thanks Yorick for the update :) Ack about the deprecation of SPCreateFarm and SPJoinFarm.

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
