### ISSUE TITLE
Enhance SPUserProfileServiceApp to allow for NoILM to be enabled.

### ISSUE THREAD

**Issue by DarenDaigle** [PowerShell/SharePointDsc#622]
**Details of the scenario you try and problem that is occurring:**
I am configuring a system that is using the "Active Directory Import" and think this would be a good thing to enable in the initial creation of the resource.

Currently to do this, I use the following three lines.

    $upa = Get-SPServiceApplication | where-object { $_.DisplayName -eq "User Profile Service Application" }
    $upa.NoILMUsed = $true
    $upa.Update()

Daren

**Comment by ykuijs** [comment]
Hi @DarenDaigle, I am not sure what you are trying to say here. Can you explain the issue a little more?

**Comment by DarenDaigle** [comment]
In order to use the "Active directory import" non-Miis connection to AD, you set NoILMUsed to $true

**Comment by ykuijs** [comment]
You are using SharePoint 2013, correct?

So you are suggesting when creating a new User Profile Service Application, you would like to be able to have a NoILMUsed parameter, so you don't need to add the SPUserProfileSyncConnection resource to your config. Am I correct?

**Comment by BrianFarnhill** [comment]
@ykuijs I believe you are correct here - and this is something I know I have a customer request for as well, so we should get this option in there if we can.

**Comment by ykuijs** [comment]
Included in my next Rollup PR

**Comment by BrianFarnhill** [comment]
This has been rolled in to dev and will be included in our next release. Closing this issue.
