### ISSUE TITLE
Deploy SPAccessServiceApp won't connect to database

### ISSUE THREAD

**Issue by Chiliyago** [PowerShell/SharePointDsc#623]
**Details of the scenario you try and problem that is occurring:**
Attempting to deploy SPAccessServiceApp but receive this error:

A connection could be established to the Application Database Server but mixed mode authentication isn't enabled.
    + CategoryInfo          : ObjectNotFound: (Access Services Service Application:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Access.Services.PowerShell.NewSPAccessServicesApplication
    + PSComputerName        : SP-APP1
 

**The DSC configuration that is using the resource:**
SPAccessServiceApp AccessServices
        {
            Name                 = "Access Services Service Application"
            ApplicationPool      = $serviceAppPoolName
            DatabaseServer       = $SqlServerName
            PsDscRunAsCredential = $FarmSetupCredential
            DependsOn            = "[SPFarm]CreateSPFarm"
            Ensure               = "Present"
        }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, PowerShell  5.1

**Version of the DSC module you're using:**
1.7

**Comment by ykuijs** [comment]
Hi @Chiliyago, as the error suggests: You have to enable Mixed Mode authentication on your SQL instance before you can use the Access Service Application. See the properties of your instance in the SQL Management Studio:
https://www.top-password.com/images/server-authentication-mode.png

Can you change that setting, try again and let us know the results?

**Comment by Chiliyago** [comment]
Yes that did the trick. Does Access Services require Mixed Mode or is that a function of the resource for some reason?

**Comment by BrianFarnhill** [comment]
@Chiliyago This is a requirement of Access Services as it uses SQL authentication for each individual database. Have a look at this link for more info:

https://social.technet.microsoft.com/wiki/contents/articles/12514.sharepoint-2013-access-services.aspx#Required_SQL_Server_settings_for_Access_apps
