### ISSUE TITLE
SPProductUpdate Shutdown Services Product Version Check is always false

### ISSUE THREAD

**Issue by llowevad** [PowerShell/SharePointDsc#624]
**Details of the scenario you try and problem that is occurring:**
When running SPProductUpdate in Set-TargetResource it is checking the product version using the following condition. I was running the configuration on a SharePoint 2013 farm and received a PowerShell error saying it could not find OSearch16 since the following condition returned false, it assumed I was running SharePoint 2016.

if ((Get-SPDSCInstalledProductVersion) -eq 15) {

This will always return FALSE since a hashtable is returned from the command

It should be something more like

if ( ((Get-SPDSCInstalledProductVersion).ProductVersion).Split(".")[0] -eq 15)

**The DSC configuration that is using the resource:**
        SPProductUpdate InstallSharePointCU 
        { 
             SetupFile = $ParamSPCUInstallFile 
             Ensure = "Present" 
             PsDSCRunAsCredential = $ParamCredsSPFarmAccount
             DependsOn = "[SPFarm]CreateSPFarm"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2
PS - 5.0

**Version of the DSC module you're using:**
1.7

**Comment by llowevad** [comment]
Actually it looks like line 311 has a check for the right version as 

(Get-SPDSCInstalledProductVersion).FileMajorPart

Need to update line 341 to use this

**Comment by ykuijs** [comment]
Will be fixed in my next Rollup PR

**Comment by ykuijs** [comment]
Issue is fixed in PR630

**Comment by ykuijs** [comment]
Linking to #630
