### ISSUE TITLE
Attempted to perform an unauthorized operation when provisioning a host name site collection

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/SharePointDsc#625]
When I tried to provision a host name site collection, I got an error. Appreciate if anyone can shed some lights. 

Here is the verbose log:

[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Setting site collection http://finance.share.xxx.com
[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Executing as the local run as user domain\SP16_Setup
[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Leaving BeginProcessing Method of Get-SPSite.
[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Leaving ProcessRecord Method of Get-SPSite.
[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Leaving EndProcessing Method of Get-SPSite.
[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Leaving BeginProcessing Method of New-SPSite.
[EPGIDVWEUE1141]:                            [[SPSite]SharePointSitesSiteTeamSites] Performing the operation "New-SPSite" on target 
"http://finance.share.xxx.com".
Attempted to perform an unauthorized operation.
    + CategoryInfo          : InvalidData: (Microsoft.Share...SPCmdletNewSite:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSite
    + PSComputerName        : epgidvweue1141.nam.corp.gm.com

The DSC configuration looks like:

                SPWebApplication $webAppInternalName
                {
                    Name                   = $webApp.Name
                    ApplicationPool        = $webApp.AppPool
                    ApplicationPoolAccount = $webApp.APpPoolAccount
                    AllowAnonymous         = $webApp.Anonymous
                    AuthenticationMethod   = $webApp.Authentication
                    DatabaseName           = $webApp.DatabaseName
                    DatabaseServer         = $ConfigurationData.NonNodeData.SQLServer.ContentDatabaseServer
                    Url                    = $webApp.Url
                    HostHeader             = $webApp.HostHeader
                    Port                   = [Uri]::new($webApp.Url).Port
                    PsDscRunAsCredential   = $SPSetupAccount
                    DependsOn              = "[SPManagedAccount]WebPoolManagedAccount"
                }

                # If using host named site collections, create the empty path based site here
                if ($webApp.UseHostNamedSiteCollections -eq $true) {
                    SPSite HNSCRootSite
                    {
                        Url                      = $webApp.Url
                        OwnerAlias               = $SPSetupAccount.Username
                        Name                     = "Root site"
                        Template                 = "STS#0"
                        PsDscRunAsCredential     = $SPSetupAccount
                        DependsOn                = "[SPWebApplication]$webAppInternalName"
                    }
                }

**Comment by ykuijs** [comment]
Hi @tonyhxh, can you check the ULS log of the specific server to see if you can get more information?

**Comment by ykuijs** [comment]
Any update? Also: The config you shared does not contain the HNSC config you are trying to create, just the path based root site collection. Can you also share the HNSC config you are using?

**Comment by ykuijs** [comment]
Close issue due to no reply from @tonyhxh
