### ISSUE TITLE
Creating a new resource to be included

### ISSUE THREAD

**Issue by DarenDaigle** [PowerShell/SharePointDsc#627]
I am not sure the protocol to propose a new resource to the community for review.

I have it created and now that the code functions , I am doing some more testing.

Daren

P.S. the Resource for inclusion, i call SPWebModification.

It's intent is to include the ability to use SharePoints native WebConfigModifications property of a website to make such changes.

**Comment by ykuijs** [comment]
Hi @DarenDaigle, this is definitely the way to suggest new resources for SharePointDsc, so keep those ideas coming :-)

Over a year ago, we had a quite extensive discussion about this exact resource. You can read all about it in #219. Back then we decided not to use the SPWebConfigModifications class for the following reasons:
- It does not enforce the values in the web.config file
- It sometimes is a little unreliable

However, there were some alternative solutions but we never decided to go for them or not.

**Comment by DarenDaigle** [comment]
Well, i guess i should have asked before i had it 90% complete.

I the one I made seems to be reliable when applying the first time.

And for my purposes it works since i am using DSC for an initial deployment and the leaving the system be.

Daren

**Comment by BrianFarnhill** [comment]
On this one, I know that @PlagueHO is working on a generic (as in not SharePoint or even just XML file specific) resource that will let you work with configuration files, so when that is ready you can use this to manage the files on each server. 

Happy to accept that it's possible to write a resource to manage the SPWebConfigModification class itself and it might work for the initial deployment, as per the discussion that @ykuijs linked to above there I'm still very hesitant to look at putting this in based on it's reliability in a wider range of scenarios. So thank you for writing the contribution there but I don't think we'll pull it in to the module here. In future though if you do want to write something just raise an issue here first like you have here and we can have these sorts of discussions before you get too far in to your code to head this sort of thing off. Thanks Daren!
