### ISSUE TITLE
'MSFT_SPWebPolicyPermissions' is not recognized

### ISSUE THREAD

**Issue by wickedave** [PowerShell/SharePointDsc#628]
Hi,

I'm trying to use SPWebAppPolicy resource in release 1.7.0.0. I'm using the MembersToInclude but always getting an error. I would like to know if it is a but or if my sintax is not correct. I used the same kind of sintax as the example in the help:

```
SPWebAppPolicy WebAppPolicy
            {
                WebAppUrl            = "http://sharepoint.contoso.com"
                MembersToInclude = @(
                    @(MSFT_SPWebPolicyPermissions {
                        Username        = "contoso\user1"
                        PermissionLevel = "Full Control"
                    })
                    @(MSFT_SPWebPolicyPermissions {
                        Username        = "contoso\user2"
                        PermissionLevel = "Full Read"
                    })
                )
                SetCacheAccountsPolicy = $true 
                PsDscRunAsCredential   = $SetupAccount
            }
```
While doing this, I'm getting the following error:

> MSFT_SPWebPolicyPermissions : The term 'MSFT_SPWebPolicyPermissions' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by NikCharlebois** [comment]
Dave does that mean you figured out what your issue was? If so, can you post your solution here?

**Comment by BrianFarnhill** [comment]
@NikCharlebois The Syntax is wrong, he has each of the policy permissions objects wrapped in an array syntax where they don't need to be, so perhaps this is why it was closed

**Comment by wickedave** [comment]
I was an errror because I put the "MembersToInclude" in a variable without quotes so it was interpreting 'MSFT_SPWebPolicyPermissions' as a function or command while it is not. It was an error from my part and when I realized it, I closed the issue.
