### ISSUE TITLE
SPServiceAppSecurity not working with Secure Store service application

### ISSUE THREAD

**Issue by wickedave** [PowerShell/SharePointDsc#633]
**Details of the scenario you try and problem that is occurring:**
I'm trying to add rights on the Secure Store service application with SPServiceAppSecurity DSC resource but the accepted 'AccessLevel values are: 

Change Permissions
Full Control
Write
Read 

While this service application values must be:

Full Control
Create Target Application
Delete Target Application
Manage Target Application
All Target Applications

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Window Server 2016 with SharePoint 2016

**Version of the DSC module you're using:**
1.7.0.0

**Comment by wickedave** [comment]
I have the same problem for User Profile Service Application. The access rights on that service are: 

Full Control
Manage Profiles
Manage Audiences
Manage Permissions
Retrieve People Data for Search Crawlers
Manage Social Data

**Comment by BrianFarnhill** [comment]
Thanks for reporting @wickedave - We are already tracking this issue at #585 which has all of the additions you need listed there as well, so I'll close this off as a duplicate and we can keep tracking the other issue for progress on this one. Thanks!
