### ISSUE TITLE
Getting error with "Administrators" security type in SPServiceAppSecurity

### ISSUE THREAD

**Issue by wickedave** [PowerShell/SharePointDsc#634]
**Details of the scenario you try and problem that is occurring:**
I'm trying to execute this code:
```
Configuration Example 
{
    param(
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $SetupAccount
    )
    Import-DscResource -ModuleName SharePointDsc

    node localhost {
        $membersToInclude = @()
        $membersToInclude += MSFT_SPServiceAppSecurityEntry {
                                Username    = "CONTOSO\SharePointFarmAccount"
                                AccessLevel = "Full Control"
                            }
        $membersToInclude += MSFT_SPServiceAppSecurityEntry {
                                Username    = "CONTOSO\SharePointServiceApps"
                                AccessLevel = "Full Control"
                            }
        SPServiceAppSecurity UserProfileServiceSecurity
        {
            ServiceAppName       = "User Profile Service Application"
            SecurityType = "Administrators"
            Members  = $membersToInclude
            PsDscRunAsCredential = $SetupAccount 
        }
    }
}
```
I'm receiving the following error:
```
Cannot bind argument to parameter 'ReferenceObject' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje
   ctCommand
```
When I look in the MOF file, I can see that there is no empty value. Everything is well populated. Perhaps I'm doing something wrong but I don't see what. I didn't try to use 'MembersToInclude' and use 'Members' instead because I want to make sure that only the list provided is admin on the service and no one else.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 with SharePoint 2016

**Version of the DSC module you're using:**
1.7.0.0

**Comment by BrianFarnhill** [comment]
@wickedave This is likely due to an error happening in our script. Are you able to share the verbose output from that resource up to the error you have there so we can assess the code path it was taking to get to the error?

**Comment by wickedave** [comment]
@BrianFarnhill Here is the verbose output:

```
VERBOSE: [SP-Server]: LCM:  [ Start  Resource ]  [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
VERBOSE: [SP-Server]: LCM:  [ Start  Test     ]  [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Testing all security options for Administrators in Lab-UPA-01
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Getting all security options for Administrators in Lab-UPA-01
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Executing as the local run as user UBISOFT-ORG\svc_sps_setup
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Leaving BeginProcessing Method of Get-SPServiceApplicationSecurity.
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Leaving ProcessRecord Method of Get-SPServiceApplicationSecurity.
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Leaving EndProcessing Method of Get-SPServiceApplicationSecurity.
VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Processing Members parameter
Cannot bind argument to parameter 'ReferenceObject' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje
   ctCommand
    + PSComputerName        : SP-Server

VERBOSE: [SP-Server]:                            [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
Security list matches - checking that permissions match on each object
VERBOSE: [SP-Server]: LCM:  [ End    Test     ]  [[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators]
in 0.4370 seconds.
The PowerShell DSC resource '[SPServiceAppSecurity]SAPermission-UPA-01-Lab-Administrators' with SourceInfo
'C:\Users\MyUser\Documents\GitHub\sp-scripts\DSC\SP2016-Config.ps1::623::25::SPServiceAppSecurity' threw one or
more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW
channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : SP-Server```

**Comment by ykuijs** [comment]
@wickedave Have you tried to use the format:
`$membersToInclude += 
        $membersToInclude += 
        SPServiceAppSecurity UserProfileServiceSecurity
        {
            ServiceAppName       = "User Profile Service Application"
            SecurityType = "Administrators"
            Members = @(
                        MSFT_SPServiceAppSecurityEntry {
                                Username    = "CONTOSO\SharePointFarmAccount"
                                AccessLevel = "Full Control"
                            }
                        MSFT_SPServiceAppSecurityEntry {
                                Username    = "CONTOSO\SharePointServiceApps"
                                AccessLevel = "Full Control"
                            }
                )
            PsDscRunAsCredential = $SetupAccount 
        }
`

And have you tried to test this with v1.8?

**Comment by wickedave** [comment]
@ykuijs I've updated the DSC module to 1.8.0.0 and I got the same error. I also tried the syntax you proposed me and the configuration is not even starting. Here's the error I'm getting:
```
PS C:\Windows\system32> Update-DscConfiguration -Wait -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SP-Server with user sid
S-1-5-21-842925246-1390067357-682003330-55004.
VERBOSE: [SP-Server]:                            [] Executing Get-Action with configuration 's checksum returned
result status: GetConfiguration.
VERBOSE: [SP-Server]:                            [] Checksum is different. LCM will execute GetConfiguration to
pull configuration .
VERBOSE: [SP-Server]:                            [] Executing GetConfiguration failed. Configuration
SharePoint.SP-Server.ubisoft.org is not pulled.
Cannot find module MSFT_SPServiceAppSecurityEntry from the server https://DSCPullServer/PSDSCPullServer.svc/Modules(ModuleName='MSFT_SPServiceAppSecurityEntry',ModuleVersion='')/ModuleContent.
    + CategoryInfo          : ResourceUnavailable: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : WebDownloadManagerModuleNotFound,Microsoft.PowerShell.DesiredStateConfiguration.Commands
   .GetDscModuleCommand
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.493 seconds
```

If I'm changing Members for MembersToInclude, it is working well. So the issue seems to happen only with Members parameter.

**Comment by BrianFarnhill** [comment]
I think I see it, we are looking at [line 349](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1#L349) here. It's got the $CurrentValues.Members.Username there which is the null object, so I'm assuming that there are no objects in $CurrentValues.Members to make that happen. This is different to the MembersToInclude approach as we use -notcontains and things like that to match things, so it wouldn't throw an error.

@wickedave Can you confirm if the service app you are running this against has no current permissions applied to it? And if you manually add one in central admin does this same bit of code execute? If so we can just drop a null test in and this is a quick fix.

**Comment by wickedave** [comment]
@BrianFarnhill Hi you are right. As soon a an account is already present, there's no error but I have another issue. I've put an account that is not part of "Members" parameter and after the SET, nothing has changed.

**Comment by BrianFarnhill** [comment]
@wickedave OK, so two things then - lets use this issue to track that quick fix at line 349 (@ykuijs is good at picking up these kind of quick fixes in his bug fix rollups), but can I get you to open a new issue and include the verbose output of when it runs without making that change? Then we can track the two as separate issues.

**Comment by wickedave** [comment]
@BrianFarnhill Sure. I will open another issue for the "doing nothing" matter. Thanks

**Comment by ykuijs** [comment]
Closed with PR 660

**Comment by shurick81** [comment]
@BrianFarnhill, I wonder If the issue when current user list is empty was separately registered. I experience the error when I try to use SharePointDSC 2.2.0.0

**Comment by BrianFarnhill** [comment]
@ykuijs Can you have a look at this one for @shurick81 .

@shurick81  I don't look after this project anymore, but Yorick and the guys will be able to help you out! :)

**Comment by ykuijs** [comment]
I guess this is registered in issue #641, which is still open.
