### ISSUE TITLE
SPSecureStoreServiceApp Get-TargetResource returning incomplete value for DatabaseServer

### ISSUE THREAD

**Issue by ronx** [PowerShell/SharePointDsc#638]
**Details of the scenario you try and problem that is occurring:**

After initial configuration of SPSecureStoreServiceApp specifying DatabaseServer as ServerName\Instance, subsequent consistency checks are throwing an error that the database server does not match. I debugged the problem and discovered that on line 123 of MSFT_SPSecureStoreServiceApp.psm1, the DatabaseServer property is being set to $db.Server.Name. Exploring this object, I noticed that $db.Server.Name only returns the server name and not the instance. Therefore, when Test-TargetResource compares this to the originally configured server\instance value, it complains about the values not matching and thinks you're trying to move the service to a different database server.

I currently don't have a farm set up using the default instance, and thus, only the database server name for the connection, so I can't test different scenarios. However, it looks like the best choice might be to use $db.NormalizedDatasource. Another option could be to use $db.ServiceInstance.Name in conjunction with $db.Server.Name.

**The DSC configuration that is using the resource:**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

WS 2012 R2
WMF 5.1

**Version of the DSC module you're using:**

1.7.0.0

**Comment by BrianFarnhill** [comment]
Looks legit to me, I'll put it on the bug list. Thanks for reporting!

**Comment by Christwe** [comment]
This is happening under SharePointDSC 1.8.0.0 as well

**Comment by ykuijs** [comment]
Issue will be fixed in my next Rollup PR.

@BrianFarnhill Isn't this an issue for more resources. We use Server.Name a lot, which probably means the instance issue exists there as well. Do you agree?

**Comment by BrianFarnhill** [comment]
@ykuijs In a lot of cases you get the SPServer object back instead of just the name, so it's applied inconsistently. I don't think we have this issue in too many other places though so I would believe this is related to just this resource in this case.

**Comment by ykuijs** [comment]
That is true, but then we return only the Name property, just like we do in this (SPSecureStoreServiceApp) resource. For example SPAppManagementServiceApp and SPWordAutomationServiceApp

I don't have an environment which is using named instances, so am unable to test. Does anyone have an environment available?

**Comment by BrianFarnhill** [comment]
@ykuijs Sorry I got confused there - yea there are a few places we will need to check this out :P I don't have a lab handy, I would need to spin one up by hand since all my scripts rely on default instance names.

**Comment by ronx** [comment]
I can help test this one. @ykuijs which method are you using? In my local repo, I decided to go with $db.NormalizedDatasource and it seems to be working fine for me. I haven't tested that property in a farm using aliases, but it works fine when using databaseserver\instance. I can start making some changes in resources I'm already using to make sure they're returning the right values. I can either submit a pull request with any progress, or if you'd rather knock them all out, I'll just overwrite my local repo when you're done.

If you guys want me to submit pull requests, is the dev branch the best place?

**Comment by ronx** [comment]
Here's another question. How often are we actually using the values returned from Get-TargetResource? For example, in MSFT_SPFarm, it looks like the Test-TargetResource is calling Get-TargetResource and then only checking the value of Ensure. Am I reading that correctly or am I missing something? For example, if you have an existing farm and then change your DSC configuration to set RunCentralAdmin to $true when it was previously $false, won't Test-TargetResource report that nothing has changed since Ensure is the only thing that appears to be checked for changes? Sorry if I'm missing something here ;)

**Comment by NikCharlebois** [comment]
@ronx While understand your question is mostly related to the relationship between the three methods (Get, Test, and Set), I'll add that ReverseDSC for SharePoint is all about the Get-TargetResource methods and what they actually return.
https://Github.com/Microsoft.SharePointDSC.Reverse

**Comment by ronx** [comment]
Thanks Nik. I think these changes will only be beneficial to ReverseDSC. My main concern is if there is anything in the SharePointDsc codebase that might be depending on the incomplete value being returned for the DatabaseServer property in any of the affected resources. For example, maybe someone noticed this in the past and has code to append the instance name to the end of DatabaseServer. If I don't notice that and change the property to be set from NormalizedDatasource, then the instance name could be appended twice.

I don't think this is the case anywhere, but just bringing it up in case those more familiar with the codebase might be able to think of anything that might break. Speaking of testing the changes, I'm kind of surprised the pester tests don't test to make sure the values returned from Get-TargetResource match the desired values passed in. Or maybe there is a test for that, but the test scenario doesn't use a named instance. I'm still learning about writing Pester tests, so I would appreciate some suggestions on how and where to write this particular test.

**Comment by ronx** [comment]
BTW @ykuijs , if you haven't started on this one, I can take it. Locally, I've updated and tested 12 resources so far. There are 2 other resources I believe need to be updated, but I'm not using Performance Point or Word Automation in my staging instance here. I'm in the process of rebuilding my Azure lab though, so I can probably test these other 2 in the next week. LMK.

**Comment by BrianFarnhill** [comment]
@ronx We use the get-targetresource values in the test methods everywhere, so if they are returning the wrong values I 100% want to get them returning the right values with instance names

**Comment by ykuijs** [comment]
@ronx I am working on a large bugfix PR and already have changed the following resources: SPAppManagementServiceApp, SPBCSServiceApp, SPSecureStoreServiceApp, SPWordAutomationServiceApp
I am planning to do the rest of the resources as well (just search for Server.Name to see which ones) before I submit the PR.

As for the Get-TargetResource question: Ideally Get-TargetResource returns all the properties and Test-TargetResource tests for all of them. However not all properties are editable once initially set, to we can test for them but changing them means recreating the component for example, which can have a huge impact for the environment. Second, not all resources have the logic implemented to change all properties. So if you run into a resource where you require a certain property to be changed, just raise an issue in the issue list, so we implement it.

**Comment by ykuijs** [comment]
Updated all resources, will be included in my next rollup PR

**Comment by ykuijs** [comment]
Closed with PR 660
