### ISSUE TITLE
SPUserProfileProperty resource is not working for Active Directory Import syncronisation

### ISSUE THREAD

**Issue by DenisK87** [PowerShell/SharePointDsc#639]
**Details of the scenario you try and problem that is occurring:**
In farm configuration where user profile application has synchronization connection with type "Active Directory Import" DSC resource SPUserProfileProperty with mapping settings will cause the error:

> PowerShell DSC resource MSFT_SPUserProfileProperty  failed to execute Set-TargetResource functionality with error message: You cannot call a method on a null-valued expression. 

The reason is that in file MSFT_SPUserProfileProperty.psm1 in Set-Script block in lines since 586 till 595 is used variable $Connection instead of $syncConnection.

Also, lines since 177 till 180 in Test-Script block  cause the same error.  It is required to check first - if connection manager property mapping is not $null 
```
$syncConnection  = $userProfileConfigManager.ConnectionManager | `
Where-Object -FilterScript { 
$null -ne $_.PropertyMapping -and `
$null -ne $_.PropertyMapping.Item($params.Name) 
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, PowerShell 5.1, SharePoint 2016

**Version of the DSC module you're using:**
1.8.0.0

**Comment by BrianFarnhill** [comment]
Looks legit, I'll put it on the bug list. Thanks for reporting

**Comment by ykuijs** [comment]
Closed with PR 660
