### ISSUE TITLE
No Service Apps available from use of SPFarm

### ISSUE THREAD

**Issue by alistairl** [PowerShell/SharePointDsc#640]
**Details of the scenario you try and problem that is occurring:**
I encountered the same issue as #621 using SPCreateFarm and SPJoinFarm i.e. an error at farm creation stage so switched the PLA based configuration to use SPFarm instead. This created a farm but all service application creation steps failed with parameter errors. In Central Admin the only Service Application in the new button was Access Services.

Removed all servers from farm, deleted config & central admin content databases and applied DSC configuration again with same result.

Manually ran PSConfigui on the first application server (which runs the service app config) and this cured the problem with service application creation.

**The DSC configuration that is using the resource:**
SPFarm CreateSPFarm
                           {
                                  Ensure                    = "Present"
                                  DatabaseServer            = $ConfigurationData.NonNodeData.SQLServer.FarmDatabaseServer
                                  FarmConfigDatabaseName    = $ConfigurationData.NonNodeData.SharePoint.Farm.ConfigurationDatabase
                                  AdminContentDatabaseName  = $ConfigurationData.NonNodeData.SharePoint.Farm.AdminContentDatabase
                                  Passphrase                = $PassPhrase
                                  FarmAccount               = $FarmAccount
                                  RunCentralAdmin           = $true
                                  PsDscRunAsCredential      = $SPSetupAccount
                                  CentralAdministrationPort = $ConfigurationData.NonNodeData.SharePoint.Farm.CentralAdminPort
                                  ServerRole                = $Node.ServerRole
                                  DependsOn                 = $FarmInstallTask,"[xGroup]AddADUserToLocalAdminGroup"
                           }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012R2 (en-gb) and PowerShell 5

**Version of the DSC module you're using:**
SharePointDSC 1.7.0.0 as per Azure Gallery

**Comment by BrianFarnhill** [comment]
OK so a couple of things - the fix for #621 was only included in v1.8, so if you are experiencing the issue there you will need to get the latest version of that. 

In terms of errors with creating services apps etc. can you provide some examples of what you are seeing in your logs so we can troubleshoot that a bit better?

**Comment by alistairl** [comment]
Here is a list of the highlights:

PowerShell DSC resource MSFT_SPStateServiceApp failed to execute Set-TargetResource functionality with error message: Cannot bind argument to parameter 'ServiceApplication' because it is null. 

"SerializedRemoteException":  "System.ArgumentNullException: Value cannot be null.\r\nParameter name: service\r\n   at Microsoft.SharePoint.BusinessData.SharedService.BdcServiceApplication.Create(String name, BdcService service, SPDatabaseParameters databaseParameters, Boolean createServiceApplicationProxy, SPIisWebServiceApplicationPool applicationPool, Boolean partitionMode)\r\n   at Microsoft.SharePoint.BusinessData.SharedService.SPNewBusinessDataCatalogServiceApplication.CreateBDCServiceApplication(String serviceAppName, Boolean partitionMode, Boolean sharing, String databaseServer, String databaseName, String failoverDatabaseServer, SPIisWebServiceApplicationPool applicationPool, String username, SecureString password, Boolean deferUpgradeActions)\r\n   at Microsoft.SharePoint.BusinessData.SharedService.SPNewBusinessDataCatalogServiceApplication.CreateDataObject()\r\n   at Microsoft.SharePoint.PowerShell.SPNewCmdletBase`1.InternalProcessRecord()\r\n   at Microsoft.SharePoint.PowerShell.SPCmdlet.ProcessRecord()",

PowerShell DSC resource MSFT_SPAppManagementServiceApp failed to execute Set-TargetResource functionality with error message: App Management Shared Service is not installed. 

PowerShell DSC resource MSFT_SPSubscriptionSettingsServiceApp failed to execute Set-TargetResource functionality with error message: The SPSubscriptionSettingsService object is unavailable. 

PowerShell DSC resource MSFT_SPUserProfileServiceApp failed to execute Set-TargetResource functionality with error message: The property 'NetBIOSDomainNamesEnabled' cannot be found on this object. Verify that the property exists and can be set.

**Comment by alistairl** [comment]
I disconnected the servers from the farm, deleted the databases and reverted to createfarm with v1.8 which has displayed the same services behaviour i.e. none available on farm creation and join.

**Comment by BrianFarnhill** [comment]
@alistairl So when the farm is in the failing state of not having the service applications, can you create them via PowerShell yourself? Like for example you see the BCS one failing there - can you run:

    New-SPBusinessDataCatalogServiceApplication

to get it to create one for you?

**Comment by alistairl** [comment]
Apologies for the delay in getting back to you - raised a ticket with premier and have been working through it. I'll need to deploy again to get farm in failing state then will let you know.

**Comment by alistairl** [comment]
@BrianFarnhill just got a farm in to this failing state and tested via PowerShell. From what I can see the result is identical i.e. the error I get back in an interactive PowerShell is the same as that I see reported back to the pull server in Azure Automation.

PowerShell was:

PS C:\Users\SPDeploy> $SvcAppPool = Get-SPServiceApplicationPool "SharePoint SVC Apps"
PS C:\Users\SPDeploy> $SvcApp = New-SPBusinessDataCatalogServiceApplication -ApplicationPool
 $SvcAppPool -Name "BCS SA" -DatabaseName "BCSDB" -DatabaseServer "AGL"
New-SPBusinessDataCatalogServiceApplication : Value cannot be null.
Parameter name: service
At line:1 char:11
+ $SvcApp = New-SPBusinessDataCatalogServiceApplication -ApplicationPoo ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...viceApplication:
   SPNewBusinessDa...viceApplication) [New-SPBusinessD...viceApplication], Ar
  gumentNullException
    + FullyQualifiedErrorId : Microsoft.SharePoint.BusinessData.SharedService.
   SPNewBusinessDataCatalogServiceApplication

**Comment by BrianFarnhill** [comment]
OK, so it looks like the inability to run things is not happening because of the runtime in DSC. Can I get you to loop me in to your premier case (just ask the support engineer you are working with to include me, they can look me up in the GAL) and I'll work with you guys through that mechanism to sort this out as I don't think what we are seeing is DSC related, but I would like to help confirm that there.

**Comment by alistairl** [comment]
Thanks Brian - by way of an update we can work around our particular issue by running PSCONFIGUI to fix the service apps and then either stsadm.exe or Install-SPFeature -path "SharedServices" -Force to kick search back in to action. For the time being due to time constraints we are going ahead with these workarounds. If we reengage with premier I'll make sure to include you.

**Comment by BrianFarnhill** [comment]
@alistairl Interesting - as far as I knew that SharedServices feature gets installed when we for the line below from SPFarm

    Install-SPFeature -AllExistingFeatures -Force

I think for the time being then we might close this issue as we have a work around, but if by chance you come across it again anywhere I would love to see the verbose output of your SPFarm resource when it runs the first time (for the set methods output) so we can see if that all ran fine to set those features up in the first place. Thanks for keeping the conversation going here and let me know if we can do more to help from this side.
