### ISSUE TITLE
SPTimerJobState can't set details for job in different web apps

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#644]
**Details of the scenario you try and problem that is occurring:**

Currently the SPTimerJobState only has the job name as a key. This means that where a job exists in two web applications, we can not include them both in the same configuration without there being a conflict. To address this we need to include the WebAppUrl as a key attribute as well (and allow people to set "n/a" or something as the value for jobs that do not relate to a specific web application).

This would form a breaking change as the WebAppUrl property would become mandatory where it is currently optional - so will need to go in to the 2.0 release as well.

**Version of the DSC module you're using:**

SharePointDsc v1.8

**Comment by NikCharlebois** [comment]
Any chances of WebAppUrl becoming an array?

**Comment by BrianFarnhill** [comment]
@NikCharlebois Actually that might be a better option as opposed to making it mandatory. Makes a more complicated resource but I think we can do it. @ykuijs what do you think mate?

**Comment by ykuijs** [comment]
Totally agree! That will make the resource more flexible. Will implement this in the 2.0 PR I am working on.

**Comment by ykuijs** [comment]
Closed with PR 660

**Comment by egor-yudkin** [comment]
This one didn't make it to release, but from the discussion it should. Can anyone more knowledgeable of github issue tracker than myself check this?

**Comment by ykuijs** [comment]
Hi @egor-yudkin, what makes you think that this one didn't make it to release. PR 660 fixed the issue and the current version (v2.1) has the possibility to specify a WebAppUrl parameter. Check out the [Wiki](https://github.com/PowerShell/SharePointDsc/wiki/SPTimerJobState) for more info.

**Comment by egor-yudkin** [comment]
Hi @ykuijs, sorry for the confusion, I was talking about WebAppUrl becoming an array, which you said will be implemented in 2.0
