### ISSUE TITLE
Updating the server with service pack or cumulative update before joining the farm

### ISSUE THREAD

**Issue by shurick81** [PowerShell/SharePointDsc#645]
**Details of the scenario you try and problem that is occurring:**
I am trying to install SharePoint 2013 with SP1 via DSC. The SPProductUpdate looks only proper for updating existing farm but what I need is updating the servers before building any farm. Is it possible with this or any other DSC resource?

**The DSC configuration that is using the resource:**

```
        SPProductUpdate InstallSPServicePack
        {
            SetupFile   = "C:\Install\SPServicePack\officeserversp2013-kb2880552-fullfile-x64-en-us.exe"
            PsDscRunAsCredential = $localAdminCredential
        }
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012,
PowerShell:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1005

```
**Version of the DSC module you're using:**
I use it via Set-AzureRmVmDscExtension in Azure so I guess the version should be 1.8.0.0

**Comment by srinidaram** [comment]
I was able to upgrade servers before farm creation ( tested with SP2016 Farm/Feature Pack 1) using Slipstreaming patches. Extracting the files to updates folder worked for me

Below is a good article on slipstreaming patches in SharePoint
http://www.toddklindt.com/blog/Lists/Posts/Post.aspx?ID=403

**Comment by shurick81** [comment]
Unfortunately, slipstreaming SharePoint 2013 with service pack is not supported as far as I know. It would be great if Microsoft offered slipstreamed media in some public downloads (not on the MSDN and Volume License site), where DSC could download from via xRemoteFile resource.

**Comment by BrianFarnhill** [comment]
@shurick81 Slip-streaming is a supported way of installing updates for a new farm and is absolutely the method we recommend for installing updates for a new farm using SharePointDsc. Todd's blog post there is one of the best I've seen on the topic.

If you are installing SP1 though, there is actual media for that that in all the usual places such as MSDN and the volume licensing portal. As far as I'm aware the current trial downloads that are public are all also SP1 as well. 

Based on all that, I'm going to close this one off and suggest you use the slipstreaming method. If you have any further questions though let us know.

**Comment by ykuijs** [comment]
Pay attention with slipstreaming CUs when using Language Packs. Since a CU is multilingual, you need to install that last when also installing Language Packs. You can use DSC to accomplish this following the procedure mentioned at https://github.com/PowerShell/SharePointDsc/wiki/SPProductUpdate

**Comment by shurick81** [comment]
Thank you colleagues.

Brian, the current trial download is not SP1 slipstreamed as far as I can tell. https://www.microsoft.com/en-us/evalcenter/evaluate-sharepoint-server-2013 page gives me the http://care.dlservice.microsoft.com/dl/download/3/D/7/3D713F30-C316-49B8-9CC0-E1BFC34B63A0/SharePointServer_x64_en-us.img which is not slipstreamed. The only option to download slipstreamed image is using MSDN, volume licensing and other sites that are not the best for using xRemoteFile resource for downloading. For example, as far as I know, the download link from MSDN site is valid for only limited number of hours.

When it comes to slipstreaming, what will be the most correct set of the resources for unpacking content of the service pack and cumulative updates?

**Comment by BrianFarnhill** [comment]
OK so if you are trying to download binaries to a server, can I give you another approach to try? I've got a resource - AzureStorageDsc (in teh dev branch at https://github.com/powershell/xAzureStorage/tree/dev). This will basically download the contents of a blob storage container, so you can set up your own slipstreamed binaries there and have them be downloaded directly to your servers - just as an alternative to the xRemoteFile option. Storing the few GB of file for event a large slipstreamed image would be well and truly under $1 a month in storage, and would be far easier to maintain and then also to update the storage later if you want to include a more up to date slipstreamed package. Would that help address the approach you are taking here?

**Comment by shurick81** [comment]
Hello Brian, that sounds like a good idea. I will use this approach for some scenarios too, thank you.
Anyway, are there good resources for slipstreaming via DSC? For example, is there a way to fire unpacking service pack or cumulative update?

**Comment by BrianFarnhill** [comment]
@shurick81 There isn't a specific resource for it, but you could use a script resource to do this. Use the test method to determine if there are files in the directory you are unpacking to, and then in the set method trigger the command to start the unpacking.

**Comment by shurick81** [comment]
Thank you for your suggestions colleagues.

I will try to use script resource.
I also considering some options outside of the DSC: using AutoSPSourceBuilder or virtual machine images (which might be even more complicated for users then downloading prepared iso-image from Azure Storage).

With regard to downloading slipstreamed image from Azure Storage, I ended up with using cAzureStorage and this worked perfectly. The only inconvenience is that the image should be uploaded there. Strange that MS did not make slipstreamed SP 2013 with SP1 media publicly available and everyone have to find their workarounds.
