### ISSUE TITLE
MSFT_SPContentDatabase - language dependend

### ISSUE THREAD

**Issue by Fwiest** [PowerShell/SharePointDsc#646]
Hello,

me and mariusv-msft currently working on utilizing SharePoint DSC to be used for other OS and SharePoint languages than EN-US.
This works pretty fine.
Within the Ressource MSFT_SPContentDatabase you identify if the content database is there or not on the Type:
Line 41

        $cdb = Get-SPDatabase | Where-Object -FilterScript {

            $_.Type -eq "Content Database" -and $_.Name -eq $params.Name

        }

In other SharePoint languages this type has a different name.
So it tries to Mount the database which is already mounted as it doesnt find it.

This could be avoided when using "Get-SPContentDatabase" as it just gives you content databases and the database name and web app. 
We are using SharePoint DSC 1.8.

Best regards,
Florian

**Comment by BrianFarnhill** [comment]
We had the same thing as this turn up a while back in regards to the service applications - so we can use the same approach to fix it. I'll put it on the backlog.

**Comment by ykuijs** [comment]
Picking this up

**Comment by ykuijs** [comment]
Closed with PR 660
