### ISSUE TITLE
SPServiceAppSecurityEntry Potential Conflict

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#647]
**Details of the scenario you try and problem that is occurring:**
Taking a look at the CIMInstance MSFT_SPServiceAppSecurityEntry defined in the SPServiceAppSecurity Resource's schema, I see that it can only accept certain string values for the AccessLevel property (e.g. Full Control, Write, Read, etc.). However when retrieving the AccessRules manually for my Managed Metadata Service App, the AccessRight, which is the property being used in the resource's Get-TargetResource to retrieve the "AccessLevel" of the members, has numbers instead for some permissions. That throws an error when trying to compile my resource. Here is the extract

PS C:\> Get-SPServiceApplication -Name MMS

DisplayName          TypeName             Id
-----------          --------             --
MMS                  Managed Metadata ... 7d8088dd-d7a1-429a-9678-cadff0885932

PS C:\> Get-SPServiceApplication -Name MMS | Get-SPServiceApplicationSecurity | %{$_.AccessRules | select Name, AllowedRights}

Name                                                                                           AllowedRights
----                                                                                               -------------
c:0%.c|system|1e017e5e-9ebe-4390-8739-2e620c13464e         28672
i:0#.w|hq_dom\sp13_farmadmin                                                 4096

**The DSC configuration that is using the resource:**
$members = @();
        $members += MSFT_SPServiceAppSecurityEntry {
                                Username    = "1e017e5e-9ebe-4390-8739-2e620c13464e";
                                AccessLevel = "28672";
            };
        $members += MSFT_SPServiceAppSecurityEntry {
                                Username    = "hq_dom\sp13_farmadmin";
                                AccessLevel = "4096";
            };
        SPServiceAppSecurity 3cdd53cd-e255-4da4-a380-1db3d9b0381a
        {
            SecurityType = "SharingPermissions";
            ServiceAppName = "MMS";
            PsDscRunAsCredential = $CredsAdministrator;
            Members = $members;
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2
**Version of the DSC module you're using:**
1.8.0.0

**Comment by BrianFarnhill** [comment]
This looks like a duplicate of #585 - if so can we close this one off, if not can you explain how it's different?

**Comment by NikCharlebois** [comment]
Not 100% convinced it is the same thing. In my case, the AccessLevel seems to be a Mask of some king (integers instead of text based). This was off course causing problems for ReverseDSC, and I worked around it by making sure that the Permissions level we extract is not Integer based, so it's your call whether or not you want to close it down and just keep 585.

**Comment by BrianFarnhill** [comment]
@NikCharlebois Given 585 talks about all the specifically named permission levels I'm inclined to run with that - anything more specialised than that I think will fall out of the boundaries of where we go with SharePointDsc. Thanks mate
