### ISSUE TITLE
CodeCov.yml comment

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#648]
**Details of the scenario you try and problem that is occurring:**
Very very minor stuff. The codeCov.yml has a comment saying that we are setting a 70% coverage as our goal, but the target is set to 80%. We should probably align the comment to reflect the actual value or simply remove the comment from there.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
N/A

**Comment by ykuijs** [comment]
Will correct this.

**Comment by ykuijs** [comment]
Closed with PR 660
