### ISSUE TITLE
Error Installing SharePoint 2016 Prerequisites in Offline mode

### ISSUE THREAD

**Issue by srinidaram** [PowerShell/SharePointDsc#649]
**Details of the scenario you try and problem that is occurring:**

PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message:
The prerequisite installer ran with the following unknown exit code 1000

I am trying to install SharePoint 2016 on Windows Server 2016 using DSC Pull Server setup, while installing prerequisites below is the error from DSC verbose output 

VERBOSE: [SP2016APP]:                            [[SPInstallPrereqs]InstallPrereqs] Args for prereq installer are:
/unattended /SQLNCli:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\sqlncli.msi"
/Sync:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\Synchronization.msi"
/AppFabric:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\WindowsServerAppFabricSetup_x64.exe"
/IDFX11:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\MicrosoftIdentityExtensions-64.msi"
/MSIPCClient:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\setup_msipc_x64.msi"
/KB3092423:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\AppFabric-KB3092423-x64-ENU.exe"
/WCFDataServices56:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\WcfDataServices.exe"
/DotNetFx:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\dotNetfx45_Full_setup.exe"
/MSVCRT11:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\vcredist_x64.exe"
/MSVCRT14:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\vc_redist.x64.exe"
/ODBC:"\\DSC\SoftwareShared\SP2016\prerequisiteinstallerfiles\msodbcsql.msi"
VERBOSE: [SP2016APP]: LCM:  [ End    Set      ]  [[SPInstallPrereqs]InstallPrereqs]  in 221.5740 seconds.
PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message:
The prerequisite installer ran with the following unknown exit code 1000
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Just wondering if anyone faced the similar issue and possible workaround for the issue

OS: Windows Server 2016
SP: SharePoint 2016
DSC: SharePointDSC 1.8.0.0

**Comment by BrianFarnhill** [comment]
From memory this error code happens when the prerequisite installer can't install the .NET 3.5 components. You need to use the "SXSPath" property to point to where the directory is that has that installer (from the Windows Installation Media).

To be sure though - you'll find the logs for the installation at C:\windows\temp - sort that folder by date modified and you'll see the most recent installation attempt near the top, so crack open that log file and let us know how you go.

**Comment by srinidaram** [comment]
Thank you Brian. Your solution (SXSPath) worked for me.  

I really appreciate your response.
