### ISSUE TITLE
MSFT_SPUsageApplication not creating UsageLogPath

### ISSUE THREAD

**Issue by ronx** [PowerShell/SharePointDsc#650]
**Details of the scenario you try and problem that is occurring:**

When using the SPUsageApplication resource, if the UsageLogLocation path does not exist, the installation succeeds but the event viewer logs critical errors since the path does not exist. It seems like the Set-SPUsageService cmdlet expects the UsageLogLocation to already exist even though it allows you to set it to a path that does not exist. Perhaps the Set-TargetResource could bridge the gap and try to create the folder if it does not exist? Thoughts?

**The DSC configuration that is using the resource:**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

WS2016, PS 5.1

**Version of the DSC module you're using:**

1.8.0.0

**Comment by ronx** [comment]
On further investigation, it seems that only the first server in the farm, the central admin server, was affected by the missing Usage folder. Has anyone else experienced anything similar? I dealt with a few hiccups during the initial push to "APP01", so there's a chance that the Usage application was initialized enough to pass a Test-TargetResource but not completely provisioned (i.e. folder not created). If no one else has experienced this, maybe we don't worry about it.

Or, another option would be to check for the UsageLogLocation folder in Test-TargetResource. What do you guys think?

**Comment by NikCharlebois** [comment]
Not sure letting the Set function create the folder would be our best approach here. I would tend to recommend throwing an error instead, letting the user know that the path doesn't exist. The user could use the File DSC block in their script to have the folder created beforehand if needs be. That's how it is handled in MSFT_SPDiagnosticLoggingSettings at least.

**Comment by ronx** [comment]
That would be an acceptable solution. However, since the folder was created automatically on 3/4 farm servers, I'm wondering if this was just a fluke or if it might have to do with the first time the service is installed. I'd be curious to know if anyone else has experienced this or might have a lab they could test it in. I'm planning to spin up a new lab in Azure this week, so I'll keep an eye on this one.

If it's just a fluke and the folder is usually created automatically, it wouldn't make sense to throw an error to force the user to manually create the folder. Make sense?

**Comment by BrianFarnhill** [comment]
I agree to let it throw the error if that's what its gonna do - but I'm 99% sure that I've seen it create the path even in my single server environments, so I don't believe there's an issue here. I'll tag this as investigating and let you know when I get time to check it (I'm literally getting married in 4 days so will be at least a week before I get to it!)

**Comment by NikCharlebois** [comment]
Hi @ronx after further investigation, it looks like the folder **does **not**** have to exist for the Usage Service Application to create it. Upon calling the Set-SPUsageService cmdlet in the Set-TargetResource, if the folder does not exist, it will get created the moment new usage log for that server are available. Could you please try to replicate your issue once more, and close the issue if you are not able to? Thanks

**Comment by NikCharlebois** [comment]
@ronx , can we close this one?

**Comment by ronx** [comment]
@NikCharlebois I haven't had a chance to test it. I can go ahead and close it for now and reopen if I run into it again.
