### ISSUE TITLE
MSFT_SPSearchCrawlerImpactRule Error in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#657]
**Details of the scenario you try and problem that is occurring:**
The logic for the Get-TargetResource function of the SPSearchCrawlerImpactRule resource is based around the call to Get-SPEnterpriseSearchSiteHitRule cmdlet. In the code, we are passing it a reference to the Enterprise Search service application, but the cmdlet doesn't accept it. This is for SharePoint 2016. If I run the following two lines:

        $serviceApp = Get-SPEnterpriseSearchServiceApplication -Identity "Search Service Application 1"
        Get-SPEnterpriseSearchSiteHitRule -SearchService $serviceApp

Where $serviceApp is not null, I get the following error thrown back:
Get-SPEnterpriseSearchSiteHitRule : Cannot bind parameter 'SearchService'. Cannot convert the "SearchServiceApplication Name=Search Service Application 1" value of type "Microsoft.Office.Server.Search.Administration.SearchServiceApplication" to type "Microsoft.Office.Server.Search.Cmdlet.SearchServicePipeBind".

When you go and add a new Crawler Impact Rule via the interface, you are brought to a generic administrative page that does not seem to be associated with a specific Search Service Application instance. Also, if you just run Get-SPEnterpriseSearchSiteHitRule | fl * it doesn't seem like the instances returned are associated with an SSA instance either. I don't believe the Get-TargetResource should be using the -SearchService....or at least that we are using it right.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 5.1 / SP2016

**Version of the DSC module you're using:**
1.9.0.0

**Comment by ykuijs** [comment]
Just tested this on SP2013 and SP2016. The service app name is required for the SearchService parameter, not the object itself. Will fix this in my Bugfix PR

**Comment by ykuijs** [comment]
Closed via PR #734
