### ISSUE TITLE
SPFarm errors with "the user does not exist or is not unique"

### ISSUE THREAD

**Issue by mattcowen** [PowerShell/SharePointDsc#659]
Creating Sharepoint 2016 single server farm on Azure using DSC extension. 

SPFarm fails with "The user does not exist or is not unique." as the first error. See attached log.

Trying to install on Windows Server 2016 using PowerShell 5. SQL Server 2014. SharePointDSC v1.8.

I have attached the logs for one of the jobs. I am deleting the admin and config databases each time i try and run this since they do get created with schema and data present.

The SpSetup user or "mydomain\spsetup" exists as does "mydomain\spfarm". SpSetup is both a local admin as well as a sysadmin in SQL Server and a domain admin.

SPFarm CreateSPFarm
        {
            Ensure = "Present"
            DatabaseServer           = "sql"
            AdminContentDatabaseName = "SP_AdminContent"
            FarmConfigDatabaseName   = "SP_Config"
            Passphrase               = $Passphrase
            FarmAccount              = $SharePointFarmAccountcreds
            PsDscRunAsCredential     = $SharePointSetupUserAccountcreds
			ServerRole               = "Application"
            RunCentralAdmin          = $true
            DependsOn                = "[SPInstall]InstallSharePoint"
		}

[spfarm-error.txt](https://github.com/PowerShell/SharePointDsc/files/1356113/spfarm-error.txt)

**Comment by mattcowen** [comment]
Actually there is a difference in the error if I run the configuration on the VM directly. In this case I get an error....
VERBOSE: [sharePoint]:                            [[SPFarm]CreateSPFarm] Now joining to farm at server sql database SP_Config
Value cannot be null.
Parameter name: service
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase
    + PSComputerName        : localhost
 
VERBOSE: [sharePoint]:                            [[SPFarm]CreateSPFarm] Leaving ProcessRecord Method of Connect-SPConfigurationDatabase.
VERBOSE: [sharePoint]:                            [[SPFarm]CreateSPFarm] Leaving EndProcessing Method of Connect-SPConfigurationDatabase.
VERBOSE: [sharePoint]:                            [[SPFarm]CreateSPFarm] Leaving BeginProcessing Method of Install-SPHelpCollection.
VERBOSE: [sharePoint]: LCM:  [ End    Set      ]  [[SPFarm]CreateSPFarm]  in 19.5360 seconds.
PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Cannot access the local farm. Verify that the local farm is properly 
configured, currently available, and that you have the appropriate permissions to access the database before trying again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [sharePoint]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

**Comment by ykuijs** [comment]
The issue occurs in the New-SPConfigurationDatabase cmdlet, so this isn't DSC related. Can you please test what happens when you run that cmdlet locally.

Also: Search for "New-SPConfigurationDatabase The user does not exist or is not unique" and you will find a lot of hits about the same error. Most solutions say you have to use "MACHINENAME\FarmAccount" instead of "DOMAINNAME\FarmAccount,", but I am not sure if this will work in combination with SharePointDSC

**Comment by mattcowen** [comment]
I ran the following script via the Sharepoint Management shell logged in as SpSetup and it created and joined the farm with no problem. This would appear to point to a problem in these DSC modules.

New-SPConfigurationDatabase -DatabaseName SP_Config -DatabaseServer sql -LocalServerRole SingleServerFarm -AdministrationContentDatabaseName SP_AdminContent -FarmCredentials $FarmAccount -Passphrase $passphrase.Password -Verbose

Does anyone have any thoughts about how I can resolve this please?

**Comment by NikCharlebois** [comment]
@mattcowen based on the logs, I see:
               [[SPFarm]CreateSPFarm] Executing as the local run as user HOUSEKEEPER\\SpSetup"}
which will cause the error you are seeing for sure. Make sure that this guy ($SharePointSetupUserAccountcreds) is a domain account

**Comment by mattcowen** [comment]
@NikCharlebois sorry for the delay. I dont fully understand...$SharePointSetupUserAccountcreds is a domain account AND a local administrator on the server. Is this correct?

**Comment by mattcowen** [comment]
@NikCharlebois $SharePointSetupUserAccountcreds is a domain account and that user is also a local admin. I'm not sure why this user (housekeeper\spsetup) is causing this error

**Comment by NikCharlebois** [comment]
@mattcowen that spsetup account has access to the DB? Are the databases (admin and config) getting created if you check with SQL Server Management Studio?

**Comment by mattcowen** [comment]
Yes databases are created, populated and the user account has access. I
have to delete them each time I run the Dsc configuration.

On 23 Oct 2017 9:22 p.m., "Nik Charlebois" <notifications@github.com> wrote:

@mattcowen <https://github.com/mattcowen> that spsetup account has access
to the DB? Are the databases (admin and config) getting created if you
check with SQL Server Management Studio?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PowerShell/SharePointDsc/issues/659#issuecomment-338784858>,
or mute the thread

**Comment by NikCharlebois** [comment]
@mattcowen Any chances you can post your complete DSC config along with any ConfigurationData?

**Comment by mattcowen** [comment]
The DSC configuration is here...
[sharepointconfig.txt](https://github.com/PowerShell/SharePointDsc/files/1409812/sharepointconfig.txt)

And I run this using...

$thumb = "xx"


$configData =@{
    AllNodes = @(
        @{
            NodeName = "localhost";
			PSDscAllowDomainUser = $true;
			RebootNodeIfNeeded = $true;
			ActionAfterReboot = "ContinueConfiguration";
            #PsDscAllowPlainTextPassword = $true
            Thumbprint = $thumb
            CertificateFile = "C:\cert.cer"
         }
    );

}


$paramHash = 
@{ 
    configurationData = $configData
    DomainName = "housekeeper.local"
	primaryAdIpAddress = "14.1.1.4"
    AdminCreds = (Get-Credential -Message "Domain Admin user" -UserName "azureuser")
	SharePointSetupUserAccountcreds = (Get-Credential -Message "Sharepoint Setup creds" -UserName "SpSetup")
	SharePointFarmAccountcreds = (Get-Credential -Message "Sharepoint Farm creds" -UserName "SpFarm")
	Passphrase = (Get-Credential -Message "Sharepoint Farm passphrase creds" -UserName "ignore")
	DatabaseName = "SP_Content"
	DatabaseServer = "sql"
	InstallSourceDrive = "F:"
	InstallSourceFolderName = "installer" # ignored atm
	ProductKey = "xx"
	SPDLLink = "https://.....an.iso"


}

PrepareSharepoint @paramHash -Verbose

$creds = Get-Credential housekeeper\azureuser

Start-DscConfiguration -ComputerName localhost -Credential $creds -Path .\PrepareSharepoint -Verbose -Wait -Force

I really appreciate your help with this. Thank you.

**Comment by mattcowen** [comment]
Has there been any chance to look at this please? I'd appreciate any work arounds.

Thanks
Matt

**Comment by andikrueger** [comment]
Hi @mattcowen,
afais you are not specifying the domain name. I had some issues when i did not pass the domain name into the credential object. Have you tried to to add the domain name to your SharePointSetupUserAccountcreds and does this make a difference?
```
Get-Credential -Message "SharePoint Setup creds" -UserName "houskeeper\spsetup"
```
The same applies for the farm and your other accounts. Hope it helps.

**Comment by mattcowen** [comment]
Hi @andikrueger, 

I have tried both with and without the domain. If I switch to the SharePoint Shell and run the New-SPConfigurationDatabase cmdlet with the same creds that fail in DSC it does work.

**Comment by BrianFarnhill** [comment]
@mattcowen Can you have a look in the ULS logs to see if they shine any light on this? Realistically the SharePointDsc modules do nothing more than calling the cmdlets the same as you have done, so it is extremely rare to see a time that the cmdlet works when running in a PowerShell session as the user that DSC is trying to do it in. If we can see where exactly the ULS is up to when the command fails that might help us figure out what is different about it executing in the DSC run time that in a normal PowerShell session.

Another couple of things to try so we can isolate where this is happening is to call the resource directly. If you can open a PowerShell window as $SharePointSetupUserAccountcreds and then try each of these:

1. Use [Invoke-DSCResource](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/invoke-dscresource?view=powershell-5.1) to call the resource directly from there
2. Import the module directly and execute it:

    Import-Module "[Path to SharePointDsc]\DscResources\MSFT_SPFarm\MSFT_SPFarm.ps1"
    Set-TargetResources @YourParamsHere

Lastly, some other questions to help me understand the environment a bit more:

1. Does the Netbios name of the domain match whats in the FQDN (e.g. if your FQDN is domain.local is the Netbios name "Domain" or is it something else?)
2. Is the computer name that you are running this on longer than 15 characters?
3. Are there any group policies applied to this machine that will impact on the ability to impersonate accounts or restrict network access in any way (specifically relating to resolution of assets from AD)?

Let us know how you go with those and we'll see what we can figure out for next steps.

**Comment by mattcowen** [comment]
@BrianFarnhill Here are the ULS logs for an ARM initiated configuration the first time it runs...

Begin trace logging for SharePoint Products and Technologies PowerShell.  Version 16.0.4345.1000
11/13/2017 18:38:22  4  INF  Entering function SPCmdletNewSPConfigurationDatabase.InternalProcessRecord
11/13/2017 18:38:22  4  INF    Creating connection string for config db SP_Config server sql
11/13/2017 18:38:22  4  INF    Creating connection string for admin content db SP_AdminContent server sql
11/13/2017 18:38:22  4  INF    Using NTLM for sql connection string
11/13/2017 18:38:22  4  INF    Creating a new farm with config db SP_Config content db SP_AdminContent server sql for farm mode
11/13/2017 18:40:32  4  WRN    Not performing security registration because this server is not joined to a farm
11/13/2017 18:41:24  4  INF    Entering function SPCmdletNewSPCentralAdministration.InternalProcessRecord
11/13/2017 18:41:24  4  ERR      You are not joined with a farm.  You have to be joined first

When I use Invoke-DSCResource to the call the resource directly e.g.

$paramHash = 
@{ 
    
    Ensure                   = "Present"
    DatabaseServer           = "sql"
    AdminContentDatabaseName = "SP_AdminContent"
    FarmConfigDatabaseName   = "SP_Config"
    Passphrase               = (Get-Credential -Message "Sharepoint Farm passphrase creds" -UserName "ignore")
    FarmAccount              = (Get-Credential -Message "Sharepoint Farm creds" -UserName "SpFarm")
    PsDscRunAsCredential     = (Get-Credential -Message "Sharepoint Setup creds" -UserName "SpSetup")
	ServerRole               = "SingleServerFarm"
    RunCentralAdmin          = $true
}

Invoke-DscResource -Name SPFarm -Method Test -Property $paramHash -ModuleName SharePointDSC
Invoke-DscResource -Name SPFarm -Method Set -Property $paramHash -ModuleName SharePointDSC
Invoke-DscResource -Name SPFarm -Method Get -Property $paramHash -ModuleName SharePointDSC

I get the same errors logged....

1. This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_SPFarm DSC resource. FullyQualifiedErrorId is Microsoft.SharePoint.PowerShell.SPCmdletNewSPConfigurationDatabase. Error Message is The user does not exist or is not unique..
2. This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_SPFarm DSC resource. FullyQualifiedErrorId is Microsoft.SharePoint.PowerShell.SPCmdletNewSPConfigurationDatabase. Error Message is The user does not exist or is not unique..
3. This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_SPFarm DSC resource. FullyQualifiedErrorId is Microsoft.SharePoint.PowerShell.SPCmdletInstallSPHelpCollection. Error Message is Object reference not set to an instance of an object..
4. Error Message: Object reference not set to an instance of an object.
Message ID: Microsoft.SharePoint.PowerShell.SPCmdletInstallSPHelpCollection
5. This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_SPFarm DSC resource. FullyQualifiedErrorId is Microsoft.SharePoint.PowerShell.SPCmdletInitializeSPResourceSecurity. Error Message is Cannot perform security configuration because the configuration database does not exist.  You must create or join to a configuration database before doing security configuration..

To answer your other questions.

1. It does match. HOUSEKEEPER is the NetBIOS name and housekeeper.local the fqdn
2. No, the server name is "sharepoint".
3. Nothing has been configured beyond a "default" AD installation.

I can make my Visual Studio solution available to you if you want to try deploying this yourself.

Thanks
Matt

**Comment by mattcowen** [comment]
When I try the import-module I get an error and not sure what I need to do to sort it.

PS C:\Users\SpSetup> Import-Module "C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\DSCResources\MSFT_SPFarm\MSFT_SPFarm.psm1"
Set-TargetResource @paramHash

Set-TargetResource : A parameter cannot be found that matches parameter name 'PsDscRunAsCredential'.

**Comment by ykuijs** [comment]
Update your ParamHash and removing the PsDscRunAsCredential parameter. That is a DSC parameter, but is unknown to the Set-TargetResource function.

Then try again

**Comment by mattcowen** [comment]
Thanks, was a long day. Here are the results of the import-module which failed with the same errors. 

PS C:\Windows\system32> $paramHash = 
@{ 
    
    Ensure                   = "Present"
    DatabaseServer           = "sql"
    AdminContentDatabaseName = "SP_AdminContent"
    FarmConfigDatabaseName   = "SP_Config"
    Passphrase               = (Get-Credential -Message "Sharepoint Farm passphrase creds" -UserName "ignore")
    FarmAccount              = (Get-Credential -Message "Sharepoint Farm creds" -UserName "SpFarm")
    #PsDscRunAsCredential     = (Get-Credential -Message "Sharepoint Setup creds" -UserName "SpSetup")
	ServerRole               = "SingleServerFarm"
    RunCentralAdmin          = $true
}


Import-Module "C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\DSCResources\MSFT_SPFarm\MSFT_SPFarm.psm1"
Set-TargetResource @paramHash
VERBOSE: Executing as the local run as user HKPR\SpSetup
The local farm is not accessible. Cmdlets with FeatureDependencyId are not registered.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\SharePoi
ntDSC\Modules\SharePointDsc.Farm\SPFarm.psm1'.
VERBOSE: Exporting function 'Get-SPDSCConfigDBStatus'.
VERBOSE: Exporting function 'Add-SPDSCConfigDBLock'.
VERBOSE: Exporting function 'Remove-SPDSCConfigDBLock'.
VERBOSE: Importing function 'Add-SPDSCConfigDBLock'.
VERBOSE: Importing function 'Get-SPDSCConfigDBStatus'.
VERBOSE: Importing function 'Remove-SPDSCConfigDBLock'.
VERBOSE: Detected Version: SharePoint 2016 - configuring server as SingleServerFarm
VERBOSE: The SharePoint config database 'SP_Config' does not exist, so this server wil
l create the farm.
VERBOSE: Leaving BeginProcessing Method of New-SPConfigurationDatabase.
VERBOSE: Entering function SPCmdletNewSPConfigurationDatabase.InternalProcessRecord
VERBOSE: Creating connection string for config db SP_Config server sql
VERBOSE: Creating connection string for admin content db SP_AdminContent server sql
VERBOSE: Using NTLM for sql connection string
VERBOSE: Creating a new farm with config db SP_Config content db SP_AdminContent serve
r sql for farm mode
New-SPConfigurationDatabase : The user does not exist or is not unique.
At line:145 char:17
+                 New-SPConfigurationDatabase @executeArgs
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:SPCmdl 
   etNewSPConfigurationDatabase) [New-SPConfigurationDatabase], SPException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSPConfigura 
   tionDatabase
 
VERBOSE: Leaving ProcessRecord Method of New-SPConfigurationDatabase.
VERBOSE: Leaving EndProcessing Method of New-SPConfigurationDatabase.
VERBOSE: Leaving BeginProcessing Method of Install-SPHelpCollection.
Install-SPHelpCollection : Object reference not set to an instance of an object.
At line:157 char:9
+         Install-SPHelpCollection -All | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...PHelpCollection:SPCmdl 
   etInstallSPHelpCollection) [Install-SPHelpCollection], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletInstallSPHelpC 
   ollection
 
VERBOSE: Leaving ProcessRecord Method of Install-SPHelpCollection.
VERBOSE: Leaving EndProcessing Method of Install-SPHelpCollection.
VERBOSE: Leaving BeginProcessing Method of Initialize-SPResourceSecurity.
WARNING: Not performing security registration because this server is not joined to a f
arm
Initialize-SPResourceSecurity : Cannot perform security configuration because the 
configuration database does not exist.  You must create or join to a configuration 
database before doing security configuration.
At line:158 char:9
+         Initialize-SPResourceSecurity | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...esourceSecurity:SPCmdl 
   etInitializeSPResourceSecurity) [Initialize-SPResourceSecurity], SPException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletInitializeSPRe 
   sourceSecurity
 
VERBOSE: Leaving ProcessRecord Method of Initialize-SPResourceSecurity.
VERBOSE: Leaving EndProcessing Method of Initialize-SPResourceSecurity.
VERBOSE: Leaving BeginProcessing Method of Install-SPService.
VERBOSE: Successfully installed service: Microsoft.Ceres.Diagnostics.Administration.Di
agnosticsService.
VERBOSE: Successfully installed service: Access Services 2010.
Install-SPService : Exception has been thrown by the target of an invocation.
At line:159 char:9
+         Install-SPService | Out-Null
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...tInstallService:SPCmdl 
   etInstallService) [Install-SPService], TargetInvocationException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletInstallService
 
VERBOSE: Leaving ProcessRecord Method of Install-SPService.
VERBOSE: Leaving EndProcessing Method of Install-SPService.
VERBOSE: Leaving BeginProcessing Method of Install-SPFeature.
....deleted for brevity

**Comment by mattcowen** [comment]
In the ULS logs I see dozens of rows generated like this...

Querying the DB for Name:[] of 2033e2da-e8a0-4ca9-8ab7-6d1ee09b600e with type:Microsoft.SharePoint.Administration.SPUsageManager <GUID ID>

**Comment by mattcowen** [comment]
I see this Stack Trace in the ULS logs

Microsoft.SharePoint.SPException: The user does not exist or is not unique. ---> 
System.Runtime.InteropServices.COMException: The user does not exist or is not unique.     
at Microsoft.SharePoint.Library.SPRequestInternalClass.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolean bRemoveFromCurrentScopeOnly, Boolean bSendEmail)     
at Microsoft.SharePoint.Library.SPRequest.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolea...	ed5a319e-36dd-7025-5197-e93a05dbb3ffn bRemoveFromCurrentScopeOnly, Boolean bSendEmail)     
--- End of inner exception stack trace ---     
at Microsoft.SharePoint.SPGlobal.HandleComException(COMException comEx)     
at Microsoft.SharePoint.Library.SPRequest.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolean bRemoveFromCurrentScopeOnly, Boolean bSendEmail)     
at Microsoft.SharePoint.SPUserCollection.UpdateMembers(Object objUpdateInfo, Object objAddIds, Object objRemoveLogins, Object objRemoveIds, Boolean fSendEmail)     
at Microsoft.SharePoint.SPUserCollection.AddCollection(SPUserInfo[] addUsersInfo, IEnumerable`1 addUsers)     
at Microsoft....	ed5a319e-36dd-7025-5197-e93a05dbb3ffSharePoint.SPUserCollection.Add(String loginName, String email, String name, String notes)     
at Microsoft.SharePoint.Administration.SPAdministrationWebApplication.CreateAdministratorsGroup(SPSite site, String farmUser)     
at Microsoft.SharePoint.Administration.SPAdministrationWebApplication.CreateDefaultInstance(SqlConnectionStringBuilder administrationContentDatabase, SPWebService adminService, IdentityType identityType, String farmUser, SecureString farmPassword)     at Microsoft.SharePoint.Administration.SPFarmFactory.CreateAdministrationWebService(SPFarm farm, SqlConnectionStringBuilder administrationContentDatabase, IdentityType identityType, String farmUser, SecureString farmPassword)     
at Microsoft.SharePoint.Administration.SPFarmFactory.CreateBasicServices(SPFarm farm)     
at ...	ed5a319e-36dd-7025-5197-e93a05dbb3ffMicrosoft.SharePoint.Administration.SPFarmFactory.Create()     
at Microsoft.SharePoint.Administration.SPFarm.Create(SqlConnectionStringBuilder configurationDatabase, SqlConnectionStringBuilder administrationContentDatabase, SqlConnectionStringBuilder siteMapDatabase, IdentityType identityType, String farmUser, SecureString farmPassword, SecureString masterPassphrase)     
at Microsoft.SharePoint.PowerShell.SPCmdletNewSPConfigurationDatabase.InternalProcessRecord()     
at Microsoft.SharePoint.PowerShell.SPCmdlet.ProcessRecord()	ed5a319e-36dd-7025-5197-e93a05dbb3ff

**Comment by mattcowen** [comment]
@BrianFarnhill do you know what might be causing this COM exception?

**Comment by BrianFarnhill** [comment]
@mattcowen Nothing more than the suggestions we have already made. From what I understand that is to do with an inbuilt lookup within the commands that are setting up the new databases that runs to validate a user before it uses it to initialise the config DBs, this is pretty down in the depths of the source code of SharePoint itself, and well beyond the scope of our DSC resources, which as best I can see are calling the cmdlet correctly.

You said you could shoot me your visual studio solution - send it over to me (brian.farnhill@microsoft.com) and I'll see if anything jumps out at me, but I see nothing related to the DSC modules that should be causing this to fail at this point. I should get some time this week to look at your solution and try to run it, but at this point I'll also give the reminder that support of this module thats done through GitHub like this (as opposed to through a premier support case) is on a best effort basis - just to set expectations on this one since I still have a day job to do outside of this :)

**Comment by mattcowen** [comment]
@BrianFarnhill yes I saw the COM exception and decided to back away and think of alternatives :)

I have implemented a work around with a Script resource which was surprisingly painless. 

Script CreateSPFarm
        {
            SetScript =
            {
				$passphrase = ConvertTo-SecureString -String 'sharepoint' -AsPlainText -Force
				$farmParams = @{
					DatabaseServer = "sql"
					DatabaseName = "SP_Config"
					AdminDatabaseName = "SP_AdminContent"
					FarmAccount = $using:FarmAccount.UserName
					CentralAdminPort = "2016"
					CentralAdminAuthProvider = "NTLM"
					ManagedAccounts = @("SpServicePool","SpWebPool")
					FarmCredentials = $using:FarmAccount
					Passphrase = $passphrase
				}

				Invoke-SPDSCCommand -Credential $null -Arguments $farmParams -ScriptBlock  {
					$params = $args[0]

					New-SPConfigurationDatabase -LocalServerRole SingleServerFarm `
                            -DatabaseName $params.DatabaseName `
                            -DatabaseServer $params.DatabaseServer `
                            -FarmCredentials $params.FarmCredentials `
                            -Passphrase  $params.Passphrase `
                            -AdministrationContentDatabaseName $params.AdminDatabaseName

					Write-Output "Creating SharePoint Central Administration web application..."
					New-SPCentralAdministration -Port $params.CentralAdminPort -WindowsAuthProvider $params.CentralAdminAuthProvider

					Write-Output "Installing SharePoint help collection..."
					Install-SPHelpCollection -All

					Write-Output "Initializing local resource security..."
					Initialize-SPResourceSecurity

					Write-Output "Installing SharePoint services..."
					Install-SPService

					Write-Output "Installing SharePoint features..."
					Install-SPFeature -AllExistingFeatures | Out-Null

					Write-Output "Installing SharePoint application content..."
					Install-SPApplicationContent
					
					Write-Output "Configuring security token service..."
					$Sts = Get-SPSecurityTokenServiceConfig
					$Sts.AllowOAuthOverHttp = $true
					$Sts.Update()
				}
            }
            GetScript =  { @{} }
            TestScript = { $false }
			PsDscRunAsCredential = $SPSetupAccount
            DependsOn = "[SPInstall]InstallSharePoint"
        }

**Comment by BrianFarnhill** [comment]
@mattcowen ok so that is blowing my mind since we do almost the exact same thing in our code - we use Invoke-SPDscCommand and run the same cmdlets. I have no explanation why that works and our normal resource doesn't. Do you have any other issues with other SharePointDsc resources?

Also - make sure you take this resource out after its run once - the test method will cause this to be run every time you execute your config, which will throw errors after it is run once.

Lastly, as you have a workaround, I'm thinking that we can close this one off. Any issues with that?

**Comment by ykuijs** [comment]
Hi @mattcowen, one question:
In the configuration you shared earlier, you said you did the following:

Passphrase               = (Get-Credential -Message "Sharepoint Farm passphrase creds" -UserName "ignore")
FarmAccount              = (Get-Credential -Message "Sharepoint Farm creds" -UserName "SpFarm")
#PsDscRunAsCredential     = (Get-Credential -Message "Sharepoint Setup creds" -UserName "SpSetup")

The Username in this config is specified without domain (SpFarm). Are you 100% sure you used the account in domain\username format?

**Comment by mattcowen** [comment]
I'm sure I tested this but I made some changes and ran it again successfully. What is confusing is that I have passed in the user account into the DSC configuration as just "SpFarm". I then follow what I see in the various quickstart templates and reconstruct credentials in another variable in the form "<domainnetbiosname>\SpFarm". I'm sure I tested both username formats by simply switching variables however what I was also doing is creating SpReader and SpAdmin AD users earlier in the config where I set the username directly but used the FarmAccount credentials as the password for the user. I just changed this so that I construct both SpReader and SpAdmin with their own creds and it now works. It may be unrelated but I thought I would mention all the changes made to my configuration now that it works.

Thank you all for the help, much appreciated.

**Comment by ykuijs** [comment]
Good to hear and thanks for the update!

**Comment by VerdonTrigance** [comment]
@mattcowen I faced with same problem. But I didn't understand what did you mean. 
I run command manually and it works, but not from DSC.
@ykuijs it related to issue #1075  I use PsDscRunAsCredential, not InstallAccount. I guess 
```
Write-Verbose -Message "Server not part of farm, creating or joining farm"

        $actionResult = Invoke-SPDscCommand -Credential $InstallAccount `
            -Arguments @($PSBoundParameters, $MyInvocation.MyCommand.Source, $PSScriptRoot) `
            -ScriptBlock {
            $params = $args[0]
            $eventSource = $args[1]
            $scriptRoot = $args[2]
```
from SPFarm resource may be connected to what happened.

**Comment by ykuijs** [comment]
Update from the other issue:
Make sure you always specify all accounts in Domain\User format. This issue can be caused by the fact that you don't.
