### ISSUE TITLE
Update SPInstall doco to mention support of only English ISOs

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#665]
**Details of the scenario you try and problem that is occurring:**
In some cases customers insist on a SharePoint base installation language other than English. If this is the case, SPServiceAppSecurity will fail, because the access levels are translated into German, French or whatever language ISO is used. 

For example:
"Full control" is "Vollzugriff" in German. Therefore adding a User with Full Control on a German SharePoint installation will fail.

I see two possible options:
1. Point out, that non English SharePoint ISOs are not supported by SharePointDSC. 
2. For other installation languages than English an extended handling/dictionary in the resource should be added.

There is a very detailed discussion on this topic related to [AutoSPInstaller](http://autospinstaller.codeplex.com/discussions/265749). I think they went with option 1.

**Comment by ykuijs** [comment]
We already have implemented several solutions to make the different resources as language independant as possible. Since it is one hell of a job to inventory all possible values for all languages, I would prefer to go for option 1 as well.

**Comment by BrianFarnhill** [comment]
I agree with @ykuijs on this one as well - we don't have the manpower and expertise across multiple languages to make this one work. I just updated the wiki, but let's leave this one open until we can commit a change in that adds to the doco of SPInstall to calls it out clearly there as well.

**Comment by ykuijs** [comment]
I will include this in my next PR

**Comment by ykuijs** [comment]
Fixed in PR #680
