### ISSUE TITLE
VSCode Workspace settings to meet DSC coding guidelines

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#668]
**Details of the scenario you try and problem that is occurring:**
When using VSCode with the current settings the DSC coding guidelines will not be met. e.g.
1. Curly braces are on the same line
2. A new line at the end of a file is not enforced
3. Tailing whitespaces are not removed

In the [DSCResource repo](https://github.com/PowerShell/DscResources/issues/284) issue is a long discussion about this topic and I really think that SharePointDSC should have these settings included.

(Currently) the complete list of seetings is [here](https://github.com/PowerShell/DscResources/issues/284#issuecomment-312453403)

**Comment by ykuijs** [comment]
I agree with this issue. @BrianFarnhill, what do you think?

**Comment by ykuijs** [comment]
Will be added in my next PR

**Comment by ykuijs** [comment]
Fixed in PR #680
