### ISSUE TITLE
Add solution for the MaxEnvelopeSize issue to the wiki

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#670]
**Details of the scenario you try and problem that is occurring:**
When working with large SharePointDsc configurations, you often hit the MaxEnvelopeSize issue. Shouldn't we add some information to the Wiki on what to do when you experience this issue?

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
All

**Version of the DSC module you're using:**
1.9.0.0

**Comment by BrianFarnhill** [comment]
We should - you wanna write it up? :)

**Comment by ykuijs** [comment]
v1, any comments?

**Error: “Exceeded the configured MaxEnvelopeSize quota”**

When deploying DSC configurations, you may run into the following issue when executing Start-DscConfiguration:

> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
> The WinRM client sent a request to the remote WS-Management service and was notified that the request size exceeded the configured MaxEnvelopeSize quota.
>     + CategoryInfo          : LimitsExceeded: [root/Microsoft/...gurationManager:String] [], CimException
>     + FullyQualifiedErrorId : HRESULT 0x80338111
>     + PSComputerName        : [servername]
>  
> VERBOSE: Operation 'Invoke CimMethod' complete.
> VERBOSE: Time taken for configuration job to complete is 0.648 seconds
> 

The solution for this issue is to increase the maximum envelope size, by running the following command in an elevated PowerShell session:
`Set-Item -Path WSMan:\localhost\MaxEnvelopeSizeKb -Value 2048`

**Note:** The default value is MaxEnvelopeSizeKB is 500

**Note 2:** When your computer is configured to use the Public network profile, the Set-Item cmdlet might throw the following error:

> Set-Item : WinRM firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or 
Private and try again.

Change the network profile to Domain or Private in order to change the setting.

More information about the MaxEnvelopeSize can be found at:
- https://msdn.microsoft.com/en-us/library/cc251449.aspx
- https://msdn.microsoft.com/en-us/library/aa384372%28VS.85%29.aspx

**Comment by ykuijs** [comment]
Created a first draft Wiki article: https://github.com/PowerShell/SharePointDsc/wiki/Error-“Exceeded-the-configured-MaxEnvelopeSize-quota”

**Comment by ykuijs** [comment]
Added a Known Issues section to the startpage of the Wiki and added this page to the list: https://github.com/PowerShell/SharePointDsc/wiki/Error-Exceeded-the-configured-MaxEnvelopeSize-quota

(URL is different than above, had to remove the special characters because Markdown didn't like them when linking to it)
