### ISSUE TITLE
MSFT_SPWebAppGeneralSettings - Need ability to set default quota when self-service creation is enabled

### ISSUE THREAD

**Issue by wfeaser** [PowerShell/SharePointDsc#675]
The MSFT_SPWebAppGeneralSettings resource allows self-service site creation to be enabled, but does not provide the ability to set a default quota template.

Release-1.9 and Preview-2.0 branches have been reviewed and neither provide the option to specify a default quota template with self-service site creation.

Issue discovered on a SP2013 / Windows Server 2012 R2 infrastructure.

**Comment by BrianFarnhill** [comment]
Thanks @wfeaser - we'll put this on to the backlog to see if we can get someone to code up this enhancement.

**Comment by ykuijs** [comment]
@wfeaser I think this is a duplicate with #507. I have implemented a fix for that issue in my next PR

**Comment by ykuijs** [comment]
Fixed in PR #680
