### ISSUE TITLE
Resource SPWebApplicationExtension uses wrong object to return property AllowAnonymous in hashtable returned by Get-TargetResource

### ISSUE THREAD

**Issue by Yvand** [PowerShell/SharePointDsc#676]
Get-TargetResource returns property AllowAnonymous like this:
```powershell
return @{
	[...]
	AllowAnonymous = $authProvider.AllowAnonymous
	[...]
}
```
But property AllowAnonymous does not exist in $authProvider, it should use $waExt instead:
```powershell
return @{
	[...]
	AllowAnonymous = $waExt.AllowAnonymous
	[...]
}
```

As a consequence, Test-TargetResource always returns $false, which in turns causes LCM to always call Set-TargetResource, even if everythying is already fine.
And Set-TargetResource takes a while to run, it's a waste of time.

I submitted PR #677 to fix this.

**Comment by ykuijs** [comment]
Closed via PR 677
