### ISSUE TITLE
SPSearchTopology creates new topology at every check

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#683]
**Details of the scenario you try and problem that is occurring:**
If a SPSearchTopology is extended using SPSearchIndexPartition the SPSearchTopology test always returns false and a new topology is created.

Easy fix is to remove the "IndexPartition" line in ValuesToCheck switch of Test-SPDSCParameterState. The number of IndexPartition is larger than in the definition of this resource and therefore the test fails unless only the partitions in SPSearchTopology are used.

**The DSC configuration that is using the resource:**
                    SPSearchTopology SearchTopology
                    {
                        ServiceAppName          = $SearchServiceApplicationName
                        Admin                   = $SearchTopologySettings.Admin
                        Crawler                 = $SearchTopologySettings.Crawler
                        ContentProcessing       = $SearchTopologySettings.ContentProcessing
                        AnalyticsProcessing     = $SearchTopologySettings.AnalyticsProcessing
                        QueryProcessing         = $SearchTopologySettings.QueryProcessing
                        FirstPartitionDirectory = ($IndexLocation + $SearchTopologySettings.Index)
                        IndexPartition          = $SearchTopologySettings.IndexServerGroup
                        PsDscRunAsCredential    = $SetupAccount
                        DependsOn            = "[SPSearchServiceApp]SearchServiceApp"
                    }
					foreach ($IndexPartition in $SearchConfig.SearchIndexPartitions) {
						$internalPartitionName = "IndexPartition_$($IndexPartition.Index)"
						SPSearchIndexPartition $internalPartitionName {
	                        Servers              = $IndexPartition.IndexServerGroup
	                        Index                = $IndexPartition.Index
	                        RootDirectory        = ($IndexLocation + $IndexPartition.Index)
	                        ServiceAppName       = $SearchServiceApplicationName
	                        PsDscRunAsCredential = $SetupAccount
	                        DependsOn            = "[SPSearchServiceApp]SearchServiceApp"
						}
					}

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2 with PowerShell 5.1

**Version of the DSC module you're using:**
1.8

**Comment by ykuijs** [comment]
Not sure if removing the Index Partition parameter from the test is the solution here. What if you want to change the number of servers running the index partition in a situation where you only have one index partition?

Would it be an alternative to have the Get-TargetResource only return the items for Index Partition 0?

**Comment by typozh** [comment]
you are right it would be better to just check index partition 0 as this partition is always managed in this resource and higher index partitions are not.

**Comment by ykuijs** [comment]
Great! Will see if I can get this into our v2.0 release which is coming up!

**Comment by ykuijs** [comment]
Fixes implemented in PR #695
