### ISSUE TITLE
SPFarm not accepting Passphrase

### ISSUE THREAD

**Issue by whytoe** [PowerShell/SharePointDsc#686]
**Details of the scenario you try and problem that is occurring:**
Write-NodeMOFFile : Invalid MOF definition for node 'SP13RGP20': Exception calling "ValidateInstanceText" with "1" argument(s): "Convert property 'Passphrase' value from type 'STRING' to type 'INSTANCE' 
failed

**The DSC configuration that is using the resource:**
            SPFarm SharePointFarm
            {
                Ensure                    = "Present"
                DatabaseServer            = "SQLServer\MSSQLSERVER"
                FarmConfigDatabaseName    = "SP_Config"
                AdminContentDatabaseName  = "SP_AdminContent"
                CentralAdministrationPort = 5000
                CentralAdministrationAuth = "Kerberos"
                Passphrase                = "Jointhefarm"
                FarmAccount               = $farmcred
                RunCentralAdmin           = $true
                PsDscRunAsCredential      = $farmcred
            }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Powershell - 5.1
Windows 10

**Version of the DSC module you're using:**
1.9.0.0

**The Documentation says the Passphrase is a String but in the examples it is a PSCredential Object. Which one is it and can you fix the documentation?**

**Comment by NikCharlebois** [comment]
@whytoe The passphrase parameter needs to be of type PSCredential. Try:

SPFarm SharePointFarm
{
Ensure = "Present"
DatabaseServer = "SQLServer\MSSQLSERVER"
FarmConfigDatabaseName = "SP_Config"
AdminContentDatabaseName = "SP_AdminContent"
CentralAdministrationPort = 5000
CentralAdministrationAuth = "Kerberos"
Passphrase = New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString -String "JointheFarm" -AsPlainText -Force));
FarmAccount = $farmcred
RunCentralAdmin = $true
PsDscRunAsCredential = $farmcred
}

**Comment by ykuijs** [comment]
Solution for issue provided, closing issue

**Comment by whytoe** [comment]
Please update the documentation, dont just close the issue. My whole point of the issue was the documentation was incorrect.

![image](https://user-images.githubusercontent.com/12265878/33223194-611a198a-d12b-11e7-8ceb-a617b9d643c7.png)

**Comment by ykuijs** [comment]
@whytoe Fair point, my apologies. Will update the documentation accordingly! Thanks for pointing this out.

**Comment by whytoe** [comment]
Thanks for the quick response, :) I just want to save people from troubleshooting MOF errors, they arent always fun

**Comment by ykuijs** [comment]
Since we generate the Wiki content automatically, the generation script needs to get updated. Just created an issue in the Powershell/DscResources.Tests repo: PowerShell/DscResource.Tests#201

**Comment by ykuijs** [comment]
PR is reviewed, will be merged soon. I think the issue will be fixed with the release of v2.0

**Comment by ykuijs** [comment]
The fix has been merged into the DscResource.Tests repo. This means the v2.0 release will have the correct wiki content generated. Closing the issue now. Thanks for your input!
