### ISSUE TITLE
SPUserProfileSyncService not Properly Detecting instalation

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#696]
**Details of the scenario you try and problem that is occurring:**
The SPUserProfileSyncService resource is not properly detecting if the server is currently in the desired state, and is not dealing with the right Service Instance in the Set-TargetResource function.

**The DSC configuration that is using the resource:**
SPUserProfileSyncService UserProfileSyncService
        {  
            UserProfileServiceAppName = "UPS"
            Ensure                    = "Present"
            FarmAccount               = $FarmAccount
            PsDscRunAsCredential      = $FarmAccount
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2k2 R2/ PoSh 5.1

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Closed via PR 698
