### ISSUE TITLE
SPWebApplication error in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#703]
**Details of the scenario you try and problem that is occurring:**
With the new breaking changes in 2.0.0.0, param UseSSL is no longer valid, however the Get-TargetResource does return it.

return @{
            Name = $wa.DisplayName
            ApplicationPool = $wa.ApplicationPool.Name
            ApplicationPoolAccount = $wa.ApplicationPool.Username
            Url = $wa.Url
            AllowAnonymous = $authProvider.AllowAnonymous
            DatabaseName = $wa.ContentDatabases[0].Name
            DatabaseServer = $wa.ContentDatabases[0].Server
            HostHeader = (New-Object -TypeName System.Uri $wa.Url).Host
            Path = $wa.IisSettings[0].Path
            Port = (New-Object -TypeName System.Uri $wa.Url).Port
            UseClassic = $classicAuth    
            **UseSSL = (New-Object -TypeName System.Uri $wa.Url).Scheme -eq "https"**
            InstallAccount = $params.InstallAccount
            Ensure = "Present"
        }

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 / WMF 5.1

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Pushed this fix to the v2.0 release
