### ISSUE TITLE
SPFarm Get-TargetResource issue with ServerRole

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#705]
**Details of the scenario you try and problem that is occurring:**

In the Get-TargetResource block of SPFarm, we have the following code:

**elseif($installedVersion.FileMajorPart -eq 15)
{
           $returnValue.Add("ServerRole", $null)
}**

However, if we were to call the Get-TargetResource function passing is a null ServerRole parameter with a SharePoint 2013 environment, it would throw the following error:

**Server role is only supported in SharePoint 2016**.

In my opinion, Get-TargetResource should not return something it cannot "consume". My recommendation is not to return the "ServerRole" property at all if we detected that the server is based on SharePoint 2013.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 / WMF 5.1 / SP2013

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Closed via PR #734
