### ISSUE TITLE
SPUserProfileSyncService Get-TargetResource issue

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#706]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource method doesn't return the new mandatory FarmAccount property:

return @{
            UserProfileServiceAppName = $upa.Name
            Ensure = $localEnsure
            RunOnlyWhenWriteable = $params.RunOnlyWhenWriteable
            InstallAccount = $params.InstallAccount
        }

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 / WMF 5.1

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Fixed in my next Bugfix PR

**Comment by ykuijs** [comment]
Closed via PR #734
