### ISSUE TITLE
SPWebAppAuthentication error only setting AuthenticationMethod to NTLM

### ISSUE THREAD

**Issue by ColinHJ** [PowerShell/SharePointDsc#707]
**Details of the scenario you try and problem that is occurring:
                SPWebAppAuthentication $webAppInternalName
                {
                    WebAppUrl   = $webApp.Url
                    Default = @(
                        MSFT_SPWebAppAuthenticationMode 
                        {
                            AuthenticationMethod = "NTLM"
                        }
                    )
                }

Attempting to run the above config to confirm the web application is set to NTLM generates the below error: 
"you cannot use AuthenticationProvider, MembershipProvider or RoleProvider when using NTLM"

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 WFM 5.1
**Version of the DSC module you're using:**
SharePointDSC 2.0.0.0

**Comment by ykuijs** [comment]
Found cause, fix will be included in my next Bugfix PR

**Comment by MikeLacher448** [comment]
same behavior when using AuthenticationMethod = Kerberos as well.

**Comment by ykuijs** [comment]
Correct, this will be corrected for all

**Comment by Yvand** [comment]
Fyi, the same problem affects Federated and very likely FBA as well: the code checks if properties exist (which is always true) instead of checking if they have a value set.
I worked around the issue by commenting the tests that check the properties, can you please update this thread once you pushed your PR?
Thanks!

**Comment by ykuijs** [comment]
Closed via PR #734
