### ISSUE TITLE
SharePoint installation on the targetted node reboots the node very often.

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#712]
Thank you for providing latest changes. 

**Details of the scenario you try and problem that is occurring:**
Somehow sharepoint installation on my machine doing frequent reboots. I understand the fact that SP install reboots the machine while installation. However in my case, as soon as it restarts the machine and in the next one minute restarts again. This was not the case with previous SharePointDSC version. 

**The Sample DSC configuration which worked fine with old sharepointdsc
 SPInstall InstallSharePoint 
        { 
            Ensure = "Present" 
            BinaryDir = $AllNodes.SharePointBinaryPath 
            ProductKey = $AllNodes.ProductKey
            DependsOn = @("[SPInstallPrereqs]SPPrereqs", "[xFirewall]SQLFirewallRule")
            PSDSCRunasCredential = $domjoincreds 
        }

Windows 2016,  WMF 5.0

SharePoint DSC 2.0.0.0

**Comment by rsganta** [comment]
I waited for 4 hours and did not finish  sharepoint installation.

**Comment by ykuijs** [comment]
Hi @rsganta, what does the DSC eventlog say? Does this reveal which resource is causing this reboot?

In the past I have seen SQLServerAlias and CredSSP cause endless reboots. The most recent versions of those resources should fix these issues (I recently submitted a PR for SQLServerAlias to fix the issue, so that is not yet in the Powershell Gallery).

**Comment by rsganta** [comment]
I looked at desiredstateventlogs and it does not provide any info related to reboot.  In the application event log it says "failed to end a windows installer transaction OSERVER. Error 1603 occurred while ending the transaction". Source is MSIInstaller

Also another installer 
Product:Microsoft Server Proof(Russian) 2013 --ERROR1704 . An installation for Microsoft Sharepoint foundation 2016 core is currently suspended. To proceed further, you have to undo the changes " 
Not sure what this is..

**Comment by rsganta** [comment]
Finally I could see sharepoint installation succeeded on my machine.  Not sure whether any other processes e.g. sql processes preventing sharepoint setup.exe (or) normally it is taking more time to complete the installation. Thank you for your time.

**Comment by rsganta** [comment]
I found another dependency called strong name validation should  be run before installation. However, script calling sn.ps1 is not working as expected. Hence, closing this thread.
