### ISSUE TITLE
SPAccessServices2010 throws farm unavailable error

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#713]
**Details of the scenario you try and problem that is occurring:**
AccessServices2010 throws an error. Below is the LCM Verbose.

VERBOSE: [DSC-SP11]: LCM:  [ End    Test     ]  [[SPAccessServices2010]AccessServices2010]  in 10.0220 seconds.
PowerShell DSC resource MSFT_SPAccessServices2010  failed to execute Test-TargetResource functionality with error message: The farm 
is unavailable. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

DSC configuration 
   SPAccessServices2010 AccessServices2010
        {
            Name                 = "Access Services 2010 Application"
            ApplicationPool      = "SharePoint Service Applications" 
            #DatabaseServer      = $AllNodes.NodeName 
            PsDscRunAsCredential       =  $creds
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2016 & WMF5.1

**Version of the DSC module you're using:**
1.9.0.0

**Comment by rsganta** [comment]
does it need v 2.0.0.0?

**Comment by ykuijs** [comment]
Hi @rsganta, has the farm been created when this resource runs? And does the used account (InstallAccount or PSDscRunAsCredential) have the correct permissions (local admin)?

**Comment by NikCharlebois** [comment]
@rsganta I believe this one is also related to the DependsOn clause not being properly set. The farm probably doesn't get created properly and because there are no dependencies set on the SPAccessService block, it still tries to create it, which will fail unless the farm is properly created. Can you confirm if it works with your updated script and close the issue if it does? Thanks

**Comment by rsganta** [comment]
Sure @NikCharlebois .  I will close this after I validate it.

**Comment by rsganta** [comment]
@NikCharlebois 
Currently I am trying to change the account for PsDscRunAsCredential       to farmadmin account. To answer the question, farm is available.
SPAccessServices2010 AccessServices2010
        {
            Name                 = "Access Services 2010 Application"
            ApplicationPool      = "SharePoint Service Applications" 
            PsDscRunAsCredential       = $SqlFarmAdmincreds
            DependsOn = @("[SPServiceAppPool]SharePointServiceApplications"); 
        }

**Comment by rsganta** [comment]
It worked when I used farm admin credentials. Hence closing .

**Comment by rsganta** [comment]
closing.
