### ISSUE TITLE
Configurating service apps are causing failures

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#714]
I am using sharepoint DSC 1.9.0.0  . While configuring few other services , I have encountered few errors  though I have a valid application pool. I would like to understand whether I am incorrectly configuring or known issues with sharepoint dsc 1.9.0.0  . Appreciate your inputs.

1.BCS Service App:
===========

BCS Service App Config:
===============
 SPBCSServiceApp BCSServiceApp
        {
            Name                 = "Business Data Connectivity Service Application"
            ApplicationPool      = "SharePoint Service Applications"
            DatabaseName         = "BDC_Service_DB"
            DatabaseServer       = $AllNodes.NodeName
            PsDscRunAsCredential = $domjoincreds #$SetupAccount
        }
VERBOSE: [DSC-SP11]:                            [[SPBCSServiceApp]BCSServiceApp] Leaving BeginProcessing Method of New-SPBusinessDataC
atalogServiceApplication.
Value cannot be null.
Parameter name: applicationPool
    + CategoryInfo          : InvalidData: (Microsoft.Share...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.BusinessData.SharedService.SPNewBusinessDataCatalogServiceApplication
    + PSComputerName        : localhost

2.AppManagement service app:

SPAppManagementServiceApp AppManagementServiceApp
        {
            Name                 = "App Management Service Application"
            ApplicationPool      = "SharePoint Service Applications"
            DatabaseServer       = $AllNodes.NodeName 
            DatabaseName         = "App_Management_DB"  
            PsDscRunAsCredential = $domjoincreds        
        }
Error:
VERBOSE: [DSC-SP11]: LCM:  [ End    Set      ]  [[SPAppManagementServiceApp]AppManagementServiceApp]  in 1.0940 seconds.
PowerShell DSC resource MSFT_SPAppManagementServiceApp  failed to execute Set-TargetResource functionality with error message: 
Cannot bind argument to parameter 'ServiceApplication' because it is null. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

3. SPMachineTranslationService

SPMachineTranslationServiceApp MachineTranslationServiceApp
        {  
            Name                 = "Machine Translation Service Application"
            ApplicationPool      = "SharePoint Service Applications"
            DatabaseName         = "Machine_Translation_Service_DB"
            DatabaseServer       = $AllNodes.NodeName         
            PsDscRunAsCredential = $domjoincreds
        }
VERBOSE: [DSC-SP11]:                            [[SPMachineTranslationServiceApp]MachineTranslationServiceApp] Leaving BeginProcessing
 Method of New-SPTranslationServiceApplication.
The specified application pool is not valid.
    + CategoryInfo          : ObjectNotFound: (Microsoft.Offic...eApplicationNew:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.TranslationServices.Powershell.TranslationServiceApplicationNew
    + PSComputerName        : localhost

4.Secure Store Service App
  SPSecureStoreServiceApp SecureStoreServiceApp
        {  
            Name                 = "Secure Store Service Application"
            ApplicationPool      = "SharePoint Service Applications"
            AuditingEnabled      = $true
            AuditlogMaxSize      = 30
            DatabaseName         = "Secure_Store_Service_DB"
            #DatabaseServer       = $AllNodes.NodeName            
            PsDscRunAsCredential = $domjoincreds
        }

VERBOSE: [DSC-SP11]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] This will create a new Secure Store A
pplication entry.
Value cannot be null.
Parameter name: applicationPool
    + CategoryInfo          : InvalidData: (Microsoft.Offic...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.SecureStoreService.PowerShellCmdlet.SPNewSecureStoreServiceApplication
    + PSComputerName        : localhost

5. SP Visio Services

 SPVisioServiceApp VisioServices
        {
            Name                  = "Visio Graphics Service Application"
            ApplicationPool       = "SharePoint Service Applications"
            PsDscRunAsCredential  = $domjoincreds
        }

VERBOSE: [DSC-SP11]: LCM:  [ End    Set      ]  [[SPVisioServiceApp]VisioServices]  in 0.9380 seconds.
PowerShell DSC resource MSFT_SPVisioServiceApp  failed to execute Set-TargetResource functionality with error message: The term 
'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

6. SPWorkmanagement

SPWorkManagementServiceApp WorkManagementServiceApp
        {
            Name                   = "Work Management Service Application"
            ApplicationPool        = "SharePoint Service Applications" 
            #MinimumTimeBetweenEwsSyncSubscriptionSearches = 10
            PsDscRunAsCredential   = $domjoincreds
        }

VERBOSE: [DSC-SP11]:                            [[SPWorkManagementServiceApp]WorkManagementServiceApp] Leaving BeginProcessing Method 
of New-SPWorkManagementServiceApplication.
The application pool specified does not exist.
    + CategoryInfo          : InvalidArgument: (Microsoft.Offic...nagementService:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.WorkManagement.Cmdlet.SPCmdletNewWorkManagementService
    + PSComputerName        : localhost

7.Subsription Services setting app

SPSubscriptionSettingsServiceApp SubscriptionSettingsServiceApp
        {
            Name                 = "Subscription Settings Service Application"
            ApplicationPool      = "SharePoint Service Applications" #"SharePoint web services"
            DatabaseServer       = $AllNodes.NodeName
            DatabaseName         = "SubscriptionSettingsServiceDB"
            PsDscRunAsCredential = $domjoincreds
        }

VERBOSE: [DSC-SP11]:                            [[SPSubscriptionSettingsServiceApp]SubscriptionSettingsServiceApp] Leaving BeginProces
sing Method of New-SPSubscriptionSettingsServiceApplication.
The specified application pool could not be found.
    + CategoryInfo          : InvalidArgument: (Microsoft.Share...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSubscriptionSettingsServiceApplication
    + PSComputerName        : localhost

**Comment by NikCharlebois** [comment]
@rsganta Are you sure the Service Application Pool got created properly before attempting to create the service applications? One recommendation would be to use the DependsOn clause to make sure that DSC doesn't attempt to create the service applications until the Service Application Pool has been successfully created.

**Comment by rsganta** [comment]
@NikCharlebois  , Thank you.
Yes, I have checked it. I have checked IIS manager I could see app pool is running with the name Share Point Service applications (created manually)  Should we create the pool using ?

   SPServiceAppPool SharePointServiceApplications
        {
            Name = "SharePointServiceApplications";
            ServiceAccount = $SqlFarmAdmincreds.UserName 
            PsDSCRunAsCredential = $domjoincreds 
            Ensure = "Present";
        }

**Comment by rsganta** [comment]
@NikCharlebois , 
As suggested I have created app pool using SPServiceAppPool and able to resolve few app pool dependency issues. However, I have noticed few issues with the below service apps .Based on the verbose logs e.g. SPWorkManagementServiceApp  is not supported in 1.9.0.0 ? Does the below list of service application's configuration have any dependency on sharepoint DSC version 2.0.0.0?

[[SPWorkManagementServiceApp
SPWebAppPolicy]WebAppPolicy
SPVisioServiceApp]VisioServices:
SPSecureStoreServiceApp]SecureStoreServiceApp
SPAccessServiceApp
SPAccessServices2010

VERBOSE: [DSC-SP11]:                            [[SPWorkManagementServiceApp]WorkManagementServiceApp] Leaving BeginProcessing Method 
of New-SPWorkManagementServiceApplication.
We have made some changes and this functionality is no longer supported.
    + CategoryInfo          : InvalidData: (Microsoft.Offic...nagementService:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.WorkManagement.Cmdlet.SPCmdletNewWorkManagementService
    + PSComputerName        : localhost

SPVisioServiceApp]VisioServices:
VERBOSE: [DSC-SP11]: LCM:  [ End    Set      ]  [[SPVisioServiceApp]VisioServices]  in 1.0930 seconds.
PowerShell DSC resource MSFT_SPVisioServiceApp  failed to execute Set-TargetResource functionality with error message: The term 
'New-SPVisioServiceApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [DSC-SP11]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Specified database name does not matc
h the actual database name. This resource cannot rename the database.

SPAccessServiceApp:
============
VERBOSE: [DSC-SP11]: LCM:  [ End    Set      ]  [[SPAccessServiceApp]AccessServices]  in 0.9090 seconds.
PowerShell DSC resource MSFT_SPAccessServiceApp  failed to execute Set-TargetResource functionality with error message: The term 
'New-SPAccessServicesApplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

AccessServices2010:
VERBOSE: [DSC-SP11]: LCM:  [ End    Test     ]  [[SPAccessServices2010]AccessServices2010]  in 3.6250 seconds.
PowerShell DSC resource MSFT_SPAccessServices2010  failed to execute Test-TargetResource functionality with error message: The farm 
is unavailable. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

WebAppPolicy:
=========
VERBOSE: [DSC-SP11]: LCM:  [ End    Test     ]  [[SPWebAppPolicy]WebAppPolicy]  in 1.5470 seconds.
PowerShell DSC resource MSFT_SPWebAppPolicy  failed to execute Test-TargetResource functionality with error message: Cache accounts 
not configured properly. PortalSuperUserAccount or PortalSuperReaderAccount property is not configured. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by rsganta** [comment]
Does the above apps need  sharepoint DSC version 2.0.0.0 to work ?

**Comment by ykuijs** [comment]
Hi @rsganta, all these service app should also work in v1.9. I have seen some issues that might explain your issues:

- SPSecureStore: The database name does not match the configured name. The service app probably exists with DBName1 and you specify DBName2. The resource cannot rename datbases.
- Are you using SharePoint 2016? If so, you cannot use the Work Management service app, since it has been removed in SP2016: https://technet.microsoft.com/en-us/library/mt346112(v=office.16).aspx
- SPWebAppPolicy: You probably specified the SetCacheAccountsPolicy parameter to true, but have not yet configured the cache accounts. Make sure you first use SPCacheAccounts before setting the WebAppPolicy.

**Comment by rsganta** [comment]
Thanks @ykuijs 
1. SPSecureStore: You mean Secure_Store_Service_DB name is incorrect ? I re checked my dbs and I could see the DB with the above name in my database server.
 #SP SecureStore Service App
        SPSecureStoreServiceApp SecureStoreServiceApp
        {  
            Name                 = "Secure Store Service Application"
            ApplicationPool      = "SharePoint Service Applications"
            AuditingEnabled      = $true
            AuditlogMaxSize      = 30
            DatabaseName         = "Secure_Store_Service_DB"   
            PsDscRunAsCredential = $domjoincreds
            DependsOn = @("[SPServiceAppPool]SharePointServiceApplications");
        }

SPWebAppPolicy: Yes I set that SetCacheAccountsPolicy to $true. It is complaining about that I need to configure portalsuperuseraccount or portalsuperreaderaccount 

workmanagerment service: yes, I am using sp2019/

**Comment by rsganta** [comment]
SPSecureStore is working .  I still have to fix  SPWebAppPolicy, SPAccessServices2010, SPAccessServiceAPP (error:  The application database server does not have full-text search feature installed), UPA install,SPShelladmins etc

**Comment by rsganta** [comment]
SPAccessService2010 is working fine. However I tried to fix 
SPAccessServiceApp and SPWebAppPolicy but they are still encountering issues.

SPAccessService: (noted) I changed to mixed mode in sql database but still it fails.

VERBOSE: [DSC-SP12]:                            [[SPAccessServiceApp]AccessServices] Leaving BeginProcessing Method of New-SPAccessSer
vicesApplication.
A connection could be established to the Application Database Server but mixed mode authentication isn't enabled.
    + CategoryInfo          : ObjectNotFound: (Access Services Application:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Access.Services.PowerShell.NewSPAccessServicesApplication
    + PSComputerName        : localhost

SPWebApp Policy:
Though I have created superuser and superreader accounts, it still throws below error.
PowerShell DSC resource MSFT_SPWebAppPolicy  failed to execute Test-TargetResource functionality with error message: Cache accounts 
not configured properly. PortalSuperUserAccount or PortalSuperReaderAccount property is not configured. 

Any idea?

**Comment by rsganta** [comment]
I am able to get spwebapppolicy working after using spcacheaccounts however it met with a different issue account does not exist. Because I am executing this against domain 1 and setting the policy for domain 2\user which has trust relationship but it did not work..

**Comment by rsganta** [comment]
SpAccessService is  failing with an error below.
VERBOSE: [DSC-SP12]:                            [[SPAccessServiceApp]AccessServices] Leaving BeginProcessing Method of Get-SPAccessSer
vicesDatabaseServer.
Access Services Web Service Application not supplied.
    + CategoryInfo          : InvalidData: (Microsoft.Offic...sDatabaseServer:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Access.Services.PowerShell.GetSPAccessServicesDatabaseServer
    + PSComputerName        : localhost



SPAccessServiceApp AccessServices
        {
            Name                 = "Access Services Application" #Access Services Service Application
            ApplicationPool      = "SharePoint Service Applications" 
            DatabaseServer       = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName #"DSC-SP13"#$AllNodes.NodeName #"SQL.contoso.local\SQLINSTANCE"
            PsDscRunAsCredential =   $SqlFarmAdmincreds #$domjoincreds #$SetupAccount
            DependsOn = @("[SPServiceAppPool]SharePointServiceApplications");
        }

**Comment by ykuijs** [comment]
Are you testing with SP2019? That is really great, but we haven't added support for SP2019 yet.

We are in the process of testing the module with SP2019 and making sure all found issues are fixed, so we can add SP2019 support when that version goes RTM. But right now: Please expect you run into issues, possibly new issues every time you use a new build released in the TAP program.

**Comment by NikCharlebois** [comment]
@rsganta @ykuijs and for everyone else on the thread, as a reminder, no SP19 details can be posted in this public channel. we are still evaluating how can SPDSC for SP19 details be communicated with TAP participant

**Comment by rsganta** [comment]
@NikCharlebois , @ykuijs 
Thanks for the details. Thanks @NikCharlebois  for the suggestions and inputs on Spaccessservice app. I have deleted the existing service which was in stale condition and re run. it fixed the issue.
