### ISSUE TITLE
Quesition: SPInstallLanguagePack: How can I install multiple language packs ?

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#715]
Details of the scenario:
Trying to install multiple Language packs on the share point VMs. Below config works for a single language pack. If I want to install  4 different language packs one after the other, how can we configure either is the .psd1 ? or Config ? Should we create some array and feed that array ?
array = {german,chiniese ,spanish} . Any sample or efficient solution ?

The DSC configuration that is using the resource:
 SPInstallLanguagePack InstallLPBinaries
        {
            BinaryDir = $AllNodes.LanguagePackPath
            Ensure = "Present"
            DependsOn = "[SPInstall]InstallSharePoint"
            PsDscRunAsCredential = $domjoincreds 
        }
ConfigData:
$AllNodes.LanguagePackPath
SharePointBinaryPath = "\\DSC-Share\Media\SP2016Binaries" 

Version of the Operating System and PowerShell the DSC Target Node is running:
Windows 2016 and WMF 5.1

Version of the DSC :
Sharepoint Version 1.9.0.0

**Comment by rsganta** [comment]
I think this may work but it needs 4 different binary directories.  Any other samples ?
SPInstallLanguagePack Language1
{

}

SPInstallLanguagePack Language2
{

}

**Comment by NikCharlebois** [comment]
@rsganta try something like the following:
[PS1]
node $AllNodes.NodeName
{
	foreach($languagePack in $node.LanguagePacks)
	{
		SPInstallLanguagePack $languagePack.Language
		{
			BinaryDir = $languagePack.Path
			Ensure = "Present"
			DependsOn = "[SPInstall]InstallSharePoint"
			PsDscRunAsCredential = $domjoincreds
		}
	}
}

[PSD1]
@{   
	AllNodes = @(  
	@{     
		NodeName = "Server1"
                LanguagePacks = @({
			Language = "English"
			Path = "E:\Data\LP\English\"
		},
		{
			Language = "French"
			Path = "E:\Data\LP\French\"
		}
		)
        }
	)
}
Or use NonConfigData (which I recommend you do) since the same LP need to be installed on all servers.

**Comment by rsganta** [comment]
Thanks @NikCharlebois . I tried the way you recommended in the blog. However  , I will try the above option too.

**Comment by rsganta** [comment]
I think the advantage with the above suggested way  would eliminate changes to config.ps1 even if number of language packs change. As long as if the client can edit the .psd1 based on his requirement, he/she should be good. Do you see the similar advantage ?  My requirement is  to install at least 7 different language packs in all of My sharepoint vms.

**Comment by rsganta** [comment]
Thank you @NikCharlebois .

**Comment by NikCharlebois** [comment]
@rsganta Can we close this issue?

**Comment by rsganta** [comment]
Sure @NikCharlebois . We are good here. Thank you for your  timely help. Appreciate it.
