### ISSUE TITLE
SPInstallPrereqs Exit Code -1073741515

### ISSUE THREAD

**Issue by Steve-Lewis** [PowerShell/SharePointDsc#716]
I'm creating a partial to handle all the basic SharePoint prereqs and environmental configs.

When the SPInstallPrereqs runs I receive the following:

PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message:
The prerequisite installer ran with the following unknown exit code -1073741515
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [TSI-SP-01]:                            [] Consistency check completed.
One or more partial configurations failed to apply. No configuration could be created.  LCM failed to start desired
state configuration manually.
    + CategoryInfo          : ObjectNotFound: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 6
    + PSComputerName        : localhost

Any suggestions?

**Comment by NikCharlebois** [comment]
@Steve-Lewis any chances you could post your configuration script?

**Comment by Steve-Lewis** [comment]
I figured out what the problem was...

I ran the prerequisiteinstaller.exe by hand and ran into the following error: Vcruntime140.dll missing.

I went ahead and installed it and reran my DSC and it worked.

**Comment by xenophobentx** [comment]
Use the resource below as workaround before applying prereq in a config otherwise it will fail.
Kind of funny the prereq installer cannot run withouth a package that supposed to be installed by the prereq installer.

Package InstallVisualC2017Plus
        {
            #need to install due to prerequisiteinstaller bug
            Ensure = "Present"
            Name = "vc_redist.x64.exe"
            Path = $ConfigurationData.Bootstrapconfig.SPPreReqsDestination + "vc_redist.x64.exe"
            Arguments = "/passive"
            ProductId = "fd9b6070-d13e-45dc-819b-41806bf45b6b"
            }
