### ISSUE TITLE
Handling dependency in multiVM scenario

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#717]
My configuration contains multiple VMs, 
1- SQL  VM
1-AP
1-FrontEnd
In SQL VM, only SQL installation has to go.
In AP VM, sharepoint installation has to go and farm has to be created
In FrontEnd VM- Join to the farm which was created in AP VM

In the above scenario (multi VM), If I have a dependency among those VMs, how can I refer them?
e.g. I cannot join FrontEndVM until farm gets created in AP VM. I need to use depends on . 
Appreciate any samples in multi VM scenario.

Version of the Operating System and PowerShell the DSC Target Node is running:
Windows 2016 and WMF 5.1

Version of the DSC :
1.9.0.0

**Comment by ykuijs** [comment]
Hi @rsganta, please check out the DSC WaitForXXX resources: https://docs.microsoft.com/en-us/powershell/dsc/crossnodedependencies You can use these to accomplish what you want.

**Comment by rsganta** [comment]
Thank you. I will use it.
