### ISSUE TITLE
SPProductUpdate is not working with fresh install

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SharePointDsc#718]
We cannot use the resource SPProductUpdate when the farm is not exist.

The DSC configuration that is using the resource:
N/A

Version of the Operating System and PowerShell the DSC Target Node is running:
Win 2012 R2/WMF 5.1

Version of the DSC module you're using:
2.0.0.0

**Comment by ykuijs** [comment]
That is correct: The resource requires the farm to exist, as specified in the documentation: https://github.com/PowerShell/SharePointDsc/wiki/SPProductUpdate

We are thinking about changing this, but not yet 100% figured out how to do this. Check issue #679 for more info.
