### ISSUE TITLE
SPUserProfileServiceApp throws winrm client error 

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#722]
Issue:
I am trying to  create User Profile instance 

VERBOSE: [DSC-SP12]:                            [[SPUserProfileServiceApp]UserProfileServiceApp] Executing using a provided credential
 and local PSSession as user Officedog\SP997FRM
Connecting to remote server DSC-SP12 failed with the following error message : The WinRM client cannot process the request. CredSSP 
authentication is currently disabled in the client configuration. Change the client configuration and try the request again. CredSSP 
authentication must also be enabled in the server configuration. Also, Group Policy must be edited to allow credential delegation to 
the target computer. Use gpedit.msc and look at the following policy: Computer Configuration -> Administrative Templates -> System 
-> Credentials Delegation -> Allow Delegating Fresh Credentials.  Verify that it is enabled and configured with an SPN appropriate 
for the target computer. For example, for a target computer name "myserver.domain.com", the SPN can be one of the following: 
WSMAN/myserver.domain.com or WSMAN/*.domain.com For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:) [], CimException
    + FullyQualifiedErrorId : -2144108126,PSSessionOpenFailed
    + PSComputerName        : localhost
 
VERBOSE: [DSC-SP12]:                            [[SPUserProfileServiceApp]UserProfileServiceApp] Leaving BeginProcessing Method of New
-SPProfileServiceApplication.
The site specified by the MySiteHostLocation parameter must either use the "SPSMSITEHOST#0" template or have no template applied.
    + CategoryInfo          : InvalidArgument: (Microsoft.Offic...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.UserProfiles.PowerShell.SPCmdletNewProfileServiceApplication
    + PSComputerName        : localhost

Sharepoint dsc version : 1.9.0.0 
 
DSC Configuration:
SPUserProfileServiceApp UserProfileServiceApp
            {
                Name                 = "User Profile Service Application"
                ApplicationPool      = "SharePoint Service Applications"
                MySiteHostLocation   = "http://" + $Node.NodeName + "/"; 
                ProfileDBName        = "SP_UserProfiles"
                ProfileDBServer      = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
                SocialDBName         = "SP_Social"
                SocialDBServer       = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
                SyncDBName           = "SP_ProfileSync"
                SyncDBServer         = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
                EnableNetBIOS        = $false
                FarmAccount          = $SqlFarmAdmincreds
                PsDscRunAsCredential = $domjoincreds #$SqlFarmAdmincreds
            }

**Comment by NikCharlebois** [comment]
Hi @rsganta this would be automatically taken care of in version 2.0.0.0. If you are sticking with an earlier version, I suggest taking a look at the following article to enable credssp for your SP environment:
http://nikcharlebois.com/configure-your-sharepoint-environment-for-sharepointdsc/

**Comment by rsganta** [comment]
Thanks Nik.
I have tried to run the powershell commands and still get this error.

VERBOSE: [DSC-SP12]:                            [[SPUserProfileServiceApp]UserProfileServiceApp] Creating user profile service applica
tion User Profile Service Application
VERBOSE: [DSC-SP12]:                            [[SPUserProfileServiceApp]UserProfileServiceApp] Executing using a provided credential
 and local PSSession as user Officedog\SP997FRM
Connecting to remote server DSC-SP12 failed with the following error message : The WinRM client cannot process the request. The 
authentication mechanism requested by the client is not supported by the server or unencrypted traffic is disabled in the service 
configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication mechanisms 
supported by the server.  To use Kerberos, specify the computer name as the remote destination. Also verify that the client computer 
and the destination computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify 
Basic authentication and provide user name and password. Possible authentication mechanisms reported by server:     Negotiate 
Kerberos For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:) [], CimException
    + FullyQualifiedErrorId : AccessDenied,PSSessionOpenFailed
    + PSComputerName        : localhost

**Comment by NikCharlebois** [comment]
@rsganta You most likely will need to add the VM to the list of trusted host. Take a look at the following thread:
https://stackoverflow.com/questions/18284132/winrm-cannot-process-the-request-fails-only-over-a-specific-domain

**Comment by NikCharlebois** [comment]
@rsganta Your issue was solved by running Enable-WSManCredSSP on both the client and Server. Please close this issue when you get a chance. Thanks

**Comment by rsganta** [comment]
@NikCharlebois , Thanks for your help and resolving the issue. Hence closing the issue.
