### ISSUE TITLE
LCM: VMs under DSC nodes in azure portal were disappered

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#723]
Details:
Though this is not related to sharepoint DSC module, but experts can help me to figure out the issue.

In azure portal, all of my nodes got disappeared . However I can assign node configuration for new VM using Set-AzureRmAutomationDscNode.

Greatly appreciate your inputs.

**Comment by NikCharlebois** [comment]
@rsganta Do you get the list of your node config using Get-AzureRmAutomationDscNode ?

**Comment by rsganta** [comment]
@NikCharlebois  
Yes , I get the nodes using get-AzureRmAutomationDscNode  but not under Nodes .

**Comment by NikCharlebois** [comment]
Looks like that may be more related to permissions on your tenant than on the Azure Automation side. Either way, not sure what can be fixed on our end...

**Comment by NikCharlebois** [comment]
@rsganta can we also close this one? Thanks

**Comment by rsganta** [comment]
Closing. I am still exploring on the solution.
