### ISSUE TITLE
Question: How to enable IIS logging during sharepoint installation ?

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#724]
During share point installation, do we have any module which can help to enable IIS logging. Noticed modules around if IIS feature is installed ? or enable ULS logging through PDiagnosticLoggingSettings but not specific to enable IIS logging

Share Point DSC 1.9.0.0
Windows 2016 and WMF 5.1

**Comment by ykuijs** [comment]
Hi @rsganta, you can use the resource xIISLogging in the module xWebAdministration for this:
https://github.com/PowerShell/xWebAdministration

**Comment by NikCharlebois** [comment]
@rsganta this would be outside the scope of SPDSC as @ykuijs mentioned. Can we close this issue?

**Comment by rsganta** [comment]
thanks @NikCharlebois , @ykuijs .  
Sure .closing the issue and will track with xwebadministration module team.
