### ISSUE TITLE
Question: IIS loggig examples for sharpoint

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#726]
SPDiagnosticLoggingSettings seems to be the major logging component for sharepoint. Besided this, if i want to enable IIS logging, i noticed xIISmodule as below 

xIisModule phpHandler 
            { 
               Name = "phpFastCgi" 
               Path = "$($DestinationPath)\php-cgi.exe" 
               RequestPath = "*.php" 
               Verb = "*" 
               Ensure = "Present" 
               DependsOn = @("[Package]vcRedist","[File]PhpIni")  
}

Question:  What would be the target component for sharepoint binary  in the path variable?

windws 2016 , wmf 5.1

**Comment by NikCharlebois** [comment]
Hi @rsganta , 

Using xIISLogging you should be able to specify where you want IIS to store its log. I don't believe xIISModule will be of any help. I recommend you close the issue from here and ask the xWebAdministration team what other logging mechanisms are available. For SharePointDSC, the only "logging" resource we have, as you pointed out, is SPDiagnosticsLoggingSettings. Thanks

**Comment by rsganta** [comment]
Thanks @NikCharlebois
