### ISSUE TITLE
SPOutgoingEmailSettings were not properly set

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#727]
With the below config , unable to set smtp server,from and to addresses in share point DSC 1.9.0.0 

DSC Configuration:
   SPOutgoingEmailSettings FarmWideEmailSettings
        {  
            WebAppUrl             = "http://" + $Node.NodeName + "/"; 
            SMTPServer            = "domain.com"
            FromAddress           = "from`@contso.com"
            ReplyToAddress        = "to`@consto.com"
            CharacterSet          = "65001"
            PsDscRunAsCredential  = $domjoincreds
        }

Windows 2016 and WMF 5.1
Sharepoint DSC 1.9.0.0

**Comment by NikCharlebois** [comment]
@rsganta I just tried your exact script and it works fine. Can you make sure you go to Application Management >  Web Applications, select the web application for which you are settings the outgoing email and click General Settings > Outgoing Email from the ribbon?

**Comment by rsganta** [comment]
@NikCharlebois , Thank you. I was looking at Systems stettings. Closing this.
