### ISSUE TITLE
Question: Sharing ULS logs to the respective groups

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#730]
Context: In my share point farm, all logs are being logged in the default directory.  I would like to share the logs to the respective groups.  I have looked at spodiagnostics module but it does not contain any info about sharing the logs with the group. Any other pointers ?

Share point dsc 1.9.0.0

**Comment by ykuijs** [comment]
@rsganta What do you mean by "sharing with the respective groups"?

**Comment by rsganta** [comment]
Giving access to securitygroups, couple of team DLs

**Comment by ykuijs** [comment]
@rsganta You need to use a different DSC module for this for example cNtfsAccessControl.

SharePointDsc isn't meant for changing file system permissions, but for managing SharePoint.

**Comment by rsganta** [comment]
thank you.
