### ISSUE TITLE
SPServiceIdentity throws an error Unable to locate service SharePoint Service Applications 

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#731]
Context: I am trying to ensure "Confirm or Modify Service Acccount Associtions " after sharepoint is installed. It encounters an error  Unable to 
locate service SharePoint Service Applications . This happens all of the other accounts but  below is the example for share point service applications
DSC Configuration:
SPServiceIdentity SharePointServiceApplications
        {
            Name           = "SharePoint Service Applications"
            ManagedAccount = $SP997SAPcreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }

LCM Verbose for sharepoint service applications
 
VERBOSE: [DSC-SP12]: LCM:  [ Start  Resource ]  [[SPServiceIdentity]SharePointServiceApplications]
VERBOSE: [DSC-SP12]: LCM:  [ Start  Test     ]  [[SPServiceIdentity]SharePointServiceApplications]
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Getting identity for service instan
ce 'SharePoint Service Applications'
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Executing as the local run as user 
OFFICEDOG\Sankarg_adm
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving BeginProcessing Method of G
et-SPServiceInstance.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving ProcessRecord Method of Get
-SPServiceInstance.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving EndProcessing Method of Get
-SPServiceInstance.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] WARNING: Service SharePoint Service
 Applications does not support setting the process identity
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Testing service instance 'SharePoin
t Service Applications' Process Identity
VERBOSE: [DSC-SP12]: LCM:  [ End    Test     ]  [[SPServiceIdentity]SharePointServiceApplications]  in 0.8440 seconds.
VERBOSE: [DSC-SP12]: LCM:  [ Start  Set      ]  [[SPServiceIdentity]SharePointServiceApplications]
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Setting service instance 'SharePoin
t Service Applications' to 'Officedog\SP997SAP'
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Executing as the local run as user 
OFFICEDOG\Sankarg_adm
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving BeginProcessing Method of G
et-SPServiceInstance.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving ProcessRecord Method of Get
-SPServiceInstance.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving EndProcessing Method of Get
-SPServiceInstance.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving BeginProcessing Method of G
et-SPManagedAccount.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving ProcessRecord Method of Get
-SPManagedAccount.
VERBOSE: [DSC-SP12]:                            [[SPServiceIdentity]SharePointServiceApplications] Leaving EndProcessing Method of Get
-SPManagedAccount.
VERBOSE: [DSC-SP12]: LCM:  [ End    Set      ]  [[SPServiceIdentity]SharePointServiceApplications]  in 0.8610 seconds.
PowerShell DSC resource MSFT_SPServiceIdentity  failed to execute Set-TargetResource functionality with error message: Unable to 
locate service SharePoint Service Applications 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Windows 2016 and WMF > 5.0
Share Point DSC version 1.9.0.0

**Comment by rsganta** [comment]
For more information, Adding DSC Configurations for other services.
 SPServiceIdentity FarmAccount
        {
            Name           = "Farm Account"
            ManagedAccount = $SqlFarmAdmincreds.UserName 
            PsDscRunAsCredential = $domjoincreds
        }

        SPServiceIdentity DistributedCache
        {
            Name           = "Distributed Cache"
            ManagedAccount = $SqlFarmAdmincreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }
 SPServiceIdentity SharePointServerSearch
        {
            Name           = "SharePoint Server Search"
            ManagedAccount = $SqlFarmAdmincreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }
 SPServiceIdentity SecurityTokenServiceApplicationPool
        {
            Name           = "SecurityTokenServiceApplicationPool"
            ManagedAccount = $SqlFarmAdmincreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }

        SPServiceIdentity SharePointServiceApplications
        {
            Name           = "SharePoint Service Applications"
            ManagedAccount = $SP997SAPcreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }

        SPServiceIdentity SharePointWebServicesSystem
        {
            Name           = "SharePoint Web Services System"
            ManagedAccount = $SqlFarmAdmincreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }

**Comment by rsganta** [comment]
Any help here ?

**Comment by ykuijs** [comment]
Which version of SharePoint are you using? I cannot find the service instance "SharePoint Service Applications" in SP2013

**Comment by rsganta** [comment]
2016

**Comment by ykuijs** [comment]
I cannot find any service instance called "SharePoint Service Applications" in SP2016 either. What does the following command generate as output on your environment?

Get-SPServiceInstance | Select-Object -Property TypeName | Sort-Object -Property TypeName

**Comment by rsganta** [comment]
testing 2019 builds

**Comment by ykuijs** [comment]
We do not support 2019 yet. The plan is to support it once SP2019 has gone RTM. So for now, this issue can't be fixed.
