### ISSUE TITLE
SPServiceIdentity for SharePointServerSearch throws an error  'CurrentIdentityType' cannot be found on this object.

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#732]
Context: SPServiceIdentity for SharePointServerSearch throws an error  'CurrentIdentityType' cannot be found on this object.

Sharepoint DSC Version : 1.9.0.0 
OS: Windows 2016  with WMF 5.1
DSC Configuration:
 SPServiceIdentity SharePointServerSearch
        {
            Name           = "SharePoint Server Search"
            ManagedAccount = $SqlFarmAdmincreds.UserName
            PsDscRunAsCredential = $domjoincreds
        }
VERBOSE: [DSC-SP12]: LCM:  [ End    Set      ]  [[SPServiceIdentity]SharePointServerSearch]  in 0.9210 seconds.
PowerShell DSC resource MSFT_SPServiceIdentity  failed to execute Set-TargetResource functionality with error message: The property 
'CurrentIdentityType' cannot be found on this object. Verify that the property exists and can be set. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by NikCharlebois** [comment]
This looks like a bug in the SPServiceIdentity resource. We are trying to set the CurrentIdentityType property on the Search Service, but that service instance doesn't expose this as a property. We will take a closer look at that resource.

**Comment by rsganta** [comment]
Thanks @NikCharlebois .

**Comment by ykuijs** [comment]
Did some investigation on this issue and found the cause:
The ProcessIdentity parameter returns a String object with the "SharePoint Server Search" instance. For all other instance, it is returning an SPProcessIdentity. For Search the following command is required to get the ProcessIdentity: Get-SPEnterpriseSearchService).get_ProcessIdentity()

Will include a fix in my next PR

**Comment by rsganta** [comment]
Thank you both. What about #731 ?

**Comment by ykuijs** [comment]
Close via PR #757
