### ISSUE TITLE
How to create web app pool for web application ?

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#736]
Context:  Like Service App Pool, I would like to create web application pool  called Sharepoint Web Applications that can be used for web applications. Since the below config is not working ,  does this resource support SPWebApppool ?  Any other pointers?

DSCConfiguration: 
SPServiceAppPool SharePointWebApplications        
        {
            Name = "SharePoint Web Applications";
            ServiceAccount = $SP997WAPcreds.UserName 
            PsDSCRunAsCredential = $SqlFarmAdmincreds 
            Ensure = "Present";
        }   

Share point DSC module : 1.9.0.0.0
OS : > Windows 2016, WMF 5.1

**Comment by rsganta** [comment]
As per  LCM verbose logs  it says it run successfully but it is not displayed in application pools from inet manager.

VERBOSE: [997C-DM2-TAP01]: LCM:  [ Start  Resource ]  [[SPServiceAppPool]SharePointWebApplications]
VERBOSE: [997C-DM2-TAP01]: LCM:  [ Start  Test     ]  [[SPServiceAppPool]SharePointWebApplications]
VERBOSE: [997C-DM2-TAP01]:                            [[SPServiceAppPool]SharePointWebApplications] Testing service application pool 'SharePoint Web Applications'
VERBOSE: [997C-DM2-TAP01]:                            [[SPServiceAppPool]SharePointWebApplications] Getting service application pool 'SharePoint Web Applications'
VERBOSE: [997C-DM2-TAP01]:                            [[SPServiceAppPool]SharePointWebApplications] Executing as the local run as user REDMOND\sankarg
VERBOSE: [997C-DM2-TAP01]:                            [[SPServiceAppPool]SharePointWebApplications] Leaving BeginProcessing Method of Get-SPServiceApplicationPool.
VERBOSE: [997C-DM2-TAP01]:                            [[SPServiceAppPool]SharePointWebApplications] Leaving ProcessRecord Method of Get-SPServiceApplicationPool.
VERBOSE: [997C-DM2-TAP01]:                            [[SPServiceAppPool]SharePointWebApplications] Leaving EndProcessing Method of Get-SPServiceApplicationPool.
VERBOSE: [997C-DM2-TAP01]: LCM:  [ End    Test     ]  [[SPServiceAppPool]SharePointWebApplications]  in 0.8750 seconds.
VERBOSE: [997C-DM2-TAP01]: LCM:  [ Skip   Set      ]  [[SPServiceAppPool]SharePointWebApplications]
VERBOSE: [997C-DM2-TAP01]: LCM:  [ End    Resource ]  [[SPServiceAppPool]SharePointWebApplications]

**Comment by NikCharlebois** [comment]
SPServiceAppPool creates a SharePoint service app pool which is not the same as a traditional IIS apppool. Can you elaborate on what it is you are expecting to see? What endgoal are you trying to achieve?

**Comment by rsganta** [comment]
Thank you @NikCharlebois for your help. I have used xWebAppPool as suggested.
