### ISSUE TITLE
Sharepoint SPWebApplication for SLL creating two sites with different states(stop and start) and fails to run spwebapplication

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#737]
Sharepoint dsc module : 1.9.0.0 
Hi,
I am configuration SPWebApplication with SSL and somehow it creates two sites(observed from inet manager) one with stop state officegemini.redmond.corp.microsoft.com and otherone with officegemini(start 

Configuration:

SPWebApplication a
        {
            DatabaseName = "Sharepoint_Content";  
            Url = "https://a.redmond.corp.microsoft.com"
            ApplicationPool =  "SharePoint Web Applications"          
            Path = "C:\inetpub\wwwroot\wss\VirtualDirectories\443";
            UseSSL = $true;  
            AllowAnonymous = $false;
            Name = "a.Redmond.Corp.microsoft.com" 
            AuthenticationMethod = "NTLM";   
            PsDSCRunAsCredential = $domjoinRavicreds 
            ApplicationPoolAccount = $sp997wapcreds.UserName;
            Ensure = "Present";
            Port = "443"; 
            DatabaseServer = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
            AuthenticationProvider = "Windows Authentication"; 
            DependsOn = "[SPServiceAppPool]SharePointWebApplications"
             
        }

VERBOSE: [997C-DM2-TAP01]: LCM:  [ Start  Resource ]  [[SPWebApplication]OfficeGemini]
VERBOSE: [997C-DM2-TAP01]: LCM:  [ Start  Test     ]  [[SPWebApplication]OfficeGemini]
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Testing for web application 'OfficeGemini.Redmond.Corp.microsoft.com' config
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Getting web application 'OfficeGemini.Redmond.Corp.microsoft.com' config
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Executing as the local run as user REDMOND\sankarg
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving BeginProcessing Method of Get-SPWebApplication.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving ProcessRecord Method of Get-SPWebApplication.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving EndProcessing Method of Get-SPWebApplication.
VERBOSE: [997C-DM2-TAP01]: LCM:  [ End    Test     ]  [[SPWebApplication]OfficeGemini]  in 0.6250 seconds.
VERBOSE: [997C-DM2-TAP01]: LCM:  [ Start  Set      ]  [[SPWebApplication]OfficeGemini]
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Setting web application 'OfficeGemini.Redmond.Corp.microsoft.com' config
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Executing as the local run as user REDMOND\sankarg
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving BeginProcessing Method of Get-SPWebApplication.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving ProcessRecord Method of Get-SPWebApplication.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving EndProcessing Method of Get-SPWebApplication.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving BeginProcessing Method of Get-SPManagedAccount.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving ProcessRecord Method of Get-SPManagedAccount.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving EndProcessing Method of Get-SPManagedAccount.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving BeginProcessing Method of New-SPAuthenticationProvider.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving ProcessRecord Method of New-SPAuthenticationProvider.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving EndProcessing Method of New-SPAuthenticationProvider.
VERBOSE: [997C-DM2-TAP01]:                            [[SPWebApplication]OfficeGemini] Leaving BeginProcessing Method of New-SPWebApplication.
The directory C:\inetpub\wwwroot\wss\VirtualDirectories\443 is already being used by another IIS Web Site.  Choose a different root directory for your new Web application.
    + CategoryInfo          : InvalidData: (Microsoft.Share...PWebApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewSPWebApplication
    + PSComputerName        : localhost

**Comment by NikCharlebois** [comment]
Hi Ravi,

I’d recommend changing the path for your webapp to use a folder that goes by the webapp’s name instead of the port number. This way you won’t have two web apps, using ssl trying to overwrite one another

**Comment by rsganta** [comment]
thanks for your help @NikCharlebois . It helped
