### ISSUE TITLE
Question: Resource to self service site creation

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#738]
Any resource that could help with self service site creation ?

**Comment by andikrueger** [comment]
Please use the SPWebAppGeneralSettings Resource to configure Self Service Site Creation.

**Comment by ykuijs** [comment]
Like @andikrueger says, you can use SPWebAppGeneralSettings to configure Self Service Site Creation or SPSite to create new site collections.

Is that what you meant? If not, please elaborate a little more what you mean.

**Comment by rsganta** [comment]
yes, @andikrueger  response helped it.
