### ISSUE TITLE
Extend SPServiceIdentity with the ability to select Local System

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#739]
sharepoint dsc version : 1.9.0.0
dsc configuration: Please let me know if I misconifgure this resource.
SPServiceIdentity DocumentConversionsLauncherService
        {
            Name           = "Document Conversions Launcher Service"
            ManagedAccount = "Local System"
            PsDscRunAsCredential = $domjoincreds
        }

        SPServiceIdentity DocumentConversionsLoadBalancerService
        {
            Name           = "Document Conversions Load Balancer Service"
            ManagedAccount = "Local Service"
            PsDscRunAsCredential = $domjoincreds
        }

**Comment by ykuijs** [comment]
Hi @rsganta, the Managed Account parameter has to point to an existing Managed Account in SharePoint (Get-SPManagedAccount and in Central Admin). Not 100% sure and don't have my test environment ready, but I believe that Local System isn't a Managed Account. Therefore you cannot configure it as a managed account.

What is the error you are getting in this case?

**Comment by rsganta** [comment]
Below is the error for reference. In the central admin, when I select these services, it shows it runs with account Local service . My goal is to validate whether this service is running under the account. I could see success only in [[SPServiceIdentity]SearchHostControllerService] and all of the remaining service account associations are failing.

VERBOSE: [897C-MN-PAP01]:                            [[SPServiceIdentity]DocumentConversionsLoadBalancerService] Leaving BeginProcessi
ng Method of Get-SPManagedAccount.
No matching accounts were found.
    + CategoryInfo          : InvalidData: (Microsoft.Share...tManagedAccount:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGetManagedAccount
    + PSComputerName        : localhost
 
VERBOSE: [897C-MN-PAP01]:                            [[SPServiceIdentity]DocumentConversionsLoadBalancerService] Leaving ProcessRecord
 Method of Get-SPManagedAccount.
VERBOSE: [897C-MN-PAP01]:                            [[SPServiceIdentity]DocumentConversionsLoadBalancerService] Leaving EndProcessing
 Method of Get-SPManagedAccount.
VERBOSE: [897C-MN-PAP01]: LCM:  [ End    Set      ]  [[SPServiceIdentity]DocumentConversionsLoadBalancerService]  in 0.6720 seconds.
PowerShell DSC resource MSFT_SPServiceIdentity  failed to execute Set-TargetResource functionality with error message: Unable to 
locate Managed Account Local Service 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by ykuijs** [comment]
Ok, this means we have to extend SPServiceIdentity with the ability to select Local System. Will place this issue on the backlog

**Comment by ykuijs** [comment]
Will be implemented in my next PR

**Comment by ykuijs** [comment]
Close via PR #757
