### ISSUE TITLE
xpfximport throws  import requires either a different password or membership in an Active Directory error.

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#740]
xPfxImport throws an activedirectory error. I am trying to import a certificate(password protected) to Personal store.  I have compared the parameters with github module and looks everything ok except Exportable parameter ( did not use it). Any help would be greatly appreciated.

sharepoint DSC module 1.9.0.0

Configuration:

xPfxImport OfficeCert
        {
            Thumbprint = $ConfigurationData.NonNodeData.CertificateThumbprint
            Path       = "C:\SXS\OfficeGemini.pfx"
            Location   = 'LocalMachine'
            Store      = $ConfigurationData.NonNodeData.CertificateStoreName
            Credential = $domjoincreds
            DependsOn  = '[WindowsFeature]IIS'
        }

VERBOSE: [897C-MN-PAP01]:                            [[xPfxImport]OfficeCert] '3BB3BEA5B7BED702261AD79A15FA55B349CCEBF9' is not a vali
d hash.
VERBOSE: [897C-MN-PAP01]:                            [[xPfxImport]OfficeCert] Set-TargetResource: Setting Pfx '3BB3BEA5B7BED702261AD79
A15FA55B349CCEBF9' existence in 'Cert:\LocalMachine\My'.
VERBOSE: [897C-MN-PAP01]:                            [[xPfxImport]OfficeCert] Performing the operation "Set-TargetResource" on target 
"Importing Pfx '\\DSC-Share\Media\SXS\OfficeGemini.pfx' into 'Cert:\LocalMachine\My'".
VERBOSE: [897C-MN-PAP01]:                            [[xPfxImport]OfficeCert] Set-TargetResource: Importing Pfx '\\DSC-Share\Media\SXS
\OfficeGemini.pfx' into 'Cert:\LocalMachine\My'.
The PFX file you are trying to import requires either a different password or membership in an Active Directory principal to which 
it is protected.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.CertificateServices.Commands.ImportPfxCertificate
    + PSComputerName        : localhost
 
VERBOSE: [897C-MN-PAP01]: LCM:  [ End    Set      ]  [[xPfxImport]OfficeCert]  in 1.1570 seconds.
The PowerShell DSC resource '[xPfxImport]OfficeCert' with SourceInfo '::641::9::xPfxImport' threw one or more non-terminating errors 
while running the Set-TargetResource functionality. These errors are logged to the ETW channel called

**Comment by rsganta** [comment]
I have the private key but need to know which parameter will help to get this key and ensure certificate imports successfully.

**Comment by ykuijs** [comment]
Hi @rsganta, since xPfxImport isn't part of SharePointDsc, I would suggest to redirect questions about this resource to the module of that resource: [xCertificate](https://github.com/PowerShell/xCertificate)

**Comment by rsganta** [comment]
thanks. Though it is not a share point dsc, i have found the solution and so that it would help to the people who encounters the same problem . Basically i have passed the key via Credentials from azure portal.

**Comment by jfletcher93** [comment]
@rsganta  - can you expand on your fix for this please? I am having the same issue but running the dsc locally on a Windows 2016 vm.

> The PFX file you are trying to import requires either a different password or membership in an Active Directory principal to which it is protected.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.CertificateServices.Commands.ImportPfxCertificate
    + PSComputerName        : localhost
