### ISSUE TITLE
Question: Which resource could help to validate OU of the computer based on the role of VM ?

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#741]
Context: Since we have different roles front end ,application server etc. If i join the machines to domain domain.host..company.com  and How to validate whether this VM is placed in right OU ?

I am not sure whether this covers part of Share Point DSC.

**Comment by ykuijs** [comment]
Hi @rsganta, within DSC each module has its own purpose. SharePointDsc is meant for managing SharePoint settings/configuration. This module will not be able to manage anything that does not specifically have anything to do with SharePoint, like security group memberships, IIS settings, SQL settings, etc.

OU's are part of Active Directory, so you need the DSC module that is able to manage AD: [xActiveDirectory](https://github.com/PowerShell/xActiveDirectory). When reviewing this module, you can see that [xADComputer](https://github.com/PowerShell/xActiveDirectory/tree/dev/DSCResources/MSFT_xADComputer) is the resource you are looking for.

**Comment by rsganta** [comment]
closing this as  I found xADOrganizationalUnit seems to be related resource.
