### ISSUE TITLE
How to execute SPWebAppPeoplePickerSettings using 1.9.0.0

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#744]
SPWebAppPeoplePickerSettings is available in 2.0.0.0. However, I would like to compile my config with 1.9.0.0. For that , I have downloaded 2.0.0.0 and copied the SPWebAppPeoplePickerSettings  resource to 1.9.0.0 resources and compilation still fails.

Any other step to be executed ? Does this need to be in Azure too ?

**Comment by ykuijs** [comment]
Hi @rsganta, why not use 2.0?

**Comment by rsganta** [comment]
I will after all break in changes to 1.9.0.0 gets fixed . But I am closing it now as I will try to add this resource to 1.9.0.0 and upload to azure.

**Comment by ykuijs** [comment]
@rsganta FYI: We have fixed several issues that were introduced in 2.0. These will be formally released early Feb, but you can already download these by downloading everything from:
https://github.com/PowerShell/SharePointDsc/tree/dev/Modules/SharePointDsc
And using that to update the existing version of the v2.0 module
