### ISSUE TITLE
Windows Server 2016 Prereqs Major bug

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#746]
**Details of the scenario you try and problem that is occurring:**
This should be a great way of ending the week. During a client engagement of mine, we realized that there are two typos in the list of windows features prerequisites for Windows Server 2016:

1 - Web-Filering should be Web-Filtering (6th line)
2 - "Web-Net-Ext45Web-Asp-Net" (8th line) should be two features "Web-Net-Ext45", "Web-Asp-Net"

$Script:SP2016Win16Features = @("Web-Server", "Web-WebServer", 
                                "Web-Common-Http", "Web-Default-Doc", "Web-Dir-Browsing", 
                                "Web-Http-Errors", "Web-Static-Content", "Web-Health", 
                                "Web-Http-Logging", "Web-Log-Libraries", "Web-Request-Monitor", 
                                "Web-Http-Tracing", "Web-Performance", "Web-Stat-Compression", 
                                "Web-Dyn-Compression", "Web-Security", "Web-Filering", "Web-Basic-Auth", 
                                "Web-Digest-Auth", "Web-Windows-Auth", "Web-App-Dev", "Web-Net-Ext", 
                                "Web-Net-Ext45Web-Asp-Net", "Web-Asp-Net45", "Web-ISAPI-Ext", 
                                "Web-ISAPI-Filter", "Web-Mgmt-Tools", "Web-Mgmt-Console", 
                                "Web-Mgmt-Compat", "Web-Metabase", "Web-Lgcy-Scripting", "Web-WMI", 
                                "NET-Framework-Features", "NET-HTTP-Activation", "NET-Non-HTTP-Activ", 
                                "NET-Framework-45-ASPNET", "NET-WCF-Pipe-Activation45", 
                                "Windows-Identity-Foundation", "WAS", "WAS-Process-Model", 
                                "WAS-NET-Environment", "WAS-Config-APIs", "XPS-Viewer")

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows server 2016 / SPDSC 2.0

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SP2016

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Will fix this in my next PR

**Comment by ykuijs** [comment]
Close via PR #757
