### ISSUE TITLE
SQLServer.ps1 Configuration should be updated to use SqlServerDsc

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/SharePointDsc#749]
**Details of the scenario you try and problem that is occurring:**
The integration tests are still using xSQLServer 5.0.0.0 which is no longer supported. This should be updated to utilize SqlServerDsc 10.0.0.0 which is fully supported.

**The DSC configuration that is using the resource:**
[SQLServer.ps1](https://github.com/PowerShell/SharePointDsc/blob/release-2.0/Tests/Integration/Azure/DscConfigs/SQLServer.ps1)

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of SharePoint that is used (e.g. SharePoint 2016):**
n/a

**Version of the DSC module you're using:**
2.0, dev

**Comment by ykuijs** [comment]
Implemented in PR #758. Closing issue
