### ISSUE TITLE
SPWebAppAuthentication resource cannot configure multiple authentication provider on a same zone

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SharePointDsc#751]
**Details of the scenario you try and problem that is occurring:**
SPWebAppAuthentication resource cannot configure multiple authentication provider on a same zone.
Or it's possible with the Cmdlet Set-SPWebApplication and the parameter -AuthenticationProvider
Defines the authentication **provider(s)** that applies to the Web application.

**The DSC configuration that is using the resource:**
SPWebAppAuthentication
   
```
SPWebAppAuthentication APPLICATION_SetSPWebApp_SPS_FBA
{            
    PsDscRunAsCredential = $credential
    WebAppUrl            = "http://$($env:COMPUTERNAME)"
    Default              = @(
        MSFT_SPWebAppAuthenticationMode 
        {
            AuthenticationMethod = 'FBA'
            MembershipProvider   = 'FBALoginMember'
            RoleProvider         = 'FBALoginRole'
        }
        MSFT_SPWebAppAuthenticationMode
        {
            AuthenticationMethod = 'NTLM'
        }
    )
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2
PowerShell 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2013

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Hi @luigilink I just tested this and it works fine on my environment. What exactly is happening on your end? Do you get an error message?

**Comment by ykuijs** [comment]
@luigilink Do you still encounter this issue? And have you tested with v2.1 which also contains a fix in SPWebAppAuthentication?

**Comment by luigilink** [comment]
@ykuijs thanks for your patience.
You're right it works great with 2.2 (and I think 2.1).
You can  closed this issue.
