### ISSUE TITLE
SPSecureStoreServiceApp Issue in Get-TargetResource

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#752]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource function returns a property named:

 AuditEnabled           = $auditEnabled

When it should be **"AuditingEnabled**.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2016/WMF 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2016

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Fixed via PR #753
