### ISSUE TITLE
Still can't figure out how tomake the search working 

### ISSUE THREAD

**Issue by Tpaquot** [PowerShell/SharePointDsc#755]
Hello, 

I am running SharepointDSC 2.0.0.0 on a windows 2012r2 with Powershell 5.1
I started with the example provided with the module (single server), fine for me. 
If I run this, I have a search service, but it gives no result 
I'd like a basic search that has everything on the same server and that has is index on another drive
Si I tried using 

SPSearchIndexPartition SPI
        {
            ServiceAppName = "Search Service Application"
            Servers = @("MyServer1")
            PsDscRunAsCredential = $FarmAccount
            RootDirectory = "e:\index"
            Index = 0
            DependsOn = '[SPSearchServiceApp]SearchServiceApp'
        }
 SPSearchTopology SPSTop
        {
           ContentProcessing = @("MyServer1");
           AnalyticsProcessing = @("MyServer1");
           PsDscRunAsCredential = $FarmAccount
           IndexPartition = @("MyServer1");
           Crawler = @("MyServer1");
           Admin = @("MyServer1");
           ServiceAppName = "Search Service Application";
           QueryProcessing = @("MyServer1");
           FirstPartitionDirectory = "e:\index"
           DependsOn = '[SPSearchIndexPartition]SPI'
        }
but no. 

How do I get it working without trying to cheat making it workin with powershell, and then trying to change my DSC document accordingly 

Regards

**Comment by andikrueger** [comment]
Your search topology looks fine. Are there any errors in the Event logs when you provision the search?

I provision the search by using the following resources in order:

- SPSearchServiceApp
- SPSearchTopology
- SPServiceInstance (to provision the search service application on that server)

**Comment by Tpaquot** [comment]
I spent the 4 hours to test. 
I works ! 
Many Thanks Andi !

**Comment by ykuijs** [comment]
Hi @Tpaquot, looks like your issue is resolved. Can we close the issue?

**Comment by Tpaquot** [comment]
Yes it is …
Thanks

Thierry
