### ISSUE TITLE
Update Wiki to Reflect the Use of SqlServerDsc

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/SharePointDsc#759]
**Details of the scenario you try and problem that is occurring:**
I am attempting to update the Wiki to reflect the changes made to the lab build. [Here is my updated branch](https://github.com/randomnote1/SharePointDsc/wiki/Creating%20an%20Azure%20development%20environment).

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of SharePoint that is used (e.g. SharePoint 2016):**
N/A

**Version of the DSC module you're using:**
N/A

**Comment by ykuijs** [comment]
Moved over your changed to the article in the repo. Thanks for you contribution!
