### ISSUE TITLE
SPMinRoleCompliance function Get-SPDscRoleTestMethod needs to be Exported

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#760]
**Details of the scenario you try and problem that is occurring:**
The SPMinRoleCompliance resource is only exporting *-TargetResource functions, however it also needs to export the Get-SPDscRoleTestMethod method.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/WMF 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2016

**Version of the DSC module you're using:**
2.0.0.0

**Comment by ykuijs** [comment]
Hi @NikCharlebois What is the reason that this method also needs to be exported??

**Comment by NikCharlebois** [comment]
Set-TargetResource is calling it from within the Invoke-SPDSCCommand block, which at that point requires the function to be exposed publicly. We ran into several issues in the SPOA if the function is not exposed.

**Comment by ykuijs** [comment]
Closed via PR #761
