### ISSUE TITLE
SPManagedMetaDataServiceApp resource fails when setting Content Type Hub URL

### ISSUE THREAD

**Issue by wfeaser** [PowerShell/SharePointDsc#764]
The SPManagedMetaDataServiceApp resource fails when attempting to set a content type hub URL on an existing MMS instance that was created without a content type hub URL.  There is logic in the Set-TargetResource function that attempts to compare the CT hub URL that was provided as a parameter to the current CT hub URL.  As part of this operation, a "TrimEnd()" is attempted.  This fails when the existing instance's CT hub URL was not set because $result.ContentTypeHubUrl will be $null (resulting in an error of "You cannot call a method on a null-valued expression.").

Confirmed that SharePoint DSC 1.7, 1.9, 2.0, and 2.1 all have the incorrect code.

OS:  Windows Server 2012 / 2012 R2

SharePoint version:  SharePoint 2013

DSC version:  Using 1.7, but have confirmed issue still exists in newer releases.

**Comment by ykuijs** [comment]
Will be included in my next Bugfix PR

**Comment by ykuijs** [comment]
Closed via PR #775
