### ISSUE TITLE
SPUserProfileSyncConnection cannot set filter

### ISSUE THREAD

**Issue by wickedave** [PowerShell/SharePointDsc#766]
I'm setting a User Profile Sync connection but I don't have the option to setup the LDAP filter. When you are setting the connection from the Central Admin, we have a field for the filter.

Version of the Operating System and PowerShell the DSC Target Node is running: Windows Server 2016
Version of SharePoint: SharePoint 2016
Version of the DSC module you're using: 2.1.0.0

**Comment by NikCharlebois** [comment]
@wickedave $IncludedOUs should allow you to specify your LDAP query

**Comment by wickedave** [comment]
@NikCharlebois 
I'm not sure what the syntax should be in this case. In our scenario, I need to exclude users with specific employeeNumber and where title is not empty. I'm not sure it will fit for $IncludedOUs purpose.

**Comment by NikCharlebois** [comment]
It should be able to handle traditional LDAP queries. If you can build your query and test it out (use PowerShell to test it against your AD), then it should work and only select the proper users.

**Comment by wickedave** [comment]
I noticed that with useSSL parameter, the connection to LDAP is not working.

**Comment by ykuijs** [comment]
Hi @wickedave Unfortunately I have to say that I am unable to add configuring an LDAP filter. All required methods to configure LDAP filters are internal, so cannot be called from our resource.

If you (or anybody else) have way of configuring the LDAP filter via PowerShell, let us know!

**Comment by wickedave** [comment]
Hi @ykuijs,

Thanks for looking into this.

**Comment by ykuijs** [comment]
Closing this issue, since the SharePoint object model doesn't allow us to specify an LDAP filter
