### ISSUE TITLE
MySiteHostLocation and MySiteManagedPath

### ISSUE THREAD

**Issue by shurick81** [PowerShell/SharePointDsc#770]
**Details of the scenario you try and problem that is occurring:**
I need to configure different `-MySiteHostLocation` and `-MySiteManagedPath`, like it's possible via https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Set-SPProfileServiceApplication?view=sharepoint-ps

![image](https://user-images.githubusercontent.com/11289124/36388751-f7472210-15ad-11e8-81de-650d249c0bbb.png)

**The DSC configuration that is using the resource:**
The resource I am trying to use is SPUserProfileServiceApp but it does not seem capable of it, it only has one parameter, `MySiteHostLocation`.
There seems to be no correct parameter set if I want to have the desired config.
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2016, PS 5.1
**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2016
**Version of the DSC module you're using:**
1.9

**Comment by NikCharlebois** [comment]
Even though we allow for MySiteHostLocation to be passed as a param, the Set-TargetResource never does anything with it. I will fix, add support for the managed path and submit a PR

**Comment by ykuijs** [comment]
Closed via PR #787
