### ISSUE TITLE
Discussion: Breaking Change: SPWebApp... parameters are not consistent: WebAppUrl vs. Url vs. WebApplication

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#771]
**Details of the scenario you try and problem that is occurring:**
In a recent customer engagement I stumbled about some inconsistency about the naming of the WebAppUrl, URL and WebApplication parameter in the SPWebApp... Resources.

The WebAppUrl, Url or WebApplication are parameter (keys) for these resources:

Resource | WebAppUrl | Url | WebApplication
----- | ----- | ----- | ------
MSFT_SPWebAppAuthentication | x | - | -
MSFT_SPWebAppBlockedFileTypes | - | x | -
MSFT_SPWebAppGeneralSettings | - | x | -
MSFT_SPWebAppPeoplePickerSettings | x | - | -
MSFT_SPWebAppPermissions | x | - | -
MSFT_SPWebAppPolicy | x | - | -
MSFT_SPWebAppProxyGroup | x | - | -
MSFT_SPWebAppSiteUseAndDeletion | - | x | -
MSFT_SPWebAppSuiteBar | x | - | -
MSFT_SPWebAppThrottlingSettings | - | x | -
MSFT_SPWebAppWorkflowSettings | - | x | -
MSFT_SPWebApplication | - | x | -
MSFT_SPWebApplicationAppDomain | - | - | x
MSFT_SPWebApplicationExtension | x | - | -

Changing these parameters would be a breaking change. I just wanted to point this out and hope we will find a way on how to match these keys.

The SqlServerDsc Resource did something similar: [Issue 308](https://github.com/PowerShell/SqlServerDsc/issues/308)

**Comment by NikCharlebois** [comment]
@andikrueger As you pointed out, this would definitively be a breaking change. The best we can really do, is duplicate some of the params, deprecate the original ones, and when 3.0 comes out, then introduce the breaking changes. I am just not convinced that this would be worth the effort though.

I understand that the SQLServer team went through the exercise, but we've been a little more on the conservative front with SPDSC, where we only released one set of breaking changes over the past 2 years. The floor is open for discussions :)

**Comment by andikrueger** [comment]
I'm uncertain about the effort too - There are way to many parameters that need to be changed and the change would be more cosmetics, than really necessary. 
Maybe we could stick with  the current mix, but should find a commitment which of the three current parameters is the one for new SPWebApp... resources.

**Comment by ykuijs** [comment]
These aren't the only resources that require the web application url:

Resource | WebAppUrl | Url | WebApplication
----- | ----- | ----- | ------
SPAppStoreSettings | x | - | -
SPBlobCacheSettings | x | - | -
SPCacheAccounts | x | - | -
SPContentDatabase | x | - | -
SPDesignerSettings | - | x | -
SPFarmSolution | - | - | x (WebApplications)
SPManagedPath | x | - | -
SPOutgoingEmailSettings | x | - | -
SPTimerJobState | x | - | -

I like the idea of standardizing the parameter names, but agree with Nik that we should not do this before v3.0.

If we agree on a parameter name, we can make sure that from now on any new resources would use the same name. Personally I like the name WebAppUrl. What do you think?

**Comment by ykuijs** [comment]
Implementing this change into the newly created v3.0-development branch. Changing all parameters to WebAppUrl.

**Comment by ykuijs** [comment]
Just submitted PR #824

**Comment by ykuijs** [comment]
Merged via PR 824, closing issue
