### ISSUE TITLE
SPUserProfileSyncConnection SSL issue

### ISSUE THREAD

**Issue by wickedave** [PowerShell/SharePointDsc#774]
Hi,

I'm trying to configure an Active Directory Sync connection with SPUserProfileSyncConnection resource. I don't have any problem if I'm not using SSL but if I set the UseSSL parameter to true, I'm getting the error:

`The LDAP server is unavailable.`

I'm trying with SharePoint 2016 on Windows Server 2016 with the SharePointDSC module version 2.1.0.0

**Comment by ykuijs** [comment]
Hi @wickedave, does this work when you use the Add-SPProfileSyncConnection manually?

**Comment by ykuijs** [comment]
@wickedave Just to check: When testing this setting, did you configure your AD to use LDAPS before configuring this setting?
https://social.technet.microsoft.com/wiki/contents/articles/2980.ldap-over-ssl-ldaps-certificate.aspx

Reason I ask is that I investigated this issue yesterday and wasn't able to use LDAPS via SharePointDsc, PowerShell directly or Central Admin at all. I got the same error message as you did. Some searches revealed that you have to configure certificates before it will work.

**Comment by wickedave** [comment]
Hi Yorick,

LDAPS is configured on our side. I was able to set the SSL connection from the central admin without any issue. I didn’t try to configure it with the default SharePoint Powershell command yet because I’m so busy at work that I don’t have spare time to try it on my lab.

thanks


[my-signature]

**Comment by ykuijs** [comment]
I found the issue: When specifying UseSSL, you also have to specify that the port should be 636 instead of the default port 389. The code does not do this. Will update the resource, which will be included in my next Bugfix PR!

**Comment by ykuijs** [comment]
Fixed in PR #811

**Comment by ykuijs** [comment]
PR merged, closing issue
