### ISSUE TITLE
How far I've got - just leaving a sample

### ISSUE THREAD

**Issue by IlleNilsson** [PowerShell/SharePointDsc#777]
Setting up sub site collections without "sites" , is bugging me,

Version of the Operating System and PowerShell the DSC Target Node is running:": All the latest of today

Version of SharePoint that is used SharePoint 2016 sp1

As of today the latest pubic available

I'm new to git, how do I leave a script sample with my issue.
 
By the way, I appreciate all they work.

Found it, att the bottom :) had to rename them ....

[SPI.ps1.txt](https://github.com/PowerShell/SharePointDsc/files/1794784/SPI.ps1.txt)
[SPI.psd1.txt](https://github.com/PowerShell/SharePointDsc/files/1794785/SPI.psd1.txt)
[SPI-Create.ps1.txt](https://github.com/PowerShell/SharePointDsc/files/1794786/SPI-Create.ps1.txt)

**Comment by NikCharlebois** [comment]
Can you please elaborate on what the error is? Are you getting errors creating SPWeb objects?

**Comment by IlleNilsson** [comment]
Hi Nik,

The failure is  "site collection could not be created as the provided hostheader managed path does not exist"

I guess it has to do with the available sub site/collection available intermediate naming like "sites". But I don't want sites to be in my url. 

Do you se any FU's in my script please let me know.

I'm liking your work, WaitForAll is great in this scenario. That is PSDSC not your work, But previous installer did only work for single machine.

God work, thumbs up.

**Comment by NikCharlebois** [comment]
Based on your files, it looks like you are trying to create a Site Collection at:
http://sif:82/docs
However, in order for you to be able to achieve this, you will need a HostName Explicit Managed Path. You can use the following to accomplish this and have the SPSite block DepnedSOn it

SPManagedPath DocsImplicit
{
    WebAppUrl = "$($webApplication.Url):$($webApplication.Port)"
    RelativeUrl = $siteCollection.RelativeUrl
    Explicit = $true
    HostHeader = $true
    PsDscRunAsCredential = $SpAdminCredential
}

**Comment by ykuijs** [comment]
Hi @IlleNilsson, does the answer of Nik solve your question? If so, could you please close the issue? Thanks!

**Comment by IlleNilsson** [comment]
Yes it did, sorry for the delay. Answer was much appriciated
