### ISSUE TITLE
SPFarmAdministrators: This resource can be used multiple times in a configuration

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#778]
**Details of the scenario you try and problem that is occurring:**
The key "Name" of the SPFarmAdministrators resource can be unique and therefor allows this resource to be used multiple times - which is not best practices.

The parameter "Name" should be changed to something with a validate set, which only allows one name. e.g.: https://github.com/PowerShell/SharePointDsc/blob/09256aca5e81fa01ef4477ad97680336772c4f1c/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1#L8

**Comment by ykuijs** [comment]
I think we should implement this consistent across all resources. Unfortunately DSC does not implement anything to enforce this, but like you say we can use a validateset as described in: https://docs.microsoft.com/en-us/powershell/dsc/singleinstance

SPDiagnosticSettings and probably others have the same issue. This is a breaking change, so will have to wait for v3.


________________________________

**Comment by ykuijs** [comment]
I did a quick check of all resources which maybe also should only have one instance in each config:
SPAntivirusSettings
SPDiagnosticLoggingSettings
SPInfoPathFormsServiceConfig
SPPasswordChangeSettings
SPSecurityTokenServiceConfig

And potentially also:
SPMinRoleCompliance

What do you think?

**Comment by andikrueger** [comment]
I think I found some more resource, that could need an update. I was very cautious with my choices of the following resources. Please find more details in the table below.
I included the resources you pointed out as well as any resources that implements IsSingleInstance properly.

SPInstall and SPInstallPreqs made it into the list as well. They should also only be used once per node.

All resources using Ensure as key can be used twice.

Resource Name|Uses IsSingleInstance|Comment
------|------|------
SPAntivirusSettings|-| ScanOnDownload as key
SPConfigWizard |-|Ensure as key
SPDiagnosticLoggingSettings|-|LogPath as key
SPDistributedCacheClientSettings|x
SPFarm|-|Ensure as key
SPInfoPathFormsServiceConfig|-|Ensure as key
SPInstall |-| BinaryDir as key, which would allow the side by side installation of several SP Versions
SPInstallPrereqs | - | InstallerPath as key, which could be changed for another usage of this resource
SPIrmSettings|-|Ensure as key
SPManagedMetadataServiceAppDefault|x|
SPMinRoleCompliance|-|State as key and can therefore be used two times.
SPPasswordChangeSettings|-| MailAddress as key
SPProjectServerLicense|-|Ensure as key
SPSecurityTokenServiceConfig|-
SPShellAdmins|-|Name as Key. This allow to use several SPShellAdmin resources and could allow a  not consistent setting

Changing all resources it not a must, but there are cases we should limit the usage of these resources so that consistency checks are meaningful.

The floor is open for discussions :)

**Comment by ykuijs** [comment]
Update:
SPAntivirusSettings: Implemented in fork
SPDiagnosticLoggingSettings: Implemented in fork
SPFarmAdministrators: Implemented in fork

SPConfigWizard: Planned for implementation
SPFarm: Planned for implementation
SPInfoPathFormsServiceConfig: Planned for implementation
SPInstall: Planned for implementation
SPInstallPrereqs: Planned for implementation
SPIrmSettings: Planned for implementation
SPMinRoleCompliance: Planned for implementation
SPPasswordChangeSettings: Planned for implementation
SPProjectServerLicense: Planned for implementation
SPSecurityTokenServiceConfig: Planned for implementation

SPShellAdmins: Won't implement because you can implement different settings for different databases.

**Comment by andikrueger** [comment]
@ykuijs Thank you! This was fast :+1: 

I just reviewed the SPShellAdmins Example for [multiple databases](https://github.com/PowerShell/SharePointDsc/blob/5e1291709387fb8c8d86ea4da69864d8a8b92e2c/Modules/SharePointDsc/Examples/Resources/SPShellAdmins/2-SpecificDBs.ps1). This resource can lead to issues, since I can change the name and then specify settings total different than before. Currently I do not see a perfect way around this issue. Maybe a resource per database or per user could help.

**Comment by ykuijs** [comment]
The question is: Should we make it 100% foolproof or can we expect some intelligence of the admin that is using DSC.

I think we have to expect some common sense, simply because DSC isn't an end-user technology and because making it 100% foolproof is impossible and trying to do so only makes the resource mega complex.

**Comment by ykuijs** [comment]
Especially since making such a mistake does not really result in major issues: Yes it will be inefficient, since the settings will be switched back and forth, but won't cause any downtime.

**Comment by johlju** [comment]
@ykuijs Would  single instance resource help https://docs.microsoft.com/en-us/powershell/dsc/singleinstance. Setting the Key to 'Yes' (using validateset), it can only be once such resource in the configuration.

**Comment by NikCharlebois** [comment]
I agree with the list of resources above. Just one thing to make sure though, is that some resources can have ONE instance max per NODE (e.g. SPFarm), whereas others can only have ONE instance per CONFIGURATION (e.g. SPDiagnosticLoggingSettings). 

We had discussed implementing such best practices in some resources a while ago. For example, all resources identified as Distributed in the wiki, should only appear once for all the farm. I just want to make sure we keep that in mind when implementing the change. My 2 cents

**Comment by andikrueger** [comment]
@johlju We are already implementing the single instance resource pattern. See: https://github.com/PowerShell/SharePointDsc/issues/778#issuecomment-372012732 
The challenge about the SPShellAdmins resource are the various options available...

@NikCharlebois I totally agree with you. AFAIK There is no option to guarantee a "single instance" behavior across several nodes.

I really think we are already putting great effort into making SharePointDsc as user friendly as we can.

**Comment by ykuijs** [comment]
@johlju That is exactly what I am implementing.

@andikrueger I have reviewed the resource some more and am starting to think you are right. Let me dive into this further!

**Comment by NikCharlebois** [comment]
@andikrueger Yes agreed, we are already doing our best to make it as friendly as possible. What I meant here, is that we need to make sure that some of these resources can actually be used more than once in the config, but only once per server.

**Comment by ykuijs** [comment]
I agree with you Nik, but unfortunately DSC currently has no way of enforcing that a resource can only be specified once in a configuration. The method described in the SingleInstance link that was shared before only allows us to enforce one instance per server.

**Comment by ykuijs** [comment]
I have also implemented IsSingleInstance in SPShellAdmin.

Just submitted PR #824

**Comment by ykuijs** [comment]
Merged via PR 824, closing issue
Changes will be released in v3.0
