### ISSUE TITLE
[SPManagedMetaDataServiceAppDefault] Test-TargetResource querys for a non existent Type Name and fails

### ISSUE THREAD

**Issue by ChristophHannappel** [PowerShell/SharePointDsc#779]
**Details of the scenario you try and problem that is occurring:**
I'm trying to set the Managed Metadata Service Application Proxy settings.
The DSC Configuration fails with the error:

> VERBOSE: [YFG-SP16-01]: LCM:  [ End    Test     ]  [[SPManagedMetaDataServiceAppDefault]SP-ManagedMetadataServiceAppDefault]  in 0.2630 seconds.
> PowerShell DSC resource MSFT_SPManagedMetaDataServiceAppDefault  failed to execute Test-TargetResource functionality with error message: There 
> are no Managed Metadata Service Application Proxy available in the farm 
>     + CategoryInfo          : InvalidOperation: (:) [], CimException
>     + FullyQualifiedErrorId : ProviderOperationExecutionFailure

I took a look at "SharePointDsc/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1"
on line 41 a filter tries to find a Service Application Proxy with the FullName 'Managed Metadata Service Connection'

```
        $serviceAppProxies = $serviceAppProxies | Where-Object -FilterScript {
            $_.GetType().FullName -eq "Managed Metadata Service Connection"
}
```
I checked the Fullname on my Sp2016 VM and it should be: 'Microsoft.SharePoint.Taxonomy.MetadataWebServiceApplicationProxy'
```
PS C:\Windows\system32> $msp = Get-SPServiceApplicationProxy d89e1e1c-d38c-4a78-b3b7-c9c7e0036116

PS C:\Windows\system32> $msp.GetType().fullname
Microsoft.SharePoint.Taxonomy.MetadataWebServiceApplicationProxy
```
**The DSC configuration that is using the resource:**
```
#Managed Metadata Service
        SPManagedMetaDataServiceApp SP-ManagedMetadataServiceApp
        {
            PsDscRunAsCredential = $SPSetupAccount
            Name = 'ManagedMetadataService_Default'
            ProxyName = 'ManagedMetadataService_Default Proxy'
            ApplicationPool = 'SharePoint Service Application Pool Shared'
            DatabaseName = ($ConfigurationData.NonNodeData.SPServiceDatabasePrefix + 'ManagedMetadata_Default')
            DatabaseServer = $ConfigurationData.NonNodeData.SPServiceDatabaseServer
            ContentTypeHubUrl = ($ConfigurationData.NonNodeData.SPContentBaseURL+'/sites/CTH')
            TermStoreAdministrators = @(
                $ConfigurationData.NonNodeData.SPFarmAdministratorsGroup,
                $ConfigurationData.NonNodeData.SPContentAdministratorsGroup
                )
            DefaultLanguage = 1033
            Languages = @(1031,1033)
            Ensure = 'Present'
            DependsOn = '[SPServiceAppPool]SP-SvcAppPool-Shared'
        }
        #Managed Metadata Proxy Settings
        SPManagedMetaDataServiceAppDefault SP-ManagedMetadataServiceAppDefault
        {
            PsDscRunAsCredential = $SPSetupAccount
            IsSingleInstance = 'Yes'
            DefaultSiteCollectionProxyName = "ManagedMetadataService_Default Proxy"
            DefaultKeywordProxyName = "ManagedMetadataService_Default Proxy"
            DependsOn = '[SPManagedMetaDataServiceApp]SP-ManagedMetadataServiceApp'
        }
```
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016

> Name                           Value                                                                                                            
> PSVersion                      5.1.14393.1944                                                                                                   
> PSEdition                      Desktop                                                                                                          
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                          
> BuildVersion                   10.0.14393.1944                                                                                                  
> CLRVersion                     4.0.30319.42000                                                                                                  
> WSManStackVersion              3.0                                                                                                              
> PSRemotingProtocolVersion      2.3                                                                                                              
> SerializationVersion           1.1.0.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint Server 2016

**Version of the DSC module you're using:**

> Import-DscResource -ModuleName SharePointDSC -ModuleVersion 2.1.0.0

**Comment by andikrueger** [comment]
I ran a quick test and there is something confusing:
```

PS C:\Windows\system32> (Get-SPServiceApplicationProxy)[5]

DisplayName          TypeName             Id                                  
-----------          --------             --                                  
Managed Metadata ... Managed Metadata ... 01e3304b-eba0-4d21-9ebb-cf071e40dd75

PS C:\Windows\system32> $wa = (Get-SPServiceApplicationProxy)[5]

PS C:\Windows\system32> $wa.TypeName
Managed Metadata Service Connection

PS C:\Windows\system32> $wa.GetType().fullname
Microsoft.SharePoint.Taxonomy.MetadataWebServiceApplicationProxy
```

There is a `Managed Metadata Service Connection` - this will be returned for TypeName. The used call to `GetType().FullName` returns `Microsoft.SharePoint.Taxonomy.MetadataWebServiceApplicationProxy`. 

I will submit a PR to fix this issue.
