### ISSUE TITLE
SPFarm create farm: Execution Timeout Expired

### ISSUE THREAD

**Issue by JeanNetryValere** [PowerShell/SharePointDsc#781]
Hi,
I have the following error executing SPFarm:
_PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Exception calling "ExecuteNonQuery" with "0" 
argument(s): "Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding." 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : XXXXX_

The error is raised after detecting no config and no admin database, then the creation is launched.

The configuration portion:
SPFarm CreateSPFarm
        {
            Ensure                    = "Present"
            ServerRole                = "ApplicationWithSearch"
            DatabaseServer            = $ConfigurationData.NonNodeData.SQLServer.FarmDatabaseServer
            FarmConfigDatabaseName    = $ConfigurationData.NonNodeData.SharePoint.Farm.ConfigurationDatabase
            Passphrase                = New-Object System.Management.Automation.PSCredential ('Passphrase', (ConvertTo-SecureString -String $ConfigurationData.NonNodeData.SharePoint.Farm.Passphrase -AsPlainText -Force))
            FarmAccount               = $FarmAccount
            PsDscRunAsCredential      = $SPSetupAccount
            AdminContentDatabaseName  = $ConfigurationData.NonNodeData.SharePoint.Farm.AdminContentDatabase
            RunCentralAdmin           = $true
            CentralAdministrationPort = 5000
            CentralAdministrationAuth	= "NTLM"
        }
        
The mof portion:
instance of MSFT_SPFarm as $MSFT_SPFarm1ref
{
Ensure = "Present";
 FarmConfigDatabaseName = "SP_Config";
 ServerRole = "ApplicationWithSearch";
 PsDscRunAsCredential = $MSFT_Credential1ref;
 ResourceID = "[SPFarm]CreateSPFarm";
 DatabaseServer = "SP2016SQL.xx.xx.xx\\SP2016";
 Passphrase = $MSFT_Credential2ref;
 SourceInfo = "D:\\Sources\\Scripts\\03_SP_CreateFarmNodesOnly.ps1::25::9::SPFarm";
 CentralAdministrationAuth = "NTLM";
 RunCentralAdmin = True;
 ModuleVersion = "2.1.0.0";
 ModuleName = "SharePointDSC";
 CentralAdministrationPort = 5000;
 FarmAccount = $MSFT_Credential3ref;
 AdminContentDatabaseName = "SP_AdminContent";

 ConfigurationName = "SharePointServer";

};

Installing SharePoint 2016 Enterprise on Windows Server 2016
The SharePoint Prereq et Binaries has been run successfully (Patched to January 2018 with Language Pack)
No Wizard launched.
The database has not received any connection from the machine that creating the node. No Db created. The udl test from the targeted server is ok.

Any clues ?
Many thanks

**Comment by andikrueger** [comment]
Are there any errors in the Event Logs correlated to this dsc configuration?

Is this issue reproducible? Could you try to apply the configuration a second time and  post the outcome. If the error persists: Which SharePointDsc Version are you using and are you able to start the configuration wizard and connect to your database server?

**Comment by JeanNetryValere** [comment]
Hi andikrueger,
Yes i reproduced the error a couple of times, and the Wizard was contacting the database (steps pushed to the finish). But i figured it out by using the machine FQDN. I was using mahine aliases (except for the database: SQL Alias) provided by the DC admin (i don't know the type). When i change them (Small farm) the farm has been created.

**Comment by andikrueger** [comment]
Good to hear, that you were able to create the farm.

**Comment by JeanNetryValere** [comment]
Yes me too, you can close this issue. There is maybe something to dig around alias usage, but this issue is not linked to SPFarm i guess.
