### ISSUE TITLE
SPFarm resource should be able to recreate a deleted CentralAdmin

### ISSUE THREAD

**Issue by ronx** [PowerShell/SharePointDsc#782]
**Details of the scenario you try and problem that is occurring:**
After initial provisioning, delivery resource was having problems with central admin and deleted the CA site from IIS. Re-running the DSC, SPFarm's Test-TargetResource returned true, so it skipped Set-TargetResource. Looking at the code, it seems the test function is only checking for the Ensure param and not doing further testing if the resource is supposed to provision central admin to make sure central admin is indeed provisioned. Also, Yorick, just a reminder from our chat that you mentioned you'd probably need to update Set as well, since the current method will return an error if the farm already exists.

**The DSC configuration that is using the resource:**
PLA

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WS2016, PS 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2016

**Version of the DSC module you're using:**
2.2 preview

**Comment by ykuijs** [comment]
Closed via PR #826
