### ISSUE TITLE
SPWebApplication kerberos

### ISSUE THREAD

**Issue by Bjorn80** [PowerShell/SharePointDsc#783]
**Details of the scenario you try and problem that is occurring:**
create a web application with Kerberos in sharepoint 2016

The cmd new-spwebapplication supports parameter -AuthenticationMethod 
The DSCresource SPWebApplication does not.

I would like to create my web application with kerberos AuthenticationMethod .
Any suggestions?

**The DSC configuration that is using the resource:**
        SPWebApplication MySiteWebApplication
        {
            Name                   = "MySite WebApplication"
            Ensure                 = "Present"
            ApplicationPool        = "MySiteAppPool"
            ApplicationPoolAccount = $ContentAppPoolAccountCred.username
            AllowAnonymous         = $false
            DatabaseName           = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "MySiteContent")
            DatabaseServer         = $ConfigurationData.NonNodeData.SharePoint.SqlAlias
            Url                    = ("http://" + $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Hostheader)
            Hostheader             = $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Hostheader
            Port                   = $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Port
            PsDscRunAsCredential   = $SPSetupCred
            Dependson = "[SPManagedMetaDataServiceApp]ManagedMetadataServiceApp"
        }
**Version of the Operating System and PowerShell the DSC Target Node is running:**
server 2012R2 and Powershell 5.0
**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2016
**Version of the DSC module you're using:**
2.1.0.0

**Comment by NikCharlebois** [comment]
Hi @Bjorn80 the resource does handle Kerberos. Please refer to the wiki for more details. Here is an example of how you can achieve this. You do need to leverage the new SPWebAppAuthentication resource though:

SPWebApplication MySiteWebApplication
    {
        Name = "MySite WebApplication"
        Ensure = "Present"
        ApplicationPool = "MySiteAppPool"
        ApplicationPoolAccount = $ContentAppPoolAccountCred.username
        AllowAnonymous = $false
        DatabaseName = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "MySiteContent")
        DatabaseServer = $ConfigurationData.NonNodeData.SharePoint.SqlAlias
        Url = ("http://" + $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Hostheader)
        Hostheader = $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Hostheader
        Port = $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Port
        PsDscRunAsCredential = $SPSetupCred
        Dependson = "[SPManagedMetaDataServiceApp]ManagedMetadataServiceApp"
    }

    SPWebAppAuthentication ContosoAuthentication
    {
        WebAppUrl   = ("http://" + $ConfigurationData.NonNodeData.SharePoint.UPSA.WebApplication.Hostheader)
        Default = @(
            MSFT_SPWebAppAuthenticationMode {
                AuthenticationMethod = "Kerberos"
            }
        )
        Internet = @(
            MSFT_SPWebAppAuthenticationMode {
                AuthenticationMethod = "NTLM"
            }
        )
    }

**Comment by Bjorn80** [comment]
@NikCharlebois 

I see, thank you very much!
Works like a charm!

brgs

Bjørn Roalkvam
