### ISSUE TITLE
SPTimerJobState - 2 Service Applications throws errors

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#791]
**Details of the scenario you try and problem that is occurring:**
The changes we made in 2.0.0.0 for the SPTimerJobState resource has logic to throw an error the moment a timer Job, with a Web Application Url of "N/A" (no specific Web App) has more than one instance. A customer of mine has two User Profile Service Application, which actually generates two instances of the "Service principal de profil utilisateur_SweepSync" (or whatever the English translation would be for that User_SweepSync timer job is).

The code then throws an error because the count # is not equal to 1. We should look at removing that check for exactly 1 instance. Brian Lalancette, who I'll add to this thread got an even weirder error complaining about '0' instances found (which off course is also not equal to 1....but very weird). Will continue to investigate: https://github.com/Microsoft/SharePointDSC.Reverse/issues/48

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2013

**Version of the DSC module you're using:**
2.2.0.0

**Comment by NikCharlebois** [comment]
FWIW - I can replicate the issue. Deploying the Word Automation Service App does create a new timer job with name **Word Automation Services Timer Job**, I do see it in the list when I do Get-SPTimerJob, but can't get to it by doing Get-SPTimerJob -Type "Word Automation Services Timer Job"

**Comment by ykuijs** [comment]
Closed via PR #800
