### ISSUE TITLE
Prerequisits for SP 2016 (only) hangs in offline mode

### ISSUE THREAD

**Issue by IlleNilsson** [PowerShell/SharePointDsc#792]
I'm trying to get SPInstallPrereqs to work with SP 2016 (Only) Offline.

In Online mode it works, of course. I've tested access to the local installers, and yes the PsDscRunAsCredential has access to read the installer files.

Running it offline, it just sits there, hanging. I can't find anything in the registry of target machine.

[[SPInstallPrereqs]Prerequisites] Args for prereq installer are: /unattended
 /SQLNCli:"\\DSC\Media\SPPrereqs\sqlncli.msi" /Sync:"\\DSC\Media\SPPrereqs\Synchronization.msi"
/AppFabric:"\\DSC\Media\SPPrereqs\WindowsServerAppFabricSetup_x64.exe"
/IDFX11:"\\DSC\Media\SPPrereqs\MicrosoftIdentityExtensions-64.msi"
/MSIPCClient:"\\DSC\Media\SPPrereqs\setup_msipc_x64.msi"
/KB3092423:"\\DSC\Media\SPPrereqs\AppFabric-KB3092423-x64-ENU.exe"
/WCFDataServices56:"\\DSC\Media\SPPrereqs\WcfDataServices.exe"
/DotNetFx:"\\DSC\Media\SPPrereqs\NDP47-KB3186497-x86-x64-AllOS-ENU.exe"
/MSVCRT11:"\\DSC\Media\SPPrereqs\vc_redist11.x64.exe" /MSVCRT14:"\\DSC\Media\SPPrereqs\vc_redist14.x64.exe"
/ODBC:"\\DSC\Media\SPPrereqs\msodbcsql.msi"

All Windows Server  2016 Standard

SharePoint 2016 

Latest SharePointDSC of today

**Comment by andikrueger** [comment]
Could you please check the paths to the installer files? They look odd to me. I think either a drive letter is missing or another backslash. All your paths start with \DSC\

Lately I did a few offline installations and I did use the full path to the installer files.

**Comment by NikCharlebois** [comment]
@IlleNilsson check out my blog post regarding this http://nikcharlebois.com/sharepoint-dsc-gotchas-and-best-practices/

**Comment by IlleNilsson** [comment]
The paths are \\, UNC Paths. I aggree they look funny without the first backslash in the output.

But still, just hanging without errors is not good.

I ran prerequisitsinstaller.exe from a powershsell prompt with the same arguments and briefly I got a dialog for a blink of a second. I could’nt read it.

BR // Ilian

**Comment by IlleNilsson** [comment]
SPInstallPrereqs "Prerequisites"
        {
            PsDscRunAsCredential = $SpAdminCredential
            SxsPath = "$($Node.WinSourcePath)\"
            InstallerPath = "$($Node.SpSourcePath)\PrerequisiteInstaller.exe"
            OnlineMode = $True
            SqlNCli = "$($Node.PrSourcePath)\sqlncli.msi"
            ODBC = "$($Node.PrSourcePath)\msodbcsql.msi"
            MSVCRT11 = "$($Node.PrSourcePath)\vc_redist11.x64.exe"
            MSVCRT14 = "$($Node.PrSourcePath)\vc_redist14.x64.exe"
            DotNetFX = "$($Node.PrSourcePath)\NDP47-KB3186497-x86-x64-AllOS-ENU.exe"
            IDFX11 = "$($Node.PrSourcePath)\MicrosoftIdentityExtensions-64.msi"
            AppFabric = "$($Node.PrSourcePath)\WindowsServerAppFabricSetup_x64.exe"
            KB3092423 = "$($Node.PrSourcePath)\AppFabric-KB3092423-x64-ENU.exe"
            Sync = "$($Node.PrSourcePath)\Synchronization.msi"
            WCFDataServices56 = "$($Node.PrSourcePath)\WcfDataServices.exe"
            MSIPCClient = "$($Node.PrSourcePath)\setup_msipc_x64.msi"
            Ensure = "Present"
            DependsOn = @("[xWebSite]RemoveDefaultWebSite")
        }

        @{
            NodeName = "*"
            PSDscAllowDomainUser = $True
            PsDscAllowPlainTextPassword = $True
            WinSourcePath = "D:\Sources\Sxs"
            PrSourcePath = "\\DSC\Media\SPPrereqs"
            SpSourcePath = "\\DSC\Media\SPInstaller"
            ProductKey = "XXXX”
            DatabaseServer = "QS1\INTSHPCNT"
            PivotServer = "QS1\INTSHPPVT"
            FarmConfigDatabaseName = "_FarmConfig"
            FarmContentDatabaseName = "_FarmContent"
            CentralAdministrationPort = 5500
            RunCentralAdmin = $False
        }

**Comment by IlleNilsson** [comment]
Thanks, I’ll check’em out

**Comment by IlleNilsson** [comment]
Thanks, I’ll check tommorow, gotta snooze

**Comment by IlleNilsson** [comment]
Found the problem. I had an .MSI for setup_msipc_x64.msi, found setup_msipc_x64.exe version instead and that worked. Thanks for pointing me in the right direction.
