### ISSUE TITLE
SPUserProfileSyncConnection missing filter disabled users

### ISSUE THREAD

**Issue by blysspluss** [PowerShell/SharePointDsc#794]
**Details of the scenario you try and problem that is occurring:**

**The DSC configuration that is using the resource:**
MSFT_SPUserProfileSyncConnection
**Version of the Operating System and PowerShell the DSC Target Node is running:**
Server 2016, powershell 5.1
**Version of SharePoint that is used (e.g. SharePoint 2016):**
Sharepoint 2016
**Version of the DSC module you're using:**
Release 2.2

The powershell add-spprofilesyncconnection has a few extra params that are not available via this DSC resource. Most importantly the ability to filter disabled users via the -ConnectionUseDisabledFilter param. It would be excellent to add this to a future release.

**Comment by ykuijs** [comment]
Implemented in my next Bugfix PR

**Comment by ykuijs** [comment]
Fixed in PR #811

**Comment by ykuijs** [comment]
PR merged, closing issue
