### ISSUE TITLE
Error for SP 2016 for SPInstallPrereqs resource 

### ISSUE THREAD

**Issue by Harish9211** [PowerShell/SharePointDsc#796]
Hi All,

I am trying to create DSC script for SP 2016 prereqs and getting below error. I am installing it on Server 2016 and its SP 2016 so not sure why i am getting error for SP 2013. As per SharePointDSC KBs SP 2016 is supported.

PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error 
message: A known issue prevents installation of SharePoint 2013 on servers that have .NET 4.6 already 
installed. See details at https://support.microsoft.com/en-us/kb/3087184 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : LocalHost

My script looks like below
===================

Configuration MIMSharePoint
{
    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName SharePointDSC
    Node LocalHost
    {
        SPInstallPrereqs SPPreReqs
        {
            InstallerPath = "C:\Sharepoint Extract\prerequisiteinstaller.exe"
            OnlineMode = $false
            AppFabric = "C:\SPPrereqs\WindowsServerAppFabricSetup_x64"
            IDFX = "C:\SPPrereqs\Windows6.1-KB974405-x64.msu"
            SQLNCli = "C:\SPPrereqs\msodbcsql.msi"
            PowerShell = "C:\SPPrereqs\Windows6.1-KB2506143-x64.msu"
            Sync = "C:\SPPrereqs\Synchronization.msi"
            IDFX11 = "C:\SPPrereqs\MicrosoftIdentityExtensions-64.msi"
            MSIPCClient = "C:\SPPrereqs\setup_msipc_x64.msi"
            WCFDataServices = "C:\SPPrereqs\WcfDataServices.exe"
            MSVCRT14 =  "C:\SPPrereqs\vc_redist.x64.exe"
            Ensure = "Present"
            
        }  
    }
}

MIMSharePoint
Start-DscConfiguration -Path .\MIMSharePoint -Wait -Verbose -Force

**Comment by andikrueger** [comment]
Could you please double check the parameter values for this resource. I think there is an error for the Windows Server App Fabric installer path. 
Are you missing the file extension: ".exe"?
Hope this helps.

**Comment by Harish9211** [comment]
Thank you for the response.

I just found out the issue, its my mistake, i thought i am using SP2016 but
it was SP2016. I got to know when i checked SharePointDSC resource script
file.

**Comment by ykuijs** [comment]
Closing the issue since it has been solved
