### ISSUE TITLE
SharePointDsc: Update labels to the same as other resource modules in Dsc Resource Kit

### ISSUE THREAD

**Issue by johlju** [PowerShell/SharePointDsc#798]
**Details of the scenario you try and problem that is occurring:**
@ykuijs @NikCharlebois  I would like to suggest to update the labels to match the name, color and description as other resource modules in DSC Resource Kit. If so I will update these labels for you, but want your approval first so this doesn't mess up any process you got going, because it will change the color on some, and name on some. 

See issue https://github.com/PowerShell/DscResources/issues/364.
See labels here; https://github.com/PowerShell/PSDscResources/labels

This will help in the future if we can get more automation around issues and PR's, see issue https://github.com/PowerShell/DscResources/issues/365. It will also help us to have the [Waffle board](https://waffle.io/powershell/dscresources) working better if we use the same labels. 

**The DSC configuration that is using the resource:**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of SharePoint that is used (e.g. SharePoint 2016):**
n/a

**Version of the DSC module you're using:**
n/a

**Comment by johlju** [comment]
I will make sure all issues and PR's keep the correct labels of course, even if they change name slightly. 🙂

**Comment by NikCharlebois** [comment]
Thanks Johan,

I personally don't see any issues with the change. I will let @ykuijs confirm, but I would say go ahead.

**Comment by johlju** [comment]
Awesome! Will do this in the beginning of next week unless I hear anything else. 

/cc @ykuijs

**Comment by ykuijs** [comment]
Great idea, go ahead!

**Comment by johlju** [comment]
@NikCharlebois @ykuijs labels updated, and all open issues labeled. If you could label new issues that come in I would appreciate it, especially 'Help wanted' if you want the community to work on an issue. If you see there are easier issues, then please label those 'good first issue' so new contributors can jump on board easier.
Thanks!
