### ISSUE TITLE
SPWebAppPropertyBag: new resource: Set Properties on web application level

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#799]
**Details of the scenario you try and problem that is occurring:**
Currently there is no resource available that allows to set property bag values at the web application level. There is a resource available to set the farm property bag.

There should be a resource that allows setting web application property bag values. There are the following options:

1. Extend SPWebApplication resource: Add a new parameter that consumes a custom object 
2. Create a new resource SPWebAppPropertyBag

@ykuijs @NikCharlebois What do you prefer?

**Comment by ykuijs** [comment]
To keep it consistent with the Farm resource I prefer a new resource. Also because there are already several other specific resources for configuring web app settings.

**Comment by jensotto** [comment]
@ykuijs I can try start working on this.

**Comment by ykuijs** [comment]
@jensotto Sure, it is all yours!
