### ISSUE TITLE
SPUserProfileProperty: Allow several mapping connections

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#801]
**Details of the scenario you try and problem that is occurring:**
Currently we are working with a customer that uses several mapping connections for one User Profile Property.

With the current resource, there is no support to set several mapping connections for one property. 

Adding this capability would result in a breaking change. We would have to add a new custom type to make the resource more versatile. I can think of a addition like this:

Current state of resource:
```
SPUserProfileProperty WorkEmailProperty
{
    Name = "WorkEmail2"
    Ensure = "Present"
    UserProfileService = "User Profile Service Application"
    DisplayName = "Work Email"
    Type = "Email"
    Description = "" #implementation isn't using it yet
    PolicySetting = "Mandatory"
    PrivacySetting = "Public"
    MappingConnectionName = "contoso.com"
    MappingPropertyName = "mail"
    MappingDirection = "Import"
    Length = 10
    DisplayOrder =25 
    IsEventLog =$false
    IsVisibleOnEditor=$true
    IsVisibleOnViewer = $true
    IsUserEditable = $true
    IsAlias = $false 
    IsSearchable = $false 
    TermStore = ""
    TermGroup = ""
    TermSet = "" 
    UserOverridePrivacy = $false
    PsDscRunAsCredential = $SetupAccount
}
```

Proposed change:

```
SPUserProfileProperty WorkEmailProperty
{
    Name                 = "WorkEmail2"
    Ensure               = "Present"
    UserProfileService   = "User Profile Service Application"
    DisplayName          = "Work Email"
    Type                 = "Email"
    Description          = "" #implementation isn't using it yet
    PolicySetting        = "Mandatory"
    PrivacySetting       = "Public"
    Mapping              = @(
        MSFT_SPUserProfilePropertyMapping {
            ConnectionName = "contoso.com"
            PropertyName   = "mail"
            Direction      = "Import"
        }
    )
    Length               = 10
    DisplayOrder =25 
    IsEventLog =$false
    IsVisibleOnEditor=$true
    IsVisibleOnViewer    = $true
    IsUserEditable       = $true
    IsAlias              = $false 
    IsSearchable         = $false 
    TermStore            = ""
    TermGroup            = ""
    TermSet              = "" 
    UserOverridePrivacy  = $false
    PsDscRunAsCredential = $SetupAccount
}
```

**Comment by johlju** [comment]
@andikrueger would MSFT_SPUserProfilePropertyMapping suit better as it own resource if it is possible to add and remove individual mappings? Or is it only possible to add mapping as part of the property?

**Comment by andikrueger** [comment]
One user profile property can have 0-n mappings. 
A new resource SPUserProfilePropertyMapping could solve this issue too, but would still be a breaking change, as we would have to remove the three mapping specific parameters from the SPUserProfileProperty resource. 

The new resource will need at least the following parameters:

- PropertyName (key)
- UserProfileService (key)
- mapping direction
- mapping connection 
- mapping direction

I think, staying with the current resource is the better way, but this is just a feeling.

**Comment by johlju** [comment]
My thought was if we wanted an `Ensure` parameter to be able to remove mappings too. If there is no need to remove mappings, or not possible to remove mappings, then I see no benefit to having it as a separate resource. But if we should be able to remove mappings then a separate resource seem the best approach. If there are duplicated code that could potentially be solved by helper functions. 

Agree that it's still a breaking change since we should remove existing functionality from the other resource if we move out that functionality.

**Comment by andikrueger** [comment]
Having an `Ensure` parameter seems to be nice, but we get the same result, if we remove an item from the `MSFT_SPUserProfilePropertyMapping` array.

From a performance side, I think a single resource would be better. In the Get-/Test- Methods, we would need to instantiate some SharePoint objects only once. If we pack these parts into a single resource, we would have to instantiate the same objects several times.

**Comment by johlju** [comment]
I'm good with that.

**Comment by ykuijs** [comment]
Will you be implementing this change @andikrueger? Or do you want to leave it up for grabs?

**Comment by andikrueger** [comment]
I started working on this issue. Unfortunately, I ran out of time back then... 
Next week I'm going to be traveling a lot by train. I hope, I can prepare a new branch for this issue and integrate the gist into the current methods. The gist is a draft version on how to retrieve the mappings properly for an AD Connection: [Get-SPUserProfilePropertyMapping.ps1](https://gist.github.com/andikrueger/ddfb769a6069f3abcd85f6b3462b834c) 

@ykuijs What's your opinion on extending the current resource?

**Comment by ykuijs** [comment]
Hi @andikrueger I lost track of this issue, my apologies. I agree with you that we should extend this resource. If a mapping exists in SharePoint, which is not in the MSFT_SPUserProfilePropertyMapping array, we should remove it. That way we make sure the exact array is configured in SharePoint.

**Comment by ykuijs** [comment]
Hi @andikrueger Since this is a breaking change, I would like to include this in the v3.0 release (we only release breaking changes in major releases).

That version is planned to be released shortly after the release of SharePoint 2019, which is planned for later this month. Would it be possible to submit this PR at short notice, so we can have it included with v3.0?

**Comment by andikrueger** [comment]
I will see what I can do. The Get-Method and Set-Methods are close to ready. I think the testing will be troublesome and needs additional integration tests.

**Comment by andikrueger** [comment]
I will push my changes to this [branch](https://github.com/andikrueger/SharePointDsc/tree/issue-801-v3.0). Currently I need to setup a new test environment with a minimum of two connections - doh!
