### ISSUE TITLE
Installed with ServerRole (MinRole) but Services are not deployed

### ISSUE THREAD

**Issue by PSchicht** [PowerShell/SharePointDsc#802]
Hi!

I'm installing a small server farm and having trouble with the ServerRole (MinRole) configuration. The configuration I'm using is this (For the application server):
```
SPFarm CreateSPFarm
        {
            Ensure                   = "Present"
            DatabaseServer           = $node.DatabaseServer
            FarmConfigDatabaseName   = $node.FarmConfigDatabaseName
            Passphrase               = $node.Passphrase
            FarmAccount              = $node.FarmAccount
            PsDscRunAsCredential     = $node.SetupAccount
            AdminContentDatabaseName = $node.AdminContentDatabaseName
	    ServerRole               = "ApplicationWithSearch"
            RunCentralAdmin          = $true
	    CentralAdministrationPort = 30000
        }
```
But no service applications have been created and configured.

My understanding is that with the minrole configuration, the default service application topology should be created automatically. Or is it necessary to specify the service applications and service instances manually regardless of the ServerRole usage?

Thx for your help!

**Comment by NikCharlebois** [comment]
@PSchicht You'll still need to define the SA you want. MinRole just determines what will be allowed to be created and where it will run. It doesn't automatically create the topology.

**Comment by PSchicht** [comment]
@NikCharlebois Thank you for clearing this up! I expected it to work more like the standard SharePoint installer :)

**Comment by NikCharlebois** [comment]
Glad to help. @ykuijs please close the issue when you get a chance. Cheers!

**Comment by johlju** [comment]
Closing this issue as per previous comment.
