### ISSUE TITLE
SPUserProfileSyncConnection: Connection get's recreated every time if the name contains a dot

### ISSUE THREAD

**Issue by cvollmann** [PowerShell/SharePointDsc#804]
**Details of the scenario you try and problem that is occurring:**

We're adding multiple sync connections to the UPS.
If the name for the connection contains a ".", this connections is recreated every time you run the script.
We were able to "fix" it, by replacing the dots with hyphens (see code below).

The connection was already beeing named with the hyphen in SP, even without replacing the dot. So if the forest is "ads.foobar.de" it shows up as: Name "ads-foobar-de" and forest "ads.foobar.de".

    $SharePointConfigData.Services.UserProfiles.SyncConnections | ForEach-Object -Process {
        SPUserProfileSyncConnection $_.Forest
        {
            Name                  = $_.Forest.Replace(".", "-")
            Forest                = $_.Forest
            UserProfileService    = $SharePointConfigData.Services.UserProfiles.Name
            IncludedOUs           = $_.IncludedOUs
            ConnectionType        = $connectionType
            ConnectionCredentials = $UpsSyncAccount
            UseSSL                = $false

            DependsOn             = "[SPUserProfileServiceApp]UserProfileServiceApp"
            PsDscRunAsCredential  = $SpSetupAccount
        }
    }

**Example from our configuration file:**

    SyncConnections  = @(
        @{
            Forest      = "adm.bla.blub.ads.foobar.de"
            IncludedOUs = @(
                "CN=MANAGED SERVICE ACCOUNTS,DC=ADM,DC=SWE,DC=baz,DC=ADS,DC=foobar,DC=DE",
                "CN=USERS,DC=ADM,DC=SWE,DC=baz,DC=ADS,DC=foobar,DC=DE",
                # <snip>
                "OU=TESTSERVERS,DC=ADM,DC=SWE,DC=baz,DC=ADS,DC=foobar,DC=DE"
            )
        },
        @{
            Forest      = "ADS.foobar.COM"
            IncludedOUs = @(
                "CN=USERS,DC=ADS,DC=foobar,DC=COM",
                # <snip>
                "OU=RO,DC=ADS,DC=foobar,DC=COM"
            )
        }
        # <snip>
    }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, PowerShell 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2016

**Version of the DSC module you're using:**
2.1.0.0

**Comment by ykuijs** [comment]
I am working on an update for this resource in my next bugfix PR. I will investigate this issue and implement a fix at the same time!

**Comment by ykuijs** [comment]
Fixed in PR #811

**Comment by ykuijs** [comment]
PR merged, closing issue
