### ISSUE TITLE
Hanging att prerequisits install

### ISSUE THREAD

**Issue by IlleNilsson** [PowerShell/SharePointDsc#807]
Hanging att prerequisits install. Found all the missbeaving prerequisits, disabled UAC and still hanging.

SPInstallPrerequisits

Windows Server 2016 Standard Edition (Deskstop Experence)

SharePoint 2016

DSC is latest of today

If i manualy reboot target servers the next forced Start-DscConfiuguration works, sometime.

Any help appriciated. // Ilian

**Comment by NikCharlebois** [comment]
Are you installing form a Shared location or are the files local on the server?

**Comment by IlleNilsson** [comment]
They are on a share. I could add the share servers address to trusted sites, but why does it work when i forcefully restart machines and Start-DscConfiguration again?

**Comment by NikCharlebois** [comment]
Well, some of the prerequisites (i.e. .NET) may introduce a pending reboot. If you run Get-DSCLocalConfigurationManager, what are the values for properties RebootNodeIfNeeded and ActionAfterReboot ?

**Comment by IlleNilsson** [comment]
The are set to $True and continue after reboot. How ever. I have now discarder DscResource xPendingReboot and xUAC and run a prescript over all farm nodes (Disable-UAC.ps1 script by Vincent BootsI), and also …


    ### Enable double hop kerberos authentication via delegation to machines roled OpsDsc
    $FarmNodes | ? { $_.Role -eq "OpsDsc" } |
        % { Set-ADComputer -Identity $_.Node -PrincipalsAllowedToDelegateToAccount @(
            $FarmNodes | ? { $_.Role -ne "OpsDsc" } |
                % { Get-ADComputer -Identity $_.Node } ) }

    ### Set other than OpsDsc roled machines to trust OpsDsc roled machines
    $FarmNodes | ? { $_.Role -ne "OpsDsc" } |
        % { Invoke-Command -ComputerName $_.Node -ScriptBlock {
                param([array]$FarmNodes)
                $FarmNodes | ? { $_.Role -eq "OpsDsc" } | 
                    % { Set-Item -Path "WSMan:\localhost\Client\TrustedHosts" -Value $_.Node -Concatenate -Force -Verbose } 
                } -ArgumentList (,$FarmNodes) -Verbose }

Then rebooted nodes, and then it works on Windows Server 2016, for SharePoint 2016

I'm just trying to get to the goal, so I just may overwork things. But it is working in a repetable matter now. 

Thanks for your efforts and support.

**Comment by ykuijs** [comment]
Closing the issue per previous comment
