### ISSUE TITLE
new resource: SPSiteUrl

### ISSUE THREAD

**Issue by shurick81** [PowerShell/SharePointDsc#808]
**Details of the scenario you try and problem that is occurring:**
I need to set up a URL for site collection via DSC. I can try to use Script resource and use `Set-SPSiteUrl` but it's always better to have an industrial tool then inventing a one for myself. 

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 10, WMF 5.1.

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2016

**Version of the DSC module you're using:**
2.2

**Comment by ykuijs** [comment]
Am on it.
