### ISSUE TITLE
SPUserProfileSyncConnection Reflection not working.

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#809]
**Details of the scenario you try and problem that is occurring:**
Need to change the way we dynamically obtain the Methods using reflection from the UserProfiles.dll in order to ensure portability.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2016

**Version of the DSC module you're using:**
2.3.0.0

**Comment by ykuijs** [comment]
I discovered these issues as well while implementing fixes for other issues in this resource. Have already implemented fixes which will be in my next bugfix PR

**Comment by ykuijs** [comment]
Fixed in PR #811

**Comment by ykuijs** [comment]
PR merged, closing issue
