### ISSUE TITLE
SPDistributedCacheService Why this resource wait 30 minutes for stopping serviceinstance

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SharePointDsc#812]
**Details of the scenario you try and problem that is occurring:**
Why we have to wait that spservice instance is stopped:
[[SPDistributedCacheService]APPLICATION_SpsEnableDistributedCache_Master] 10:36 - Waiting for distributed cache to stop on all servers (waited 0 of
 30 minutes)
Workaround: kill the AppFabric process.

**The DSC configuration that is using the resource:**
```
SPDistributedCacheService APPLICATION_SpsEnableDistributedCache
{
  PsDscRunAsCredential = $SvcSPSetup
  Name                 = 'AppFabricCachingService'
  Ensure               = 'Present'
  CacheSizeInMB        = 1024
  ServiceAccount       = $SvcSPAppFabric
  CreateFirewallRules  = $true
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012 R2 / PowerShell 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
Sharepoint 2013

**Version of the DSC module you're using:**
2.2.0.0

**Comment by andikrueger** [comment]
Link to #786 as they are related.

**Comment by ykuijs** [comment]
When you stop the DC service on a server, you have the options to gracefully shutdown the service or kill it. With a graceful shutdown, all objects in the cache are transferred to other DC servers in the farm before the DC service is stopped. This will take some time, but will ensure that you won't lose any cached objects.

When killing the AppFabric process, you lose all the objects in the cache which has a performance impact (objects have to be retrieved from the database again when they are needed) and a data loss impact (some objects are only stored in the DC and not in the database):

`Tags and document activities are saved only to the Feed Cache. Tags and document activities are not persisted to content databases. When the Distributed Cache service is stopped, tags and document activities are lost.`

Source: https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service#start-and-stop-the-distributed-cache-service

That is why this time-out has been built-in.

**Comment by ykuijs** [comment]
And this time-out is a maximum time-out. If the service stops in two minutes, the resource also continues with the next steps.

**Comment by luigilink** [comment]
You're right @ykuijs  after a few test, the resource continues with the next steps. The service stops in a few minutes (never the same time, but it doesn't matter)
Thank you. You can close this issue.
