### ISSUE TITLE
SPUserProfileSyncConnection issue with connection name

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#813]
**Details of the scenario you try and problem that is occurring:**
There is still a possibility that the connection was created via the Central Admin interface, in which case the connection name could contain periods (ex: contoso.com). The Get-TargetResource replaces the '.' by '-' at the beginning, resulting in invalid connection name, and the rest of the function can't extract information from it. I recommend we don't try to rename the connection.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2012 R2 PoSh 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2013 and 2016

**Version of the DSC module you're using:**
2.3.0.0

**Comment by NikCharlebois** [comment]
Wanted to add more context to this issue. It is true that when we create a connection using PowerShell, that the '.' get replace by '-'. But DSC is more than just about configuration, it is about monitoring. Assume the case where the users already have an existing farm for which they created connections manually, say they are named contoso.com. If the user wants to write a DSC to apply to that existing farm so that it now leverages the monitoring power of DSC, we need to allow them to specify '.' in their names so that DSC will find a match between the existing connection and what is defined within DSC.

**Comment by ykuijs** [comment]
Agree, but I think it is important to also add a warning message when using a dot and SP2016 stating that this might cause issues (trying to create the connection over and over again).

**Comment by ykuijs** [comment]
Closed via PR #814
