### ISSUE TITLE
SharePoint 2019

### ISSUE THREAD

**Issue by shurick81** [PowerShell/SharePointDsc#815]
**Details of the scenario you try and problem that is occurring:**
It would be nice if at least SPFarm resource could work with SharePoint 2019. I hope you have some early access to the new version of the SP and you have opportunity to adjust this module.

**The DSC configuration that is using the resource:**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2019

**Version of the DSC module you're using:**

**Comment by NikCharlebois** [comment]
Due to the current NDA nature of SharePoint 2019, the SPDSC bits that support that version cannot be place on a public repository. However, we do have a commitment to make them available on day 1 when the Public Beta gets released.

**Comment by ykuijs** [comment]
Question has been answered. Closing issue.

**Comment by shurick81** [comment]
Now SP 2019 Preview is released, is there any plan to include support of this version in SharePointDsc 2.4?

**Comment by andikrueger** [comment]
Have a look at this blog post by @NikCharlebois [SHAREPOINTDSC STARTER TEMPLATE FOR SHAREPOINT 2019](http://nikcharlebois.com/sharepointdsc-starter-template-for-sharepoint-2019/)

Check out this [v3.0 development branch](https://github.com/PowerShell/SharePointDsc/tree/v3.0-development). This branch contains all current preps for SharePoint 2019.

**Comment by NikCharlebois** [comment]
The preview branch will be submitted as a PR shortly. The existing 3.0 branch on github does not yet have the 2019 bits. Apologies for the conflicting info

**Comment by shurick81** [comment]
Thanks for all the answers colleagues. @NikCharlebois, does this mean we will soon be able to install preview version from PS galery or should we take it directly from github branch?

**Comment by NikCharlebois** [comment]
@shurick81 the plan is to release 3.0 to the PoSh Gallery the same day SP2019 hits GA. Until then, GitHub will be the main repository.

**Comment by shurick81** [comment]
Hello colleagues, is there any updates regarding the schedule for 3.0 version?

**Comment by ykuijs** [comment]
Hi @shurick81, we are in the final stages of testing v3.0 with SP2019. I expect the release to happen soon.
