### ISSUE TITLE
SPCacheAccounts incorrectly fails test when SetWebAppPolicy is false

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#818]
**Details of the scenario you try and problem that is occurring:**
When SPCacheAccounts are defined with SetWebAppPolicy set to $False and the cache accounts are added to the web app policy either manually or by SPWebAppPolicy, Test-DscConfiguration fails on the SPCaceAccounts. This is because the test implementation of SPCaceAccounts expects that if SetWebAppPolicy is false then the cache accounts should not exist in the web application policy.
According to the documentation this should be possible, but in effect it's impossible to set SetWebAppPolicy to false unless the cache accounts are never configured in the web application policy, which is of little or no use.
When SetWebAppPolicy is set to false the test should not consider if the web application policy for cache users are set or not.

**The DSC configuration that is using the resource:**
        SPCacheAccounts CacheAccounts
        {
            SetWebAppPolicy = $False;
            SuperUserAlias = $SPCacheUserCredential.UserName;
            WebAppUrl = "http://webappurl/";
            PsDscRunAsCredential = $SPSetupCredential;
            SuperReaderAlias = $SPCacheReadCredential.UserName;
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2
WMF 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2013

**Version of the DSC module you're using:**
2.2.0.0

**Comment by ykuijs** [comment]
I see what you mean. Will correct this in a future bugfix PR.

**Comment by ykuijs** [comment]
Closed via PR #826
