### ISSUE TITLE
WSS_UsageApplication database

### ISSUE THREAD

**Issue by IlleNilsson** [PowerShell/SharePointDsc#819]
When implementing MinRole via DSC, all of a suthen a new database occurs WSS_UsageApplication.

SPSearch*

WS 2016 latest bits

SharePoint 2016 latest bits

SharePointDsc latest bits

I would like to control the name of the database for retention, backup & restore reasons.

Any help appriciated

BR // Ilian

**Comment by ykuijs** [comment]
Hi @IlleNilsson Can you share the config you are using?

**Comment by IlleNilsson** [comment]
Yes, but it has to be in private confidence. The SharePoint installation is for a Swedish defense object.

If that is ok, and you promise to not forward the specifics.

Then yes, I can share it with you.

BR // Ilian

**Comment by ykuijs** [comment]
Just send you an email directly to which to can share your config.

**Comment by ykuijs** [comment]
Issue has been solved. Closing issue
