### ISSUE TITLE
Simplify QuotaTemplate for SPSite

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#829]
**Details of the scenario you try and problem that is occurring:**
Currently, if we wish to specify a Quota template for a new SPSite, we need to pass in its ID which is an integer we have no control over. We should modify this to also accept the name of the QuotaTemplate, not just the id.

**The DSC configuration that is using the resource:**
This will error out, saying that Quota for the SPSite can't be found.

        SPQuotaTemplate RegularQuota
        {
            Name                        = "RegularQuota"
            StorageMaxInMb              = 2048
            StorageWarningInMb          = 1600
            MaximumUsagePointsSolutions = 400
            WarningUsagePointsSolutions = 360
            PSDSCRunAsCredential        = $credsDomainAdmin
            DependsOn                   = "[SPWebApplication]Root"
        }

        SPSite RootSite
        {
            Name                     = "Root Site Collection"
            Url                      = "http://root.contoso.com"
            OwnerAlias               = "contoso\lcladmin"
            ContentDatabase          = "Root_Content_DB"
            HostHeaderWebApplication = "http://root.contoso.com"
            Description              = "Root Site Collection"
            Template                 = "STS#0"
            QuotaTemplate            = "RegularQuota"
            PSDSCRunAsCredential     = $credsSPSetup
            DependsOn                = "[SPQuotaTemplate]RegularQuota"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2016

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SP2016

**Version of the DSC module you're using:**
2.3.0.0

**Comment by ykuijs** [comment]
This will be a breaking change, so will have to wait for implementation in v3.0. Agree?
