### ISSUE TITLE
SPSearchContentSource Support for LoB

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#830]
**Details of the scenario you try and problem that is occurring:**
Currently, the SPSearchContentSource resource doesn't support 'Business' type. Since this is a very common scenario with clients, we need to add support for it. However, this may open another can of worms since we currently don't have any resources to support BDC schemas. 

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of SharePoint that is used (e.g. SharePoint 2016):**
2013, and 2016

**Version of the DSC module you're using:**
2.3.0.0

**Comment by ykuijs** [comment]
Closed via PR #831
