### ISSUE TITLE
SPDiagnosticsProvider 'Enabled' is a ReadOnly property

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#846]
**Details of the scenario you try and problem that is occurring:**
SPDiagnosticsProvider have incorrect implementation!
The error report: 'Enabled' is a ReadOnly property
I check implementation code and is not correct because get object and try to update the property "Enable" that is read-only.
The right code for enable = $true must be similar at:
$diagnosticProvider | Set-SPDiagnosticsProvider -Enable

**The DSC configuration that is using the resource:**
SPDiagnosticsProvider BlockingQueryProvider
            {
                Ensure = "Present"
                Name = "job-diagnostics-blocking-query-provider"
                Enabled = $true
                PsDscRunAsCredential = $Credssp_admin;
                Retention = 7 
            }
**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2016
**Version of the DSC module you're using:**
last

**Comment by johlju** [comment]
Sounds like a bug. Labeled it as such, and also labeled it 'help wanted' so that anyone in the community can run with it, and send in a PR.

**Comment by ykuijs** [comment]
The code was calling the incorrect methods. Have updated the code, which will be included in my next PR

**Comment by ykuijs** [comment]
Closed via PR #850
