### ISSUE TITLE
SPLogLevel - 'High' is not supported or valid for property 'TraceLevel'

### ISSUE THREAD

**Issue by kflamand** [PowerShell/SharePointDsc#848]
**Details of the scenario you try and problem that is occurring:**

I'm trying to configure Event Throttling with SPLogLevel resource.
It seems "High" value is missing from MSFT_SPLogLevelItem class. Am I missing something?

Error: 
SharePointDsc\MSFT_SPLogLevelItem : At least one of the values 'High' is not supported or valid for property 'TraceLevel' on class 'MSFT_SPLogLevelItem'. Please specify only supported values: 
None, Unexpected, Monitorable, Medium, Verbose, VerboseEx, Default.

**The DSC configuration that is using the resource:**

        SPLogLevel SharePointFoundationLogLevel
        {
	        Name = "SharePointFoundationCustom"
	        SPLogLevelSetting = @(
		        MSFT_SPLogLevelItem {
			        Area           = "SharePoint Foundation"
			        Name           = "*"
			        TraceLevel     = "High"
			        EventLevel     = "Default"
		        }
	        )
	        PsDscRunAsCredential = $SetupAccount
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2016 / PowerShell 5

**Version of SharePoint that is used (e.g. SharePoint 2016):**

SharePoint 2016

**Version of the DSC module you're using:**

2.4

**Comment by johlju** [comment]
That option is missing in the schema.mof

https://github.com/PowerShell/SharePointDsc/blob/eacaf4f57df1737280730da8c1f378d3cec11045/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.schema.mof#L6

**Comment by ykuijs** [comment]
Closed via PR #850
