### ISSUE TITLE
SPAppCatalog should automatically handle required farm account credentials

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#855]
Using SPAppCatalog requires use of the farm account according to the documentation. This will not work as long as the farm account is not member of the local administrators group. This will result in a access denied when trying to execute the resource.

Could the resource implement the same functionality to temporarily add the farm account as local administrator and get the farm account credentials automatically from SharePoint like it has been done for the SPUserProfileServiceApp? This way the Install account can be specified for the PsDscRunAsCredential parameter.

**The DSC configuration that is using the resource:**

        SPAppCatalog AppCatalog
        {
            PsDscRunAsCredential = $SPFarmCredential;
            SiteUrl = "http://farm/sites/app-catalog";
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2
PowerShell 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2013

**Version of the DSC module you're using:**
2.4.0.0

**Comment by johlju** [comment]
I'm labeling this as an enhancement, and help wanted so that anyone in the community can pick this up.

**Comment by johlju** [comment]
@ykuijs please relabel if my conclusion was wrong.

**Comment by ykuijs** [comment]
@jensotto Good point, that is what we do in SPUserProfileServiceApp. Wasn't aware that this resource required the farm account as well. Thanks for your suggestion!

**Comment by ykuijs** [comment]
Implemented, will be included in my next PR
