### ISSUE TITLE
Update conflict when creating User Profile Service Application

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#856]
Creating a new User Profile Service Application when specifying either EnableNetBIOS or NoILMUsed or both results in an update conflict:
Exception calling "Update" with "0" argument(s): "An update conflict has occurred, and you must re-try this action. The object UserProfileApplicati
on Name=User Profile Service Application was updated by <FarmAccount> , in the wsmprovhost (3292) process, on machine <ProvisioningServer>.  Vi
ew the tracing log for more information about the conflict."

It seems that this line is responsible for the error:
https://github.com/PowerShell/SharePointDsc/blob/5b508e036dfa76b020a263541507fe0f732a4048/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L406
Maybe the service application should be refetched from the farm and the operation retried.

**The DSC configuration that is using the resource:**

        SPUserProfileServiceApp UserProfileService
        {
            PsDscRunAsCredential = $SPSetupCredential;
            ApplicationPool = "SharePoint Web Services";
            ProxyName = "User Profile Service Application";
            ProfileDBName = "SP_Profile";
            NoILMUsed = $false;
            Name = "User Profile Service Application";
            SocialDBName = "SP_Social";
            Ensure = "Present";
            EnableNetBIOS = $true;
            SyncDBServer = $ConfigurationData.NonNodeData.SyncDBServer;
            ProfileDBServer = $ConfigurationData.NonNodeData.ProfileDBServer;
            SyncDBName = "SP_Sync";
            SocialDBServer = $ConfigurationData.NonNodeData.SocialDBServer;
            MySiteHostLocation = http://mysite
            MySiteManagedPath = /personal
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2
PowerShell 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2013

**Version of the DSC module you're using:**
2.4.0.0

**Comment by ykuijs** [comment]
Fix will be implemented in my next PR
