### ISSUE TITLE
SPUserProfileServiceApp is unable to set SiteNamingConflictResolution

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#857]
**Details of the scenario you try and problem that is occurring:**

SPUserProfileServiceApp does not provide any means of configuring SiteNamingConflictResolution. This is part of the New-SPProfileServiceApplication command, so it should be surfaced into the SPUserProfileServiceApp resource

**The DSC configuration that is using the resource:**

N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2
PowerShell 5.1

**Version of SharePoint that is used (e.g. SharePoint 2016):**
SharePoint 2013

**Version of the DSC module you're using:**
2.4.0.0

**Comment by ykuijs** [comment]
Is trying to implement this functionality, however I have a hard time retrieving the configured value. When I run the following code, a value is returned:
`
$ca = Get-SPWebApplication -IncludeCentralAdministration | Where-Object -FilterScript {$_.IsAdministrationWebApplication}
$caSite = $ca.Sites[0]
$serviceContext = Get-SPServiceContext($caSite)
$userProfileManager = New-Object Microsoft.Office.Server.UserProfiles.UserProfileManager($serviceContext)
$userProfileManager.PersonalSiteFormat
`
However if I then configure a different value using
`
Set-SPProfileServiceApplication -Identity $ups -SiteNamingConflictResolution Resolve -MySiteHostLocation <MYSITE_URL>
`
I see that the radio button changes in Central admin, however when I run the above code again, I get the same result as before.

Does anybody know how to retrieve this info?

**Comment by jensotto** [comment]
@ykuijs I think this is because the values are cached. If you update the User Profile Service Application using the Set-SPProfileServiceApplication SharePoint uses the User Profile Service Application to persist the data. If you use the UserProfileManager SharePoint uses the User Profile Service Application **Proxy** to read and persist the data. The cache is reset only for the object that is used when committing data. This is why you get the old value back when querying the UserProfileManager after updating the value with Set-SPProfileServiceApplication. The properties page uses the User Profile Service Application, so the cache has been cleared and you see the updated data.
If you on the other hand use the User Profile Manager to update the data the proxy cache is cleared. The properties page does not seem to use any cache, so the value is correct on that page no matter what method is used to update the name format.
You can check this out if you look at the methods ClearPartitionPropertiesCache and ComminPersonalSiteSettings methods in the class Microsoft.Office.Server.UserProfiles.PersonalSiteConfiguration in the 
Microsoft.Office.Server.UserProfiles assembly.

Conclusion is to use the User Profile Manager to read **and** write the data, and **not** use Set-SPProfileServiceApplication

**Comment by jensotto** [comment]
An alternative approach could be to use both methods so that both the caches are cleared.

**Comment by ykuijs** [comment]
Hi @jensotto, I did some further testing and saw that when I restart PowerShell, the code returns the correct value. So you are correct, it is a caching issue.

I then tested updating the value via the UserProfileManager object, it is updated correctly and is returning the correct values!

I will update the code accordingly! Will be included in my next PR.

Thanks for your help!

**Comment by jensotto** [comment]
Great. Thank you for implementing this so quickly @ykuijs
