### ISSUE TITLE
SPFarm: CentralAdministrationPort should be configurable

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#858]
#### Details of the scenario you tried and the problem that is occurring
Recently I was tasked to changed the central admin port. I tried to use the sp_farm resource, but failed. currently the CentralAdministrationPort will not be checked.

#### Suggested solution to the issue
Add CentralAdministrationPort to the test params and add function to set the central admin port.

#### Version of the DSC module that was used ('dev' if using current dev branch)
master - 2.4.0.0

**Comment by ykuijs** [comment]
Have implemented this. Will be included in my next PR
