### ISSUE TITLE
Help needed - Facing an issue when trying to install prerequisites

### ISSUE THREAD

**Issue by GabCeb95** [PowerShell/SharePointDsc#861]
Hi !! Thanks in advance for any help!

I have been struggling with this error, it is giving me an error with the AddServiceToLocalAdmins piece, as you can see the error says “The user name or password is incorrect” but I already double checked and the credentials are correct, so I am trying to find a way about how to fix this issue…

![error](https://user-images.githubusercontent.com/18234563/44883354-03848380-ac74-11e8-82c3-d6c73ad3c3d8.PNG)

This issue is happening when running the prerequisites DSC configuration command: Invoke-SPPLAPreRequisiteDscConfiguration -ConfigDataFilePath ./SPPLAConfigData.psd1 –Verbose

Do you have any idea what can be happening here? I will really appreciate it if you can give me any idea about how can I solve this issue

Note: I went to each of the servers and the account was added correctly, but the scripts does not complete successfully because of this error...

**Comment by johlju** [comment]
The cmdlet `Invoke-SPPLAPreRequisiteDscConfiguration` is not part of this resource module (PLA is a packing of a delivery method?), and it seems the problem you are facing is the Group resource which is not part of this resource module either.
Look from which resource module the Group resource are used, and please submit an issue in that repository to get better help.
For example see https://github.com/PowerShell/PSDscResources/issues/82#issuecomment-325716274.

**Comment by ykuijs** [comment]
PLA is the Product Line Architecture, a delivery of Microsoft Consulting Services (MCS).

Are you deploying SharePoint as part of that delivery? If so, you might ask the consultants delivering this service for help. As Johan suggests, you are having issues with the Group resource, which is not part of SharePointDsc but part of the build in DSC resources.

**Comment by johlju** [comment]
Closing this as another issue has been opened https://github.com/PowerShell/PSDscResources/issues/114
