### ISSUE TITLE
Wiki Update for SPSearchTopology

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#871]
The SPSearchTopology wiki page's first paragraph talks about:

FirstPartitionIndex, FirstPartitionDirectory and FirstPartitionServers 

However, only FirstPartitionDirectory exists. Should this be reviewed?

**Comment by ykuijs** [comment]
Since the previous release I haven't updated the documentation yet. Thanks for reminding me!

**Comment by ykuijs** [comment]
I have updated the Wiki documentation, but the parameters you are refering to are not in there. I checked the code and schema and they are missing in there as well.

I can see the parameter mentioned in the readme, but no clue where that is coming from. Do you have any idea?

**Comment by NikCharlebois** [comment]
No idea either, that's what I was trying to flag with this issue. Those are coming out of nowhere :)

**Comment by ykuijs** [comment]
Ok great, then I will just remove that section ;-)
