### ISSUE TITLE
Latest change in SPUserProfileServiceApp breaks creation of UPSA proxy

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#873]
Change from 2.4.0.0 to 2.5.0.0 breaks creation of User Profile Service Application.

The newly created service application is not assigned to the app variable, and therefore line 406 will always fail as $app is $null.

https://github.com/PowerShell/SharePointDsc/blob/402d3d69d4873a4e1ed90b2778b0d20c808f63de/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L405-L411

**Comment by johlju** [comment]
Thanks for reporting this. Looks like there is a unit tests not catching this.

**Comment by ykuijs** [comment]
Will be fixed in my next bugfix PR
