### ISSUE TITLE
SPSite: Owner and Secondary Owner claims issues during Test-DSCConfiguration

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#875]
When specifying owner and secondary owner on a site collection in a web application that uses claims authentication it is required to use the encoded claims format (i:0#.w|domain\username)
The test method gets the decoded logon name and compares it to the claims encoded value from the resource. This will not match, and the test fails.

#### Details of the scenario you tried and the problem that is occurring
N/A

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue

Test method needs to compare the correct user logon values when using claims authentication

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
SPSite EniCoMSite
{
    Name = "EniCoM"
    OwnerAlias = "i:0#.w|domain\username";
    SecondaryOwnerAlias = "i:0#.w|domain\username2";
    PsDscRunAsCredential = $SPSetupCredential;
    Url = "http://sharepoint";
    Language = 1033;
    CompatibilityLevel = 15;
     Template = "STS#0";
}

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19101.amd64fre.winblue_ltsb_escrow.180718-1800
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by ykuijs** [comment]
The resource is build in such a way that you can use the classic format and the code does the conversion to claims for you. That is why the claim gets decoded. Eveything should work fine if you use domain\username.

**Comment by ykuijs** [comment]
But your example config has the claims values in the Alias parameters. What happens if your try this:

SPSite EniCoMSite
{
Name = "EniCoM"
OwnerAlias = "domain\username";
SecondaryOwnerAlias = "domain\username2";
PsDscRunAsCredential = $SPSetupCredential;
Url = "http://sharepoint";
Language = 1033;
CompatibilityLevel = 15;
Template = "STS#0";
}

**Comment by jensotto** [comment]
I did get an argument exception last time I tried this. Now it works as expected. Not sure if it could have been because of different versions of Sharepointdsc or if there was an issue with the claims configuration on the server.

**Comment by jensotto** [comment]
@ykuijs Please reopen this issue. I managed to get the error now. Not sure what is happening, but when I use the suggested method I am unable to connect to the site using PnP PowerShell after configuring with DSC.
I get this error message when running Test-DSCConfiguration:

VERBOSE: [server]: LCM:  [ Start  Test     ]  [[SPSite]Site]
VERBOSE: [server]:                            [[SPSite]Site] Testing site collection http://sp
VERBOSE: [server]:                            [[SPSite]Site] Getting site collection http://sp
VERBOSE: [server]:                            [[SPSite]Site] Executing as the local run as user <domain>\<user>
VERBOSE: [server]:                            [[SPSite]Site] Leaving BeginProcessing Method of Get-SPSite.
VERBOSE: [server]:                            [[SPSite]Site] Leaving ProcessRecord Method of Get-SPSite.
VERBOSE: [server]:                            [[SPSite]Site] Leaving EndProcessing Method of Get-SPSite.
VERBOSE: [server]:                            [[SPSite]Site] Leaving BeginProcessing Method of New-SPClaimsPrincipal.
Exception of type 'System.ArgumentException' was thrown.
Parameter name: identifier
    + CategoryInfo          : InvalidData: (Microsoft.Share...ClaimsPrincipal:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletNewClaimsPrincipal
    + PSComputerName        : NOSVGSV1185
 
VERBOSE: [server]:                            [[SPSite]Site] Leaving ProcessRecord Method of New-SPClaimsPrincipal.
