### ISSUE TITLE
rerun of SPSearchServiceApp after initial degreded searchIndexerror gives spesific error

### ISSUE THREAD

**Issue by Bjorn80** [PowerShell/SharePointDsc#877]
#### Details of the scenario you tried and the problem that is occurring
Creating the search service application and running the resource block with spadmin (sharepoint setup user) will sometimes result in a degraded index partition. When I then try to remove search application through Central Administration and run the configuration again i get the error shown under.

#### Verbose logs showing the problem
``` 
VERBOSE: [APP1]:                            [[SPSearchServiceApp]SearchServiceApp] Leaving BeginProcessing Method of New-SPEnterpriseSearchServiceApplication.
A database exception occurred when creating Search Application: Cannot find the principal 'CONTOSO\SPFarm', because it does not exist or you do not have permission.
    + CategoryInfo          : InvalidData: (Microsoft.Offic...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.Search.Cmdlet.NewSearchServiceApplication
    + PSComputerName        : App1
 
VERBOSE: [APP1]:                            [[SPSearchServiceApp]SearchServiceApp] Leaving ProcessRecord Method of New-SPEnterpriseSearchServiceApplication.
VERBOSE: [APP1]:                            [[SPSearchServiceApp]SearchServiceApp] Leaving EndProcessing Method of New-SPEnterpriseSearchServiceApplication.
VERBOSE: [APP1]: LCM:  [ End    Set      ]  [[SPSearchServiceApp]SearchServiceApp]  in 103.2150 seconds.
The PowerShell DSC resource '[SPSearchServiceApp]SearchServiceApp' with SourceInfo '\\file1\Share\Scripts\SP\RoleDataSource\BackEndServer.ps1::599::9::SPSearchServiceApp' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : App1
 
VERBOSE: [APP1]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : App1
 
VERBOSE: Operation 'Invoke CimMethod' complete.
```

#### Suggested solution to the issue
What I have found out that works, is letting the spfarm account run the resource block SPSearchServiceApp (creating a new mof). The search service application is created without issue.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
``` powershell
        #Add Search Service Application
        SPSearchServiceApp SearchServiceApp
        {
            Name                        = "Search Service Application"
            Ensure                      = "Present"
            DatabaseName                = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "Search")
            ApplicationPool             = $ConfigurationData.NonNodeData.SharePoint.ApplicationPool
            PsDscRunAsCredential        = $SPSetupCred #$FarmAccountCred          
            DefaultContentAccessAccount = $SPCrawlCred
            CloudIndex                  = $false
            WindowsServiceAccount       = $ServiceAppPoolAccountCred
            DependsOn                   = "[AddEntryToLog]Log_SPStateServiceApp"
        }
``` 
SharePointDSC 2.5.0.0
# insert configuration here

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016 July PU 2018
#### Version and build of PowerShell the target node is running
Powershell 5.0

#### Version of the DSC module that was used ('dev' if using current dev branch)
SharePointDSC 2.5.0.0

**Comment by johlju** [comment]
@Bjorn80 am I understanding you correctly that stripping out the same SPSearchServiceApp configuration from the original configuration, and run that separately works? 
If so, it sounds like something that is run before that block is doing something that results in this error? 

Do you have anymore information from the ULS logs that can be of some help for the community to figuring out what is causing this?

**Comment by Bjorn80** [comment]
Hi @johlju 



`        SPSearchServiceApp SearchServiceApp
        {
            Name                        = "Search Service Application"
            Ensure                      = "Present"
            DatabaseName                = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "Search")
            ApplicationPool             = $ConfigurationData.NonNodeData.SharePoint.ApplicationPool
            PsDscRunAsCredential        = $FarmAccountCred          
            DefaultContentAccessAccount = $SPCrawlCred
            CloudIndex                  = $false
            WindowsServiceAccount       = $ServiceAppPoolAccountCred
            DependsOn                   = "[AddEntryToLog]Log_SPStateServiceApp"
        }`

**Works**

`        SPSearchServiceApp SearchServiceApp
        {
            Name                        = "Search Service Application"
            Ensure                      = "Present"
            DatabaseName                = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "Search")
            ApplicationPool             = $ConfigurationData.NonNodeData.SharePoint.ApplicationPool
            PsDscRunAsCredential        = $SPSetupCred #$FarmAccountCred          
            DefaultContentAccessAccount = $SPCrawlCred
            CloudIndex                  = $false
            WindowsServiceAccount       = $ServiceAppPoolAccountCred
            DependsOn                   = "[AddEntryToLog]Log_SPStateServiceApp"
        }`

**Does not work**


I have never before encountered a case where the SharePoint setup user cannot create the search service application.

**Comment by johlju** [comment]
Ah, thank you for the additional information. I'm following you know. Labeling this as question until it is determine if it is a permission problem, bug or enhancement.

/cc @ykuijs @NikCharlebois

**Comment by ykuijs** [comment]
Hi @Bjorn80, the issue with using the Farm account is that the farm account needs to have local admin permissions, which is against best practices. Some other resources require the use of the Farm account (like the UPS Service App) and we have implemented a solution there, but the downside of that solution is that it requires CredSSP which can introduce security issues. That is why we would like to use that method as little as possible.

Maybe we can track the cause of the issue and implement a workaround: Does this issue occur all the time or only in specific cases? Do you have the ULS log of a failed provisioning of the Search SA?

**Comment by jacostero** [comment]
Hi all,
maybe this information can help. When I create the Search Service Application with the $SPSetupCred (sysadmin on SQL Server Instance and local admin in SharePoint servers) the dbowner of Search Databases is $SPSetupCred instead $SPfarmCred (only local admin in SharePoint servers during configuration and non sysadmin on SQL Server Instance) and I have errors in SharePoint Logs related to database permisions.

**Comment by Bjorn80** [comment]
Sorry to get back to this so late, seems that adding the search account to the local admin group fixes all issues. Account can be removed from local admins after search has been configured. Hence I can use normal spsetup to setup search.
