### ISSUE TITLE
MSFT_SPServiceAppSecurity: Missing access level entries in MSFT_SPServiceAppSecurityEntry

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#880]
Access level entries for Managed Metadata Service Application Sharing Permissions are missing in MSFT_SPServiceAppSecurityEntry
#### Details of the scenario you tried and the problem that is occurring
Set sharing permissions on the Managed Metadata Service Application and administration permissions on the user profile service application.

#### Verbose logs showing the problem
SharePointDSC\MSFT_SPServiceAppSecurityEntry : At least one of the values 'Full Access to Term Store' is not supported or valid for property 'AccessLevel' on class 'M
SFT_SPServiceAppSecurityEntry'. Please specify only supported values: 
Change Permissions, Full Control, Write, Read.

#### Suggested solution to the issue
Add these levels to the allowed access levels:
Read Access to Term Store
Read and Restricted Write Access to Term Store
Full Access to Term Store

Manage Profiles
Manage Audiences
Manage Permissions
Retrieve People Data for Search Crawlers
Manage Social Data

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
        $membersToInclude = @()
        $membersToInclude += MSFT_SPServiceAppSecurityEntry {
                                Username    = <Domain>\<Username>
                                AccessLevel = "Full Access to Term Store"
                            }
        SPServiceAppSecurity UserProfileServiceSecurity
        {
            ServiceAppName       = "Managed Metadata Service"
            SecurityType         = "SharingPermissions"
            MembersToInclude     = $membersToInclude
            PsDscRunAsCredential = $SPSetupCredential 
        }

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by ykuijs** [comment]
I think this issue is similar to #825. Am I correct?

**Comment by jensotto** [comment]
Yes, you are correct. I did not see that one.

**Comment by ykuijs** [comment]
Closing as duplicate
