### ISSUE TITLE
SPWebAppSuiteBar: Does not work

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#883]
#### Details of the scenario you tried and the problem that is occurring
This resource will never work as it only cheks for the Ensure value wich is not part of the resource properties.
https://github.com/PowerShell/SharePointDsc/blob/402d3d69d4873a4e1ed90b2778b0d20c808f63de/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L246-L248
#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue
Verify relevant values.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A
#### The operating system the target node is running
N/A
#### Version of SharePoint that is used (e.g. SharePoint 2016)
N/A
#### Version and build of PowerShell the target node is running
N/A
#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by ykuijs** [comment]
Good spot! This needs to get fixed!

**Comment by ykuijs** [comment]
Closed via PR #888
