### ISSUE TITLE
MSFT_SPSearchTopology: Issue with Set-TargetResource (Server name is null)

### ISSUE THREAD

**Issue by JoeAlanis** [PowerShell/SharePointDsc#891]
ISSUE DESCRIPTION:
I am receiving the following error when pushing a Search topology configuration: 
> Failed to execute Set-TargetResource functionality with error message: Cannot bind argument to parameter 'SearchServiceInstance' because it is null. 

#### Details of the scenario you tried and the problem that is occurring
I am using a Push configuration using Partial configuration for both SQL 2017 and SharePoint 2016 onto a single server farm configuration. Server name is SQL1-2016 (localhost). There is a check in the MSFT_SPSearchTopology resource that is causing the error.

#### Verbose logs showing the problem
VERBOSE: [Sql1-2016]:                            [[SPSearchTopology]FarmSearchTopology] Leaving ProcessRecord Method of Get-SPEnterpriseSearchServiceApplication.
VERBOSE: [Sql1-2016]:                            [[SPSearchTopology]FarmSearchTopology] Leaving EndProcessing Method of Get-SPEnterpriseSearchServiceApplication.
VERBOSE: [Sql1-2016]:                            [[SPSearchTopology]FarmSearchTopology] Leaving BeginProcessing Method of New-SPEnterpriseSearchTopology.
VERBOSE: [Sql1-2016]:                            [[SPSearchTopology]FarmSearchTopology] Leaving ProcessRecord Method of New-SPEnterpriseSearchTopology.
VERBOSE: [Sql1-2016]:                            [[SPSearchTopology]FarmSearchTopology] Leaving EndProcessing Method of New-SPEnterpriseSearchTopology.
VERBOSE: [Sql1-2016]:                            [[SPSearchTopology]FarmSearchTopology] Setting components for 'Admin' property
VERBOSE: [Sql1-2016]: LCM:  [ End    Set      ]  [[SPSearchTopology]FarmSearchTopology]  in 0.4530 seconds.
PowerShell DSC resource MSFT_SPSearchTopology  failed to execute Set-TargetResource functionality with error message: Cannot bind argument to parameter 'SearchServiceInstance' because it is null. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
#### Suggested solution to the issue
There is something in the [Set-TargetResource](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1) that is causing this.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Data File 
#Search Topology
        Admin = @("SQL1-2016")
        Crawler  = @("SQL1-2016")
        ContentProcessing = @("SQL1-2016")
        AnalyticsProcessing = @("SQL1-2016")
        QueryProcessing = @("SQL1-2016")
        IndexPartition = @("SQL1-2016")
        SearchIndexLocation = "G:\SearchIndexes\0"

# From Configuration File
SPSearchTopology FarmSearchTopology
        {
            ServiceAppName          = "Search Service Application"
            Admin                   = $ConfigurationData.AppInfo.Admin
            Crawler                 = $ConfigurationData.AppInfo.Crawler
            ContentProcessing       = $ConfigurationData.AppInfo.ContentProcessing
            AnalyticsProcessing     = $ConfigurationData.AppInfo.AnalyticsProcessing
            QueryProcessing         = $ConfigurationData.AppInfo.QueryProcessing
            FirstPartitionDirectory = $ConfigurationData.AppInfo.SearchIndexLocation
            IndexPartition          = $ConfigurationData.AppInfo.IndexPartition
            PsDscRunAsCredential    = $SPSetupAccount
            DependsOn               = '[SPSearchServiceApp]SearchServiceApp'
        }
```
#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2430.amd64fre.rs1_release_inmarket_aim.180806-1810
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                                                                                
----                           -----                                                                                                                                                                                
PSVersion                      5.1.14393.2430                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                              
BuildVersion                   10.0.14393.2430                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                  
SerializationVersion           1.1.0.1        
#### Version of the DSC module that was used ('dev' if using current dev branch)                                                                                                         
Manifest   2.5.0.0    SharePointDSC

**Comment by ykuijs** [comment]
Hi @JoeAlanis You mention that there is a check in the code that is causing this. Have you been able to determine exactly which check that is? That would make troubleshooting a whole lot easier ;-)

**Comment by viguerre** [comment]
Good afternoon,

I am also getting this same error on a sharepoint server 2013 farm with one sharepoint server and one sql server.  Thank You!

SPSearchTopology FarmSearchTopology{
   ServiceAppName = 'Search Service Application'
   Admin = 'sp-app-01'
   Crawler  = 'sp-app-01'
   ContentProcessing = 'sp-app-01'
   AnalyticsProcessing = 'sp-app-01'
   QueryProcessing = 'sp-app-01'
   IndexPartition = 'sp-app-01'
   FirstPartitionDirectory = 'C:\SearchIndexes\0'
   PsDscRunAsCredential    = $spsetup
   DependsOn               = '[SPSearchServiceApp]SearchServiceApp'
} 


SharePointDSC 2.5
Windows Server 2012 R2 Standard 64 bit
SharePoint Server 2013 with SP1 Enterprise

**Comment by JoeAlanis** [comment]
Hi @ykuijs, I suspect that it's in the Set-TargetResource lines 258-265. I don't think it's catching that it is null.

**Comment by ykuijs** [comment]
Are you using both short names and FQDNs in the same config?

**Comment by ykuijs** [comment]
@JoeAlanis Do you have an answer to my previous question?

**Comment by ykuijs** [comment]
@JoeAlanis Any update?

**Comment by ykuijs** [comment]
And can you test with v3.1?

**Comment by Gnocchii** [comment]
I had the same issue. I confirm it works when using the FQDN instead of the short name.

**Comment by JoeAlanis** [comment]
Confirmed.... FQDN did the trick. Thank you @ykuijs !
