### ISSUE TITLE
SPSearchServiceApp: Missing SearchAlert Property

### ISSUE THREAD

**Issue by HeKr09** [PowerShell/SharePointDsc#895]
#### Details of the scenario you tried and the problem that is occurring
It is not possible to set the search alert state within the SPSearchServiceApp. Actually I did not find any other ressource that includes that property.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Implement a search alert property. As used in our project:
```powershell
Script SetSearchAlertStatus
{
    GetScript            = {
        $results = Invoke-SPDscCommand -ScriptBlock {
            $ssa = Get-SPEnterpriseSearchServiceApplication
            return $ssa.AlertsEnabled
        }
        return $results
    }
    SetScript            = {
        Invoke-SPDscCommand -Arguments $using:SharePointConfigData.Services.Search.SearchAlertStatus -ScriptBlock {
            $ssa = Get-SPEnterpriseSearchServiceApplication
            $ssa.AlertsEnabled = $args[0]
            $ssa.Update()
        }
    }
    TestScript           = {
        $results = Invoke-SPDscCommand -Arguments $using:SharePointConfigData.Services.Search.SearchAlertStatus -ScriptBlock {
            $ssa = Get-SPEnterpriseSearchServiceApplication
            return $ssa.AlertsEnabled -eq $args[0]
        }
        return $results
    }
}
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A
#### The operating system the target node is running
N/A
#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
5.1
#### Version of the DSC module that was used ('dev' if using current dev branch)
2.1.0.0

**Comment by ykuijs** [comment]
Will be included in my next Rollup PR
