### ISSUE TITLE
SPManagedMetaDataServiceApp: ContentType properties missing

### ISSUE THREAD

**Issue by HeKr09** [PowerShell/SharePointDsc#897]
#### Details of the scenario you tried and the problem that is occurring
The properties _IsContentTypePushdownEnabled_ and _IsNPContentTypeSyndicationEnabled_ are not implemented right now.
#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue
Implement the features. We implemented it as followed.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# $parentMMD is defined within a foreach
# $parentMMD = $_
Script "MMDCustomSettings$($_.Name)"
{
    GetScript            = {
        $results = Invoke-SPDscCommand -Arguments $using:parentMMD -ScriptBlock {
            $proxy = Get-SPMetadataServiceApplicationProxy -Identity $args[0].ProxyName
            return @{
                CTPushdown    = $proxy.Properties["IsContentTypePushdownEnabled"]
                CTSyndication = $proxy.Properties["IsNPContentTypeSyndicationEnabled"]
            }
        }
        return $results
    }
    SetScript            = {
        Invoke-SPDscCommand -Arguments $using:parentMMD -ScriptBlock {
            $proxy = Get-SPMetadataServiceApplicationProxy -Identity $args[0].ProxyName
            $proxy.Properties["IsContentTypePushdownEnabled"] = $args[0].CTPushdown
            $proxy.Properties["IsNPContentTypeSyndicationEnabled"] = $args[0].CTSyndication
            $proxy.Update()
        }
    }
    TestScript           = {
        $results = Invoke-SPDscCommand -Arguments $using:parentMMD -ScriptBlock {
            $proxy = Get-SPMetadataServiceApplicationProxy -Identity $args[0].ProxyName
            return $($proxy.Properties["IsContentTypePushdownEnabled"] -eq $args[0].CTPushdown -and $proxy.Properties["IsNPContentTypeSyndicationEnabled"] -eq $args[0].CTSyndication)
        }
        return $results
    }
}
```

#### The operating system the target node is running
N/A
#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
5.1
#### Version of the DSC module that was used ('dev' if using current dev branch)
2.1.0.0

**Comment by andikrueger** [comment]
I think these settings are specific to one `SPMetadataServiceApplicationProxy`. To reflect these additions these changes should be made to the `SPManagedMetadataServiceApp` Resource.

**Comment by ykuijs** [comment]
@andikrueger is right, this needs to be implemented in SPManagedMetadataServiceApp instead. Marked it as Enhancement, so someone can pick this up

**Comment by andikrueger** [comment]
I'm on it.

**Comment by ykuijs** [comment]
All yours @andikrueger
