### ISSUE TITLE
SPSite: Exception calling "CreateDefaultAssociatedGroups" with "3" argument(s): "Access is denied.

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#898]
When creating a new site collection using SPSite, if you don't have permissions on the site collection or web app policy, you are presented the following error:
Exception calling "CreateDefaultAssociatedGroups" with "3" argument(s): "Access is denied.

#### Details of the scenario you tried and the problem that is occurring
This is caused by recent submissions. We will have to correct it

#### Suggested solution to the issue
- Make sure the setup account has the correct permissions
- Make sure the documentation is updated with this requirement

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 SPSite RootSite
{
    Url				 = 'http://sp.contoso.com'
    OwnerAlias			 = 'domain\user'
    Template			 = 'STS#0'   
    PsDSCRunAsCredential = $spsetup
}  
```

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2013

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by viguerre** [comment]
good afternoon Yorik,

I added the setup account as an sca to mysite host site collection and also gave it full permissions in web application policy and im still getting a false configuration for SPSite.  Any recommendations?  Thanks!

**Comment by viguerre** [comment]
Added setup account to webapp per Yorik's explanation and it works! no more false configurations.
