### ISSUE TITLE
SPUserProfileSyncConnection facoltative IncludedOUs and allow specify LDAPfilter

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#902]
### Description
In SPUserProfileSyncConnection please set facoltative IncludedOUs, I want retrieve all domain/container and set only LDAFilter.

### Proposed properties
Add LDAFilter options and set facoltative IncludedOUs to select all

**Comment by ykuijs** [comment]
Hi @paololec Unfortunately the SharePoint Object Model doesn't allow to programmatically configure the LADP Filter. This has also been discussed in #766

**Comment by paololec** [comment]
With some hack and reflection I can do it :-)
 # Updating Ldap filter by using reflection 
    $displayName = "ConnectionName"
    $site = "http://centraladmin:2016"
    $ldapFilter = "(|(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))(objectcategory=group))"


    $serviceContext = Get-SPServiceContext -Site $Site
    $userProfileConfigManager = New-Object Microsoft.Office.Server.UserProfiles.UserProfileConfigManager($serviceContext) 
    $adConnCheck = $userProfileConfigManager.ConnectionManager.Where({$_.DisplayName -eq $displayName})
    $adConn = $userProfileConfigManager.ConnectionManager[$adConnCheck.DisplayName]
    $adConn.GetType().GetProperty("LdapFilter", [System.Reflection.BindingFlags]::Instance -bor [System.Reflection.BindingFlags]::NonPublic).SetValue($adConn, $ldapFilter) 
    $adConn.Update()

**Comment by ykuijs** [comment]
Closing this issue, since this can't be implemented due to lack of support in SharePoint
