### ISSUE TITLE
SPSearchContentSource: fullSchedule missing StartHour

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#906]
#### Details of the scenario you tried and the problem that is occurring
I try:
 FullSchedule         = MSFT_SPSearchCrawlSchedule{
                                        ScheduleType = "Weekly"
                                        CrawlScheduleDaysOfWeek = @("Sunday")
                                        StartHour = "1"
                                        StartMinute = "0"
                                       }
#### Verbose logs showing the problem
StartHour not working with schedule Weekly. 
(other problem: It's seems also that a IncrementalSchedule is set by default).
#### Suggested solution to the issue
Fix code
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 SPSearchContentSource LocalSharePointSites
            {
                Name                 = "Local SharePoint Sites"
                ServiceAppName       = "Search Service Application"
                ContentSourceType    = "SharePoint"
                Addresses            = @("https://portal.sharepoint.com")
                ContinuousCrawl      = $true
                FullSchedule         = MSFT_SPSearchCrawlSchedule{
                                        ScheduleType = "Weekly"
                                        CrawlScheduleDaysOfWeek = @("Sunday")
                                        StartHour = "1"
                                        StartMinute = "0"
                                       }
                Priority             = "Normal"
                Ensure               = "Present"
                PsDscRunAsCredential = $Credssp_admin
            }
```
#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version of the DSC module that was used ('dev' if using current dev branch)
dsc 3.0

**Comment by paololec** [comment]
After investigation, the right parameter missing is: CrawlScheduleStartDateTime

**Comment by paololec** [comment]
To fix add property as string "CrawlScheduleStartDateTime" to the code.
(example for dsc property: CrawlScheduleStartDateTime = "01:00" ) 

Need to add into MSFT_SPSearcContentSource.psm1:
$propertyTest = Test-SPDSCObjectHasProperty -Object $params.FullSchedule `
                                                            -PropertyName "CrawlScheduleStartDateTime"
                if ($propertyTest -eq $true)
                {
                    $fullSetArgs.Add("CrawlScheduleStartDateTime",
                        $params.FullSchedule.CrawlScheduleStartDateTime)
                }
before Set-SPEnterpriseSearchCrawlContentSource @allSetArguments @fullSetArgs of full schedule.

And into MSFT_SPSearchContentSource.schema,mof , class MSFT_SPSearchCrawlSchedule :
 [Write, Description("The hour and minute of the day that the schedule should begin")] String CrawlScheduleStartDateTime;

And into SPSearchContentSource.Schedules.psm1:
into "$result = @{ "  add the property:
CrawlScheduleStartDateTime = $Schedule.CrawlScheduleStartDateTime

and before switch ($CurrentSchedule.ScheduleType):
if ((Test-SPDSCObjectHasProperty -Object $DesiredSchedule `
                                     -PropertyName "CrawlScheduleStartDateTime") -eq $true `
        -and $CurrentSchedule.CrawlScheduleStartDateTime -ne $DesiredSchedule.CrawlScheduleStartDateTime)
    {
        return $false
    }

**Comment by ykuijs** [comment]
Hi @paololec Have you tested this with other ScheduleTypes? Daily for example?

I have checked the code and see that the StartHour should be configured:
https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1#L676-L682

**Comment by paololec** [comment]
Found other problem, if specify continuous crawl I can't set IncrementalSchedule, but in a normal installation it seems that a Incremental Schedule every 4 hours is neeed to execute (or different interval if you need it). So settings continuous create a misconfiguration because delete/remove the "default" incremental schedule.

Bug code/part to remove:
` 
if ($ContinuousCrawl -eq $true -and `
                $PSBoundParameters.ContainsKey("IncrementalSchedule") -eq $true)
            {
                throw ("You can not specify an incremental crawl schedule on a content source " + `
                       "that will use continous crawl")
            }
`

**Comment by paololec** [comment]
Please allow to set IncrementalSchedule also with ContinuosCrawl and not check it/throw it.

**Comment by ykuijs** [comment]
Issue will be fixed in my next Bugfix PR

**Comment by paololec** [comment]
In dev code missing delete second check of "You can not specify an incremental crawl schedule on a content source" in test section ..

**Comment by ykuijs** [comment]
Good point, missed that one! Will update this as well.
