### ISSUE TITLE
Better support for provisioning Central Administration with SSL?

### ISSUE THREAD

**Issue by ronx** [PowerShell/SharePointDsc#910]
Hey guys, I wanted to run something by you. When provisioning Central Admin with SSL, we're still only supporting the SP2013 (and earlier) method -- create CA on another port, use PowerShell to enable SSL on CA and set port to 443 (or whatever), update bindings, update AAM's... a while back, I had submitted a PR with a change to MSFT_SPAlternateUrl to bridge the gap when trying to use DSC to provision CA (with SharePointDsc) and handle the bindings (xWebAdministration) and AAM (SharePointDsc) gracefully. This worked, but I seem to remember still experiencing some strange effects later on... for example, in one customer farm, every time I ran psconfigUI.exe, it would reset the IIS bindings (and I think AAM's too) to http://<server_name>:443. I wrote the details of this scenario out somewhere, but I can't find it at the moment. The workaround was to use psconfig.exe instead of the UI wizard, since the UI seems to also try to reprovision CA each time it's run. In any case, it seemed that doing it this way was still leaving traces of an HTTP association behind.

I'm wondering if these quirks would go away if we added support in SharePointDsc to take advantage of the new param -SecureSocketsLayer when calling New-SPCentralAdministration and Set-SPCentralAdministration. I'm going to try to find time to test it in a lab, but it seems like it'd be a good idea to implement it this way since the SharePoint cmdlet supports it now. Thoughts?

**Comment by andikrueger** [comment]
This is great input! 

If we would implement the -SecureSocektsLayer (see: [New-SPCentralAdministration](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spcentraladministration?view=sharepoint-ps#optional-parameters)) param, there would still be the need to set the certificate manually or by xWebAdministration. It would be great to have further guidance or a Wiki-Page, that outlines how we can set the certificate in this scenario, when the SP DSC resource would take care of the -SecureSocketsLayer param.

**Comment by ronx** [comment]
We have a solution that automates the distribution of certificates and performs the bindings. It's part of a managed IP offering that's designed to be delivered as part of an end-to-end SharePoint planning and delivery engagement. However, I don't think it would be irresponsible to pull out example code to create a guidance wiki page here to suggest how this could be done with DSC.

I think the additional documentation would be a separate thread to track, though.

**Comment by ykuijs** [comment]
@ronx Any update on this issue? Are there any updates required? Do you have time to pick this up? Do you have the content for the Wiki ready?

**Comment by ronx** [comment]
Yeah, this is still the case with SP2019. If central admin is created without -SecureSocketsLayer and later updated to HTTPS, there are still some gotchas. One workaround is to Remove-SPWebApplication with -DeleteIISSite and then recreate CA with New-SPWebApplicationExtension -Identity https://admin.sharepoint.contoso.com -Name "SharePoint Central Administration v4" -Zone Default -HostHeader admin.sharepoint.contoso.com -Port 443 SecureSocketsLayer. You still have to edit the IIS binding to select the certificate, but at least the binding will persist after running psconfigUI.

The other workaround is to always use the command line version of psconfig, since this does not reprovision CA like psconfigUI does.

I'm going to take a stab at the code change in SPFarm. Seems simple enough. I just made the changes in my fork and am going to test it in my lab. It'll only work in SP2016 and above, but maybe that'll discourage people from creating new SP2013 farms ;). I'll keep you posted.

**Comment by ronx** [comment]
Just a quick update. Using -SecureSocketsLayer with New-SPCentralAdministration doesn't allow specifying the hostname, so it still creates CA as https://servername:443. The SPDSC code worked to recognize that since I specified 443 and was on SP2016 or higher, it included that param. Then, in my config, I have an xWebsite resource to handle the binding with the certificate I have created, and also to enable SNI for CA. My config also has an SPAlternateUrl resource after that to update the AAM to the new vanity host. However, further in my config, when it tries to create a web application on port 443 with no host header (to support HNSC), I get an error, "The IIS Web Site you have selected is in use by SharePoint.  You must select another port or hostname." We ran into this before and worked around it by creating CA on HTTP, then creating the web app, and then adding the CA binding and updating the AAM. But I don't think this is going to work this way.

I'll try to think of another approach... if not, I'll just document the steps and DSC needed to get this working. I was hoping to automate it more though. Oh well.

**Comment by ronx** [comment]
I made a first stab at a [wiki](https://github.com/ronx/SharePointDsc/wiki/Setting-up-Central-Administration-on-HTTPS) and example for CA SSL support. Could you guys check it out and let me know what you think? @andikrueger @ykuijs 

I also committed the SPFarm change to support the SecureSocketsLayer argument when creating CA. I haven't used it successfully yet, since in my testing it conflicts with web apps being created on port 443, but I think it makes sense to have it in there as an option. Here's a link to the [commit](https://github.com/ronx/SharePointDsc/commit/3f19a879f77f189bd6309dbccb719095101f9205). Let me know what you think.

**Comment by andikrueger** [comment]
@ronx Thank you for providing such detailed information on this issue.

Today I read through the list of challenges and the possible solutions (commit + wiki page). Currently everything is very complex to setup the SSL binding. 
I really like the thought of deleting the default CA web application and recreate a SSL webapp to support SSL in a persisted way. Any other way looks overly error prone. What would happen, if we change the SPFarm Resource to do so  (delete + recreate) for SSL enbaled CAs?

**Comment by ronx** [comment]
I suppose that would work. I've only tried this approach with a vanity hostname, but it would probably work with the default servername if the user did not pass a hostname. Speaking of which, I guess this would be a breaking change since we'd probably want to add CentralAdminUrl (or CentralAdminHostName) to the params to allow for vanity CA hostname. Actually, I guess it wouldn't be a breaking change if the new param was optional, right? The logic would remove and extend if the CentralAdministrationPort was passed as 443. We should probably also add an optional switch CentralAdministrationSsl to support SSL on other ports. I've seen this requirement come up in the DoD space, though I can't seem to find the requirement at the moment. I haven't actually had a customer use a non-443 port for CA before, so maybe it's not a big deal.

**Comment by andikrueger** [comment]
Adding new OPTIONAL parameters (and not changing the existing ones) wouldn't be breaking change, if the outcome of the SPFarm resource doesn't change.

**Comment by ykuijs** [comment]
That sounds like a great plan! And Andi is correct that adding optional parameters won't be a breaking change and can be implemented at any time.

@ronx Two questions:
1. Are you implementing this change?
1. Is Wiki page ready for publishing? If so, I will add it to the wiki.

**Comment by ronx** [comment]
@ykuijs If you guys think the wiki page looks good, it should be ready to go. Also, I can take a look at the SPFarm resource today and will reach out if I hit any snags navigating.

**Comment by ykuijs** [comment]
Perfect, I will copy the wiki page to this repo!

Just to make sure:
Please only recreate the CA site if it uses SSL and hasn't been configured properly.

**Comment by ykuijs** [comment]
Small update: @ronx is still working on this. Planning to do some final testing next week.

**Comment by ykuijs** [comment]
Close via PR #1049
