### ISSUE TITLE
Breaking Change - SPSearchResultSource: Make ScopeURL a Key

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#918]
#### Details of the scenario you tried and the problem that is occurring
I have a client that redefines the same Result Source (named Promotions), on several Site Collection. Problem is that with the current resource, only the name is defined as a key, causing the configuration to throw errors about duplicate resource definitions. We need to make ScopeURL a key to allow for this scenario.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Make ScopeURL a key, use "Global" as a value to identify a Global Result Source.

#### The operating system the target node is running
Windows Server 2012 R2

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PoSh 4.0

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by NikCharlebois** [comment]
@ykuijs we discussed this in the past, but there is just no way around it, this needs to be a breaking change

**Comment by NikCharlebois** [comment]
To add to the challenge, the client's installation is in French, and the ProviderType is listed in French:
Fournisseur de favoris personnels
Fournisseur de meilleurs résultats
Fournisseur de recherche Exchange
Fournisseur distant de personnes
Fournisseur local de personnes
Fournisseur SharePoint distant
Fournisseur SharePoint local
Moteur OpenSearch

Which are rejected by the resource.

**Comment by NikCharlebois** [comment]
Reported the second issue (about French provider name) as a separate Issue
Issue #920

**Comment by ykuijs** [comment]
Closed via PR #930
