### ISSUE TITLE
SPSearchResultSource - Issue with Non-English environments

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#920]
#### Details of the scenario you tried and the problem that is occurring
For environments in other languages than English, the result source providers are in a different language. For example, with a French installation, the providers are:

- Fournisseur de favoris personnels
- Fournisseur de meilleurs résultats
- Fournisseur de recherche Exchange
- Fournisseur distant de personnes
- Fournisseur local de personnes
- Fournisseur SharePoint distant
- Fournisseur SharePoint local
- Moteur OpenSearch

The resource only accepts English values, which then causes the config to fail when trying to retrieve the Provider ID.

#### Verbose logs showing the problem
PowerShell DSC resource MSFT_SPSearchResultSource  failed to execute Set-TargetResource functionality with error
message: Exception setting "ProviderId": "Cannot convert null to type "System.Guid"."

#### Suggested solution to the issue
Use the FlowName property instead of the providers' display name. This would then be a breaking change, and would make it a lot less obvious what the values are. We may still continue to access the English Names but also add support for the FlowName? (e.g. Microsoft.RemoteSharepointFlow)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows Server 2012 R2

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PoSh 4

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by ykuijs** [comment]
Currently we are using the ValidateSet to determine if the user inputted a correct value. With localizations, these potential values can be pretty much anything. This means we have to remove the ValidateSet.

This change however means that users can input values that do not exist on the environment. I have found a way to retrieve all possible localized values:
```
Add-PSSnapin Microsoft.SharePoint.PowerShell

$serviceApp = Get-SPEnterpriseSearchServiceApplication -Identity "Search Service Application"

$fedManager = New-Object Microsoft.Office.Server.Search.Administration.Query.FederationManager($serviceApp)
$providers = $fedManager.ListProviders()
$providers.Keys
```
Using this set of possible values, one of the first things we have to check in the resource is if the supplied value is part of this set.

**Comment by ykuijs** [comment]
I have updated SPSearchResultSource to validate the specified ProviderType against the possible values from SharePoint. Will submit a PR shortly.
