### ISSUE TITLE
Resources that use TypeName for Service Instance: Not working for non-english environments

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#923]
#### Details of the scenario you tried and the problem that is occurring
The SPBlobCacheSettings resource tries to retrieve and configure the blob cache, only if the "Microsoft SharePoint Foundation Web Application" service is started on the server. However, we should use TypeName to determine if a service is started or not since it is culture dependent. E.g. my client has a French SharePoint environment and the service TypeName is "Application Web de Microsoft SharePoint Foundation" and therefore never detects or configures it.

This issue is widespread across multiple resource. We should modify every resource that uses the property TypeName to determine the status or retrieve an instance, so that it uses a parameter that is culture independent.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Use .GetType().Name where possible (Web Foundation and Central Admin have the same name, so it won't work in that case), or the Name itself to determine the instance of the service (Central Admin has a name of Wss_Administration, and web foundation has an empty name).

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows Server 2012 R2 (French)

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PoSh 4

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by ykuijs** [comment]
Not fully fixed, needs some more work
