### ISSUE TITLE
SPUserProfileServiceApp: does not execute New-SPProfileServiceApplicationProxy

### ISSUE THREAD

**Issue by Yvand** [PowerShell/SharePointDsc#924]
#### Details of the scenario you tried and the problem that is occurring

The code in Set-TargetResource of resource SPUserProfileServiceApp is flawed, current logic never executes New-SPProfileServiceApplicationProxy:

```powershell
$serviceApps = Get-SPServiceApplication -Name $params.Name `
                                                    -ErrorAction SilentlyContinue
$app = $serviceApps | Select-Object -First 1
if ($null -eq $serviceApps)
{
    New-SPProfileServiceApplication @params | Out-Null
    if ($null -ne $app)
    {
        New-SPProfileServiceApplicationProxy -Name $pName `
                                             -ServiceApplication $app `
                                             -DefaultProxyGroup
    }

    $app = Get-SPServiceApplication -Name $params.Name `
                                    -ErrorAction SilentlyContinue
}
```

#### Verbose logs showing the problem

There is nothing specific in the logs, cmdlet New-SPProfileServiceApplicationProxy is just never called

#### Suggested solution to the issue

At minimum it should changed to correctly assign $app to the result of New-SPProfileServiceApplicationProxy, but it can also be simplified:

```powershell
$app = Get-SPServiceApplication -Name $params.Name `
                                -ErrorAction SilentlyContinue
if ($null -eq $app)
{
    $app = New-SPProfileServiceApplication @params
    if ($null -ne $app)
    {
        New-SPProfileServiceApplicationProxy -Name $pName `
                                             -ServiceApplication $app `
                                             -DefaultProxyGroup
    }
}
```

I'll submit a PR with that change soon

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

Any configuration reproduces the issue:

```powershell
SPUserProfileServiceApp UserProfileServiceApp
{
    Name                 = $UpaServiceName
    ApplicationPool      = $ServiceAppPoolName
    MySiteHostLocation   = "http://$MySiteHostAlias/"
    ProfileDBName        = $SPDBPrefix + "UPA_Profiles"
    SocialDBName         = $SPDBPrefix + "UPA_Social"
    SyncDBName           = $SPDBPrefix + "UPA_Sync"
    EnableNetBIOS        = $false
    PsDscRunAsCredential = $SPSetupCredsQualified
    DependsOn            = "[SPServiceAppPool]MainServiceAppPool", "[SPServiceInstance]UPAServiceInstance", "[SPSite]MySiteHost"
}
```

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2214.amd64fre.rs1_release_1.180402-1758
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

I reproduced with SharePoint 2016, I expect it to be exactly the same with SharePoint 2013

#### Version and build of PowerShell the target node is running

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2214
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2214
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

SharePointDSC 2.5.0.0

**Comment by ykuijs** [comment]
Hi @Yvand This issue was already submitted in #873 and fixed in the current Dev branch. Can you please take that code and retest to see if your issue is indeed fixed?

**Comment by ykuijs** [comment]
Exactly what did you want to implement as well? Maybe I can implement it in another PR.

Or you can pick up another issue and at the same time implement your suggestions as well ;-)

**Comment by Yvand** [comment]
My PR was to fix exactly the same thing, but my code change simplifies slightly the code.
Compared with dev branch, I would replace this:

```powershell
$app = $serviceApps | Select-Object -First 1
if ($null -eq $serviceApps)
{
    $app = New-SPProfileServiceApplication @params
    if ($null -ne $app)
    {
        New-SPProfileServiceApplicationProxy -Name $pName `
                                             -ServiceApplication $app `
                                             -DefaultProxyGroup
    }

    $claimsPrincipal = New-SPClaimsPrincipal -Identity $setupAccount `
                                             -IdentityType WindowsSamAccountName

    $serviceAppSecurity = Get-SPServiceApplicationSecurity $app
    Grant-SPObjectSecurity -Identity $serviceAppSecurity `
                           -Principal $claimsPrincipal `
                           -Rights "Full Control"
    Set-SPServiceApplicationSecurity -Identity $app `
                                     -ObjectSecurity $serviceAppSecurity

    $app = Get-SPServiceApplication -Name $params.Name `
                                    -ErrorAction SilentlyContinue
}
```

with this:

```powershell
$app = Get-SPServiceApplication -Name $params.Name `
                                -ErrorAction SilentlyContinue
if ($null -eq $app)
{
    $app = New-SPProfileServiceApplication @params
    New-SPProfileServiceApplicationProxy -Name $pName `
                                         -ServiceApplication $app `
                                         -DefaultProxyGroup
    
    $claimsPrincipal = New-SPClaimsPrincipal -Identity $setupAccount `
                                             -IdentityType WindowsSamAccountName

    $serviceAppSecurity = Get-SPServiceApplicationSecurity $app
    Grant-SPObjectSecurity -Identity $serviceAppSecurity `
                           -Principal $claimsPrincipal `
                           -Rights "Full Control"
    Set-SPServiceApplicationSecurity -Identity $app `
                                     -ObjectSecurity $serviceAppSecurity
}
```

So it's a pretty minor change but I'm fine to submit a PR for this if you think it's worth it.

**Comment by ykuijs** [comment]
What is the idea behind your proposed changes? For example the removal of the "if ($null -ne $app)" statement?

And the removal of the last Get-SPServiceApplication command? When the service app is changed in the lines before this statement, reusing the earlier created $app variable can result in errors. By calling the Get-SPServiceApplication, the $app is reinitialized.

**Comment by Yvand** [comment]
This test looks useless to me:
https://github.com/PowerShell/SharePointDsc/blob/88802efdeab51171182d1df58b53cfcdb99253e1/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L409-L414
For 2 reasons:

- if New-SPProfileServiceApplication returns $null, it's so bad that we should just throw an exception
- If $app is actually null, in current logic a NullReferenceException occurs later anyway at line 433:
https://github.com/PowerShell/SharePointDsc/blob/88802efdeab51171182d1df58b53cfcdb99253e1/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L430-L433

About Set-SPServiceApplicationSecurity, I assume it makes all the changes in the $app passed, so $app is up to date when cmdlet returns. I understand your point though, so I could be wrong

**Comment by ykuijs** [comment]
Totally agree. Have implemented a fix and will submit the PR shortly.
