### ISSUE TITLE
SPManagedMetadataServiceApp: ServiceApp proxy not created when it does not exist

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#935]
#### Details of the scenario you tried and the problem that is occurring
When the service app proxy of the MMS service app doesn't exist, doesn't this resource create it. The Test-TargetMethod does not test on proxy name.

#### Verbose logs showing the problem
Due to an issue the service app proxy wasn't created. All consecutive runs did not create the proxy.

#### Suggested solution to the issue
Add Proxy to the tested values

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Any config for MMS

#### The operating system the target node is running
Windows Server 2012 R2

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2016

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by andikrueger** [comment]
Adding issue #936 as they are related.
