### ISSUE TITLE
SPManagedMetadataServiceApp: Get method throws error when proxy doesn't exist

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#936]
#### Details of the scenario you tried and the problem that is occurring
When the service app proxy doesn't exist, the Get method throws an error on line 165:
$termStore = $session.TermStores[$proxyName]

This is because the $proxyName is set to $null

#### Suggested solution to the issue
Check for null

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Any MMS config where the proxy isn't created yet.

#### The operating system the target node is running
Windows Server 2012 R2

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2016

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by andikrueger** [comment]
Maybe this issue can be resolved by using something similar to these lines of code. https://github.com/PowerShell/SharePointDsc/blob/a38a1e2455b93d77980654922edb5a6a83b6fca2/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L105-L114

I think we need to fix the set method too: https://github.com/PowerShell/SharePointDsc/blob/a38a1e2455b93d77980654922edb5a6a83b6fca2/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L363

Currently the proxy will only be created in cases, that the MMS App does not exist at all. https://github.com/PowerShell/SharePointDsc/blob/a38a1e2455b93d77980654922edb5a6a83b6fca2/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L334

**Comment by ykuijs** [comment]
@andikrueger That is what I am implementing! Thanks for the suggestion!
