### ISSUE TITLE
SPTrustedRootAuthority: Need to add possibility to get the certificate from a file path, as an alternative to its thumbprint, as done in resource SPTrustedIdentityTokenIssuer

### ISSUE THREAD

**Issue by Yvand** [PowerShell/SharePointDsc#945]
#### Details of the scenario you tried and the problem that is occurring

If the certificate is generated in DSC configuration, its thumbprint is unknown at design time so we cannot use it.
The alternative is to use a file path to the public key of the certificate, as done in resource SPTrustedIdentityTokenIssuer.

**Comment by shurick81** [comment]
I Think it is a common practice to use thumbprint in certificate DSC resources: for example, https://github.com/PowerShell/CertificateDsc/wiki/CertificateImport or https://github.com/PowerShell/xwebadministration#xwebsite.

The workaround I use on the compiling machine:
```PowerShell
            $pfxPath = "c:\certs\contosoclubbwebb.pfx";
            $pfx = New-Object -TypeName "System.Security.Cryptography.X509Certificates.X509Certificate2";
            $pfx.Import($pfxPath,$pfxPassword,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::PersistKeySet);

            xWebsite WA00Site
            {
                Name        = "Contoso Klubbwebb"
                State       = "Started"
                BindingInfo = @(
                    MSFT_xWebBindingInformation {
                        Protocol = "HTTPS"
                        Port = 443
                        CertificateThumbprint = $pfx.thumbprint
                        CertificateStoreName = "My"
                        HostName = $hostName
                        SslFlags = 1
                    }
                )
            }
```

Mind you that in this case, `$pfx.Import(` does not actually install the certificate in any storage, but only in loads info that you can use to figure out the thumbprint for the cert.

**Comment by Yvand** [comment]
@shurick81 I wanted to test and comment your solution much earlier but I didn't find the time until now.
I cannot use your solution because it assumes that "contosoclubbwebb.pfx" already exists at compilation time.
In my scenario, I populate a completely new environment and the certificate doesn't exist yet, so DSC function fails to generate the MOF with this error:
```
Exception calling "Import" with "1" argument(s): "The system cannot find the path specified."
```

**Comment by ykuijs** [comment]
Will be added in my next PR
