### ISSUE TITLE
SPUserProfileServiceApp: Argument Rights not valid 

### ISSUE THREAD

**Issue by philippe-entringer** [PowerShell/SharePointDsc#947]
#### Details of the scenario you tried and the problem that is occurring
On a french OS, the resource SPUserProfileServiceApp throw an Error because of the Argument "Rights".

#### Verbose logs showing the problem
[[SPUserProfileServiceApp]APPLICATION_SpsSvcAppUserProfileServiceApp] Méthode EndProcessing de sortie de
New-SPProfileServiceApplication.
L’argument Rights n’est pas valide. Les valeurs valides sont : Contrôle total
    + CategoryInfo          : InvalidArgument : (Microsoft.Share...tObjectSecurity:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGrantObjectSecurity
    + PSComputerName        : SWZUDA0SPS28

COMMENTAIRES : [SWZUDA0SPS28]:
[[SPUserProfileServiceApp]APPLICATION_SpsSvcAppUserProfileServiceApp] Removing farm account from Local Administrators
group
COMMENTAIRES : [SWZUDA0SPS28]: LCM:  [ Fin    Définir  ]
[[SPUserProfileServiceApp]APPLICATION_SpsSvcAppUserProfileServiceApp]  en 53.3760 secondes.
La ressource DSC PowerShell [SPUserProfileServiceApp]APPLICATION_SpsSvcAppUserProfileServiceApp avec SourceInfo
D:\TFSBuild\agent\_work\2\s\Configurations\Scripts\CfgAppSps.ps1::2371::4::SPUserProfileServiceApp a levé une ou
plusieurs erreurs sans fin d'exécution lors du lancement de la fonctionnalité Set-TargetResource. Ces erreurs sont
enregistrées dans le canal ETW appelé Microsoft-Windows-DSC/Operational. Pour en savoir plus, reportez-vous à ce canal.
    + CategoryInfo          : InvalidOperation : (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : SWZUDA0SPS28

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
SPUserProfileServiceApp APPLICATION_SpsSvcAppUserProfileServiceApp
			{
				DependsOn            = '[SPFarm]APPLICATION_SpsCreateSPFarm', `
									   '[xSQLServerAlias]MIDDLEWARE_SqlAlias_SharedServices', `
									   "[SPSite]APPLICATION_SpsWApp$($Node.NodeName.Replace('-',''))Site"
				PsDscRunAsCredential = $ADM
				Name                 = $UserProfileServiceAppName
				ProxyName            = $UserProfileServiceAppName
				ApplicationPool      = $ConfigurationData.NonNodeData.SharePoint.Farms.Common.ServiceAppPoolName
				MySiteHostLocation   = "http://$($Node.NodeName)"
				ProfileDBName        = "D$($ConfigurationData.NonNodeData.Settings.Environment)$AppCode$($ConfigurationData.NonNodeData.SharePoint.Farms.Services.UserProfile.ProfileDB)"
				ProfileDBServer      = $ConfigurationData.NonNodeData.SQLServer.Instances.SharedServices.ServerAlias
				SocialDBName         = "D$($ConfigurationData.NonNodeData.Settings.Environment)$AppCode$($ConfigurationData.NonNodeData.SharePoint.Farms.Services.UserProfile.SocialDB)"
				SocialDBServer       = $ConfigurationData.NonNodeData.SQLServer.Instances.SharedServices.ServerAlias
				SyncDBName           = "D$($ConfigurationData.NonNodeData.Settings.Environment)$AppCode$($ConfigurationData.NonNodeData.SharePoint.Farms.Services.UserProfile.SyncDB)"
				SyncDBServer         = $ConfigurationData.NonNodeData.SQLServer.Instances.SharedServices.ServerAlias
				Ensure               = 'Present'
			}

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
5.1.14409.1005

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.6.0.0

**Comment by ykuijs** [comment]
Discovered a solution for this issue. Have shared it with Philippe for testing. If it works, I will add it to my next PR.

**Comment by philippe-entringer** [comment]
Thanks Yurick
The fix is working great on french OS.

**Comment by NikCharlebois** [comment]
Bonne nouvelle! Thanks folks, my client in Quebec City will be pleased!
