### ISSUE TITLE
Discussion: SharePointDSC with non-englisch systems or ISOs

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/SharePointDsc#955]
Lately there are a few issues focusing on localization troubles with non-english OSs or SharePoint installs - they are more or less related to #665.

The following issues are related to language issues or use ValueMaps, that will fail with non-english SharePoint setups (tbc.)

- #954 with #825 (seems to be the most challenging)
- #923
- #922 
- #920 
- #947

Do we have a chance to switch to internal enums? These should be the same across environments. 

For example:
```
namespace Microsoft.Office.Server.Administration
{
	[System.Flags]
	internal enum UserProfileApplicationUserRights : ulong
	{
		None = 0uL,
		UsePersonalFeatures = 1uL,
		CreatePersonalSite = 2uL,
		UseSocialFeatures = 4uL,
		UseMicrobloggingAndFollowing = 8uL,
		All = 15uL
	}
}
```
or in other cases the use of internal names (TypeNames) like @NikCharlebois introduced in #923.

**Comment by jensotto** [comment]
Wouldn't it work to do something like this:

$culture = [System.Globalization.CultureInfo]::InvariantCulture
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture
$security = Get-SPServiceApplication | Get-SPServiceApplicationSecurity -Admin
$security

This way I get out everything in US English on a Norwegian installation of SharePoint and Windows Server (Norwegian language packs applied on both products). Will this not also be true if you install for example Norwegian Windows Server and Norwegian SharePoint and no US English language packs as the neutral language is always included?

**Comment by jensotto** [comment]
If you want to test this you can't execute the lines one by one. It must be all executed simultaneously for example inside a function.

**Comment by andikrueger** [comment]
I'm curious if this would work regardless of any english language pack available. 

Like I mentioned in  https://github.com/PowerShell/SharePointDsc/issues/665#issue-269391450 some settings require to be set in the language the product was installed in. If we could find a way to map these values to english we would have solved several language/localization specific errors.

**Comment by ykuijs** [comment]
Linking to #947 which also is a language specific issue

**Comment by ykuijs** [comment]
For issue #920 I have found a way to retrieve the possible localized values. Do we have other examples, so I can check on my localized environment (Dutch) if I can find a way to retrieve those possible values?

**Comment by ykuijs** [comment]
@jensotto Your solution with changing the culture doesn't work in case of the SPResultSource. This code still outputs the localized names:
```
Add-PSSnapin Microsoft.SharePoint.PowerShell

$culture = [System.Globalization.CultureInfo]::InvariantCulture
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture

$serviceApp = Get-SPEnterpriseSearchServiceApplication -Identity "Search Service Application"

$fedManager = New-Object Microsoft.Office.Server.Search.Administration.Query.FederationManager($serviceApp)
$providers = $fedManager.ListProviders()
$providers.Keys
```

**Comment by jensotto** [comment]
@ykuijs I digged a bit into the code involved with getting this data, and it seems that there are no language transformation of the provider data. Everything is pulled directly from the database. I can't get the data in any other language than the original language that SharePoint was installed with (US English in my case). I don't understand why you get the localized names unless it ties directly to the original language SharePoint was installed with. If that's true there's no way to have SharePoint "translate" this to any other language, and my approach with changing the UI Culture will not work in this situation.

**Comment by ykuijs** [comment]
@jensotto I am using a Dutch version of Windows with a Dutch version of SharePoint, so I know for sure that everything that can be in Dutch will actually be in Dutch.

I just tested some more and created a new Managed Metadata service application. When running the following code, I got some worrying results:
```
$culture = [System.Globalization.CultureInfo]::InvariantCulture
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture

$perms = Get-SPServiceApplication | Get-SPServiceApplicationSecurity

foreach ($perm in $perms)
{
    $perm.NamedAccessRights.Name
}
```

> Leestoegang tot termenarchief
> Leestoegang en beperkte schrijftoegang tot termenarchief
> Volledige toegang tot termenarchief
> Full Control
> Full Control
> Full Control
> Full Control

When I don't first set the culture, everything is in Dutch. But when I do set the culture, only a few are converted into English. All MMS permission levels remain in the local language.

Note: When I use the -Admin parameter, all permissions are displayed in English.

Do you have the possibility to test this script on a Norwegian version of Windows/SharePoint?

**Comment by jensotto** [comment]
This is what I get:

> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Read Access to Term Store
> Read and Restricted Write Access to Term Store
> Full Access to Term Store
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control
> Full Control

If I don't set the CurrentUICulture I get this:

> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Read Access to Term Store
> Read and Restricted Write Access to Term Store
> Full Access to Term Store
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll
> Full kontroll

**Comment by ykuijs** [comment]
Ok, so it looks like that the non "Full Control" levels are created in one specific language and aren't translated anymore. So we probably need to do the same as with the SPSearchResultSource for the permissions levels as well.

Out of curiosity: What is the language of the OS you are using?

**Comment by ykuijs** [comment]
And are you using a Norwegian version of the SharePoint install, or have you installed the English version with the Norwegian language pack?

**Comment by jensotto** [comment]
I used a US English installation media for both SharePoint and the OS. I've installed a Norwegian language pack for both, and changed the display language to Norwegian for my user account.

**Comment by ykuijs** [comment]
I have updated SPServiceAppSecurity to validate the specified permission levels against the possible values from SharePoint. Will submit a PR shortly.
