### ISSUE TITLE
SPInstallPrereqs: Does not properly detect installed prerequisites

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#959]
#### Details of the scenario you tried and the problem that is occurring
Test-Resource for SPInstallPrereqs will fail if a more recent version of the prerequisite is installed.
For example this server had Microsoft Visual C++ 2017 x64 installed
When running the prerequisite installer manually it completed with the message that an equivalent version was already installed.

#### Verbose logs showing the problem
VERBOSE: [SP-01]:                            [[SPInstallPrereqs]PrerequisitesInstallation] Prerequisite Microsoft Visual C++ 2015 x64 Minimum Runtime - 14.0 was not found on this system

#### Suggested solution to the issue
Is there a different way to identify if a correct version of the prerequisite is installed. Could the registry key BundleUpgradeCode be used in some way? BundleUpgradeCode is identical for the 2015 and 2017 versions.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Normal SPInstallPrereqs resource implementation

#### The operating system the target node is running
Windows Server 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.6.0.0

**Comment by ykuijs** [comment]
Unfortunately it isn't always the case that a more recent version also satisfies the SharePoint prerequisites. For example the Native Client always requires the specified version. In order to fix this issue, we have to implement something specifically for this component.

Also, SP2019 requires the 2017 version of this component.
