### ISSUE TITLE
SPInstallPrereqs: Endless reboots

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#960]
#### Details of the scenario you tried and the problem that is occurring
Using SPInstallPrereqs results in endless reboots. It seems that the registry key HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations sometimes is never cleared. This combined with #959 results in an endles reboot loop because the Test-Resource method returns false and triggers the set method. 

#### Suggested solution to the issue
Does SPInstallPrereqs really need to check for items in HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations and existence of HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending and HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired ?
Isn't it enough to trigger a reboot based on the returned error code from the prerequisite installer (3010)?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows Server 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.6.0.0

**Comment by ykuijs** [comment]
If there are reboots pending, the installation of SharePoint can be impacted. But I agree that SPInstallPrereqs isn't the best place for that. Would make more sense to use [xPendingReboot](https://github.com/PowerShell/xPendingReboot).

But at the same time, it looks like you are running into a different issue. Why isn't the registry key cleared? Shouldn't a reboot clear this key? And what is causing the key to be populated in the first place?

**Comment by jensotto** [comment]
Is that registry key really an indicator for a required reboot? I've seen several environments which does not have an empty PendingFileRenameOperation key. Even brand new instances of Windows Server 2016 on Azure goes into endless reboots when running prerequirsite installer DSC resource.

**Comment by ykuijs** [comment]
Looks like these registry keys are pretty common to detect a pending reboot. The xPendingReboot is using these:
https://github.com/PowerShell/xPendingReboot/blob/154f13e534e4fbcf07d914d75ed9c26d0908cf27/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L16-L39

But also other sources on the Internet list the same keys: https://scriptingetc.wordpress.com/2017/06/16/detect-pending-reboots/

**Comment by ykuijs** [comment]
I recently deployed several Windows Server 2016 environments with SP2019 in Azure and never encountered these endless reboots. Have you ran into this issue even since you submitted the issue? What have you tried to troubleshoot?

**Comment by jensotto** [comment]
I have not encountered this issue anymore. It seems that the fix for the .NET Framework prerequisite installation fixed the issues that I had. I think it's safe to close this issue now.

**Comment by ykuijs** [comment]
Great. Closing issue
