### ISSUE TITLE
SPManagedMetadataServiceApp: Get-TargetResource method throws error when proxy does not exist

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#971]
#### Details of the scenario you tried and the problem that is occurring
When the service app proxy does not exists, the Get-TargetResource method throws an error. This is caused by the fact that the ErrorAction parameter is missing:
https://github.com/PowerShell/SharePointDsc/blob/c6940e463f3c75292fb0f9cada586eadbb9e1e3a/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L107

#### Suggested solution to the issue
Add -ErrorAction SilentlyContinue to the line

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Any MMS config where in the environment the proxy is missing.

#### The operating system the target node is running
Windows Server 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
PowerShell 5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by mariusv-msft** [comment]
@ykuijs I'm still getting this issue if the Proxy has been deleted or something else happened to it.
I'm getting the following:

PowerShell DSC resource MSFT_SPManagedMetaDataServiceApp  failed to execute Test-TargetResource functionality with error message:
Cannot bind argument to parameter 'Identity' because it is null.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SP19SP2
