### ISSUE TITLE
SPSearchServiceApp: (Discussion) Do we need to move the WindowsServiceAccount parameter to a new resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SharePointDsc#974]
The SPSearchServiceApp resource has a parameter to configure the WindowsServiceAccount. This property however is an environment wide setting, not service app specific:
https://github.com/PowerShell/SharePointDsc/blob/c6940e463f3c75292fb0f9cada586eadbb9e1e3a/Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L293

With the current implementation it is possible to set the WindowsServiceAccount to Account1 in SearchServiceApp1 and change it to Account2 in SearchServiceApp2. This will result in conflict, flipping the account back and forth.

Issue #966 also requests a parameter that is search specific. Is it an idea to combine these parameters into a new SPSearchService resource?

This can be a breaking change if we remove the parameter from the resource. But we since we just released v3.0, we have to wait until v4. In the meantime we can remove the code that implements the changes, so the parameter actually doesn't do anything but won't break existing configs at the same time.

@NikCharlebois What is your opinion?

**Comment by ykuijs** [comment]
@andikrueger, @jensotto: Also interested in your thoughts on this.

**Comment by andikrueger** [comment]
Good point! We already do have a resource that sets one Setting across all instances of a Service app: SPManagedMetaDataServiceAppDefault resource

I think we should add a new resource for the search service app, that Handel’s these settings. Naming would preferably alike the existing resource.

**Comment by ykuijs** [comment]
I suggest the name SPSearchServiceSettings, since these settings aren't directly service app settings, including "ServiceApp" in the name doesn't make sense. The resource updates the settings for the generic search service.

**Comment by NikCharlebois** [comment]
I agree with the recommendation. We will have to take this out of there in order to prevent circular conflicts from happening. I think SPSearchServiceSettings would be the right name to use.

**Comment by ykuijs** [comment]
That is exactly what I had at a customer last week. Two resources were conflicting and caused other issues because SharePoint was applying the settings and performing restarts of various services.

Already working on implementing this change!

**Comment by jensotto** [comment]
I agree with your suggestion @ykuijs 
Sorry I wasn't able to reply any sooner.
