### ISSUE TITLE
SPServiceAppSecurity: conflict AccessLevels

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#980]
#### Details of the scenario you tried and the problem that is occurring
SPServiceAppSecurity not complice, conflict AccessLevels see example
#### Verbose logs showing the problem
Test-ConflictingResources : A conflict was detected between resources ' ()' and ' ()' in node 'SRVSP01'. Resources have identical key 
properties but there are differences in the following non-key properties: 'AccessLevels'. Values 'System.Object[]' don't match values 
'System.Object[]'. Please update these property values so that they are identical in both cases.

#### Suggested solution to the issue
Fix code. 
Maybe a temporary solutions can be add a "Key" with EntryNumber in schema.mof ?? and set EntryNumber=1 for one set and EntryNumber = 2 for another set.

Problem with same Username with different AccessLevels (I thinks)
Same problem also with different SecurityType and same Username with different AccessLevels.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 $MembersToIncludeMMS = @();
            $MembersToIncludeMMS += MSFT_SPServiceAppSecurityEntry {
                Username    = $CredsspUser.UserName;
                AccessLevels = @("Full Control");
            };
            SPServiceAppSecurity ServiceAppSecurityManagedMetadata
            {
                SecurityType = "Administrators";
                ServiceAppName = "Managed Metadata Service";
                PsDscRunAsCredential = $Credssp_admin;
                MembersToInclude = @($MembersToIncludeMMS);
            }

            # User Profile Administrators Permissions
            $MembersToIncludeUP = @();   
            $MembersToIncludeUP += MSFT_SPServiceAppSecurityEntry {
                Username    = $CredsspUser.UserName;
                AccessLevels = @("Retrieve People Data for Search Crawlers");
            };     
            SPServiceAppSecurity ServiceAppSecurityUserProfileAdministrators
            {
                SecurityType = "Administrators";
                ServiceAppName = "User Profile Service Application";
                PsDscRunAsCredential = $Credssp_admin;
                MembersToInclude = @($MembersToIncludeUP);
            }
```

#### The operating system the target node is running
Win Server 2016
#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019
#### Version and build of PowerShell the target node is running
PSVersion: 5.1.14393.2608    

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.0

**Comment by ykuijs** [comment]
Found the issue, will be included in my next PR
