### ISSUE TITLE
SPConfigWizard may result in inccorect psconfig command is used on SP2016

### ISSUE THREAD

**Issue by MartinHallin** [PowerShell/SharePointDsc#981]
ISSUE TITLE:
SPConfigWizard may result in inccorect psconfig command is used on SP2016

    ISSUE DESCRIPTION (this template):
I updated an SP2016 RTM with the JULY2016 CU 
When using the command SPConfigWizard on a SP2016 RTM installation run psconfig this resulted in that an correct command line switch was used.
the command line that was used was
psconfig.exe -cmd upgrade -inplace b2b -wait -force -cmd installcheck -noinstallcheck
the command line that should have been used is.
PSConfig.exe -cmd upgrade -inplace b2b -force -cmd applicationcontent -install -cmd installfeatures

this as SP2016 as a featurep ack released 

#### Details of the scenario you tried and the problem that is occurring
Due to that incorrect command line was used.
the issue described in this link occures. and Cetnral admin is not fully functional,
https://sharepoint.stackexchange.com/questions/247258/sp2016-central-admin-error-databinding-system-data-datarowview-does-not-cont

#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue
maybe a switch to allow for adding installfeatures command
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

SPConfigWizard ConfigWiz
    {
        IsSingleInstance  = 'Yes'
        DependsOn = "[SPProductUpdate]July2018"
        PSDSCRunAsCredential = $credsSPSetup
 
    }

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19153.amd64fre.winblue_ltsb.180908-0600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
Sp2016
#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      5.1.14409.1012                                                                                                                 
PSEdition                      Desktop                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                   10.0.14409.1012                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                
WSManStackVersion              3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                        

#### Version of the DSC module that was used ('dev' if using current dev branch)
SharepointDSC 3.0

**Comment by paololec** [comment]
Example of better code:
`
if ((Get-SPDSCInstalledProductVersion).FileMajorPart -eq 15)
    {
        $binaryDir = Join-Path $env:CommonProgramFiles "Microsoft Shared\Web Server Extensions\15\BIN"
    }
    else
    {
        $binaryDir = Join-Path $env:CommonProgramFiles "Microsoft Shared\Web Server Extensions\16\BIN"
    }
    $psconfigExe = Join-Path -Path $binaryDir -ChildPath "psconfig.exe"

             $stdOutTempFile = "$env:TEMP\$((New-Guid).Guid)"
             $stdErrTempFile = "$env:TEMP\$((New-Guid).Guid)"
             $psconfig = Start-Process -FilePath $psconfigExe `
                                  -ArgumentList "-cmd upgrade -inplace b2b -wait -force -cmd applicationcontent -install -cmd installfeatures -cmd secureresources -cmd services -install -cmd helpcollections -installall" `
                                  -RedirectStandardError $stdErrTempFile `
                                  -RedirectStandardOutput $stdOutTempFile `
                                  -Wait `
                                  -PassThru
            $cmdOutput = Get-Content -Path $stdOutTempFile -Raw
            $cmdError = Get-Content -Path $stdErrTempFile -Raw
            if ($cmdError) {
                    Write-Verbose -Message $cmdError.Trim()
                }
            if ($cmdOutput) {
                    Write-Verbose -Message $cmdOutput.Trim()
                }
             Write-Verbose -Message $psconfig.ExitCode
             return $psconfig.ExitCode
`

**Comment by ykuijs** [comment]
The updates to the PSConfig parameters have been corrected according to the article of Stefan Gossner via #1012 and PR #1016 

I like the suggestion by @paololec. Will update the resource in my next Bugfix PR

**Comment by ykuijs** [comment]
Did some further thinking about adding the logging suggested by @paololec. PSConfig already creates a log file. By storing the logging and outputting that to screen, it increases the logging tremendously, but doesn't add any additional troubleshooting info. So I don't think we should add this.

**Comment by ykuijs** [comment]
@NikCharlebois What is your opinion?

**Comment by NikCharlebois** [comment]
I don't see any issues displaying it whenever the -Verbose switch is used. I think there might be some useful info in there. At a minimum prompt the user about the location of the log file and let them access the file on the server if need be.

**Comment by ykuijs** [comment]
The amount of output it generates is quite large. If you deploy a multiserver farm, this will be added to the screen output multiple times. And since PSConfig already generates a log file.....

But I like the idea of displaying the log file location. Will implement that for sure!

**Comment by paololec** [comment]
Yes, I use -verbose and I like to see it on screen , but also with link to log files location can be good.

**Comment by ykuijs** [comment]
Fixed in PR #1036
