### ISSUE TITLE
SPSearchContentSource: calls New-SPEnterpriseSearchCrawlContentSource multiple times

### ISSUE THREAD

**Issue by scoreman** [PowerShell/SharePointDsc#985]
#### Details of the scenario you tried and the problem that is occurring
New-SPEnterpriseSearchCrawlContentSource is called on line 422 and then it's called again on line 430 in MSFT_SPSearchContentSource. This causes an exception and configuration of content source will not finish.

#### Verbose logs showing the problem
VERBOSE: [JSSP-DSC-SINGLE]:                            [[SPSearchContentSource]PeopleContentSource] Leaving BeginProcessing Method of New-SPEnterpriseSearchCrawlContentSource.
VERBOSE: [JSSP-DSC-SINGLE]:                            [[SPSearchContentSource]PeopleContentSource] Leaving ProcessRecord Method of New-SPEnterpriseSearchCrawlContentSource.
VERBOSE: [JSSP-DSC-SINGLE]:                            [[SPSearchContentSource]PeopleContentSource] Leaving EndProcessing Method of New-SPEnterpriseSearchCrawlContentSource.
VERBOSE: [JSSP-DSC-SINGLE]:                            [[SPSearchContentSource]PeopleContentSource] Leaving BeginProcessing Method of New-SPEnterpriseSearchCrawlContentSource.
name
Parameter name: Object People Search already exists.
    + CategoryInfo          : InvalidData: (Microsoft.Offic...wlContentSource:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Server.Search.Cmdlet.NewSearchCrawlContentSource
    + PSComputerName        : JSSP-DSC-SINGLE
 
#### Suggested solution to the issue
Remove duplicate New-SPEnterpriseSearchCrawlContentSource  

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019
#### Version of the DSC module that was used ('dev' if using current dev branch)
Release 3.0

**Comment by ykuijs** [comment]
Corrected the issue, will be included in my next PR
