### ISSUE TITLE
Invoke-SPDscCommand -ScriptBlock in a script resource unable to pass variables

### ISSUE THREAD

**Issue by bminisi** [PowerShell/SharePointDsc#992]
I have a configuration with a few script resources that are adding SharePoint Powershell:

Add-PSSnapin Microsoft.SharePoint.PowerShell

I need to use the PsDscRunAsCredential in a couple of the script resources.  However, when I do this, I get the error "An item with the same key has already been added".

To get around this problem, I tried using Invoke-SPDscCommand -ScriptBlock {} in SetScript.  This resolves the problem above.  However, I am unable to pass in variables to the script resource with $using:varName.

For some reason, all values are null.  How do you pass in variables to a script resource while using Invoke-SPDscCommand -ScriptBlock {}?

**Comment by ykuijs** [comment]
You can use the Arguments parameter of Invoke-SPDscCommand to pass arguments.

But to get back at your first issue: Can you share your config?
And have you checked the Credential parameter, as specified in the documentation: https://docs.microsoft.com/en-us/powershell/dsc/scriptresource

**Comment by bminisi** [comment]
Here is an example of my script resource.  Using PsDscRunAsCredential works by having the SetScript run under the credential passed in.  I will look into passing arguments as mentioned above.  However, I have not seen any examples of this other than using $PSBoundParameters.  I want to use variables that have been set in the configuration and not parameters.  Such as,

```
configuration DevEnvSP
{

Node localhost
{

$SomeVar = 'Test'
Script InstallNintex
{
    SetScript =
    {
        Invoke-SPDscCommand -ScriptBlock {
            ...
            $MyVar = $using:SomeVar #this returns a null value.
        }
    }

    TestScript = { 
        ...
    }

    GetScript = { ... }

    PsDscRunAsCredential = $SPInstallCred
}
}
}
```

**Comment by ykuijs** [comment]
That is correct, we have an example which adds more parameters in:
https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1#L173

You don't have to add the using clause, just pass @($Var1, Var2). In the scriptblock, you can use $args[0] for Var1, $args[1] for Var2, etc.

**Comment by bminisi** [comment]
Great!  Thanks.

**Comment by ykuijs** [comment]
Hi @bminisi, is your issue been resolved? If yes, can I go ahead and close this issue?
