### ISSUE TITLE
SPDistributedCacheClientSettings: missing some SP2016 settings

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#996]
#### Details of the scenario you tried and the problem that is occurring
Missing for SP2016 this options:
```
#DistributedFileLockThrottlerCache
DFLTCMaxConnectionsToServer = 4
DFLTCRequestTimeout = "3000"
DFLTCChannelOpenTimeOut = "3000"

#DistributedSharedWithUserCache
DSWUCMaxConnectionsToServer = 4
DSWUCRequestTimeout = "3000"
DSWUCChannelOpenTimeOut = "3000"

#DistributedUnifiedGroupsCache
DUGCMaxConnectionsToServer = 4
DUGCRequestTimeout = "3000"
DUGCChannelOpenTimeOut = "3000"

#DistributedResourceTallyCache
DRTCMaxConnectionsToServer = 4
DRTCRequestTimeout = "3000"
DRTCChannelOpenTimeOut = "3000"

#DistributedHealthScoreCache
DHSCMaxConnectionsToServer = 4
DHSCRequestTimeout = "3000"
DHSCChannelOpenTimeOut = "3000"
```
#### Verbose logs showing the problem
Missing options..
#### Suggested solution to the issue
Implement it

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.1

**Comment by ykuijs** [comment]
Will be added in my next BugFix PR
